namespace sERPCustomer
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr69 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr70 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr71 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr72 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr73 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr74 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr75 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr76 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr77 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr78 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr79 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr80 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr81 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr82 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr83 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.ERPCustomers = new Srvtools.InfoCommand(this.components);
            this.ucERPCustomers = new Srvtools.UpdateComponent(this.components);
            this.View_ERPCustomers = new Srvtools.InfoCommand(this.components);
            this.ERPPayKind = new Srvtools.InfoCommand(this.components);
            this.ucERPPayKind = new Srvtools.UpdateComponent(this.components);
            this.CustBill = new Srvtools.InfoCommand(this.components);
            this.SalesMan = new Srvtools.InfoCommand(this.components);
            this.City = new Srvtools.InfoCommand(this.components);
            this.CustDept = new Srvtools.InfoCommand(this.components);
            this.CustArea = new Srvtools.InfoCommand(this.components);
            this.SalesType = new Srvtools.InfoCommand(this.components);
            this.PayType = new Srvtools.InfoCommand(this.components);
            this.Industry = new Srvtools.InfoCommand(this.components);
            this.CustJob = new Srvtools.InfoCommand(this.components);
            this.Region = new Srvtools.InfoCommand(this.components);
            this.LetterType = new Srvtools.InfoCommand(this.components);
            this.SYSVar = new Srvtools.InfoCommand(this.components);
            this.PaperType = new Srvtools.InfoCommand(this.components);
            this.PostType = new Srvtools.InfoCommand(this.components);
            this.SYSVar2 = new Srvtools.InfoCommand(this.components);
            this.CustNotes = new Srvtools.InfoCommand(this.components);
            this.ucCustNotes = new Srvtools.UpdateComponent(this.components);
            this.NextCallTime = new Srvtools.InfoCommand(this.components);
            this.IndustryType = new Srvtools.InfoCommand(this.components);
            this.NotesType = new Srvtools.InfoCommand(this.components);
            this.SYSVar3 = new Srvtools.InfoCommand(this.components);
            this.info0800Cus = new Srvtools.InfoCommand(this.components);
            this.infoConnection2 = new Srvtools.InfoConnection(this.components);
            this.updateComponent1 = new Srvtools.UpdateComponent(this.components);
            this.updateComponent2 = new Srvtools.UpdateComponent(this.components);
            this.info0800Account = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPCustomers)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_ERPCustomers)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPPayKind)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustBill)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesMan)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.City)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustDept)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustArea)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Industry)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustJob)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Region)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.LetterType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYSVar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PaperType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PostType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYSVar2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustNotes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.NextCallTime)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.IndustryType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.NotesType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYSVar3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.info0800Cus)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.info0800Account)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "CheckCustNO";
            service1.NonLogin = false;
            service1.ServiceName = "CheckCustNO";
            service2.DelegateName = "CheckPayKind";
            service2.NonLogin = false;
            service2.ServiceName = "CheckPayKind";
            service3.DelegateName = "CheckDelCustNO";
            service3.NonLogin = false;
            service3.ServiceName = "CheckDelCustNO";
            service4.DelegateName = "procSyncContact";
            service4.NonLogin = false;
            service4.ServiceName = "procSyncContact";
            service5.DelegateName = "procAddERPCustomerToDoNotes";
            service5.NonLogin = false;
            service5.ServiceName = "procAddERPCustomerToDoNotes";
            service6.DelegateName = "procAddJBERPCustomerSaleType";
            service6.NonLogin = false;
            service6.ServiceName = "procAddJBERPCustomerSaleType";
            service7.DelegateName = "procUpdateJBERPCustomerSaleType";
            service7.NonLogin = false;
            service7.ServiceName = "procUpdateJBERPCustomerSaleType";
            service8.DelegateName = "procDeleteJBERPCustomerSaleType";
            service8.NonLogin = false;
            service8.ServiceName = "procDeleteJBERPCustomerSaleType";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // ERPCustomers
            // 
            this.ERPCustomers.CacheConnection = false;
            this.ERPCustomers.CommandText = resources.GetString("ERPCustomers.CommandText");
            this.ERPCustomers.CommandTimeout = 30;
            this.ERPCustomers.CommandType = System.Data.CommandType.Text;
            this.ERPCustomers.DynamicTableName = false;
            this.ERPCustomers.EEPAlias = "JBADMIN";
            this.ERPCustomers.EncodingAfter = null;
            this.ERPCustomers.EncodingBefore = "Windows-1252";
            this.ERPCustomers.EncodingConvert = null;
            this.ERPCustomers.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CustNO";
            this.ERPCustomers.KeyFields.Add(keyItem1);
            this.ERPCustomers.MultiSetWhere = false;
            this.ERPCustomers.Name = "ERPCustomers";
            this.ERPCustomers.NotificationAutoEnlist = false;
            this.ERPCustomers.SecExcept = null;
            this.ERPCustomers.SecFieldName = null;
            this.ERPCustomers.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPCustomers.SelectPaging = false;
            this.ERPCustomers.SelectTop = 0;
            this.ERPCustomers.SiteControl = false;
            this.ERPCustomers.SiteFieldName = null;
            this.ERPCustomers.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPCustomers
            // 
            this.ucERPCustomers.AutoTrans = true;
            this.ucERPCustomers.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "CustNO";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "CustName";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "CustShortName";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "SalesID";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "BossName";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "TaxNO";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "IndustryTypeID";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "CustTelNO";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "CustCityNO";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "CustRegion";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "CustPost";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CustAddr";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "CustFaxNO";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "CustDeptID";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "CustDeptName";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "CustAreaID";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "PMID";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "ContactA";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "ContactATel";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "ContactASubTel";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "ContactAMail";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "ContactAJobID";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "ContactAIsMail";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "ContactB";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "ContactBTel";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "ContactBSubTel";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "ContactBMail";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "ContactBJobID";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "ContactBIsMail";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "BalanceDay";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "CustNotes";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "RecallDate";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "IsPutInvoice";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "IsPutPaperInvoice";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "CreateBy";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = "_username";
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "CreateDate";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "LastUpdateBy";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr37.DefaultValue = "_username";
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "LastUpdateDate";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "LatelyDayD";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "LatelyDayP";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "LatelyDayW";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "LatelyDayN";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "DealNotesP";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "DealNotesW";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "DealNotesN";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr1);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr2);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr3);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr4);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr5);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr6);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr7);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr8);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr9);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr10);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr11);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr12);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr13);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr14);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr15);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr16);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr17);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr18);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr19);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr20);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr21);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr22);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr23);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr24);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr25);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr26);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr27);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr28);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr29);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr30);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr31);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr32);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr33);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr34);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr35);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr36);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr37);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr38);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr39);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr40);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr41);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr42);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr43);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr44);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr45);
            this.ucERPCustomers.LogInfo = null;
            this.ucERPCustomers.Name = "ucERPCustomers";
            this.ucERPCustomers.RowAffectsCheck = false;
            this.ucERPCustomers.SelectCmd = this.ERPCustomers;
            this.ucERPCustomers.SelectCmdForUpdate = null;
            this.ucERPCustomers.SendSQLCmd = true;
            this.ucERPCustomers.ServerModify = true;
            this.ucERPCustomers.ServerModifyGetMax = false;
            this.ucERPCustomers.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPCustomers.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPCustomers.UseTranscationScope = false;
            this.ucERPCustomers.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucERPCustomers.AfterInsert += new Srvtools.UpdateComponentAfterInsertEventHandler(this.ucERPCustomers_AfterInsert);
            // 
            // View_ERPCustomers
            // 
            this.View_ERPCustomers.CacheConnection = false;
            this.View_ERPCustomers.CommandText = "SELECT * FROM dbo.[ERPCustomers]";
            this.View_ERPCustomers.CommandTimeout = 30;
            this.View_ERPCustomers.CommandType = System.Data.CommandType.Text;
            this.View_ERPCustomers.DynamicTableName = false;
            this.View_ERPCustomers.EEPAlias = null;
            this.View_ERPCustomers.EncodingAfter = null;
            this.View_ERPCustomers.EncodingBefore = "Windows-1252";
            this.View_ERPCustomers.EncodingConvert = null;
            this.View_ERPCustomers.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "CustNO";
            this.View_ERPCustomers.KeyFields.Add(keyItem2);
            this.View_ERPCustomers.MultiSetWhere = false;
            this.View_ERPCustomers.Name = "View_ERPCustomers";
            this.View_ERPCustomers.NotificationAutoEnlist = false;
            this.View_ERPCustomers.SecExcept = null;
            this.View_ERPCustomers.SecFieldName = null;
            this.View_ERPCustomers.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_ERPCustomers.SelectPaging = false;
            this.View_ERPCustomers.SelectTop = 0;
            this.View_ERPCustomers.SiteControl = false;
            this.View_ERPCustomers.SiteFieldName = null;
            this.View_ERPCustomers.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ERPPayKind
            // 
            this.ERPPayKind.CacheConnection = false;
            this.ERPPayKind.CommandText = "select  A.*,B.CUSTSHORTNAME\r\n from ERPPayKind A\r\n LEFT JOIN ERPCustomers  B\r\n ON " +
    " A.Custno=B.CustNO\r\n\r\n\r\n\r\n";
            this.ERPPayKind.CommandTimeout = 30;
            this.ERPPayKind.CommandType = System.Data.CommandType.Text;
            this.ERPPayKind.DynamicTableName = false;
            this.ERPPayKind.EEPAlias = "JBADMIN";
            this.ERPPayKind.EncodingAfter = null;
            this.ERPPayKind.EncodingBefore = "Windows-1252";
            this.ERPPayKind.EncodingConvert = null;
            this.ERPPayKind.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "PayKindNO";
            keyItem4.KeyName = "CustNO";
            keyItem5.KeyName = "SalesTypeID";
            this.ERPPayKind.KeyFields.Add(keyItem3);
            this.ERPPayKind.KeyFields.Add(keyItem4);
            this.ERPPayKind.KeyFields.Add(keyItem5);
            this.ERPPayKind.MultiSetWhere = false;
            this.ERPPayKind.Name = "ERPPayKind";
            this.ERPPayKind.NotificationAutoEnlist = false;
            this.ERPPayKind.SecExcept = null;
            this.ERPPayKind.SecFieldName = null;
            this.ERPPayKind.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPPayKind.SelectPaging = false;
            this.ERPPayKind.SelectTop = 0;
            this.ERPPayKind.SiteControl = false;
            this.ERPPayKind.SiteFieldName = null;
            this.ERPPayKind.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPPayKind
            // 
            this.ucERPPayKind.AutoTrans = true;
            this.ucERPPayKind.ExceptJoin = false;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "PayKindNO";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "CustNO";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "SalesTypeID";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "PayTypeID";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "BalanceDay";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "PayDays";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "PayLeadDays";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "CreateBy";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = "_username";
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "CreateDate";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            this.ucERPPayKind.FieldAttrs.Add(fieldAttr46);
            this.ucERPPayKind.FieldAttrs.Add(fieldAttr47);
            this.ucERPPayKind.FieldAttrs.Add(fieldAttr48);
            this.ucERPPayKind.FieldAttrs.Add(fieldAttr49);
            this.ucERPPayKind.FieldAttrs.Add(fieldAttr50);
            this.ucERPPayKind.FieldAttrs.Add(fieldAttr51);
            this.ucERPPayKind.FieldAttrs.Add(fieldAttr52);
            this.ucERPPayKind.FieldAttrs.Add(fieldAttr53);
            this.ucERPPayKind.FieldAttrs.Add(fieldAttr54);
            this.ucERPPayKind.LogInfo = null;
            this.ucERPPayKind.Name = "ucERPPayKind";
            this.ucERPPayKind.RowAffectsCheck = false;
            this.ucERPPayKind.SelectCmd = this.ERPPayKind;
            this.ucERPPayKind.SelectCmdForUpdate = null;
            this.ucERPPayKind.SendSQLCmd = true;
            this.ucERPPayKind.ServerModify = true;
            this.ucERPPayKind.ServerModifyGetMax = false;
            this.ucERPPayKind.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPPayKind.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPPayKind.UseTranscationScope = false;
            this.ucERPPayKind.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucERPPayKind.BeforeInsert += new Srvtools.UpdateComponentBeforeInsertEventHandler(this.ucERPPayKind_BeforeInsert);
            this.ucERPPayKind.AfterInsert += new Srvtools.UpdateComponentAfterInsertEventHandler(this.ucERPPayKind_AfterInsert);
            this.ucERPPayKind.AfterDelete += new Srvtools.UpdateComponentAfterDeleteEventHandler(this.ucERPPayKind_AfterDelete);
            // 
            // CustBill
            // 
            this.CustBill.CacheConnection = false;
            this.CustBill.CommandText = "select  TOP 10   CustNO ,CustTelNO,RTRIM(CustShortName) AS CustShortName \r\nfrom V" +
    "iew_Cust\r\norder by  CustNO ";
            this.CustBill.CommandTimeout = 30;
            this.CustBill.CommandType = System.Data.CommandType.Text;
            this.CustBill.DynamicTableName = false;
            this.CustBill.EEPAlias = "JBADMIN";
            this.CustBill.EncodingAfter = null;
            this.CustBill.EncodingBefore = "Windows-1252";
            this.CustBill.EncodingConvert = null;
            this.CustBill.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "CustNO";
            this.CustBill.KeyFields.Add(keyItem6);
            this.CustBill.MultiSetWhere = false;
            this.CustBill.Name = "CustBill";
            this.CustBill.NotificationAutoEnlist = false;
            this.CustBill.SecExcept = null;
            this.CustBill.SecFieldName = null;
            this.CustBill.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustBill.SelectPaging = false;
            this.CustBill.SelectTop = 0;
            this.CustBill.SiteControl = false;
            this.CustBill.SiteFieldName = null;
            this.CustBill.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesMan
            // 
            this.SalesMan.CacheConnection = false;
            this.SalesMan.CommandText = "select  ERPSalesMan.SalesID,\r\n        ERPSalesMan.SalesID+\' \'+ERPSalesMan.SalesNa" +
    "me as SalesName,\r\n        ERPSalesMan.SalesEmployeeID    \r\nfrom   ERPSalesMan";
            this.SalesMan.CommandTimeout = 30;
            this.SalesMan.CommandType = System.Data.CommandType.Text;
            this.SalesMan.DynamicTableName = false;
            this.SalesMan.EEPAlias = "JBADMIN";
            this.SalesMan.EncodingAfter = null;
            this.SalesMan.EncodingBefore = "Windows-1252";
            this.SalesMan.EncodingConvert = null;
            this.SalesMan.InfoConnection = this.InfoConnection1;
            this.SalesMan.MultiSetWhere = false;
            this.SalesMan.Name = "SalesMan";
            this.SalesMan.NotificationAutoEnlist = false;
            this.SalesMan.SecExcept = null;
            this.SalesMan.SecFieldName = null;
            this.SalesMan.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesMan.SelectPaging = false;
            this.SalesMan.SelectTop = 0;
            this.SalesMan.SiteControl = false;
            this.SalesMan.SiteFieldName = null;
            this.SalesMan.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // City
            // 
            this.City.CacheConnection = false;
            this.City.CommandText = "select Distinct ERPCity.CityNO,ERPCity.CityName\r\nfrom ERPCity\r\nORDER BY ERPCity.C" +
    "ityNO";
            this.City.CommandTimeout = 30;
            this.City.CommandType = System.Data.CommandType.Text;
            this.City.DynamicTableName = false;
            this.City.EEPAlias = null;
            this.City.EncodingAfter = null;
            this.City.EncodingBefore = "Windows-1252";
            this.City.EncodingConvert = null;
            this.City.InfoConnection = this.InfoConnection1;
            this.City.MultiSetWhere = false;
            this.City.Name = "City";
            this.City.NotificationAutoEnlist = false;
            this.City.SecExcept = null;
            this.City.SecFieldName = null;
            this.City.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.City.SelectPaging = false;
            this.City.SelectTop = 0;
            this.City.SiteControl = false;
            this.City.SiteFieldName = null;
            this.City.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CustDept
            // 
            this.CustDept.CacheConnection = false;
            this.CustDept.CommandText = "select ERPCustDept.CustDeptID,ERPCustDept.CustDeptName from ERPCustDept";
            this.CustDept.CommandTimeout = 30;
            this.CustDept.CommandType = System.Data.CommandType.Text;
            this.CustDept.DynamicTableName = false;
            this.CustDept.EEPAlias = null;
            this.CustDept.EncodingAfter = null;
            this.CustDept.EncodingBefore = "Windows-1252";
            this.CustDept.EncodingConvert = null;
            this.CustDept.InfoConnection = this.InfoConnection1;
            this.CustDept.MultiSetWhere = false;
            this.CustDept.Name = "CustDept";
            this.CustDept.NotificationAutoEnlist = false;
            this.CustDept.SecExcept = null;
            this.CustDept.SecFieldName = null;
            this.CustDept.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustDept.SelectPaging = false;
            this.CustDept.SelectTop = 0;
            this.CustDept.SiteControl = false;
            this.CustDept.SiteFieldName = null;
            this.CustDept.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CustArea
            // 
            this.CustArea.CacheConnection = false;
            this.CustArea.CommandText = "select ERPCustArea.CustAreaID,ERPCustArea.CustAreaName from ERPCustArea";
            this.CustArea.CommandTimeout = 30;
            this.CustArea.CommandType = System.Data.CommandType.Text;
            this.CustArea.DynamicTableName = false;
            this.CustArea.EEPAlias = null;
            this.CustArea.EncodingAfter = null;
            this.CustArea.EncodingBefore = "Windows-1252";
            this.CustArea.EncodingConvert = null;
            this.CustArea.InfoConnection = this.InfoConnection1;
            this.CustArea.MultiSetWhere = false;
            this.CustArea.Name = "CustArea";
            this.CustArea.NotificationAutoEnlist = false;
            this.CustArea.SecExcept = null;
            this.CustArea.SecFieldName = null;
            this.CustArea.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustArea.SelectPaging = false;
            this.CustArea.SelectTop = 0;
            this.CustArea.SiteControl = false;
            this.CustArea.SiteFieldName = null;
            this.CustArea.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesType
            // 
            this.SalesType.CacheConnection = false;
            this.SalesType.CommandText = "select ERPSalesType.SalesTypeID,\r\n           RTRIM(ERPSalesType.SalesTypeID)+\'-\'+" +
    "ERPSalesType.SalesTypeName  AS  SalesTypeName\r\nfrom ERPSalesType\r\n";
            this.SalesType.CommandTimeout = 30;
            this.SalesType.CommandType = System.Data.CommandType.Text;
            this.SalesType.DynamicTableName = false;
            this.SalesType.EEPAlias = null;
            this.SalesType.EncodingAfter = null;
            this.SalesType.EncodingBefore = "Windows-1252";
            this.SalesType.EncodingConvert = null;
            this.SalesType.InfoConnection = this.InfoConnection1;
            this.SalesType.MultiSetWhere = false;
            this.SalesType.Name = "SalesType";
            this.SalesType.NotificationAutoEnlist = false;
            this.SalesType.SecExcept = null;
            this.SalesType.SecFieldName = null;
            this.SalesType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesType.SelectPaging = false;
            this.SalesType.SelectTop = 0;
            this.SalesType.SiteControl = false;
            this.SalesType.SiteFieldName = null;
            this.SalesType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // PayType
            // 
            this.PayType.CacheConnection = false;
            this.PayType.CommandText = "select ERPPayType.PayTypeID,\r\n           RTRIM(ERPPayType.PayTypeID)+\'-\'+ERPPayTy" +
    "pe.PayTypeName AS PayTypeName\r\nfrom ERPPayType";
            this.PayType.CommandTimeout = 30;
            this.PayType.CommandType = System.Data.CommandType.Text;
            this.PayType.DynamicTableName = false;
            this.PayType.EEPAlias = null;
            this.PayType.EncodingAfter = null;
            this.PayType.EncodingBefore = "Windows-1252";
            this.PayType.EncodingConvert = null;
            this.PayType.InfoConnection = this.InfoConnection1;
            this.PayType.MultiSetWhere = false;
            this.PayType.Name = "PayType";
            this.PayType.NotificationAutoEnlist = false;
            this.PayType.SecExcept = null;
            this.PayType.SecFieldName = null;
            this.PayType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PayType.SelectPaging = false;
            this.PayType.SelectTop = 0;
            this.PayType.SiteControl = false;
            this.PayType.SiteFieldName = null;
            this.PayType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Industry
            // 
            this.Industry.CacheConnection = false;
            this.Industry.CommandText = "SELECT * FROM ERPIndustryType";
            this.Industry.CommandTimeout = 30;
            this.Industry.CommandType = System.Data.CommandType.Text;
            this.Industry.DynamicTableName = false;
            this.Industry.EEPAlias = "JBADMIN";
            this.Industry.EncodingAfter = null;
            this.Industry.EncodingBefore = "Windows-1252";
            this.Industry.EncodingConvert = null;
            this.Industry.InfoConnection = this.InfoConnection1;
            keyItem7.KeyName = "jb_type";
            this.Industry.KeyFields.Add(keyItem7);
            this.Industry.MultiSetWhere = false;
            this.Industry.Name = "Industry";
            this.Industry.NotificationAutoEnlist = false;
            this.Industry.SecExcept = null;
            this.Industry.SecFieldName = null;
            this.Industry.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Industry.SelectPaging = false;
            this.Industry.SelectTop = 0;
            this.Industry.SiteControl = false;
            this.Industry.SiteFieldName = null;
            this.Industry.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CustJob
            // 
            this.CustJob.CacheConnection = false;
            this.CustJob.CommandText = "select ERPCustJob.CustJobID,ERPCustJob.CustJobName from ERPCustJob";
            this.CustJob.CommandTimeout = 30;
            this.CustJob.CommandType = System.Data.CommandType.Text;
            this.CustJob.DynamicTableName = false;
            this.CustJob.EEPAlias = null;
            this.CustJob.EncodingAfter = null;
            this.CustJob.EncodingBefore = "Windows-1252";
            this.CustJob.EncodingConvert = null;
            this.CustJob.InfoConnection = this.InfoConnection1;
            this.CustJob.MultiSetWhere = false;
            this.CustJob.Name = "CustJob";
            this.CustJob.NotificationAutoEnlist = false;
            this.CustJob.SecExcept = null;
            this.CustJob.SecFieldName = null;
            this.CustJob.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustJob.SelectPaging = false;
            this.CustJob.SelectTop = 0;
            this.CustJob.SiteControl = false;
            this.CustJob.SiteFieldName = null;
            this.CustJob.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Region
            // 
            this.Region.CacheConnection = false;
            this.Region.CommandText = "select ERPCity.CityNO,ERPCity.Region,ERPCity.PostCode from ERPCity\r\nORDER BY ERPC" +
    "ity.CityNO,ERPCity.PostCode";
            this.Region.CommandTimeout = 30;
            this.Region.CommandType = System.Data.CommandType.Text;
            this.Region.DynamicTableName = false;
            this.Region.EEPAlias = null;
            this.Region.EncodingAfter = null;
            this.Region.EncodingBefore = "Windows-1252";
            this.Region.EncodingConvert = null;
            this.Region.InfoConnection = this.InfoConnection1;
            this.Region.MultiSetWhere = false;
            this.Region.Name = "Region";
            this.Region.NotificationAutoEnlist = false;
            this.Region.SecExcept = null;
            this.Region.SecFieldName = null;
            this.Region.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Region.SelectPaging = false;
            this.Region.SelectTop = 0;
            this.Region.SiteControl = false;
            this.Region.SiteFieldName = null;
            this.Region.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // LetterType
            // 
            this.LetterType.CacheConnection = false;
            this.LetterType.CommandText = "select ERPLetterType.LetterTypeID,ERPLetterType.LetterTypeName\r\nfrom ERPLetterTyp" +
    "e\r\norder by ERPLetterType.LetterTypeID";
            this.LetterType.CommandTimeout = 30;
            this.LetterType.CommandType = System.Data.CommandType.Text;
            this.LetterType.DynamicTableName = false;
            this.LetterType.EEPAlias = null;
            this.LetterType.EncodingAfter = null;
            this.LetterType.EncodingBefore = "Windows-1252";
            this.LetterType.EncodingConvert = null;
            this.LetterType.InfoConnection = this.InfoConnection1;
            this.LetterType.MultiSetWhere = false;
            this.LetterType.Name = "LetterType";
            this.LetterType.NotificationAutoEnlist = false;
            this.LetterType.SecExcept = null;
            this.LetterType.SecFieldName = null;
            this.LetterType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.LetterType.SelectPaging = false;
            this.LetterType.SelectTop = 0;
            this.LetterType.SiteControl = false;
            this.LetterType.SiteFieldName = null;
            this.LetterType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SYSVar
            // 
            this.SYSVar.CacheConnection = false;
            this.SYSVar.CommandText = "SELECT CategoryValue  FROM SYS_Variable\r\nWHERE CATEGORY=\'FWCustomerViewer\'\r\n";
            this.SYSVar.CommandTimeout = 30;
            this.SYSVar.CommandType = System.Data.CommandType.Text;
            this.SYSVar.DynamicTableName = false;
            this.SYSVar.EEPAlias = null;
            this.SYSVar.EncodingAfter = null;
            this.SYSVar.EncodingBefore = "Windows-1252";
            this.SYSVar.EncodingConvert = null;
            this.SYSVar.InfoConnection = this.InfoConnection1;
            this.SYSVar.MultiSetWhere = false;
            this.SYSVar.Name = "SYSVar";
            this.SYSVar.NotificationAutoEnlist = false;
            this.SYSVar.SecExcept = null;
            this.SYSVar.SecFieldName = null;
            this.SYSVar.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SYSVar.SelectPaging = false;
            this.SYSVar.SelectTop = 0;
            this.SYSVar.SiteControl = false;
            this.SYSVar.SiteFieldName = null;
            this.SYSVar.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // PaperType
            // 
            this.PaperType.CacheConnection = false;
            this.PaperType.CommandText = "SELECT * FROM ERPPAPERTYPE ORDER BY AUTOKEY";
            this.PaperType.CommandTimeout = 30;
            this.PaperType.CommandType = System.Data.CommandType.Text;
            this.PaperType.DynamicTableName = false;
            this.PaperType.EEPAlias = "JBADMIN";
            this.PaperType.EncodingAfter = null;
            this.PaperType.EncodingBefore = "Windows-1252";
            this.PaperType.EncodingConvert = null;
            this.PaperType.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "AutoKey";
            this.PaperType.KeyFields.Add(keyItem8);
            this.PaperType.MultiSetWhere = false;
            this.PaperType.Name = "PaperType";
            this.PaperType.NotificationAutoEnlist = false;
            this.PaperType.SecExcept = null;
            this.PaperType.SecFieldName = null;
            this.PaperType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PaperType.SelectPaging = false;
            this.PaperType.SelectTop = 0;
            this.PaperType.SiteControl = false;
            this.PaperType.SiteFieldName = null;
            this.PaperType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // PostType
            // 
            this.PostType.CacheConnection = false;
            this.PostType.CommandText = "SELECT * FROM View_ERPReferenceTable\r\nWHERE ListCategory=\'POSTTYPE\'";
            this.PostType.CommandTimeout = 30;
            this.PostType.CommandType = System.Data.CommandType.Text;
            this.PostType.DynamicTableName = false;
            this.PostType.EEPAlias = null;
            this.PostType.EncodingAfter = null;
            this.PostType.EncodingBefore = "Windows-1252";
            this.PostType.EncodingConvert = null;
            this.PostType.InfoConnection = this.InfoConnection1;
            keyItem9.KeyName = "AutoKey";
            this.PostType.KeyFields.Add(keyItem9);
            this.PostType.MultiSetWhere = false;
            this.PostType.Name = "PostType";
            this.PostType.NotificationAutoEnlist = false;
            this.PostType.SecExcept = null;
            this.PostType.SecFieldName = null;
            this.PostType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PostType.SelectPaging = false;
            this.PostType.SelectTop = 0;
            this.PostType.SiteControl = false;
            this.PostType.SiteFieldName = null;
            this.PostType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SYSVar2
            // 
            this.SYSVar2.CacheConnection = false;
            this.SYSVar2.CommandText = "SELECT CategoryValue FROM SYS_Variable WHERE CateGory=\'SetInvoiceFlagUsersEEP\'";
            this.SYSVar2.CommandTimeout = 30;
            this.SYSVar2.CommandType = System.Data.CommandType.Text;
            this.SYSVar2.DynamicTableName = false;
            this.SYSVar2.EEPAlias = "JBADMIN";
            this.SYSVar2.EncodingAfter = null;
            this.SYSVar2.EncodingBefore = "Windows-1252";
            this.SYSVar2.EncodingConvert = null;
            this.SYSVar2.InfoConnection = this.InfoConnection1;
            this.SYSVar2.MultiSetWhere = false;
            this.SYSVar2.Name = "SYSVar2";
            this.SYSVar2.NotificationAutoEnlist = false;
            this.SYSVar2.SecExcept = null;
            this.SYSVar2.SecFieldName = null;
            this.SYSVar2.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SYSVar2.SelectPaging = false;
            this.SYSVar2.SelectTop = 0;
            this.SYSVar2.SiteControl = false;
            this.SYSVar2.SiteFieldName = null;
            this.SYSVar2.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CustNotes
            // 
            this.CustNotes.CacheConnection = false;
            this.CustNotes.CommandText = "SELECT *,NextCallDate  AS PreNextCallDate,NextCallTime AS PreNextCallTime\r\n FROM " +
    "ERPCustomerToDoNotes\r\nORDER BY  CreateDate DESC\r\n";
            this.CustNotes.CommandTimeout = 30;
            this.CustNotes.CommandType = System.Data.CommandType.Text;
            this.CustNotes.DynamicTableName = false;
            this.CustNotes.EEPAlias = "JBADMIN";
            this.CustNotes.EncodingAfter = null;
            this.CustNotes.EncodingBefore = "Windows-1252";
            this.CustNotes.EncodingConvert = null;
            this.CustNotes.InfoConnection = this.InfoConnection1;
            keyItem10.KeyName = "AutoKey";
            this.CustNotes.KeyFields.Add(keyItem10);
            this.CustNotes.MultiSetWhere = false;
            this.CustNotes.Name = "CustNotes";
            this.CustNotes.NotificationAutoEnlist = false;
            this.CustNotes.SecExcept = null;
            this.CustNotes.SecFieldName = null;
            this.CustNotes.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustNotes.SelectPaging = false;
            this.CustNotes.SelectTop = 0;
            this.CustNotes.SiteControl = false;
            this.CustNotes.SiteFieldName = null;
            this.CustNotes.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucCustNotes
            // 
            this.ucCustNotes.AutoTrans = true;
            this.ucCustNotes.ExceptJoin = false;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "AutoKey";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "CustNO";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "Notes";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "NextCallDate";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "NextCallTime";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "PostSourceID";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "CreateBy";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "CreateDate";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = null;
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "UpdateBy";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr63.DefaultValue = "_username";
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "UpateDate";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr64.DefaultValue = null;
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "NotesCreateDate";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = null;
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            this.ucCustNotes.FieldAttrs.Add(fieldAttr55);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr56);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr57);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr58);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr59);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr60);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr61);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr62);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr63);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr64);
            this.ucCustNotes.FieldAttrs.Add(fieldAttr65);
            this.ucCustNotes.LogInfo = null;
            this.ucCustNotes.Name = "ucCustNotes";
            this.ucCustNotes.RowAffectsCheck = true;
            this.ucCustNotes.SelectCmd = this.CustNotes;
            this.ucCustNotes.SelectCmdForUpdate = null;
            this.ucCustNotes.SendSQLCmd = true;
            this.ucCustNotes.ServerModify = true;
            this.ucCustNotes.ServerModifyGetMax = false;
            this.ucCustNotes.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucCustNotes.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucCustNotes.UseTranscationScope = false;
            this.ucCustNotes.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucCustNotes.BeforeInsert += new Srvtools.UpdateComponentBeforeInsertEventHandler(this.ucCustNotes_BeforeInsert);
            // 
            // NextCallTime
            // 
            this.NextCallTime.CacheConnection = false;
            this.NextCallTime.CommandText = "SELECT NextCallTime\r\nFROM ERPCustomerToDoNotes\r\nWHERE (NextCallTime IS NOT NULL) " +
    "and (NextCallTime<>\'\')\r\nGROUP BY NextCallTime\r\nORDER BY  NextCallTime";
            this.NextCallTime.CommandTimeout = 30;
            this.NextCallTime.CommandType = System.Data.CommandType.Text;
            this.NextCallTime.DynamicTableName = false;
            this.NextCallTime.EEPAlias = "JBADMIN";
            this.NextCallTime.EncodingAfter = null;
            this.NextCallTime.EncodingBefore = "Windows-1252";
            this.NextCallTime.EncodingConvert = null;
            this.NextCallTime.InfoConnection = this.InfoConnection1;
            this.NextCallTime.MultiSetWhere = false;
            this.NextCallTime.Name = "NextCallTime";
            this.NextCallTime.NotificationAutoEnlist = false;
            this.NextCallTime.SecExcept = null;
            this.NextCallTime.SecFieldName = null;
            this.NextCallTime.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.NextCallTime.SelectPaging = false;
            this.NextCallTime.SelectTop = 0;
            this.NextCallTime.SiteControl = false;
            this.NextCallTime.SiteFieldName = null;
            this.NextCallTime.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // IndustryType
            // 
            this.IndustryType.CacheConnection = false;
            this.IndustryType.CommandText = "SELECT ListID,ListContent FROM ERPReferenceTable WHERE ListCategory=\'IndustryType" +
    "\' order by listid";
            this.IndustryType.CommandTimeout = 30;
            this.IndustryType.CommandType = System.Data.CommandType.Text;
            this.IndustryType.DynamicTableName = false;
            this.IndustryType.EEPAlias = "JBADMIN";
            this.IndustryType.EncodingAfter = null;
            this.IndustryType.EncodingBefore = "Windows-1252";
            this.IndustryType.EncodingConvert = null;
            this.IndustryType.InfoConnection = this.InfoConnection1;
            this.IndustryType.MultiSetWhere = false;
            this.IndustryType.Name = "IndustryType";
            this.IndustryType.NotificationAutoEnlist = false;
            this.IndustryType.SecExcept = null;
            this.IndustryType.SecFieldName = null;
            this.IndustryType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.IndustryType.SelectPaging = false;
            this.IndustryType.SelectTop = 0;
            this.IndustryType.SiteControl = false;
            this.IndustryType.SiteFieldName = null;
            this.IndustryType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // NotesType
            // 
            this.NotesType.CacheConnection = false;
            this.NotesType.CommandText = "SELECT  LISTID,LISTCONTENT FROM ERPReferenceTable WHERE LISTCATEGORY=\'NotesType\' " +
    "ORDER BY  LISTID";
            this.NotesType.CommandTimeout = 30;
            this.NotesType.CommandType = System.Data.CommandType.Text;
            this.NotesType.DynamicTableName = false;
            this.NotesType.EEPAlias = "JBADMIN";
            this.NotesType.EncodingAfter = null;
            this.NotesType.EncodingBefore = "Windows-1252";
            this.NotesType.EncodingConvert = null;
            this.NotesType.InfoConnection = this.InfoConnection1;
            this.NotesType.MultiSetWhere = false;
            this.NotesType.Name = "NotesType";
            this.NotesType.NotificationAutoEnlist = false;
            this.NotesType.SecExcept = null;
            this.NotesType.SecFieldName = null;
            this.NotesType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.NotesType.SelectPaging = false;
            this.NotesType.SelectTop = 0;
            this.NotesType.SiteControl = false;
            this.NotesType.SiteFieldName = null;
            this.NotesType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SYSVar3
            // 
            this.SYSVar3.CacheConnection = false;
            this.SYSVar3.CommandText = "SELECT CategoryValue FROM SYS_Variable WHERE CateGory=\'SetSalesIDUsersEEP\'";
            this.SYSVar3.CommandTimeout = 30;
            this.SYSVar3.CommandType = System.Data.CommandType.Text;
            this.SYSVar3.DynamicTableName = false;
            this.SYSVar3.EEPAlias = "JBADMIN";
            this.SYSVar3.EncodingAfter = null;
            this.SYSVar3.EncodingBefore = "Windows-1252";
            this.SYSVar3.EncodingConvert = null;
            this.SYSVar3.InfoConnection = this.InfoConnection1;
            this.SYSVar3.MultiSetWhere = false;
            this.SYSVar3.Name = "SYSVar3";
            this.SYSVar3.NotificationAutoEnlist = false;
            this.SYSVar3.SecExcept = null;
            this.SYSVar3.SecFieldName = null;
            this.SYSVar3.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SYSVar3.SelectPaging = false;
            this.SYSVar3.SelectTop = 0;
            this.SYSVar3.SiteControl = false;
            this.SYSVar3.SiteFieldName = null;
            this.SYSVar3.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // info0800Cus
            // 
            this.info0800Cus.CacheConnection = false;
            this.info0800Cus.CommandText = resources.GetString("info0800Cus.CommandText");
            this.info0800Cus.CommandTimeout = 30;
            this.info0800Cus.CommandType = System.Data.CommandType.Text;
            this.info0800Cus.DynamicTableName = false;
            this.info0800Cus.EEPAlias = "JOB0800";
            this.info0800Cus.EncodingAfter = null;
            this.info0800Cus.EncodingBefore = "Windows-1252";
            this.info0800Cus.EncodingConvert = null;
            this.info0800Cus.InfoConnection = this.infoConnection2;
            keyItem11.KeyName = "Id";
            keyItem12.KeyName = "Code";
            this.info0800Cus.KeyFields.Add(keyItem11);
            this.info0800Cus.KeyFields.Add(keyItem12);
            this.info0800Cus.MultiSetWhere = false;
            this.info0800Cus.Name = "info0800Cus";
            this.info0800Cus.NotificationAutoEnlist = false;
            this.info0800Cus.SecExcept = null;
            this.info0800Cus.SecFieldName = null;
            this.info0800Cus.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.info0800Cus.SelectPaging = false;
            this.info0800Cus.SelectTop = 0;
            this.info0800Cus.SiteControl = false;
            this.info0800Cus.SiteFieldName = null;
            this.info0800Cus.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoConnection2
            // 
            this.infoConnection2.EEPAlias = "JOB0800";
            // 
            // updateComponent1
            // 
            this.updateComponent1.AutoTrans = true;
            this.updateComponent1.ExceptJoin = false;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "PayKindNO";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = null;
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "CustNO";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr67.DefaultValue = null;
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "SalesTypeID";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr68.DefaultValue = null;
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            fieldAttr69.CheckNull = false;
            fieldAttr69.DataField = "PayTypeID";
            fieldAttr69.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr69.DefaultValue = null;
            fieldAttr69.TrimLength = 0;
            fieldAttr69.UpdateEnable = true;
            fieldAttr69.WhereMode = true;
            fieldAttr70.CheckNull = false;
            fieldAttr70.DataField = "BalanceDay";
            fieldAttr70.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr70.DefaultValue = null;
            fieldAttr70.TrimLength = 0;
            fieldAttr70.UpdateEnable = true;
            fieldAttr70.WhereMode = true;
            fieldAttr71.CheckNull = false;
            fieldAttr71.DataField = "PayDays";
            fieldAttr71.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr71.DefaultValue = null;
            fieldAttr71.TrimLength = 0;
            fieldAttr71.UpdateEnable = true;
            fieldAttr71.WhereMode = true;
            fieldAttr72.CheckNull = false;
            fieldAttr72.DataField = "PayLeadDays";
            fieldAttr72.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr72.DefaultValue = null;
            fieldAttr72.TrimLength = 0;
            fieldAttr72.UpdateEnable = true;
            fieldAttr72.WhereMode = true;
            fieldAttr73.CheckNull = false;
            fieldAttr73.DataField = "CreateBy";
            fieldAttr73.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr73.DefaultValue = "_username";
            fieldAttr73.TrimLength = 0;
            fieldAttr73.UpdateEnable = true;
            fieldAttr73.WhereMode = true;
            fieldAttr74.CheckNull = false;
            fieldAttr74.DataField = "CreateDate";
            fieldAttr74.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr74.DefaultValue = null;
            fieldAttr74.TrimLength = 0;
            fieldAttr74.UpdateEnable = true;
            fieldAttr74.WhereMode = true;
            this.updateComponent1.FieldAttrs.Add(fieldAttr66);
            this.updateComponent1.FieldAttrs.Add(fieldAttr67);
            this.updateComponent1.FieldAttrs.Add(fieldAttr68);
            this.updateComponent1.FieldAttrs.Add(fieldAttr69);
            this.updateComponent1.FieldAttrs.Add(fieldAttr70);
            this.updateComponent1.FieldAttrs.Add(fieldAttr71);
            this.updateComponent1.FieldAttrs.Add(fieldAttr72);
            this.updateComponent1.FieldAttrs.Add(fieldAttr73);
            this.updateComponent1.FieldAttrs.Add(fieldAttr74);
            this.updateComponent1.LogInfo = null;
            this.updateComponent1.Name = "updateComponent1";
            this.updateComponent1.RowAffectsCheck = false;
            this.updateComponent1.SelectCmd = this.info0800Cus;
            this.updateComponent1.SelectCmdForUpdate = null;
            this.updateComponent1.SendSQLCmd = true;
            this.updateComponent1.ServerModify = true;
            this.updateComponent1.ServerModifyGetMax = false;
            this.updateComponent1.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateComponent1.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateComponent1.UseTranscationScope = false;
            this.updateComponent1.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // updateComponent2
            // 
            this.updateComponent2.AutoTrans = true;
            this.updateComponent2.ExceptJoin = false;
            fieldAttr75.CheckNull = false;
            fieldAttr75.DataField = "PayKindNO";
            fieldAttr75.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr75.DefaultValue = null;
            fieldAttr75.TrimLength = 0;
            fieldAttr75.UpdateEnable = true;
            fieldAttr75.WhereMode = true;
            fieldAttr76.CheckNull = false;
            fieldAttr76.DataField = "CustNO";
            fieldAttr76.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr76.DefaultValue = null;
            fieldAttr76.TrimLength = 0;
            fieldAttr76.UpdateEnable = true;
            fieldAttr76.WhereMode = true;
            fieldAttr77.CheckNull = false;
            fieldAttr77.DataField = "SalesTypeID";
            fieldAttr77.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr77.DefaultValue = null;
            fieldAttr77.TrimLength = 0;
            fieldAttr77.UpdateEnable = true;
            fieldAttr77.WhereMode = true;
            fieldAttr78.CheckNull = false;
            fieldAttr78.DataField = "PayTypeID";
            fieldAttr78.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr78.DefaultValue = null;
            fieldAttr78.TrimLength = 0;
            fieldAttr78.UpdateEnable = true;
            fieldAttr78.WhereMode = true;
            fieldAttr79.CheckNull = false;
            fieldAttr79.DataField = "BalanceDay";
            fieldAttr79.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr79.DefaultValue = null;
            fieldAttr79.TrimLength = 0;
            fieldAttr79.UpdateEnable = true;
            fieldAttr79.WhereMode = true;
            fieldAttr80.CheckNull = false;
            fieldAttr80.DataField = "PayDays";
            fieldAttr80.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr80.DefaultValue = null;
            fieldAttr80.TrimLength = 0;
            fieldAttr80.UpdateEnable = true;
            fieldAttr80.WhereMode = true;
            fieldAttr81.CheckNull = false;
            fieldAttr81.DataField = "PayLeadDays";
            fieldAttr81.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr81.DefaultValue = null;
            fieldAttr81.TrimLength = 0;
            fieldAttr81.UpdateEnable = true;
            fieldAttr81.WhereMode = true;
            fieldAttr82.CheckNull = false;
            fieldAttr82.DataField = "CreateBy";
            fieldAttr82.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr82.DefaultValue = "_username";
            fieldAttr82.TrimLength = 0;
            fieldAttr82.UpdateEnable = true;
            fieldAttr82.WhereMode = true;
            fieldAttr83.CheckNull = false;
            fieldAttr83.DataField = "CreateDate";
            fieldAttr83.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr83.DefaultValue = null;
            fieldAttr83.TrimLength = 0;
            fieldAttr83.UpdateEnable = true;
            fieldAttr83.WhereMode = true;
            this.updateComponent2.FieldAttrs.Add(fieldAttr75);
            this.updateComponent2.FieldAttrs.Add(fieldAttr76);
            this.updateComponent2.FieldAttrs.Add(fieldAttr77);
            this.updateComponent2.FieldAttrs.Add(fieldAttr78);
            this.updateComponent2.FieldAttrs.Add(fieldAttr79);
            this.updateComponent2.FieldAttrs.Add(fieldAttr80);
            this.updateComponent2.FieldAttrs.Add(fieldAttr81);
            this.updateComponent2.FieldAttrs.Add(fieldAttr82);
            this.updateComponent2.FieldAttrs.Add(fieldAttr83);
            this.updateComponent2.LogInfo = null;
            this.updateComponent2.Name = "updateComponent2";
            this.updateComponent2.RowAffectsCheck = false;
            this.updateComponent2.SelectCmd = this.info0800Cus;
            this.updateComponent2.SelectCmdForUpdate = null;
            this.updateComponent2.SendSQLCmd = true;
            this.updateComponent2.ServerModify = true;
            this.updateComponent2.ServerModifyGetMax = false;
            this.updateComponent2.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateComponent2.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateComponent2.UseTranscationScope = false;
            this.updateComponent2.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // info0800Account
            // 
            this.info0800Account.CacheConnection = false;
            this.info0800Account.CommandText = "select Id,Name,Email,Name+\'-\'+Email as sName\r\nfrom Account\r\n WHERE TeamId=\'000000" +
    "00-0000-0000-0000-000000000001\'";
            this.info0800Account.CommandTimeout = 30;
            this.info0800Account.CommandType = System.Data.CommandType.Text;
            this.info0800Account.DynamicTableName = false;
            this.info0800Account.EEPAlias = "JOB0800";
            this.info0800Account.EncodingAfter = null;
            this.info0800Account.EncodingBefore = "Windows-1252";
            this.info0800Account.EncodingConvert = null;
            this.info0800Account.InfoConnection = this.infoConnection2;
            keyItem13.KeyName = "Id";
            this.info0800Account.KeyFields.Add(keyItem13);
            this.info0800Account.MultiSetWhere = false;
            this.info0800Account.Name = "info0800Account";
            this.info0800Account.NotificationAutoEnlist = false;
            this.info0800Account.SecExcept = null;
            this.info0800Account.SecFieldName = null;
            this.info0800Account.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.info0800Account.SelectPaging = false;
            this.info0800Account.SelectTop = 0;
            this.info0800Account.SiteControl = false;
            this.info0800Account.SiteFieldName = null;
            this.info0800Account.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPCustomers)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_ERPCustomers)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPPayKind)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustBill)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesMan)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.City)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustDept)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustArea)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Industry)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustJob)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Region)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.LetterType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYSVar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PaperType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PostType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYSVar2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustNotes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.NextCallTime)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.IndustryType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.NotesType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYSVar3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.info0800Cus)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.info0800Account)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand ERPCustomers;
        private Srvtools.UpdateComponent ucERPCustomers;
        private Srvtools.InfoCommand View_ERPCustomers;
        private Srvtools.InfoCommand ERPPayKind;
        private Srvtools.UpdateComponent ucERPPayKind;
        private Srvtools.InfoCommand CustBill;
        private Srvtools.InfoCommand SalesMan;
        private Srvtools.InfoCommand City;
        private Srvtools.InfoCommand CustDept;
        private Srvtools.InfoCommand CustArea;
        private Srvtools.InfoCommand SalesType;
        private Srvtools.InfoCommand PayType;
        private Srvtools.InfoCommand Industry;
        private Srvtools.InfoCommand CustJob;
        private Srvtools.InfoCommand Region;
        private Srvtools.InfoCommand LetterType;
        private Srvtools.InfoCommand SYSVar;
        private Srvtools.InfoCommand PaperType;
        private Srvtools.InfoCommand PostType;
        private Srvtools.InfoCommand SYSVar2;
        private Srvtools.InfoCommand CustNotes;
        private Srvtools.UpdateComponent ucCustNotes;
        private Srvtools.InfoCommand NextCallTime;
        private Srvtools.InfoCommand IndustryType;
        private Srvtools.InfoCommand NotesType;
        private Srvtools.InfoCommand SYSVar3;
        private Srvtools.InfoCommand info0800Cus;
        private Srvtools.UpdateComponent updateComponent1;
        private Srvtools.InfoConnection infoConnection2;
        private Srvtools.UpdateComponent updateComponent2;
        private Srvtools.InfoCommand info0800Account;
    }
}
