namespace sJobQuery
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.ColumnItem columnItem1 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem2 = new Srvtools.ColumnItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr69 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr70 = new Srvtools.FieldAttr();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.JobQuery = new Srvtools.InfoCommand(this.components);
            this.QueryResult = new Srvtools.InfoCommand(this.components);
            this.AssignStep = new Srvtools.InfoCommand(this.components);
            this.JobAssignNew = new Srvtools.InfoCommand(this.components);
            this.ucHUT_JobAssignNew = new Srvtools.UpdateComponent(this.components);
            this.AssignNotes = new Srvtools.InfoCommand(this.components);
            this.ucHUT_AssignNotes = new Srvtools.UpdateComponent(this.components);
            this.idHUT_JobAssignNew_HUT_AssignNotes = new Srvtools.InfoDataSource(this.components);
            this.autoNumber1 = new Srvtools.AutoNumber(this.components);
            this.AssignLogs = new Srvtools.InfoCommand(this.components);
            this.infoIndustryType = new Srvtools.InfoCommand(this.components);
            this.ucQueryResult = new Srvtools.UpdateComponent(this.components);
            this.HUT_UserInterview = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.JobQuery)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.QueryResult)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.AssignStep)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.JobAssignNew)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.AssignNotes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.AssignLogs)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoIndustryType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.HUT_UserInterview)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "AddMenu";
            service1.NonLogin = false;
            service1.ServiceName = "AddMenu";
            service2.DelegateName = "userDEL";
            service2.NonLogin = false;
            service2.ServiceName = "userDEL";
            service3.DelegateName = "writeDBurl";
            service3.NonLogin = false;
            service3.ServiceName = "writeDBurl";
            service4.DelegateName = "SearchJobFullIndex";
            service4.NonLogin = false;
            service4.ServiceName = "SearchJobFullIndex";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "Hunter";
            // 
            // JobQuery
            // 
            this.JobQuery.CacheConnection = false;
            this.JobQuery.CommandText = resources.GetString("JobQuery.CommandText");
            this.JobQuery.CommandTimeout = 30;
            this.JobQuery.CommandType = System.Data.CommandType.Text;
            this.JobQuery.DynamicTableName = false;
            this.JobQuery.EEPAlias = "Hunter";
            this.JobQuery.EncodingAfter = null;
            this.JobQuery.EncodingBefore = "Windows-1252";
            this.JobQuery.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "JobID";
            this.JobQuery.KeyFields.Add(keyItem1);
            this.JobQuery.MultiSetWhere = false;
            this.JobQuery.Name = "JobQuery";
            this.JobQuery.NotificationAutoEnlist = false;
            this.JobQuery.SecExcept = null;
            this.JobQuery.SecFieldName = null;
            this.JobQuery.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.JobQuery.SelectPaging = false;
            this.JobQuery.SelectTop = 0;
            this.JobQuery.SiteControl = false;
            this.JobQuery.SiteFieldName = null;
            this.JobQuery.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // QueryResult
            // 
            this.QueryResult.CacheConnection = false;
            this.QueryResult.CommandText = resources.GetString("QueryResult.CommandText");
            this.QueryResult.CommandTimeout = 30;
            this.QueryResult.CommandType = System.Data.CommandType.Text;
            this.QueryResult.DynamicTableName = false;
            this.QueryResult.EEPAlias = "Hunter";
            this.QueryResult.EncodingAfter = null;
            this.QueryResult.EncodingBefore = "Windows-1252";
            this.QueryResult.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "UserID";
            this.QueryResult.KeyFields.Add(keyItem2);
            this.QueryResult.MultiSetWhere = false;
            this.QueryResult.Name = "QueryResult";
            this.QueryResult.NotificationAutoEnlist = false;
            this.QueryResult.SecExcept = null;
            this.QueryResult.SecFieldName = null;
            this.QueryResult.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.QueryResult.SelectPaging = false;
            this.QueryResult.SelectTop = 0;
            this.QueryResult.SiteControl = false;
            this.QueryResult.SiteFieldName = null;
            this.QueryResult.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // AssignStep
            // 
            this.AssignStep.CacheConnection = false;
            this.AssignStep.CommandText = "select HUT_ZAssignStep.* from HUT_ZAssignStep";
            this.AssignStep.CommandTimeout = 30;
            this.AssignStep.CommandType = System.Data.CommandType.Text;
            this.AssignStep.DynamicTableName = false;
            this.AssignStep.EEPAlias = "Hunter";
            this.AssignStep.EncodingAfter = null;
            this.AssignStep.EncodingBefore = "Windows-1252";
            this.AssignStep.InfoConnection = this.InfoConnection1;
            this.AssignStep.MultiSetWhere = false;
            this.AssignStep.Name = "AssignStep";
            this.AssignStep.NotificationAutoEnlist = false;
            this.AssignStep.SecExcept = null;
            this.AssignStep.SecFieldName = null;
            this.AssignStep.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.AssignStep.SelectPaging = false;
            this.AssignStep.SelectTop = 0;
            this.AssignStep.SiteControl = false;
            this.AssignStep.SiteFieldName = null;
            this.AssignStep.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // JobAssignNew
            // 
            this.JobAssignNew.CacheConnection = false;
            this.JobAssignNew.CommandText = resources.GetString("JobAssignNew.CommandText");
            this.JobAssignNew.CommandTimeout = 30;
            this.JobAssignNew.CommandType = System.Data.CommandType.Text;
            this.JobAssignNew.DynamicTableName = false;
            this.JobAssignNew.EEPAlias = null;
            this.JobAssignNew.EncodingAfter = null;
            this.JobAssignNew.EncodingBefore = "Windows-1252";
            this.JobAssignNew.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "AssignNO";
            this.JobAssignNew.KeyFields.Add(keyItem3);
            this.JobAssignNew.MultiSetWhere = false;
            this.JobAssignNew.Name = "JobAssignNew";
            this.JobAssignNew.NotificationAutoEnlist = false;
            this.JobAssignNew.SecExcept = null;
            this.JobAssignNew.SecFieldName = null;
            this.JobAssignNew.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.JobAssignNew.SelectPaging = false;
            this.JobAssignNew.SelectTop = 0;
            this.JobAssignNew.SiteControl = false;
            this.JobAssignNew.SiteFieldName = null;
            this.JobAssignNew.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucHUT_JobAssignNew
            // 
            this.ucHUT_JobAssignNew.AutoTrans = true;
            this.ucHUT_JobAssignNew.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "AssignNO";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "UserID";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "JobID";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "AssignID";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "AssignTime";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "LastUpdateBy";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "LastUpdateDate";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            this.ucHUT_JobAssignNew.FieldAttrs.Add(fieldAttr1);
            this.ucHUT_JobAssignNew.FieldAttrs.Add(fieldAttr2);
            this.ucHUT_JobAssignNew.FieldAttrs.Add(fieldAttr3);
            this.ucHUT_JobAssignNew.FieldAttrs.Add(fieldAttr4);
            this.ucHUT_JobAssignNew.FieldAttrs.Add(fieldAttr5);
            this.ucHUT_JobAssignNew.FieldAttrs.Add(fieldAttr6);
            this.ucHUT_JobAssignNew.FieldAttrs.Add(fieldAttr7);
            this.ucHUT_JobAssignNew.LogInfo = null;
            this.ucHUT_JobAssignNew.Name = "ucHUT_JobAssignNew";
            this.ucHUT_JobAssignNew.RowAffectsCheck = true;
            this.ucHUT_JobAssignNew.SelectCmd = this.JobAssignNew;
            this.ucHUT_JobAssignNew.SelectCmdForUpdate = null;
            this.ucHUT_JobAssignNew.ServerModify = true;
            this.ucHUT_JobAssignNew.ServerModifyGetMax = false;
            this.ucHUT_JobAssignNew.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucHUT_JobAssignNew.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucHUT_JobAssignNew.UseTranscationScope = false;
            this.ucHUT_JobAssignNew.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // AssignNotes
            // 
            this.AssignNotes.CacheConnection = false;
            this.AssignNotes.CommandText = "SELECT [HUT_AssignNotes].* FROM [HUT_AssignNotes]";
            this.AssignNotes.CommandTimeout = 30;
            this.AssignNotes.CommandType = System.Data.CommandType.Text;
            this.AssignNotes.DynamicTableName = false;
            this.AssignNotes.EEPAlias = null;
            this.AssignNotes.EncodingAfter = null;
            this.AssignNotes.EncodingBefore = "Windows-1252";
            this.AssignNotes.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "AutoKey";
            this.AssignNotes.KeyFields.Add(keyItem4);
            this.AssignNotes.MultiSetWhere = false;
            this.AssignNotes.Name = "AssignNotes";
            this.AssignNotes.NotificationAutoEnlist = false;
            this.AssignNotes.SecExcept = null;
            this.AssignNotes.SecFieldName = null;
            this.AssignNotes.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.AssignNotes.SelectPaging = false;
            this.AssignNotes.SelectTop = 0;
            this.AssignNotes.SiteControl = false;
            this.AssignNotes.SiteFieldName = null;
            this.AssignNotes.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucHUT_AssignNotes
            // 
            this.ucHUT_AssignNotes.AutoTrans = true;
            this.ucHUT_AssignNotes.ExceptJoin = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "AssignNO";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "JobID";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "AssignNotes";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "CreateBy";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CreateDate";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "AssignID";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            this.ucHUT_AssignNotes.FieldAttrs.Add(fieldAttr8);
            this.ucHUT_AssignNotes.FieldAttrs.Add(fieldAttr9);
            this.ucHUT_AssignNotes.FieldAttrs.Add(fieldAttr10);
            this.ucHUT_AssignNotes.FieldAttrs.Add(fieldAttr11);
            this.ucHUT_AssignNotes.FieldAttrs.Add(fieldAttr12);
            this.ucHUT_AssignNotes.FieldAttrs.Add(fieldAttr13);
            this.ucHUT_AssignNotes.LogInfo = null;
            this.ucHUT_AssignNotes.Name = "ucHUT_AssignNotes";
            this.ucHUT_AssignNotes.RowAffectsCheck = true;
            this.ucHUT_AssignNotes.SelectCmd = this.AssignNotes;
            this.ucHUT_AssignNotes.SelectCmdForUpdate = null;
            this.ucHUT_AssignNotes.ServerModify = true;
            this.ucHUT_AssignNotes.ServerModifyGetMax = true;
            this.ucHUT_AssignNotes.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucHUT_AssignNotes.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucHUT_AssignNotes.UseTranscationScope = false;
            this.ucHUT_AssignNotes.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // idHUT_JobAssignNew_HUT_AssignNotes
            // 
            this.idHUT_JobAssignNew_HUT_AssignNotes.Detail = this.AssignNotes;
            columnItem1.FieldName = "AssignNO";
            this.idHUT_JobAssignNew_HUT_AssignNotes.DetailColumns.Add(columnItem1);
            this.idHUT_JobAssignNew_HUT_AssignNotes.DynamicTableName = false;
            this.idHUT_JobAssignNew_HUT_AssignNotes.Master = this.JobAssignNew;
            columnItem2.FieldName = "AssignNO";
            this.idHUT_JobAssignNew_HUT_AssignNotes.MasterColumns.Add(columnItem2);
            // 
            // autoNumber1
            // 
            this.autoNumber1.Active = true;
            this.autoNumber1.AutoNoID = "NotesAutoKey";
            this.autoNumber1.Description = null;
            this.autoNumber1.GetFixed = "";
            this.autoNumber1.isNumFill = true;
            this.autoNumber1.Name = "autoNumber1";
            this.autoNumber1.Number = null;
            this.autoNumber1.NumDig = 1;
            this.autoNumber1.OldVersion = false;
            this.autoNumber1.OverFlow = true;
            this.autoNumber1.StartValue = 1;
            this.autoNumber1.Step = 1;
            this.autoNumber1.TargetColumn = "AutoKey";
            this.autoNumber1.UpdateComp = this.ucHUT_AssignNotes;
            // 
            // AssignLogs
            // 
            this.AssignLogs.CacheConnection = false;
            this.AssignLogs.CommandText = resources.GetString("AssignLogs.CommandText");
            this.AssignLogs.CommandTimeout = 30;
            this.AssignLogs.CommandType = System.Data.CommandType.Text;
            this.AssignLogs.DynamicTableName = false;
            this.AssignLogs.EEPAlias = null;
            this.AssignLogs.EncodingAfter = null;
            this.AssignLogs.EncodingBefore = "Windows-1252";
            this.AssignLogs.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "AssignNO";
            this.AssignLogs.KeyFields.Add(keyItem5);
            this.AssignLogs.MultiSetWhere = false;
            this.AssignLogs.Name = "AssignLogs";
            this.AssignLogs.NotificationAutoEnlist = false;
            this.AssignLogs.SecExcept = null;
            this.AssignLogs.SecFieldName = null;
            this.AssignLogs.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.AssignLogs.SelectPaging = false;
            this.AssignLogs.SelectTop = 0;
            this.AssignLogs.SiteControl = false;
            this.AssignLogs.SiteFieldName = null;
            this.AssignLogs.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoIndustryType
            // 
            this.infoIndustryType.CacheConnection = false;
            this.infoIndustryType.CommandText = null;
            this.infoIndustryType.CommandTimeout = 30;
            this.infoIndustryType.CommandType = System.Data.CommandType.Text;
            this.infoIndustryType.DynamicTableName = false;
            this.infoIndustryType.EEPAlias = null;
            this.infoIndustryType.EncodingAfter = null;
            this.infoIndustryType.EncodingBefore = "Windows-1252";
            this.infoIndustryType.InfoConnection = this.InfoConnection1;
            this.infoIndustryType.MultiSetWhere = false;
            this.infoIndustryType.Name = "infoIndustryType";
            this.infoIndustryType.NotificationAutoEnlist = false;
            this.infoIndustryType.SecExcept = null;
            this.infoIndustryType.SecFieldName = null;
            this.infoIndustryType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoIndustryType.SelectPaging = false;
            this.infoIndustryType.SelectTop = 0;
            this.infoIndustryType.SiteControl = false;
            this.infoIndustryType.SiteFieldName = null;
            this.infoIndustryType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucQueryResult
            // 
            this.ucQueryResult.AutoTrans = true;
            this.ucQueryResult.ExceptJoin = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "UserID";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "NameC";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "NameE";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "Birthday";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "eMail1";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "eMail2";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "Gender";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "Height";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "Weight";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "BloodType";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "MarriageStatus";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "Country1";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "ArmyStatus";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "MobileNo1";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "MobileArea1";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "MobileNo2";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "MobileArea2";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "PhoneNo";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "DrivingLicense";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "Traffic";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "IMType";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "IMAccount";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "Address1";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "Address2";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "ExpPay";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "ExpDutyDt";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "ExpDutyArea";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "EduID1";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "SchoolName1";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "SchoolArea1";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "EduSubject1";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "Department1";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "GraduateYear1";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "GradStatus1";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "EduID2";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "SchoolName2";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "SchoolArea2";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "EduSubject2";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "Department2";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "GraduateYear2";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "GradStatus2";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "EduID3";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "SchoolName3";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "SchoolArea3";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "EduSubject3";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "Department3";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "GraduateYear3";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "GradStatus3";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "DocFile1";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = null;
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "DocFile2";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr63.DefaultValue = null;
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "DocFile3";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr64.DefaultValue = null;
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "PhotoFile";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = null;
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "ExcelFile";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = null;
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "CreateBy";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr67.DefaultValue = null;
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "CreateDate";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr68.DefaultValue = null;
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            fieldAttr69.CheckNull = false;
            fieldAttr69.DataField = "LastUpdateBy";
            fieldAttr69.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr69.DefaultValue = null;
            fieldAttr69.TrimLength = 0;
            fieldAttr69.UpdateEnable = true;
            fieldAttr69.WhereMode = true;
            fieldAttr70.CheckNull = false;
            fieldAttr70.DataField = "LastUpdateDate";
            fieldAttr70.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr70.DefaultValue = null;
            fieldAttr70.TrimLength = 0;
            fieldAttr70.UpdateEnable = true;
            fieldAttr70.WhereMode = true;
            this.ucQueryResult.FieldAttrs.Add(fieldAttr14);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr15);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr16);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr17);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr18);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr19);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr20);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr21);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr22);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr23);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr24);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr25);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr26);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr27);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr28);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr29);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr30);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr31);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr32);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr33);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr34);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr35);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr36);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr37);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr38);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr39);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr40);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr41);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr42);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr43);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr44);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr45);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr46);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr47);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr48);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr49);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr50);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr51);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr52);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr53);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr54);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr55);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr56);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr57);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr58);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr59);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr60);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr61);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr62);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr63);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr64);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr65);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr66);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr67);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr68);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr69);
            this.ucQueryResult.FieldAttrs.Add(fieldAttr70);
            this.ucQueryResult.LogInfo = null;
            this.ucQueryResult.Name = "ucQueryResult";
            this.ucQueryResult.RowAffectsCheck = true;
            this.ucQueryResult.SelectCmd = this.QueryResult;
            this.ucQueryResult.SelectCmdForUpdate = this.QueryResult;
            this.ucQueryResult.ServerModify = true;
            this.ucQueryResult.ServerModifyGetMax = false;
            this.ucQueryResult.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucQueryResult.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucQueryResult.UseTranscationScope = false;
            this.ucQueryResult.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // HUT_UserInterview
            // 
            this.HUT_UserInterview.CacheConnection = false;
            this.HUT_UserInterview.CommandText = "-- //0 履歷指定 => 顯示服務人員,2內部面試=>顯示面談紀錄\r\nSELECT UserID,CreateBy,CreateDate,InterviewC" +
    "ontent FROM dbo.[HUT_JobAssignLogs]\r\nwhere AssignID=2";
            this.HUT_UserInterview.CommandTimeout = 30;
            this.HUT_UserInterview.CommandType = System.Data.CommandType.Text;
            this.HUT_UserInterview.DynamicTableName = false;
            this.HUT_UserInterview.EEPAlias = null;
            this.HUT_UserInterview.EncodingAfter = null;
            this.HUT_UserInterview.EncodingBefore = "Windows-1252";
            this.HUT_UserInterview.InfoConnection = this.InfoConnection1;
            this.HUT_UserInterview.MultiSetWhere = false;
            this.HUT_UserInterview.Name = "HUT_UserInterview";
            this.HUT_UserInterview.NotificationAutoEnlist = false;
            this.HUT_UserInterview.SecExcept = null;
            this.HUT_UserInterview.SecFieldName = null;
            this.HUT_UserInterview.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.HUT_UserInterview.SelectPaging = false;
            this.HUT_UserInterview.SelectTop = 0;
            this.HUT_UserInterview.SiteControl = false;
            this.HUT_UserInterview.SiteFieldName = null;
            this.HUT_UserInterview.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.JobQuery)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.QueryResult)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.AssignStep)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.JobAssignNew)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.AssignNotes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.AssignLogs)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoIndustryType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.HUT_UserInterview)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand JobQuery;
        private Srvtools.InfoCommand QueryResult;
        private Srvtools.InfoCommand AssignStep;
        private Srvtools.InfoCommand JobAssignNew;
        private Srvtools.UpdateComponent ucHUT_JobAssignNew;
        private Srvtools.InfoCommand AssignNotes;
        private Srvtools.UpdateComponent ucHUT_AssignNotes;
        private Srvtools.InfoDataSource idHUT_JobAssignNew_HUT_AssignNotes;
        private Srvtools.AutoNumber autoNumber1;
        private Srvtools.InfoCommand AssignLogs;
        private Srvtools.InfoCommand infoIndustryType;
        private Srvtools.UpdateComponent ucQueryResult;
        private Srvtools.InfoCommand HUT_UserInterview;
    }
}
