namespace _CON_Normal_ContactActivity
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn1 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn2 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn3 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn4 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn5 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn6 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn7 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn8 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn9 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn10 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn11 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn12 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn13 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn14 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn15 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn16 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn17 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn18 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn19 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn20 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn21 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn22 = new Srvtools.SrcFieldNameColumn();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn23 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn24 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn25 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn26 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn27 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn28 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn29 = new Srvtools.SrcFieldNameColumn();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn30 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn31 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn32 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn33 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn34 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn35 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn36 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn37 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn38 = new Srvtools.SrcFieldNameColumn();
            Srvtools.SrcFieldNameColumn srcFieldNameColumn39 = new Srvtools.SrcFieldNameColumn();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.CON_CONTACT_ACTIVITY = new Srvtools.InfoCommand(this.components);
            this.ucCON_CONTACT_ACTIVITY = new Srvtools.UpdateComponent(this.components);
            this.CON_CONTACT_ACTIVITY_LOG = new Srvtools.InfoCommand(this.components);
            this.logInfo_CON_CONTACT_ACTIVITY = new Srvtools.LogInfo(this.components);
            this.ucCON_ACTIVITY_FILE = new Srvtools.UpdateComponent(this.components);
            this.CON_ACTIVITY_FILE = new Srvtools.InfoCommand(this.components);
            this.CON_ACTIVITY_FILE_LOG = new Srvtools.InfoCommand(this.components);
            this.logInfo_CON_ACTIVITY_FILE = new Srvtools.LogInfo(this.components);
            this.CON_ACTIVITY_GIFT = new Srvtools.InfoCommand(this.components);
            this.ucCON_ACTIVITY_GIFT = new Srvtools.UpdateComponent(this.components);
            this.logInfo_CON_ACTIVITY_GIFT = new Srvtools.LogInfo(this.components);
            this.CON_ACTIVITY_GIFT_LOG = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_CONTACT_ACTIVITY)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_CONTACT_ACTIVITY_LOG)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_ACTIVITY_FILE)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_ACTIVITY_FILE_LOG)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_ACTIVITY_GIFT)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_ACTIVITY_GIFT_LOG)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "FileUpload";
            service1.NonLogin = false;
            service1.ServiceName = "FileUpload";
            service2.DelegateName = "checkActivityName";
            service2.NonLogin = false;
            service2.ServiceName = "checkActivityName";
            service3.DelegateName = "checkActivityFileName";
            service3.NonLogin = false;
            service3.ServiceName = "checkActivityFileName";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "WENETGROUP";
            // 
            // CON_CONTACT_ACTIVITY
            // 
            this.CON_CONTACT_ACTIVITY.CacheConnection = false;
            this.CON_CONTACT_ACTIVITY.CommandText = resources.GetString("CON_CONTACT_ACTIVITY.CommandText");
            this.CON_CONTACT_ACTIVITY.CommandTimeout = 30;
            this.CON_CONTACT_ACTIVITY.CommandType = System.Data.CommandType.Text;
            this.CON_CONTACT_ACTIVITY.DynamicTableName = false;
            this.CON_CONTACT_ACTIVITY.EEPAlias = null;
            this.CON_CONTACT_ACTIVITY.EncodingAfter = null;
            this.CON_CONTACT_ACTIVITY.EncodingBefore = "Windows-1252";
            this.CON_CONTACT_ACTIVITY.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CONTACT_ACTIVITY_ID";
            this.CON_CONTACT_ACTIVITY.KeyFields.Add(keyItem1);
            this.CON_CONTACT_ACTIVITY.MultiSetWhere = false;
            this.CON_CONTACT_ACTIVITY.Name = "CON_CONTACT_ACTIVITY";
            this.CON_CONTACT_ACTIVITY.NotificationAutoEnlist = false;
            this.CON_CONTACT_ACTIVITY.SecExcept = null;
            this.CON_CONTACT_ACTIVITY.SecFieldName = null;
            this.CON_CONTACT_ACTIVITY.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CON_CONTACT_ACTIVITY.SelectPaging = false;
            this.CON_CONTACT_ACTIVITY.SelectTop = 0;
            this.CON_CONTACT_ACTIVITY.SiteControl = false;
            this.CON_CONTACT_ACTIVITY.SiteFieldName = null;
            this.CON_CONTACT_ACTIVITY.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucCON_CONTACT_ACTIVITY
            // 
            this.ucCON_CONTACT_ACTIVITY.AutoTrans = true;
            this.ucCON_CONTACT_ACTIVITY.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "CONTACT_ACTIVITY_ID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "CONTACT_ID";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "ACTIVITY_NAME";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "ACTIVITY_YEAR";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "BEGIN_DATE";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "END_DATE";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "BEGIN_TIME";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "END_TIME";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "ACTIVITY_TYPE_ID";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "ACTIVITY_IDENTITY_ID";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "ACTIVITY_CHILD_TYPE_ID";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "ACTIVITY_LEVEL_ID";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "ACTIVITY_STATUS_ID";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "ACTIVITY_EVALUATE_ID";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "ACTIVITY_ADDR";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "ACTIVITY_PERSON";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "ACTIVITY_WORKS";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "ACTIVITY_DESCRIPTION";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "CREATE_MAN";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = "_username";
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "CREATE_DATE";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = "_sysdate";
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "UPDATE_MAN";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr21.DefaultValue = "_username";
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "UPDATE_DATE";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr22.DefaultValue = "_sysdate";
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr1);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr2);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr3);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr4);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr5);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr6);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr7);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr8);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr9);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr10);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr11);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr12);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr13);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr14);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr15);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr16);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr17);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr18);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr19);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr20);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr21);
            this.ucCON_CONTACT_ACTIVITY.FieldAttrs.Add(fieldAttr22);
            this.ucCON_CONTACT_ACTIVITY.LogInfo = null;
            this.ucCON_CONTACT_ACTIVITY.Name = "ucCON_CONTACT_ACTIVITY";
            this.ucCON_CONTACT_ACTIVITY.RowAffectsCheck = true;
            this.ucCON_CONTACT_ACTIVITY.SelectCmd = this.CON_CONTACT_ACTIVITY;
            this.ucCON_CONTACT_ACTIVITY.SelectCmdForUpdate = null;
            this.ucCON_CONTACT_ACTIVITY.ServerModify = true;
            this.ucCON_CONTACT_ACTIVITY.ServerModifyGetMax = false;
            this.ucCON_CONTACT_ACTIVITY.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucCON_CONTACT_ACTIVITY.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucCON_CONTACT_ACTIVITY.UseTranscationScope = false;
            this.ucCON_CONTACT_ACTIVITY.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucCON_CONTACT_ACTIVITY.AfterInsert += new Srvtools.UpdateComponentAfterInsertEventHandler(this.ucCON_CONTACT_ACTIVITY_AfterInsert);
            this.ucCON_CONTACT_ACTIVITY.AfterDelete += new Srvtools.UpdateComponentAfterDeleteEventHandler(this.ucCON_CONTACT_ACTIVITY_AfterDelete);
            this.ucCON_CONTACT_ACTIVITY.AfterModify += new Srvtools.UpdateComponentAfterModifyEventHandler(this.ucCON_CONTACT_ACTIVITY_AfterModify);
            // 
            // CON_CONTACT_ACTIVITY_LOG
            // 
            this.CON_CONTACT_ACTIVITY_LOG.CacheConnection = false;
            this.CON_CONTACT_ACTIVITY_LOG.CommandText = resources.GetString("CON_CONTACT_ACTIVITY_LOG.CommandText");
            this.CON_CONTACT_ACTIVITY_LOG.CommandTimeout = 30;
            this.CON_CONTACT_ACTIVITY_LOG.CommandType = System.Data.CommandType.Text;
            this.CON_CONTACT_ACTIVITY_LOG.DynamicTableName = false;
            this.CON_CONTACT_ACTIVITY_LOG.EEPAlias = null;
            this.CON_CONTACT_ACTIVITY_LOG.EncodingAfter = null;
            this.CON_CONTACT_ACTIVITY_LOG.EncodingBefore = "Windows-1252";
            this.CON_CONTACT_ACTIVITY_LOG.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "LOG_ID";
            this.CON_CONTACT_ACTIVITY_LOG.KeyFields.Add(keyItem2);
            this.CON_CONTACT_ACTIVITY_LOG.MultiSetWhere = false;
            this.CON_CONTACT_ACTIVITY_LOG.Name = "CON_CONTACT_ACTIVITY_LOG";
            this.CON_CONTACT_ACTIVITY_LOG.NotificationAutoEnlist = false;
            this.CON_CONTACT_ACTIVITY_LOG.SecExcept = null;
            this.CON_CONTACT_ACTIVITY_LOG.SecFieldName = null;
            this.CON_CONTACT_ACTIVITY_LOG.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CON_CONTACT_ACTIVITY_LOG.SelectPaging = false;
            this.CON_CONTACT_ACTIVITY_LOG.SelectTop = 0;
            this.CON_CONTACT_ACTIVITY_LOG.SiteControl = false;
            this.CON_CONTACT_ACTIVITY_LOG.SiteFieldName = null;
            this.CON_CONTACT_ACTIVITY_LOG.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // logInfo_CON_CONTACT_ACTIVITY
            // 
            this.logInfo_CON_CONTACT_ACTIVITY.LogDateType = null;
            this.logInfo_CON_CONTACT_ACTIVITY.LogIDField = "LOG_ID";
            this.logInfo_CON_CONTACT_ACTIVITY.LogTableName = "CON_CONTACT_ACTIVITY_LOG";
            this.logInfo_CON_CONTACT_ACTIVITY.MarkField = "LOG_STATE";
            this.logInfo_CON_CONTACT_ACTIVITY.ModifierField = "LOG_USER";
            this.logInfo_CON_CONTACT_ACTIVITY.ModifyDateField = "LOG_DATE";
            this.logInfo_CON_CONTACT_ACTIVITY.Name = "logInfo_CON_CONTACT_ACTIVITY";
            this.logInfo_CON_CONTACT_ACTIVITY.NeedLog = true;
            this.logInfo_CON_CONTACT_ACTIVITY.OnlyDistinct = false;
            srcFieldNameColumn1.FieldName = "CONTACT_ACTIVITY_ID";
            srcFieldNameColumn2.FieldName = "CONTACT_ID";
            srcFieldNameColumn3.FieldName = "ACTIVITY_NAME";
            srcFieldNameColumn4.FieldName = "ACTIVITY_YEAR";
            srcFieldNameColumn5.FieldName = "BEGIN_DATE";
            srcFieldNameColumn6.FieldName = "END_DATE";
            srcFieldNameColumn7.FieldName = "BEGIN_TIME";
            srcFieldNameColumn8.FieldName = "END_TIME";
            srcFieldNameColumn9.FieldName = "ACTIVITY_TYPE_ID";
            srcFieldNameColumn10.FieldName = "ACTIVITY_IDENTITY_ID";
            srcFieldNameColumn11.FieldName = "ACTIVITY_CHILD_TYPE_ID";
            srcFieldNameColumn12.FieldName = "ACTIVITY_LEVEL_ID";
            srcFieldNameColumn13.FieldName = "ACTIVITY_STATUS_ID";
            srcFieldNameColumn14.FieldName = "ACTIVITY_EVALUATE_ID";
            srcFieldNameColumn15.FieldName = "ACTIVITY_ADDR";
            srcFieldNameColumn16.FieldName = "ACTIVITY_PERSON";
            srcFieldNameColumn17.FieldName = "ACTIVITY_WORKS";
            srcFieldNameColumn18.FieldName = "ACTIVITY_DESCRIPTION";
            srcFieldNameColumn19.FieldName = "CREATE_MAN";
            srcFieldNameColumn20.FieldName = "CREATE_DATE";
            srcFieldNameColumn21.FieldName = "UPDATE_MAN";
            srcFieldNameColumn22.FieldName = "UPDATE_DATE";
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn1);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn2);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn3);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn4);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn5);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn6);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn7);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn8);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn9);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn10);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn11);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn12);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn13);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn14);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn15);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn16);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn17);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn18);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn19);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn20);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn21);
            this.logInfo_CON_CONTACT_ACTIVITY.SrcFieldNames.Add(srcFieldNameColumn22);
            // 
            // ucCON_ACTIVITY_FILE
            // 
            this.ucCON_ACTIVITY_FILE.AutoTrans = true;
            this.ucCON_ACTIVITY_FILE.ExceptJoin = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "ACTIVITY_FILE_ID";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "CONTACT_ACTIVITY_ID";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "ACTIVIT_FILE";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "CREATE_MAN";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = "_username";
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "CREATE_DATE";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = "_sysdate";
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "UPDATE_MAN";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr28.DefaultValue = "_username";
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "UPDATE_DATE";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr29.DefaultValue = "_sysdate";
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            this.ucCON_ACTIVITY_FILE.FieldAttrs.Add(fieldAttr23);
            this.ucCON_ACTIVITY_FILE.FieldAttrs.Add(fieldAttr24);
            this.ucCON_ACTIVITY_FILE.FieldAttrs.Add(fieldAttr25);
            this.ucCON_ACTIVITY_FILE.FieldAttrs.Add(fieldAttr26);
            this.ucCON_ACTIVITY_FILE.FieldAttrs.Add(fieldAttr27);
            this.ucCON_ACTIVITY_FILE.FieldAttrs.Add(fieldAttr28);
            this.ucCON_ACTIVITY_FILE.FieldAttrs.Add(fieldAttr29);
            this.ucCON_ACTIVITY_FILE.LogInfo = null;
            this.ucCON_ACTIVITY_FILE.Name = "ucCON_ACTIVITY_FILE";
            this.ucCON_ACTIVITY_FILE.RowAffectsCheck = true;
            this.ucCON_ACTIVITY_FILE.SelectCmd = this.CON_ACTIVITY_FILE;
            this.ucCON_ACTIVITY_FILE.SelectCmdForUpdate = null;
            this.ucCON_ACTIVITY_FILE.ServerModify = true;
            this.ucCON_ACTIVITY_FILE.ServerModifyGetMax = false;
            this.ucCON_ACTIVITY_FILE.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucCON_ACTIVITY_FILE.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucCON_ACTIVITY_FILE.UseTranscationScope = false;
            this.ucCON_ACTIVITY_FILE.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucCON_ACTIVITY_FILE.AfterInsert += new Srvtools.UpdateComponentAfterInsertEventHandler(this.ucCON_ACTIVITY_FILE_AfterInsert);
            this.ucCON_ACTIVITY_FILE.AfterDelete += new Srvtools.UpdateComponentAfterDeleteEventHandler(this.ucCON_ACTIVITY_FILE_AfterDelete);
            this.ucCON_ACTIVITY_FILE.AfterModify += new Srvtools.UpdateComponentAfterModifyEventHandler(this.ucCON_ACTIVITY_FILE_AfterModify);
            // 
            // CON_ACTIVITY_FILE
            // 
            this.CON_ACTIVITY_FILE.CacheConnection = false;
            this.CON_ACTIVITY_FILE.CommandText = "SELECT A.*,\r\nACTIVITY.ACTIVITY_NAME\r\nFROM CON_ACTIVITY_FILE A\r\nleft join CON_CONT" +
    "ACT_ACTIVITY ACTIVITY ON ACTIVITY.CONTACT_ACTIVITY_ID = A.CONTACT_ACTIVITY_ID";
            this.CON_ACTIVITY_FILE.CommandTimeout = 30;
            this.CON_ACTIVITY_FILE.CommandType = System.Data.CommandType.Text;
            this.CON_ACTIVITY_FILE.DynamicTableName = false;
            this.CON_ACTIVITY_FILE.EEPAlias = null;
            this.CON_ACTIVITY_FILE.EncodingAfter = null;
            this.CON_ACTIVITY_FILE.EncodingBefore = "Windows-1252";
            this.CON_ACTIVITY_FILE.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "ACTIVITY_FILE_ID";
            this.CON_ACTIVITY_FILE.KeyFields.Add(keyItem3);
            this.CON_ACTIVITY_FILE.MultiSetWhere = false;
            this.CON_ACTIVITY_FILE.Name = "CON_ACTIVITY_FILE";
            this.CON_ACTIVITY_FILE.NotificationAutoEnlist = false;
            this.CON_ACTIVITY_FILE.SecExcept = null;
            this.CON_ACTIVITY_FILE.SecFieldName = null;
            this.CON_ACTIVITY_FILE.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CON_ACTIVITY_FILE.SelectPaging = false;
            this.CON_ACTIVITY_FILE.SelectTop = 0;
            this.CON_ACTIVITY_FILE.SiteControl = false;
            this.CON_ACTIVITY_FILE.SiteFieldName = null;
            this.CON_ACTIVITY_FILE.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CON_ACTIVITY_FILE_LOG
            // 
            this.CON_ACTIVITY_FILE_LOG.CacheConnection = false;
            this.CON_ACTIVITY_FILE_LOG.CommandText = resources.GetString("CON_ACTIVITY_FILE_LOG.CommandText");
            this.CON_ACTIVITY_FILE_LOG.CommandTimeout = 30;
            this.CON_ACTIVITY_FILE_LOG.CommandType = System.Data.CommandType.Text;
            this.CON_ACTIVITY_FILE_LOG.DynamicTableName = false;
            this.CON_ACTIVITY_FILE_LOG.EEPAlias = null;
            this.CON_ACTIVITY_FILE_LOG.EncodingAfter = null;
            this.CON_ACTIVITY_FILE_LOG.EncodingBefore = "Windows-1252";
            this.CON_ACTIVITY_FILE_LOG.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "LOG_ID";
            this.CON_ACTIVITY_FILE_LOG.KeyFields.Add(keyItem4);
            this.CON_ACTIVITY_FILE_LOG.MultiSetWhere = false;
            this.CON_ACTIVITY_FILE_LOG.Name = "CON_ACTIVITY_FILE_LOG";
            this.CON_ACTIVITY_FILE_LOG.NotificationAutoEnlist = false;
            this.CON_ACTIVITY_FILE_LOG.SecExcept = null;
            this.CON_ACTIVITY_FILE_LOG.SecFieldName = null;
            this.CON_ACTIVITY_FILE_LOG.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CON_ACTIVITY_FILE_LOG.SelectPaging = false;
            this.CON_ACTIVITY_FILE_LOG.SelectTop = 0;
            this.CON_ACTIVITY_FILE_LOG.SiteControl = false;
            this.CON_ACTIVITY_FILE_LOG.SiteFieldName = null;
            this.CON_ACTIVITY_FILE_LOG.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // logInfo_CON_ACTIVITY_FILE
            // 
            this.logInfo_CON_ACTIVITY_FILE.LogDateType = null;
            this.logInfo_CON_ACTIVITY_FILE.LogIDField = "LOG_ID";
            this.logInfo_CON_ACTIVITY_FILE.LogTableName = "CON_ACTIVITY_FILE_LOG";
            this.logInfo_CON_ACTIVITY_FILE.MarkField = "LOG_STATE";
            this.logInfo_CON_ACTIVITY_FILE.ModifierField = "LOG_USER";
            this.logInfo_CON_ACTIVITY_FILE.ModifyDateField = "LOG_DATE";
            this.logInfo_CON_ACTIVITY_FILE.Name = "logInfo_CON_ACTIVITY_FILE";
            this.logInfo_CON_ACTIVITY_FILE.NeedLog = true;
            this.logInfo_CON_ACTIVITY_FILE.OnlyDistinct = false;
            srcFieldNameColumn23.FieldName = "ACTIVITY_FILE_ID";
            srcFieldNameColumn24.FieldName = "CONTACT_ACTIVITY_ID";
            srcFieldNameColumn25.FieldName = "ACTIVIT_FILE";
            srcFieldNameColumn26.FieldName = "CREATE_MAN";
            srcFieldNameColumn27.FieldName = "CREATE_DATE";
            srcFieldNameColumn28.FieldName = "UPDATE_MAN";
            srcFieldNameColumn29.FieldName = "UPDATE_DATE";
            this.logInfo_CON_ACTIVITY_FILE.SrcFieldNames.Add(srcFieldNameColumn23);
            this.logInfo_CON_ACTIVITY_FILE.SrcFieldNames.Add(srcFieldNameColumn24);
            this.logInfo_CON_ACTIVITY_FILE.SrcFieldNames.Add(srcFieldNameColumn25);
            this.logInfo_CON_ACTIVITY_FILE.SrcFieldNames.Add(srcFieldNameColumn26);
            this.logInfo_CON_ACTIVITY_FILE.SrcFieldNames.Add(srcFieldNameColumn27);
            this.logInfo_CON_ACTIVITY_FILE.SrcFieldNames.Add(srcFieldNameColumn28);
            this.logInfo_CON_ACTIVITY_FILE.SrcFieldNames.Add(srcFieldNameColumn29);
            // 
            // CON_ACTIVITY_GIFT
            // 
            this.CON_ACTIVITY_GIFT.CacheConnection = false;
            this.CON_ACTIVITY_GIFT.CommandText = resources.GetString("CON_ACTIVITY_GIFT.CommandText");
            this.CON_ACTIVITY_GIFT.CommandTimeout = 30;
            this.CON_ACTIVITY_GIFT.CommandType = System.Data.CommandType.Text;
            this.CON_ACTIVITY_GIFT.DynamicTableName = false;
            this.CON_ACTIVITY_GIFT.EEPAlias = null;
            this.CON_ACTIVITY_GIFT.EncodingAfter = null;
            this.CON_ACTIVITY_GIFT.EncodingBefore = "Windows-1252";
            this.CON_ACTIVITY_GIFT.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "ACTIVITY_GIFT_ID";
            this.CON_ACTIVITY_GIFT.KeyFields.Add(keyItem5);
            this.CON_ACTIVITY_GIFT.MultiSetWhere = false;
            this.CON_ACTIVITY_GIFT.Name = "CON_ACTIVITY_GIFT";
            this.CON_ACTIVITY_GIFT.NotificationAutoEnlist = false;
            this.CON_ACTIVITY_GIFT.SecExcept = null;
            this.CON_ACTIVITY_GIFT.SecFieldName = null;
            this.CON_ACTIVITY_GIFT.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CON_ACTIVITY_GIFT.SelectPaging = false;
            this.CON_ACTIVITY_GIFT.SelectTop = 0;
            this.CON_ACTIVITY_GIFT.SiteControl = false;
            this.CON_ACTIVITY_GIFT.SiteFieldName = null;
            this.CON_ACTIVITY_GIFT.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucCON_ACTIVITY_GIFT
            // 
            this.ucCON_ACTIVITY_GIFT.AutoTrans = true;
            this.ucCON_ACTIVITY_GIFT.ExceptJoin = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "ACTIVITY_GIFT_ID";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "CONTACT_ACTIVITY_ID";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "GIFT_LEVEL_ID";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "GIFT_NAME";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "GIFT_PRICE";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "GIFT_MEMO";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "CREATE_MAN";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = "_username";
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "CREATE_DATE";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = "_sysdate";
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "UPDATE_MAN";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = "_username";
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "UPDATE_DATE";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = "_sysdate";
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr30);
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr31);
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr32);
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr33);
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr34);
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr35);
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr36);
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr37);
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr38);
            this.ucCON_ACTIVITY_GIFT.FieldAttrs.Add(fieldAttr39);
            this.ucCON_ACTIVITY_GIFT.LogInfo = null;
            this.ucCON_ACTIVITY_GIFT.Name = "ucCON_ACTIVITY_GIFT";
            this.ucCON_ACTIVITY_GIFT.RowAffectsCheck = true;
            this.ucCON_ACTIVITY_GIFT.SelectCmd = this.CON_ACTIVITY_GIFT;
            this.ucCON_ACTIVITY_GIFT.SelectCmdForUpdate = null;
            this.ucCON_ACTIVITY_GIFT.ServerModify = true;
            this.ucCON_ACTIVITY_GIFT.ServerModifyGetMax = false;
            this.ucCON_ACTIVITY_GIFT.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucCON_ACTIVITY_GIFT.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucCON_ACTIVITY_GIFT.UseTranscationScope = false;
            this.ucCON_ACTIVITY_GIFT.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucCON_ACTIVITY_GIFT.AfterInsert += new Srvtools.UpdateComponentAfterInsertEventHandler(this.ucCON_ACTIVITY_GIFT_AfterInsert);
            this.ucCON_ACTIVITY_GIFT.AfterDelete += new Srvtools.UpdateComponentAfterDeleteEventHandler(this.ucCON_ACTIVITY_GIFT_AfterDelete);
            this.ucCON_ACTIVITY_GIFT.AfterModify += new Srvtools.UpdateComponentAfterModifyEventHandler(this.ucCON_ACTIVITY_GIFT_AfterModify);
            // 
            // logInfo_CON_ACTIVITY_GIFT
            // 
            this.logInfo_CON_ACTIVITY_GIFT.LogDateType = null;
            this.logInfo_CON_ACTIVITY_GIFT.LogIDField = "Log_ID";
            this.logInfo_CON_ACTIVITY_GIFT.LogTableName = "CON_ACTIVITY_GIFT_LOG";
            this.logInfo_CON_ACTIVITY_GIFT.MarkField = "Log_State";
            this.logInfo_CON_ACTIVITY_GIFT.ModifierField = "Log_User";
            this.logInfo_CON_ACTIVITY_GIFT.ModifyDateField = "Log_Date";
            this.logInfo_CON_ACTIVITY_GIFT.Name = "logInfo_CON_ACTIVITY_GIFT";
            this.logInfo_CON_ACTIVITY_GIFT.NeedLog = true;
            this.logInfo_CON_ACTIVITY_GIFT.OnlyDistinct = true;
            srcFieldNameColumn30.FieldName = "ACTIVITY_GIFT_ID";
            srcFieldNameColumn31.FieldName = "CONTACT_ACTIVITY_ID";
            srcFieldNameColumn32.FieldName = "GIFT_LEVEL_ID";
            srcFieldNameColumn33.FieldName = "GIFT_NAME";
            srcFieldNameColumn34.FieldName = "GIFT_PRICE";
            srcFieldNameColumn35.FieldName = "GIFT_MEMO";
            srcFieldNameColumn36.FieldName = "CREATE_MAN";
            srcFieldNameColumn37.FieldName = "CREATE_DATE";
            srcFieldNameColumn38.FieldName = "UPDATE_MAN";
            srcFieldNameColumn39.FieldName = "UPDATE_DATE";
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn30);
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn31);
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn32);
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn33);
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn34);
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn35);
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn36);
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn37);
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn38);
            this.logInfo_CON_ACTIVITY_GIFT.SrcFieldNames.Add(srcFieldNameColumn39);
            // 
            // CON_ACTIVITY_GIFT_LOG
            // 
            this.CON_ACTIVITY_GIFT_LOG.CacheConnection = false;
            this.CON_ACTIVITY_GIFT_LOG.CommandText = resources.GetString("CON_ACTIVITY_GIFT_LOG.CommandText");
            this.CON_ACTIVITY_GIFT_LOG.CommandTimeout = 30;
            this.CON_ACTIVITY_GIFT_LOG.CommandType = System.Data.CommandType.Text;
            this.CON_ACTIVITY_GIFT_LOG.DynamicTableName = false;
            this.CON_ACTIVITY_GIFT_LOG.EEPAlias = null;
            this.CON_ACTIVITY_GIFT_LOG.EncodingAfter = null;
            this.CON_ACTIVITY_GIFT_LOG.EncodingBefore = "Windows-1252";
            this.CON_ACTIVITY_GIFT_LOG.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "LOG_ID";
            this.CON_ACTIVITY_GIFT_LOG.KeyFields.Add(keyItem6);
            this.CON_ACTIVITY_GIFT_LOG.MultiSetWhere = false;
            this.CON_ACTIVITY_GIFT_LOG.Name = "CON_ACTIVITY_GIFT_LOG";
            this.CON_ACTIVITY_GIFT_LOG.NotificationAutoEnlist = false;
            this.CON_ACTIVITY_GIFT_LOG.SecExcept = null;
            this.CON_ACTIVITY_GIFT_LOG.SecFieldName = null;
            this.CON_ACTIVITY_GIFT_LOG.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CON_ACTIVITY_GIFT_LOG.SelectPaging = false;
            this.CON_ACTIVITY_GIFT_LOG.SelectTop = 0;
            this.CON_ACTIVITY_GIFT_LOG.SiteControl = false;
            this.CON_ACTIVITY_GIFT_LOG.SiteFieldName = null;
            this.CON_ACTIVITY_GIFT_LOG.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_CONTACT_ACTIVITY)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_CONTACT_ACTIVITY_LOG)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_ACTIVITY_FILE)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_ACTIVITY_FILE_LOG)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_ACTIVITY_GIFT)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CON_ACTIVITY_GIFT_LOG)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand CON_CONTACT_ACTIVITY;
        private Srvtools.UpdateComponent ucCON_CONTACT_ACTIVITY;
        private Srvtools.InfoCommand CON_CONTACT_ACTIVITY_LOG;
        private Srvtools.LogInfo logInfo_CON_CONTACT_ACTIVITY;
        private Srvtools.UpdateComponent ucCON_ACTIVITY_FILE;
        private Srvtools.InfoCommand CON_ACTIVITY_FILE;
        private Srvtools.InfoCommand CON_ACTIVITY_FILE_LOG;
        private Srvtools.LogInfo logInfo_CON_ACTIVITY_FILE;
        private Srvtools.InfoCommand CON_ACTIVITY_GIFT;
        private Srvtools.UpdateComponent ucCON_ACTIVITY_GIFT;
        private Srvtools.LogInfo logInfo_CON_ACTIVITY_GIFT;
        private Srvtools.InfoCommand CON_ACTIVITY_GIFT_LOG;
    }
}
