namespace sERPSalesInvoices
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            Srvtools.Service service9 = new Srvtools.Service();
            Srvtools.Service service10 = new Srvtools.Service();
            Srvtools.Service service11 = new Srvtools.Service();
            Srvtools.Service service12 = new Srvtools.Service();
            Srvtools.Service service13 = new Srvtools.Service();
            Srvtools.Service service14 = new Srvtools.Service();
            Srvtools.Service service15 = new Srvtools.Service();
            Srvtools.Service service16 = new Srvtools.Service();
            Srvtools.Service service17 = new Srvtools.Service();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.ColumnItem columnItem1 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem2 = new Srvtools.ColumnItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem14 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem15 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem16 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem17 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem18 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem19 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem20 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem21 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem22 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr69 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr70 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem23 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem24 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem25 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem26 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem27 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.SalesMaster = new Srvtools.InfoCommand(this.components);
            this.ucSalesMaster = new Srvtools.UpdateComponent(this.components);
            this.SalesDetails = new Srvtools.InfoCommand(this.components);
            this.ucSalesDetails = new Srvtools.UpdateComponent(this.components);
            this.idSalesMaster_SalesDetails = new Srvtools.InfoDataSource(this.components);
            this.View_SalesMaster = new Srvtools.InfoCommand(this.components);
            this.InsGroup = new Srvtools.InfoCommand(this.components);
            this.Customer = new Srvtools.InfoCommand(this.components);
            this.SalesType = new Srvtools.InfoCommand(this.components);
            this.TaxType = new Srvtools.InfoCommand(this.components);
            this.SalesPerson = new Srvtools.InfoCommand(this.components);
            this.SalesKind = new Srvtools.InfoCommand(this.components);
            this.InvoiceType = new Srvtools.InfoCommand(this.components);
            this.SalesUploadCode = new Srvtools.InfoCommand(this.components);
            this.QInvoiceType = new Srvtools.InfoCommand(this.components);
            this.Employer = new Srvtools.InfoCommand(this.components);
            this.CustomerSaleType = new Srvtools.InfoCommand(this.components);
            this.SalesDetails_SalesTypeName = new Srvtools.InfoCommand(this.components);
            this.DonateMark = new Srvtools.InfoCommand(this.components);
            this.CarrierType = new Srvtools.InfoCommand(this.components);
            this.FeeItem = new Srvtools.InfoCommand(this.components);
            this.SalesDetailsMasterTemp = new Srvtools.InfoCommand(this.components);
            this.ucSalesDetailsMasterTemp = new Srvtools.UpdateComponent(this.components);
            this.PayWay = new Srvtools.InfoCommand(this.components);
            this.SalesDetails1 = new Srvtools.InfoCommand(this.components);
            this.ucSalesDetails1 = new Srvtools.UpdateComponent(this.components);
            this.QCustomer = new Srvtools.InfoCommand(this.components);
            this.QEmployer = new Srvtools.InfoCommand(this.components);
            this.SalesItem = new Srvtools.InfoCommand(this.components);
            this.QSalesPerson = new Srvtools.InfoCommand(this.components);
            this.QInvoiceYM = new Srvtools.InfoCommand(this.components);
            this.CustomerSaleTypeForApply = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_SalesMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsGroup)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Customer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TaxType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesPerson)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesKind)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.InvoiceType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesUploadCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.QInvoiceType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Employer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerSaleType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDetails_SalesTypeName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DonateMark)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CarrierType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.FeeItem)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDetailsMasterTemp)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayWay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDetails1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.QCustomer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.QEmployer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesItem)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.QSalesPerson)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.QInvoiceYM)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerSaleTypeForApply)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "GetSalesNO";
            service1.NonLogin = false;
            service1.ServiceName = "GetSalesNO";
            service2.DelegateName = "procCallApi_Create";
            service2.NonLogin = false;
            service2.ServiceName = "procCallApi_Create";
            service3.DelegateName = "procCallApi_Cancel";
            service3.NonLogin = false;
            service3.ServiceName = "procCallApi_Cancel";
            service4.DelegateName = "procCreateReceipt";
            service4.NonLogin = false;
            service4.ServiceName = "procCreateReceipt";
            service5.DelegateName = "selectCustomerSaleType";
            service5.NonLogin = false;
            service5.ServiceName = "selectCustomerSaleType";
            service6.DelegateName = "updateSalesMasterIsActive";
            service6.NonLogin = false;
            service6.ServiceName = "updateSalesMasterIsActive";
            service7.DelegateName = "procDeleteSales";
            service7.NonLogin = false;
            service7.ServiceName = "procDeleteSales";
            service8.DelegateName = "BatchInsertTemp";
            service8.NonLogin = false;
            service8.ServiceName = "BatchInsertTemp";
            service9.DelegateName = "DeleteSalesDetailsMasterTemp";
            service9.NonLogin = false;
            service9.ServiceName = "DeleteSalesDetailsMasterTemp";
            service10.DelegateName = "BatchInsertSales";
            service10.NonLogin = false;
            service10.ServiceName = "BatchInsertSales";
            service11.DelegateName = "UpdateSalesDetailsMasterTemp";
            service11.NonLogin = false;
            service11.ServiceName = "UpdateSalesDetailsMasterTemp";
            service12.DelegateName = "SelectRoomerFeeItems";
            service12.NonLogin = false;
            service12.ServiceName = "SelectRoomerFeeItems";
            service13.DelegateName = "Receipt_Cancel";
            service13.NonLogin = false;
            service13.ServiceName = "Receipt_Cancel";
            service14.DelegateName = "selectRemarkAndTaxNO";
            service14.NonLogin = false;
            service14.ServiceName = "selectRemarkAndTaxNO";
            service15.DelegateName = "GetUserOrgNOs";
            service15.NonLogin = false;
            service15.ServiceName = "GetUserOrgNOs";
            service16.DelegateName = "HandWriteInvoice_Cancel";
            service16.NonLogin = false;
            service16.ServiceName = "HandWriteInvoice_Cancel";
            service17.DelegateName = "CheckInvoiceNOIsInWarrantDetails";
            service17.NonLogin = false;
            service17.ServiceName = "CheckInvoiceNOIsInWarrantDetails";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            this.serviceManager1.ServiceCollection.Add(service9);
            this.serviceManager1.ServiceCollection.Add(service10);
            this.serviceManager1.ServiceCollection.Add(service11);
            this.serviceManager1.ServiceCollection.Add(service12);
            this.serviceManager1.ServiceCollection.Add(service13);
            this.serviceManager1.ServiceCollection.Add(service14);
            this.serviceManager1.ServiceCollection.Add(service15);
            this.serviceManager1.ServiceCollection.Add(service16);
            this.serviceManager1.ServiceCollection.Add(service17);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBERP";
            // 
            // SalesMaster
            // 
            this.SalesMaster.CacheConnection = false;
            this.SalesMaster.CommandText = "select * from View_sSalesInvoice_SalesMaster \r\nOrder by SalesNO";
            this.SalesMaster.CommandTimeout = 30;
            this.SalesMaster.CommandType = System.Data.CommandType.Text;
            this.SalesMaster.DynamicTableName = false;
            this.SalesMaster.EEPAlias = "JBERP";
            this.SalesMaster.EncodingAfter = null;
            this.SalesMaster.EncodingBefore = "Windows-1252";
            this.SalesMaster.EncodingConvert = null;
            this.SalesMaster.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "SalesNO";
            this.SalesMaster.KeyFields.Add(keyItem1);
            this.SalesMaster.MultiSetWhere = false;
            this.SalesMaster.Name = "SalesMaster";
            this.SalesMaster.NotificationAutoEnlist = false;
            this.SalesMaster.SecExcept = null;
            this.SalesMaster.SecFieldName = null;
            this.SalesMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesMaster.SelectPaging = false;
            this.SalesMaster.SelectTop = 0;
            this.SalesMaster.SiteControl = false;
            this.SalesMaster.SiteFieldName = null;
            this.SalesMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucSalesMaster
            // 
            this.ucSalesMaster.AutoTrans = true;
            this.ucSalesMaster.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "SalesNO";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "CustomerID";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "SalesDate";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "SalesID";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "DonateMarkID";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "InvoiceType";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "CarrierType";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "CarrierID1";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "CarrierID2";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "NPOBAN";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "TaxType";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "TaxRate";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "PayWayID";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "Remark";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "MailSend";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "InsGroupID";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "SalesTypeID";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "IsPutInvoice";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "Employer";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "CreateBy";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = "_username";
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "CreateDate";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = "_sysdate";
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "LastUpdateBy";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr22.DefaultValue = "_username";
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "LastUpdateDate";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr23.DefaultValue = "_sysdate";
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "SalesNOTemp";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "IsOutPutDetails";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "FlowFlag";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = "Z";
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "RemarkForInner";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr1);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr2);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr3);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr4);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr5);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr6);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr7);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr8);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr9);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr10);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr11);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr12);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr13);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr14);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr15);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr16);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr17);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr18);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr19);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr20);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr21);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr22);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr23);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr24);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr25);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr26);
            this.ucSalesMaster.FieldAttrs.Add(fieldAttr27);
            this.ucSalesMaster.LogInfo = null;
            this.ucSalesMaster.Name = "ucSalesMaster";
            this.ucSalesMaster.RowAffectsCheck = true;
            this.ucSalesMaster.SelectCmd = this.SalesMaster;
            this.ucSalesMaster.SelectCmdForUpdate = null;
            this.ucSalesMaster.SendSQLCmd = true;
            this.ucSalesMaster.ServerModify = true;
            this.ucSalesMaster.ServerModifyGetMax = false;
            this.ucSalesMaster.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucSalesMaster.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucSalesMaster.UseTranscationScope = false;
            this.ucSalesMaster.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucSalesMaster.BeforeInsert += new Srvtools.UpdateComponentBeforeInsertEventHandler(this.ucSalesMaster_BeforeInsert);
            this.ucSalesMaster.BeforeModify += new Srvtools.UpdateComponentBeforeModifyEventHandler(this.ucSalesMaster_BeforeModify);
            // 
            // SalesDetails
            // 
            this.SalesDetails.CacheConnection = false;
            this.SalesDetails.CommandText = resources.GetString("SalesDetails.CommandText");
            this.SalesDetails.CommandTimeout = 30;
            this.SalesDetails.CommandType = System.Data.CommandType.Text;
            this.SalesDetails.DynamicTableName = false;
            this.SalesDetails.EEPAlias = "JBERP";
            this.SalesDetails.EncodingAfter = null;
            this.SalesDetails.EncodingBefore = "Windows-1252";
            this.SalesDetails.EncodingConvert = null;
            this.SalesDetails.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "SalesNO";
            keyItem3.KeyName = "ItemNO";
            this.SalesDetails.KeyFields.Add(keyItem2);
            this.SalesDetails.KeyFields.Add(keyItem3);
            this.SalesDetails.MultiSetWhere = false;
            this.SalesDetails.Name = "SalesDetails";
            this.SalesDetails.NotificationAutoEnlist = false;
            this.SalesDetails.SecExcept = null;
            this.SalesDetails.SecFieldName = null;
            this.SalesDetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesDetails.SelectPaging = false;
            this.SalesDetails.SelectTop = 0;
            this.SalesDetails.SiteControl = false;
            this.SalesDetails.SiteFieldName = null;
            this.SalesDetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucSalesDetails
            // 
            this.ucSalesDetails.AutoTrans = true;
            this.ucSalesDetails.ExceptJoin = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "SalesNO";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "ItemNO";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "SalesTypeID";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "FeeItemID";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = "";
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "SalesTypeName";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "Quantity";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "Unit";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "UnitPrice";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "DType";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "CreateBy";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = "_username";
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "CreateDate";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = "_sysdate";
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "LastUpdateBy";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr39.DefaultValue = "_username";
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "LastUpdateDate";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr40.DefaultValue = "_sysdate";
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr28);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr29);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr30);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr31);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr32);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr33);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr34);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr35);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr36);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr37);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr38);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr39);
            this.ucSalesDetails.FieldAttrs.Add(fieldAttr40);
            this.ucSalesDetails.LogInfo = null;
            this.ucSalesDetails.Name = "ucSalesDetails";
            this.ucSalesDetails.RowAffectsCheck = true;
            this.ucSalesDetails.SelectCmd = this.SalesDetails;
            this.ucSalesDetails.SelectCmdForUpdate = null;
            this.ucSalesDetails.SendSQLCmd = true;
            this.ucSalesDetails.ServerModify = true;
            this.ucSalesDetails.ServerModifyGetMax = false;
            this.ucSalesDetails.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucSalesDetails.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucSalesDetails.UseTranscationScope = false;
            this.ucSalesDetails.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // idSalesMaster_SalesDetails
            // 
            this.idSalesMaster_SalesDetails.Detail = this.SalesDetails;
            columnItem1.FieldName = "SalesNO";
            this.idSalesMaster_SalesDetails.DetailColumns.Add(columnItem1);
            this.idSalesMaster_SalesDetails.DynamicTableName = false;
            this.idSalesMaster_SalesDetails.Master = this.SalesMaster;
            columnItem2.FieldName = "SalesNO";
            this.idSalesMaster_SalesDetails.MasterColumns.Add(columnItem2);
            // 
            // View_SalesMaster
            // 
            this.View_SalesMaster.CacheConnection = false;
            this.View_SalesMaster.CommandText = "SELECT * FROM dbo.[SalesMaster]";
            this.View_SalesMaster.CommandTimeout = 30;
            this.View_SalesMaster.CommandType = System.Data.CommandType.Text;
            this.View_SalesMaster.DynamicTableName = false;
            this.View_SalesMaster.EEPAlias = null;
            this.View_SalesMaster.EncodingAfter = null;
            this.View_SalesMaster.EncodingBefore = "Windows-1252";
            this.View_SalesMaster.EncodingConvert = null;
            this.View_SalesMaster.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "SalesNO";
            this.View_SalesMaster.KeyFields.Add(keyItem4);
            this.View_SalesMaster.MultiSetWhere = false;
            this.View_SalesMaster.Name = "View_SalesMaster";
            this.View_SalesMaster.NotificationAutoEnlist = false;
            this.View_SalesMaster.SecExcept = null;
            this.View_SalesMaster.SecFieldName = null;
            this.View_SalesMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_SalesMaster.SelectPaging = false;
            this.View_SalesMaster.SelectTop = 0;
            this.View_SalesMaster.SiteControl = false;
            this.View_SalesMaster.SiteFieldName = null;
            this.View_SalesMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // InsGroup
            // 
            this.InsGroup.CacheConnection = false;
            this.InsGroup.CommandText = "SELECT InsGroupID,InsGroupName,ShortName,APIWebCode,APIPassword,TaxNO\r\nFROM JBADM" +
    "IN.dbo.InsGroup  WHERE IsActive=1";
            this.InsGroup.CommandTimeout = 30;
            this.InsGroup.CommandType = System.Data.CommandType.Text;
            this.InsGroup.DynamicTableName = false;
            this.InsGroup.EEPAlias = "JBERP";
            this.InsGroup.EncodingAfter = null;
            this.InsGroup.EncodingBefore = "Windows-1252";
            this.InsGroup.EncodingConvert = null;
            this.InsGroup.InfoConnection = this.InfoConnection1;
            this.InsGroup.MultiSetWhere = false;
            this.InsGroup.Name = "InsGroup";
            this.InsGroup.NotificationAutoEnlist = false;
            this.InsGroup.SecExcept = null;
            this.InsGroup.SecFieldName = null;
            this.InsGroup.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.InsGroup.SelectPaging = false;
            this.InsGroup.SelectTop = 0;
            this.InsGroup.SiteControl = false;
            this.InsGroup.SiteFieldName = null;
            this.InsGroup.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Customer
            // 
            this.Customer.CacheConnection = false;
            this.Customer.CommandText = resources.GetString("Customer.CommandText");
            this.Customer.CommandTimeout = 30;
            this.Customer.CommandType = System.Data.CommandType.Text;
            this.Customer.DynamicTableName = false;
            this.Customer.EEPAlias = "JBERP";
            this.Customer.EncodingAfter = null;
            this.Customer.EncodingBefore = "Windows-1252";
            this.Customer.EncodingConvert = null;
            this.Customer.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "CustomerID";
            this.Customer.KeyFields.Add(keyItem5);
            this.Customer.MultiSetWhere = false;
            this.Customer.Name = "Customer";
            this.Customer.NotificationAutoEnlist = false;
            this.Customer.SecExcept = null;
            this.Customer.SecFieldName = null;
            this.Customer.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Customer.SelectPaging = false;
            this.Customer.SelectTop = 0;
            this.Customer.SiteControl = false;
            this.Customer.SiteFieldName = null;
            this.Customer.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesType
            // 
            this.SalesType.CacheConnection = false;
            this.SalesType.CommandText = "SELECT  SalesTypeID,SalesTypeID+\'-\'+SalesTypeName as SalesTypeName,InsGroupID FRO" +
    "M SalesType \r\nOrder By SalesTypeID";
            this.SalesType.CommandTimeout = 30;
            this.SalesType.CommandType = System.Data.CommandType.Text;
            this.SalesType.DynamicTableName = false;
            this.SalesType.EEPAlias = "JBERP";
            this.SalesType.EncodingAfter = null;
            this.SalesType.EncodingBefore = "Windows-1252";
            this.SalesType.EncodingConvert = null;
            this.SalesType.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "CustomerID";
            this.SalesType.KeyFields.Add(keyItem6);
            this.SalesType.MultiSetWhere = false;
            this.SalesType.Name = "SalesType";
            this.SalesType.NotificationAutoEnlist = false;
            this.SalesType.SecExcept = null;
            this.SalesType.SecFieldName = null;
            this.SalesType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesType.SelectPaging = false;
            this.SalesType.SelectTop = 0;
            this.SalesType.SiteControl = false;
            this.SalesType.SiteFieldName = null;
            this.SalesType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // TaxType
            // 
            this.TaxType.CacheConnection = false;
            this.TaxType.CommandText = "  SELECT  TaxTypeID,TaxTypeName,TaxRate  FROM TaxType where TaxTypeID in(\'1\',\'2\'," +
    "\'3\') Order by TaxTypeID\r\n";
            this.TaxType.CommandTimeout = 30;
            this.TaxType.CommandType = System.Data.CommandType.Text;
            this.TaxType.DynamicTableName = false;
            this.TaxType.EEPAlias = "JBERP";
            this.TaxType.EncodingAfter = null;
            this.TaxType.EncodingBefore = "Windows-1252";
            this.TaxType.EncodingConvert = null;
            this.TaxType.InfoConnection = this.InfoConnection1;
            keyItem7.KeyName = "CustomerID";
            this.TaxType.KeyFields.Add(keyItem7);
            this.TaxType.MultiSetWhere = false;
            this.TaxType.Name = "TaxType";
            this.TaxType.NotificationAutoEnlist = false;
            this.TaxType.SecExcept = null;
            this.TaxType.SecFieldName = null;
            this.TaxType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.TaxType.SelectPaging = false;
            this.TaxType.SelectTop = 0;
            this.TaxType.SiteControl = false;
            this.TaxType.SiteFieldName = null;
            this.TaxType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesPerson
            // 
            this.SalesPerson.CacheConnection = false;
            this.SalesPerson.CommandText = "SELECT SalesID,SalesName   FROM SalesPerson";
            this.SalesPerson.CommandTimeout = 30;
            this.SalesPerson.CommandType = System.Data.CommandType.Text;
            this.SalesPerson.DynamicTableName = false;
            this.SalesPerson.EEPAlias = "JBERP";
            this.SalesPerson.EncodingAfter = null;
            this.SalesPerson.EncodingBefore = "Windows-1252";
            this.SalesPerson.EncodingConvert = null;
            this.SalesPerson.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "CustomerID";
            this.SalesPerson.KeyFields.Add(keyItem8);
            this.SalesPerson.MultiSetWhere = false;
            this.SalesPerson.Name = "SalesPerson";
            this.SalesPerson.NotificationAutoEnlist = false;
            this.SalesPerson.SecExcept = null;
            this.SalesPerson.SecFieldName = null;
            this.SalesPerson.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesPerson.SelectPaging = false;
            this.SalesPerson.SelectTop = 0;
            this.SalesPerson.SiteControl = false;
            this.SalesPerson.SiteFieldName = null;
            this.SalesPerson.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesKind
            // 
            this.SalesKind.CacheConnection = false;
            this.SalesKind.CommandText = "SELECT SalesKindID,SalesKindName From SalesKIND ORDER BY SalesKindID";
            this.SalesKind.CommandTimeout = 30;
            this.SalesKind.CommandType = System.Data.CommandType.Text;
            this.SalesKind.DynamicTableName = false;
            this.SalesKind.EEPAlias = "JBERP";
            this.SalesKind.EncodingAfter = null;
            this.SalesKind.EncodingBefore = "Windows-1252";
            this.SalesKind.EncodingConvert = null;
            this.SalesKind.InfoConnection = this.InfoConnection1;
            keyItem9.KeyName = "CustomerID";
            this.SalesKind.KeyFields.Add(keyItem9);
            this.SalesKind.MultiSetWhere = false;
            this.SalesKind.Name = "SalesKind";
            this.SalesKind.NotificationAutoEnlist = false;
            this.SalesKind.SecExcept = null;
            this.SalesKind.SecFieldName = null;
            this.SalesKind.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesKind.SelectPaging = false;
            this.SalesKind.SelectTop = 0;
            this.SalesKind.SiteControl = false;
            this.SalesKind.SiteFieldName = null;
            this.SalesKind.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // InvoiceType
            // 
            this.InvoiceType.CacheConnection = false;
            this.InvoiceType.CommandText = "SELECT  INVOICETYPEID,INVOICETYPENAME  \r\nFROM InvoiceType WHERE INVOICETYPEID<97\r" +
    "\nORDER BY INVOICETYPEID";
            this.InvoiceType.CommandTimeout = 30;
            this.InvoiceType.CommandType = System.Data.CommandType.Text;
            this.InvoiceType.DynamicTableName = false;
            this.InvoiceType.EEPAlias = "JBERP";
            this.InvoiceType.EncodingAfter = null;
            this.InvoiceType.EncodingBefore = "Windows-1252";
            this.InvoiceType.EncodingConvert = null;
            this.InvoiceType.InfoConnection = this.InfoConnection1;
            keyItem10.KeyName = "CustomerID";
            this.InvoiceType.KeyFields.Add(keyItem10);
            this.InvoiceType.MultiSetWhere = false;
            this.InvoiceType.Name = "InvoiceType";
            this.InvoiceType.NotificationAutoEnlist = false;
            this.InvoiceType.SecExcept = null;
            this.InvoiceType.SecFieldName = null;
            this.InvoiceType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.InvoiceType.SelectPaging = false;
            this.InvoiceType.SelectTop = 0;
            this.InvoiceType.SiteControl = false;
            this.InvoiceType.SiteFieldName = null;
            this.InvoiceType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesUploadCode
            // 
            this.SalesUploadCode.CacheConnection = false;
            this.SalesUploadCode.CommandText = "SELECT   UPLoadCode,UPLoadDesc   FROM  SalesUploadCode \r\norder by  UPLoadCode";
            this.SalesUploadCode.CommandTimeout = 30;
            this.SalesUploadCode.CommandType = System.Data.CommandType.Text;
            this.SalesUploadCode.DynamicTableName = false;
            this.SalesUploadCode.EEPAlias = "JBERP";
            this.SalesUploadCode.EncodingAfter = null;
            this.SalesUploadCode.EncodingBefore = "Windows-1252";
            this.SalesUploadCode.EncodingConvert = null;
            this.SalesUploadCode.InfoConnection = this.InfoConnection1;
            this.SalesUploadCode.MultiSetWhere = false;
            this.SalesUploadCode.Name = "SalesUploadCode";
            this.SalesUploadCode.NotificationAutoEnlist = false;
            this.SalesUploadCode.SecExcept = null;
            this.SalesUploadCode.SecFieldName = null;
            this.SalesUploadCode.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesUploadCode.SelectPaging = false;
            this.SalesUploadCode.SelectTop = 0;
            this.SalesUploadCode.SiteControl = false;
            this.SalesUploadCode.SiteFieldName = null;
            this.SalesUploadCode.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // QInvoiceType
            // 
            this.QInvoiceType.CacheConnection = false;
            this.QInvoiceType.CommandText = "SELECT  INVOICETYPEID,INVOICETYPENAME  \r\nFROM InvoiceType WHERE  INVOICETYPEID>=9" +
    "7\r\nORDER BY INVOICETYPEID DESC";
            this.QInvoiceType.CommandTimeout = 30;
            this.QInvoiceType.CommandType = System.Data.CommandType.Text;
            this.QInvoiceType.DynamicTableName = false;
            this.QInvoiceType.EEPAlias = "JBERP";
            this.QInvoiceType.EncodingAfter = null;
            this.QInvoiceType.EncodingBefore = "Windows-1252";
            this.QInvoiceType.EncodingConvert = null;
            this.QInvoiceType.InfoConnection = this.InfoConnection1;
            keyItem11.KeyName = "CustomerID";
            this.QInvoiceType.KeyFields.Add(keyItem11);
            this.QInvoiceType.MultiSetWhere = false;
            this.QInvoiceType.Name = "QInvoiceType";
            this.QInvoiceType.NotificationAutoEnlist = false;
            this.QInvoiceType.SecExcept = null;
            this.QInvoiceType.SecFieldName = null;
            this.QInvoiceType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.QInvoiceType.SelectPaging = false;
            this.QInvoiceType.SelectTop = 0;
            this.QInvoiceType.SiteControl = false;
            this.QInvoiceType.SiteFieldName = null;
            this.QInvoiceType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Employer
            // 
            this.Employer.CacheConnection = false;
            this.Employer.CommandText = "SELECT   CUSTOMERID,SHORTNAME FROM CUSTOMER \r\nWHERE CUSTOMERTYPEID=1";
            this.Employer.CommandTimeout = 30;
            this.Employer.CommandType = System.Data.CommandType.Text;
            this.Employer.DynamicTableName = false;
            this.Employer.EEPAlias = "JBERP";
            this.Employer.EncodingAfter = null;
            this.Employer.EncodingBefore = "Windows-1252";
            this.Employer.EncodingConvert = null;
            this.Employer.InfoConnection = this.InfoConnection1;
            keyItem12.KeyName = "CustomerID";
            this.Employer.KeyFields.Add(keyItem12);
            this.Employer.MultiSetWhere = false;
            this.Employer.Name = "Employer";
            this.Employer.NotificationAutoEnlist = false;
            this.Employer.SecExcept = null;
            this.Employer.SecFieldName = null;
            this.Employer.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Employer.SelectPaging = false;
            this.Employer.SelectTop = 0;
            this.Employer.SiteControl = false;
            this.Employer.SiteFieldName = null;
            this.Employer.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CustomerSaleType
            // 
            this.CustomerSaleType.CacheConnection = false;
            this.CustomerSaleType.CommandText = resources.GetString("CustomerSaleType.CommandText");
            this.CustomerSaleType.CommandTimeout = 30;
            this.CustomerSaleType.CommandType = System.Data.CommandType.Text;
            this.CustomerSaleType.DynamicTableName = false;
            this.CustomerSaleType.EEPAlias = "JBERP";
            this.CustomerSaleType.EncodingAfter = null;
            this.CustomerSaleType.EncodingBefore = "Windows-1252";
            this.CustomerSaleType.EncodingConvert = null;
            this.CustomerSaleType.InfoConnection = this.InfoConnection1;
            keyItem13.KeyName = "CustomerID";
            keyItem14.KeyName = "SalesTypeID";
            this.CustomerSaleType.KeyFields.Add(keyItem13);
            this.CustomerSaleType.KeyFields.Add(keyItem14);
            this.CustomerSaleType.MultiSetWhere = false;
            this.CustomerSaleType.Name = "CustomerSaleType";
            this.CustomerSaleType.NotificationAutoEnlist = false;
            this.CustomerSaleType.SecExcept = null;
            this.CustomerSaleType.SecFieldName = null;
            this.CustomerSaleType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustomerSaleType.SelectPaging = false;
            this.CustomerSaleType.SelectTop = 0;
            this.CustomerSaleType.SiteControl = false;
            this.CustomerSaleType.SiteFieldName = null;
            this.CustomerSaleType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesDetails_SalesTypeName
            // 
            this.SalesDetails_SalesTypeName.CacheConnection = false;
            this.SalesDetails_SalesTypeName.CommandText = "SELECT distinct SalesTypeName FROM dbo.[SalesDetails]";
            this.SalesDetails_SalesTypeName.CommandTimeout = 30;
            this.SalesDetails_SalesTypeName.CommandType = System.Data.CommandType.Text;
            this.SalesDetails_SalesTypeName.DynamicTableName = false;
            this.SalesDetails_SalesTypeName.EEPAlias = "JBERP";
            this.SalesDetails_SalesTypeName.EncodingAfter = null;
            this.SalesDetails_SalesTypeName.EncodingBefore = "Windows-1252";
            this.SalesDetails_SalesTypeName.EncodingConvert = null;
            this.SalesDetails_SalesTypeName.InfoConnection = this.InfoConnection1;
            keyItem15.KeyName = "SalesNO";
            keyItem16.KeyName = "ItemNO";
            this.SalesDetails_SalesTypeName.KeyFields.Add(keyItem15);
            this.SalesDetails_SalesTypeName.KeyFields.Add(keyItem16);
            this.SalesDetails_SalesTypeName.MultiSetWhere = false;
            this.SalesDetails_SalesTypeName.Name = "SalesDetails_SalesTypeName";
            this.SalesDetails_SalesTypeName.NotificationAutoEnlist = false;
            this.SalesDetails_SalesTypeName.SecExcept = null;
            this.SalesDetails_SalesTypeName.SecFieldName = null;
            this.SalesDetails_SalesTypeName.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesDetails_SalesTypeName.SelectPaging = false;
            this.SalesDetails_SalesTypeName.SelectTop = 0;
            this.SalesDetails_SalesTypeName.SiteControl = false;
            this.SalesDetails_SalesTypeName.SiteFieldName = null;
            this.SalesDetails_SalesTypeName.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // DonateMark
            // 
            this.DonateMark.CacheConnection = false;
            this.DonateMark.CommandText = "SELECT DonateMarkID,DonateMark FROM DonateMark";
            this.DonateMark.CommandTimeout = 30;
            this.DonateMark.CommandType = System.Data.CommandType.Text;
            this.DonateMark.DynamicTableName = false;
            this.DonateMark.EEPAlias = "JBERP";
            this.DonateMark.EncodingAfter = null;
            this.DonateMark.EncodingBefore = "Windows-1252";
            this.DonateMark.EncodingConvert = null;
            this.DonateMark.InfoConnection = this.InfoConnection1;
            keyItem17.KeyName = "CustomerID";
            this.DonateMark.KeyFields.Add(keyItem17);
            this.DonateMark.MultiSetWhere = false;
            this.DonateMark.Name = "DonateMark";
            this.DonateMark.NotificationAutoEnlist = false;
            this.DonateMark.SecExcept = null;
            this.DonateMark.SecFieldName = null;
            this.DonateMark.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.DonateMark.SelectPaging = false;
            this.DonateMark.SelectTop = 0;
            this.DonateMark.SiteControl = false;
            this.DonateMark.SiteFieldName = null;
            this.DonateMark.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CarrierType
            // 
            this.CarrierType.CacheConnection = false;
            this.CarrierType.CommandText = "SELECT AutoKey,CarrierType,CarrierTypeName\r\n FROM CarrierType\r\nOrder By CarrierTy" +
    "pe";
            this.CarrierType.CommandTimeout = 30;
            this.CarrierType.CommandType = System.Data.CommandType.Text;
            this.CarrierType.DynamicTableName = false;
            this.CarrierType.EEPAlias = "JBERP";
            this.CarrierType.EncodingAfter = null;
            this.CarrierType.EncodingBefore = "Windows-1252";
            this.CarrierType.EncodingConvert = null;
            this.CarrierType.InfoConnection = this.InfoConnection1;
            keyItem18.KeyName = "CustomerID";
            this.CarrierType.KeyFields.Add(keyItem18);
            this.CarrierType.MultiSetWhere = false;
            this.CarrierType.Name = "CarrierType";
            this.CarrierType.NotificationAutoEnlist = false;
            this.CarrierType.SecExcept = null;
            this.CarrierType.SecFieldName = null;
            this.CarrierType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CarrierType.SelectPaging = false;
            this.CarrierType.SelectTop = 0;
            this.CarrierType.SiteControl = false;
            this.CarrierType.SiteFieldName = null;
            this.CarrierType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // FeeItem
            // 
            this.FeeItem.CacheConnection = false;
            this.FeeItem.CommandText = "select SalesTypeID,FeeItemID,FeeItemName from FeeItem";
            this.FeeItem.CommandTimeout = 30;
            this.FeeItem.CommandType = System.Data.CommandType.Text;
            this.FeeItem.DynamicTableName = false;
            this.FeeItem.EEPAlias = "JBERP";
            this.FeeItem.EncodingAfter = null;
            this.FeeItem.EncodingBefore = "Windows-1252";
            this.FeeItem.EncodingConvert = null;
            this.FeeItem.InfoConnection = this.InfoConnection1;
            this.FeeItem.MultiSetWhere = false;
            this.FeeItem.Name = "FeeItem";
            this.FeeItem.NotificationAutoEnlist = false;
            this.FeeItem.SecExcept = null;
            this.FeeItem.SecFieldName = null;
            this.FeeItem.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.FeeItem.SelectPaging = false;
            this.FeeItem.SelectTop = 0;
            this.FeeItem.SiteControl = false;
            this.FeeItem.SiteFieldName = null;
            this.FeeItem.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesDetailsMasterTemp
            // 
            this.SalesDetailsMasterTemp.CacheConnection = false;
            this.SalesDetailsMasterTemp.CommandText = resources.GetString("SalesDetailsMasterTemp.CommandText");
            this.SalesDetailsMasterTemp.CommandTimeout = 30;
            this.SalesDetailsMasterTemp.CommandType = System.Data.CommandType.Text;
            this.SalesDetailsMasterTemp.DynamicTableName = false;
            this.SalesDetailsMasterTemp.EEPAlias = "JBERP";
            this.SalesDetailsMasterTemp.EncodingAfter = null;
            this.SalesDetailsMasterTemp.EncodingBefore = "Windows-1252";
            this.SalesDetailsMasterTemp.EncodingConvert = null;
            this.SalesDetailsMasterTemp.InfoConnection = this.InfoConnection1;
            keyItem19.KeyName = "SalesNO";
            keyItem20.KeyName = "ItemNO";
            this.SalesDetailsMasterTemp.KeyFields.Add(keyItem19);
            this.SalesDetailsMasterTemp.KeyFields.Add(keyItem20);
            this.SalesDetailsMasterTemp.MultiSetWhere = false;
            this.SalesDetailsMasterTemp.Name = "SalesDetailsMasterTemp";
            this.SalesDetailsMasterTemp.NotificationAutoEnlist = false;
            this.SalesDetailsMasterTemp.SecExcept = null;
            this.SalesDetailsMasterTemp.SecFieldName = null;
            this.SalesDetailsMasterTemp.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesDetailsMasterTemp.SelectPaging = false;
            this.SalesDetailsMasterTemp.SelectTop = 0;
            this.SalesDetailsMasterTemp.SiteControl = false;
            this.SalesDetailsMasterTemp.SiteFieldName = null;
            this.SalesDetailsMasterTemp.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucSalesDetailsMasterTemp
            // 
            this.ucSalesDetailsMasterTemp.AutoTrans = true;
            this.ucSalesDetailsMasterTemp.ExceptJoin = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "Quantity";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "UnitPrice";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "FeeItemID";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "SalesTypeName";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            this.ucSalesDetailsMasterTemp.FieldAttrs.Add(fieldAttr41);
            this.ucSalesDetailsMasterTemp.FieldAttrs.Add(fieldAttr42);
            this.ucSalesDetailsMasterTemp.FieldAttrs.Add(fieldAttr43);
            this.ucSalesDetailsMasterTemp.FieldAttrs.Add(fieldAttr44);
            this.ucSalesDetailsMasterTemp.LogInfo = null;
            this.ucSalesDetailsMasterTemp.Name = "ucSalesDetailsMasterTemp";
            this.ucSalesDetailsMasterTemp.RowAffectsCheck = true;
            this.ucSalesDetailsMasterTemp.SelectCmd = this.SalesDetailsMasterTemp;
            this.ucSalesDetailsMasterTemp.SelectCmdForUpdate = null;
            this.ucSalesDetailsMasterTemp.SendSQLCmd = true;
            this.ucSalesDetailsMasterTemp.ServerModify = true;
            this.ucSalesDetailsMasterTemp.ServerModifyGetMax = false;
            this.ucSalesDetailsMasterTemp.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucSalesDetailsMasterTemp.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucSalesDetailsMasterTemp.UseTranscationScope = false;
            this.ucSalesDetailsMasterTemp.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // PayWay
            // 
            this.PayWay.CacheConnection = false;
            this.PayWay.CommandText = "select PayWay.PayWayID,PayWay.PayWayName from PayWay";
            this.PayWay.CommandTimeout = 30;
            this.PayWay.CommandType = System.Data.CommandType.Text;
            this.PayWay.DynamicTableName = false;
            this.PayWay.EEPAlias = "JBERP";
            this.PayWay.EncodingAfter = null;
            this.PayWay.EncodingBefore = "Windows-1252";
            this.PayWay.EncodingConvert = null;
            this.PayWay.InfoConnection = this.InfoConnection1;
            this.PayWay.MultiSetWhere = false;
            this.PayWay.Name = "PayWay";
            this.PayWay.NotificationAutoEnlist = false;
            this.PayWay.SecExcept = null;
            this.PayWay.SecFieldName = null;
            this.PayWay.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PayWay.SelectPaging = false;
            this.PayWay.SelectTop = 0;
            this.PayWay.SiteControl = false;
            this.PayWay.SiteFieldName = null;
            this.PayWay.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesDetails1
            // 
            this.SalesDetails1.CacheConnection = false;
            this.SalesDetails1.CommandText = resources.GetString("SalesDetails1.CommandText");
            this.SalesDetails1.CommandTimeout = 30;
            this.SalesDetails1.CommandType = System.Data.CommandType.Text;
            this.SalesDetails1.DynamicTableName = false;
            this.SalesDetails1.EEPAlias = "JBERP";
            this.SalesDetails1.EncodingAfter = null;
            this.SalesDetails1.EncodingBefore = "Windows-1252";
            this.SalesDetails1.EncodingConvert = null;
            this.SalesDetails1.InfoConnection = this.InfoConnection1;
            keyItem21.KeyName = "SalesNO";
            keyItem22.KeyName = "ItemNO";
            this.SalesDetails1.KeyFields.Add(keyItem21);
            this.SalesDetails1.KeyFields.Add(keyItem22);
            this.SalesDetails1.MultiSetWhere = false;
            this.SalesDetails1.Name = "SalesDetails1";
            this.SalesDetails1.NotificationAutoEnlist = false;
            this.SalesDetails1.SecExcept = null;
            this.SalesDetails1.SecFieldName = null;
            this.SalesDetails1.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesDetails1.SelectPaging = false;
            this.SalesDetails1.SelectTop = 0;
            this.SalesDetails1.SiteControl = false;
            this.SalesDetails1.SiteFieldName = null;
            this.SalesDetails1.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucSalesDetails1
            // 
            this.ucSalesDetails1.AutoTrans = true;
            this.ucSalesDetails1.ExceptJoin = false;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "SalesNO";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "ItemNO";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "SalesTypeID";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "FeeItemID";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = "";
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "SalesTypeName";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "Quantity";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "Unit";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "UnitPrice";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "Amount";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "DType";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "CreateBy";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = "_username";
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "CreateDate";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = "_sysdate";
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "LastUpdateBy";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr57.DefaultValue = "_username";
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "LastUpdateDate";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr58.DefaultValue = "_sysdate";
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "CustomerID";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "SalesDate";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "SalesID";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "Remark";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = null;
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "TaxType";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr63.DefaultValue = null;
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "PayWayID";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr64.DefaultValue = null;
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "InsGroupID";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = null;
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "SalesKindID";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = null;
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "BalanceDate";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr67.DefaultValue = null;
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "DebtorDays";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr68.DefaultValue = null;
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            fieldAttr69.CheckNull = false;
            fieldAttr69.DataField = "EmailAddress";
            fieldAttr69.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr69.DefaultValue = null;
            fieldAttr69.TrimLength = 0;
            fieldAttr69.UpdateEnable = true;
            fieldAttr69.WhereMode = true;
            fieldAttr70.CheckNull = false;
            fieldAttr70.DataField = "Employer";
            fieldAttr70.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr70.DefaultValue = null;
            fieldAttr70.TrimLength = 0;
            fieldAttr70.UpdateEnable = true;
            fieldAttr70.WhereMode = true;
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr45);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr46);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr47);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr48);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr49);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr50);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr51);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr52);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr53);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr54);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr55);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr56);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr57);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr58);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr59);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr60);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr61);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr62);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr63);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr64);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr65);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr66);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr67);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr68);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr69);
            this.ucSalesDetails1.FieldAttrs.Add(fieldAttr70);
            this.ucSalesDetails1.LogInfo = null;
            this.ucSalesDetails1.Name = "ucSalesDetails1";
            this.ucSalesDetails1.RowAffectsCheck = true;
            this.ucSalesDetails1.SelectCmd = this.SalesDetails1;
            this.ucSalesDetails1.SelectCmdForUpdate = null;
            this.ucSalesDetails1.SendSQLCmd = true;
            this.ucSalesDetails1.ServerModify = true;
            this.ucSalesDetails1.ServerModifyGetMax = false;
            this.ucSalesDetails1.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucSalesDetails1.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucSalesDetails1.UseTranscationScope = false;
            this.ucSalesDetails1.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucSalesDetails1.BeforeInsert += new Srvtools.UpdateComponentBeforeInsertEventHandler(this.ucSalesDetails1_BeforeInsert);
            this.ucSalesDetails1.AfterInsert += new Srvtools.UpdateComponentAfterInsertEventHandler(this.ucSalesDetails1_AfterInsert);
            // 
            // QCustomer
            // 
            this.QCustomer.CacheConnection = false;
            this.QCustomer.CommandText = resources.GetString("QCustomer.CommandText");
            this.QCustomer.CommandTimeout = 30;
            this.QCustomer.CommandType = System.Data.CommandType.Text;
            this.QCustomer.DynamicTableName = false;
            this.QCustomer.EEPAlias = "JBERP";
            this.QCustomer.EncodingAfter = null;
            this.QCustomer.EncodingBefore = "Windows-1252";
            this.QCustomer.EncodingConvert = null;
            this.QCustomer.InfoConnection = this.InfoConnection1;
            keyItem23.KeyName = "CustomerID";
            this.QCustomer.KeyFields.Add(keyItem23);
            this.QCustomer.MultiSetWhere = false;
            this.QCustomer.Name = "QCustomer";
            this.QCustomer.NotificationAutoEnlist = false;
            this.QCustomer.SecExcept = null;
            this.QCustomer.SecFieldName = null;
            this.QCustomer.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.QCustomer.SelectPaging = false;
            this.QCustomer.SelectTop = 0;
            this.QCustomer.SiteControl = false;
            this.QCustomer.SiteFieldName = null;
            this.QCustomer.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // QEmployer
            // 
            this.QEmployer.CacheConnection = false;
            this.QEmployer.CommandText = "SELECT top 20  CUSTOMERID,SHORTNAME FROM CUSTOMER \r\nWHERE CUSTOMERTYPEID=1";
            this.QEmployer.CommandTimeout = 30;
            this.QEmployer.CommandType = System.Data.CommandType.Text;
            this.QEmployer.DynamicTableName = false;
            this.QEmployer.EEPAlias = "JBERP";
            this.QEmployer.EncodingAfter = null;
            this.QEmployer.EncodingBefore = "Windows-1252";
            this.QEmployer.EncodingConvert = null;
            this.QEmployer.InfoConnection = this.InfoConnection1;
            keyItem24.KeyName = "CustomerID";
            this.QEmployer.KeyFields.Add(keyItem24);
            this.QEmployer.MultiSetWhere = false;
            this.QEmployer.Name = "QEmployer";
            this.QEmployer.NotificationAutoEnlist = false;
            this.QEmployer.SecExcept = null;
            this.QEmployer.SecFieldName = null;
            this.QEmployer.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.QEmployer.SelectPaging = false;
            this.QEmployer.SelectTop = 0;
            this.QEmployer.SiteControl = false;
            this.QEmployer.SiteFieldName = null;
            this.QEmployer.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesItem
            // 
            this.SalesItem.CacheConnection = false;
            this.SalesItem.CommandText = "select st.SalesTypeID,si.SalesItemID,si.SalesItemName from SalesItem si\r\ninner jo" +
    "in SalesType st on st.SalesItemID = si.SalesItemID";
            this.SalesItem.CommandTimeout = 30;
            this.SalesItem.CommandType = System.Data.CommandType.Text;
            this.SalesItem.DynamicTableName = false;
            this.SalesItem.EEPAlias = "JBERP";
            this.SalesItem.EncodingAfter = null;
            this.SalesItem.EncodingBefore = "Windows-1252";
            this.SalesItem.EncodingConvert = null;
            this.SalesItem.InfoConnection = this.InfoConnection1;
            this.SalesItem.MultiSetWhere = false;
            this.SalesItem.Name = "SalesItem";
            this.SalesItem.NotificationAutoEnlist = false;
            this.SalesItem.SecExcept = null;
            this.SalesItem.SecFieldName = null;
            this.SalesItem.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesItem.SelectPaging = false;
            this.SalesItem.SelectTop = 0;
            this.SalesItem.SiteControl = false;
            this.SalesItem.SiteFieldName = null;
            this.SalesItem.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // QSalesPerson
            // 
            this.QSalesPerson.CacheConnection = false;
            this.QSalesPerson.CommandText = "SELECT SalesID,SalesID+\'-\'+SalesName as SalesName   FROM SalesPerson";
            this.QSalesPerson.CommandTimeout = 30;
            this.QSalesPerson.CommandType = System.Data.CommandType.Text;
            this.QSalesPerson.DynamicTableName = false;
            this.QSalesPerson.EEPAlias = "JBERP";
            this.QSalesPerson.EncodingAfter = null;
            this.QSalesPerson.EncodingBefore = "Windows-1252";
            this.QSalesPerson.EncodingConvert = null;
            this.QSalesPerson.InfoConnection = this.InfoConnection1;
            keyItem25.KeyName = "CustomerID";
            this.QSalesPerson.KeyFields.Add(keyItem25);
            this.QSalesPerson.MultiSetWhere = false;
            this.QSalesPerson.Name = "QSalesPerson";
            this.QSalesPerson.NotificationAutoEnlist = false;
            this.QSalesPerson.SecExcept = null;
            this.QSalesPerson.SecFieldName = null;
            this.QSalesPerson.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.QSalesPerson.SelectPaging = false;
            this.QSalesPerson.SelectTop = 0;
            this.QSalesPerson.SiteControl = false;
            this.QSalesPerson.SiteFieldName = null;
            this.QSalesPerson.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // QInvoiceYM
            // 
            this.QInvoiceYM.CacheConnection = false;
            this.QInvoiceYM.CommandText = "SELECT distinct  InvoiceYM  FROM InvoiceDetails order by InvoiceYM desc";
            this.QInvoiceYM.CommandTimeout = 30;
            this.QInvoiceYM.CommandType = System.Data.CommandType.Text;
            this.QInvoiceYM.DynamicTableName = false;
            this.QInvoiceYM.EEPAlias = "JBERP";
            this.QInvoiceYM.EncodingAfter = null;
            this.QInvoiceYM.EncodingBefore = "Windows-1252";
            this.QInvoiceYM.EncodingConvert = null;
            this.QInvoiceYM.InfoConnection = this.InfoConnection1;
            this.QInvoiceYM.MultiSetWhere = false;
            this.QInvoiceYM.Name = "QInvoiceYM";
            this.QInvoiceYM.NotificationAutoEnlist = false;
            this.QInvoiceYM.SecExcept = null;
            this.QInvoiceYM.SecFieldName = null;
            this.QInvoiceYM.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.QInvoiceYM.SelectPaging = false;
            this.QInvoiceYM.SelectTop = 0;
            this.QInvoiceYM.SiteControl = false;
            this.QInvoiceYM.SiteFieldName = null;
            this.QInvoiceYM.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CustomerSaleTypeForApply
            // 
            this.CustomerSaleTypeForApply.CacheConnection = false;
            this.CustomerSaleTypeForApply.CommandText = resources.GetString("CustomerSaleTypeForApply.CommandText");
            this.CustomerSaleTypeForApply.CommandTimeout = 30;
            this.CustomerSaleTypeForApply.CommandType = System.Data.CommandType.Text;
            this.CustomerSaleTypeForApply.DynamicTableName = false;
            this.CustomerSaleTypeForApply.EEPAlias = "JBERP";
            this.CustomerSaleTypeForApply.EncodingAfter = null;
            this.CustomerSaleTypeForApply.EncodingBefore = "Windows-1252";
            this.CustomerSaleTypeForApply.EncodingConvert = null;
            this.CustomerSaleTypeForApply.InfoConnection = this.InfoConnection1;
            keyItem26.KeyName = "CustomerID";
            keyItem27.KeyName = "SalesTypeID";
            this.CustomerSaleTypeForApply.KeyFields.Add(keyItem26);
            this.CustomerSaleTypeForApply.KeyFields.Add(keyItem27);
            this.CustomerSaleTypeForApply.MultiSetWhere = false;
            this.CustomerSaleTypeForApply.Name = "CustomerSaleTypeForApply";
            this.CustomerSaleTypeForApply.NotificationAutoEnlist = false;
            this.CustomerSaleTypeForApply.SecExcept = null;
            this.CustomerSaleTypeForApply.SecFieldName = null;
            this.CustomerSaleTypeForApply.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustomerSaleTypeForApply.SelectPaging = false;
            this.CustomerSaleTypeForApply.SelectTop = 0;
            this.CustomerSaleTypeForApply.SiteControl = false;
            this.CustomerSaleTypeForApply.SiteFieldName = null;
            this.CustomerSaleTypeForApply.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_SalesMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsGroup)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Customer)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TaxType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesPerson)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesKind)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.InvoiceType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesUploadCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.QInvoiceType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Employer)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerSaleType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDetails_SalesTypeName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DonateMark)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CarrierType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.FeeItem)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDetailsMasterTemp)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayWay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDetails1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.QCustomer)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.QEmployer)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesItem)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.QSalesPerson)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.QInvoiceYM)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerSaleTypeForApply)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand SalesMaster;
        private Srvtools.UpdateComponent ucSalesMaster;
        private Srvtools.InfoCommand SalesDetails;
        private Srvtools.UpdateComponent ucSalesDetails;
        private Srvtools.InfoDataSource idSalesMaster_SalesDetails;
        private Srvtools.InfoCommand View_SalesMaster;
        private Srvtools.InfoCommand InsGroup;
        private Srvtools.InfoCommand Customer;
        private Srvtools.InfoCommand SalesType;
        private Srvtools.InfoCommand TaxType;
        private Srvtools.InfoCommand SalesPerson;
        private Srvtools.InfoCommand SalesKind;
        private Srvtools.InfoCommand InvoiceType;
        private Srvtools.InfoCommand SalesUploadCode;
        private Srvtools.InfoCommand QInvoiceType;
        private Srvtools.InfoCommand Employer;
        private Srvtools.InfoCommand CustomerSaleType;
        private Srvtools.InfoCommand SalesDetails_SalesTypeName;
        private Srvtools.InfoCommand DonateMark;
        private Srvtools.InfoCommand CarrierType;
        private Srvtools.InfoCommand FeeItem;
        private Srvtools.InfoCommand SalesDetailsMasterTemp;
        private Srvtools.UpdateComponent ucSalesDetailsMasterTemp;
        private Srvtools.InfoCommand PayWay;
        private Srvtools.InfoCommand SalesDetails1;
        private Srvtools.UpdateComponent ucSalesDetails1;
        private Srvtools.InfoCommand QCustomer;
        private Srvtools.InfoCommand QEmployer;
        private Srvtools.InfoCommand SalesItem;
        private Srvtools.InfoCommand QSalesPerson;
        private Srvtools.InfoCommand QInvoiceYM;
        private Srvtools.InfoCommand CustomerSaleTypeForApply;
    }
}
