//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQOfficeTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JQOfficeTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 attachment,附件,附件,attachment,attachment,attachment,attachment,attachment 的本地化字符串。
        /// </summary>
        internal static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Add,添加(&amp;A),添加(&amp;A),&amp;Add,&amp;Add,&amp;Add,&amp;Add,&amp;Add 的本地化字符串。
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Cancel,取消(&amp;C),取消(&amp;C),&amp;Cancel,&amp;Cancel,&amp;Cancel,&amp;Cancel,&amp;Cancel 的本地化字符串。
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Debug,調試(&amp;E),调试(&amp;E),&amp;Debug,&amp;Debug,&amp;Debug,&amp;Debug,&amp;Debug 的本地化字符串。
        /// </summary>
        internal static string btnDebug {
            get {
                return ResourceManager.GetString("btnDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Edit,編輯(&amp;E),编辑(&amp;E),&amp;Edit,&amp;Edit,&amp;Edit,&amp;Edit,&amp;Edit 的本地化字符串。
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;OK,確定(&amp;O),确定(&amp;O),&amp;OK,&amp;OK,&amp;OK,&amp;OK,&amp;OK 的本地化字符串。
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output,輸出,输出,Output,Output,Output,Output,Output 的本地化字符串。
        /// </summary>
        internal static string btnOutput {
            get {
                return ResourceManager.GetString("btnOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Remove,移除(&amp;R),移除(&amp;R),&amp;Remove,&amp;Remove,&amp;Remove,&amp;Remove,&amp;Remove 的本地化字符串。
        /// </summary>
        internal static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Reset,重置(&amp;R),重置(&amp;R),&amp;Reset,&amp;Reset,&amp;Reset,&amp;Reset,&amp;Reset 的本地化字符串。
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Save,保存(&amp;S),保存(&amp;S),&amp;Save,&amp;Save,&amp;Save,&amp;Save,&amp;Save 的本地化字符串。
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Send,發送(&amp;S),发送(&amp;S),&amp;Send,&amp;Send,&amp;Send,&amp;Send,&amp;Send 的本地化字符串。
        /// </summary>
        internal static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Start,开始(&amp;S),开始(&amp;S),&amp;Start,&amp;Start,&amp;Start,&amp;Start,&amp;Start 的本地化字符串。
        /// </summary>
        internal static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Undo,撤消(&amp;U),撤消(&amp;U),&amp;Undo,&amp;Undo,&amp;Undo,&amp;Undo,&amp;Undo 的本地化字符串。
        /// </summary>
        internal static string btnUndo {
            get {
                return ResourceManager.GetString("btnUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;View,查看(&amp;V),查看(&amp;V),&amp;View,&amp;View,&amp;View,&amp;View,&amp;View 的本地化字符串。
        /// </summary>
        internal static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DataSet {
            get {
                object obj = ResourceManager.GetObject("DataSet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Default,默認,默认,Default,Default,Default,Default,Default 的本地化字符串。
        /// </summary>
        internal static string defaulvalue {
            get {
                return ResourceManager.GetString("defaulvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail,詳情,详情,Detail,Detail,Detail,Detail,Detail 的本地化字符串。
        /// </summary>
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor,編輯器,编辑器,Editor,Editor,Editor,Editor,Editor 的本地化字符串。
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail,電子郵件,电子邮件,E-mail,E-mail,E-mail,E-mail,E-mail 的本地化字符串。
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap function {
            get {
                object obj = ResourceManager.GetObject("function", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Mail from,發件人,发件人,Mail from,Mail from,Mail from,Mail from,Mail from 的本地化字符串。
        /// </summary>
        internal static string mailfrom {
            get {
                return ResourceManager.GetString("mailfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail to,收件人,收件人,Mail to,Mail to,Mail to,Mail to,Mail to 的本地化字符串。
        /// </summary>
        internal static string mailto {
            get {
                return ResourceManager.GetString("mailto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 member,成員,成员,member,member,member,member,member 的本地化字符串。
        /// </summary>
        internal static string member {
            get {
                return ResourceManager.GetString("member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap micro {
            get {
                object obj = ResourceManager.GetObject("micro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Password,密碼,密码,Password,Password,Password,Password,Password 的本地化字符串。
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 properties,屬性,属性,properties,properties,properties,properties,properties 的本地化字符串。
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap property {
            get {
                object obj = ResourceManager.GetObject("property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Server,服務器,服务器,Server,Server,Server,Server,Server 的本地化字符串。
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap value {
            get {
                object obj = ResourceManager.GetObject("value", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap word {
            get {
                object obj = ResourceManager.GetObject("word", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
