namespace sERPSalseDetails
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.ERPSalesMaster = new Srvtools.InfoCommand(this.components);
            this.ERPSalesDetails = new Srvtools.InfoCommand(this.components);
            this.ucERPSalseDetails = new Srvtools.UpdateComponent(this.components);
            this.infoSalesMan = new Srvtools.InfoCommand(this.components);
            this.infoCustomers = new Srvtools.InfoCommand(this.components);
            this.infoERPSalesType = new Srvtools.InfoCommand(this.components);
            this.autoNumber1 = new Srvtools.AutoNumber(this.components);
            this.ucERPSalseMaster = new Srvtools.UpdateComponent(this.components);
            this.infoERPDMType = new Srvtools.InfoCommand(this.components);
            this.infoERPGrantType = new Srvtools.InfoCommand(this.components);
            this.infoERPNewsType = new Srvtools.InfoCommand(this.components);
            this.infoERPNewsArea = new Srvtools.InfoCommand(this.components);
            this.infoERPNewsPublish = new Srvtools.InfoCommand(this.components);
            this.ERPSalesDetails2 = new Srvtools.InfoCommand(this.components);
            this.ucERPSalseDetails2 = new Srvtools.UpdateComponent(this.components);
            this.infoCustomersAll = new Srvtools.InfoCommand(this.components);
            this.infoERPViewArea = new Srvtools.InfoCommand(this.components);
            this.infoSalesInfo = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoSalesMan)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomers)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPSalesType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPDMType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPGrantType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPNewsType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPNewsArea)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPNewsPublish)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesDetails2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomersAll)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPViewArea)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoSalesInfo)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "ShowToDoCount";
            service1.NonLogin = false;
            service1.ServiceName = "ShowToDoCount";
            service2.DelegateName = "InsertERPSalseDetailsLast";
            service2.NonLogin = false;
            service2.ServiceName = "InsertERPSalseDetailsLast";
            service3.DelegateName = "CheckERPSalseDetailsLast";
            service3.NonLogin = false;
            service3.ServiceName = "CheckERPSalseDetailsLast";
            service4.DelegateName = "GetInvoiceYMPoint";
            service4.NonLogin = false;
            service4.ServiceName = "GetInvoiceYMPoint";
            service5.DelegateName = "UpdateSalseDetailsIsActive";
            service5.NonLogin = false;
            service5.ServiceName = "UpdateSalseDetailsIsActive";
            service6.DelegateName = "CheckNullCustNO";
            service6.NonLogin = false;
            service6.ServiceName = "CheckNullCustNO";
            service7.DelegateName = "DeleteSalesDetails";
            service7.NonLogin = false;
            service7.ServiceName = "DeleteSalesDetails";
            service8.DelegateName = "ImportSalesDetails";
            service8.NonLogin = false;
            service8.ServiceName = "ImportSalesDetails";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // ERPSalesMaster
            // 
            this.ERPSalesMaster.CacheConnection = false;
            this.ERPSalesMaster.CommandText = resources.GetString("ERPSalesMaster.CommandText");
            this.ERPSalesMaster.CommandTimeout = 30;
            this.ERPSalesMaster.CommandType = System.Data.CommandType.Text;
            this.ERPSalesMaster.DynamicTableName = false;
            this.ERPSalesMaster.EEPAlias = null;
            this.ERPSalesMaster.EncodingAfter = null;
            this.ERPSalesMaster.EncodingBefore = "Windows-1252";
            this.ERPSalesMaster.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "SalesMasterNO";
            this.ERPSalesMaster.KeyFields.Add(keyItem1);
            this.ERPSalesMaster.MultiSetWhere = false;
            this.ERPSalesMaster.Name = "ERPSalesMaster";
            this.ERPSalesMaster.NotificationAutoEnlist = false;
            this.ERPSalesMaster.SecExcept = null;
            this.ERPSalesMaster.SecFieldName = null;
            this.ERPSalesMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPSalesMaster.SelectPaging = false;
            this.ERPSalesMaster.SelectTop = 0;
            this.ERPSalesMaster.SiteControl = false;
            this.ERPSalesMaster.SiteFieldName = null;
            this.ERPSalesMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ERPSalesDetails
            // 
            this.ERPSalesDetails.CacheConnection = false;
            this.ERPSalesDetails.CommandText = resources.GetString("ERPSalesDetails.CommandText");
            this.ERPSalesDetails.CommandTimeout = 30;
            this.ERPSalesDetails.CommandType = System.Data.CommandType.Text;
            this.ERPSalesDetails.DynamicTableName = false;
            this.ERPSalesDetails.EEPAlias = null;
            this.ERPSalesDetails.EncodingAfter = null;
            this.ERPSalesDetails.EncodingBefore = "Windows-1252";
            this.ERPSalesDetails.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "ItemSeq";
            keyItem3.KeyName = "SalesMasterNO";
            this.ERPSalesDetails.KeyFields.Add(keyItem2);
            this.ERPSalesDetails.KeyFields.Add(keyItem3);
            this.ERPSalesDetails.MultiSetWhere = false;
            this.ERPSalesDetails.Name = "ERPSalesDetails";
            this.ERPSalesDetails.NotificationAutoEnlist = false;
            this.ERPSalesDetails.SecExcept = null;
            this.ERPSalesDetails.SecFieldName = null;
            this.ERPSalesDetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPSalesDetails.SelectPaging = false;
            this.ERPSalesDetails.SelectTop = 0;
            this.ERPSalesDetails.SiteControl = false;
            this.ERPSalesDetails.SiteFieldName = null;
            this.ERPSalesDetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPSalseDetails
            // 
            this.ucERPSalseDetails.AutoTrans = true;
            this.ucERPSalseDetails.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "SalseMasterNO";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "ItemSeq";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "CustNO";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "UnitPrice";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "Commission";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "SalesDate";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "SalesQty";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "DMTypeID";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "SalesAmt";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "SalesTypeID";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "SalesEmployeeID";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "InvoiceYM";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "GrantTypeID";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "OfficeLines";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "Sections";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "OfficeAmt";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "OfficePrice";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "NewsPublishID";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "NewsAreaID";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "NewsTypeID";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "IsSetInvoice";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "SalesOutLine";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "IsImport";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "CreateBy";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "CreateDate";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "CustAmt";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "SalesDescr";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr1);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr2);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr3);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr4);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr5);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr6);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr7);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr8);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr9);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr10);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr11);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr12);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr13);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr14);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr15);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr16);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr17);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr18);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr19);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr20);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr21);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr22);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr23);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr24);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr25);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr26);
            this.ucERPSalseDetails.FieldAttrs.Add(fieldAttr27);
            this.ucERPSalseDetails.LogInfo = null;
            this.ucERPSalseDetails.Name = "ucERPSalseDetails";
            this.ucERPSalseDetails.RowAffectsCheck = true;
            this.ucERPSalseDetails.SelectCmd = this.ERPSalesDetails;
            this.ucERPSalseDetails.SelectCmdForUpdate = null;
            this.ucERPSalseDetails.ServerModify = true;
            this.ucERPSalseDetails.ServerModifyGetMax = false;
            this.ucERPSalseDetails.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPSalseDetails.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPSalseDetails.UseTranscationScope = false;
            this.ucERPSalseDetails.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucERPSalseDetails.BeforeInsert += new Srvtools.UpdateComponentBeforeInsertEventHandler(this.ucERPSalseDetails_BeforeInsert);
            this.ucERPSalseDetails.BeforeModify += new Srvtools.UpdateComponentBeforeModifyEventHandler(this.ucERPSalseDetails_BeforeModify);
            this.ucERPSalseDetails.AfterModify += new Srvtools.UpdateComponentAfterModifyEventHandler(this.ucERPSalseDetails_AfterModify);
            // 
            // infoSalesMan
            // 
            this.infoSalesMan.CacheConnection = false;
            this.infoSalesMan.CommandText = "select  SalesEmployeeID,SalesID,SalesName+\'-\'+SalesID as SalesName\r\nfrom ERPSales" +
    "Man\r\nwhere IsMedia=1\r\norder by SalesEmployeeID";
            this.infoSalesMan.CommandTimeout = 30;
            this.infoSalesMan.CommandType = System.Data.CommandType.Text;
            this.infoSalesMan.DynamicTableName = false;
            this.infoSalesMan.EEPAlias = null;
            this.infoSalesMan.EncodingAfter = null;
            this.infoSalesMan.EncodingBefore = "Windows-1252";
            this.infoSalesMan.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "SalseNO";
            this.infoSalesMan.KeyFields.Add(keyItem4);
            this.infoSalesMan.MultiSetWhere = false;
            this.infoSalesMan.Name = "infoSalesMan";
            this.infoSalesMan.NotificationAutoEnlist = false;
            this.infoSalesMan.SecExcept = null;
            this.infoSalesMan.SecFieldName = null;
            this.infoSalesMan.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoSalesMan.SelectPaging = false;
            this.infoSalesMan.SelectTop = 0;
            this.infoSalesMan.SiteControl = false;
            this.infoSalesMan.SiteFieldName = null;
            this.infoSalesMan.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoCustomers
            // 
            this.infoCustomers.CacheConnection = false;
            this.infoCustomers.CommandText = resources.GetString("infoCustomers.CommandText");
            this.infoCustomers.CommandTimeout = 30;
            this.infoCustomers.CommandType = System.Data.CommandType.Text;
            this.infoCustomers.DynamicTableName = false;
            this.infoCustomers.EEPAlias = "";
            this.infoCustomers.EncodingAfter = null;
            this.infoCustomers.EncodingBefore = "Windows-1252";
            this.infoCustomers.InfoConnection = this.InfoConnection1;
            this.infoCustomers.MultiSetWhere = false;
            this.infoCustomers.Name = "infoCustomers";
            this.infoCustomers.NotificationAutoEnlist = false;
            this.infoCustomers.SecExcept = null;
            this.infoCustomers.SecFieldName = null;
            this.infoCustomers.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoCustomers.SelectPaging = false;
            this.infoCustomers.SelectTop = 0;
            this.infoCustomers.SiteControl = false;
            this.infoCustomers.SiteFieldName = null;
            this.infoCustomers.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoERPSalesType
            // 
            this.infoERPSalesType.CacheConnection = false;
            this.infoERPSalesType.CommandText = "select SalesTypeNO,SalesTypeID,Cast(SalesTypeID as nvarchar(5))+\' : \'+SalesTypeNa" +
    "me as SalesTypeName from ERPSalesType\r\nwhere IsActive=1\r\n";
            this.infoERPSalesType.CommandTimeout = 30;
            this.infoERPSalesType.CommandType = System.Data.CommandType.Text;
            this.infoERPSalesType.DynamicTableName = false;
            this.infoERPSalesType.EEPAlias = null;
            this.infoERPSalesType.EncodingAfter = null;
            this.infoERPSalesType.EncodingBefore = "Windows-1252";
            this.infoERPSalesType.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "SalesTypeNO";
            this.infoERPSalesType.KeyFields.Add(keyItem5);
            this.infoERPSalesType.MultiSetWhere = false;
            this.infoERPSalesType.Name = "infoERPSalesType";
            this.infoERPSalesType.NotificationAutoEnlist = false;
            this.infoERPSalesType.SecExcept = null;
            this.infoERPSalesType.SecFieldName = null;
            this.infoERPSalesType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPSalesType.SelectPaging = false;
            this.infoERPSalesType.SelectTop = 0;
            this.infoERPSalesType.SiteControl = false;
            this.infoERPSalesType.SiteFieldName = null;
            this.infoERPSalesType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // autoNumber1
            // 
            this.autoNumber1.Active = true;
            this.autoNumber1.AutoNoID = "SalesMasterNO";
            this.autoNumber1.Description = null;
            this.autoNumber1.GetFixed = "";
            this.autoNumber1.isNumFill = true;
            this.autoNumber1.Name = "autoNumber1";
            this.autoNumber1.Number = null;
            this.autoNumber1.NumDig = 1;
            this.autoNumber1.OldVersion = false;
            this.autoNumber1.OverFlow = true;
            this.autoNumber1.StartValue = 1;
            this.autoNumber1.Step = 1;
            this.autoNumber1.TargetColumn = "SalesMasterNO";
            this.autoNumber1.UpdateComp = this.ucERPSalseMaster;
            // 
            // ucERPSalseMaster
            // 
            this.ucERPSalseMaster.AutoTrans = true;
            this.ucERPSalseMaster.ExceptJoin = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "SalesMasterNO";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "CustNO";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "CreateBy";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "CreateDate";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "TotalSalesQty";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "KeepDays";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "KeepDaysAlert";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "CustShortName";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            this.ucERPSalseMaster.FieldAttrs.Add(fieldAttr28);
            this.ucERPSalseMaster.FieldAttrs.Add(fieldAttr29);
            this.ucERPSalseMaster.FieldAttrs.Add(fieldAttr30);
            this.ucERPSalseMaster.FieldAttrs.Add(fieldAttr31);
            this.ucERPSalseMaster.FieldAttrs.Add(fieldAttr32);
            this.ucERPSalseMaster.FieldAttrs.Add(fieldAttr33);
            this.ucERPSalseMaster.FieldAttrs.Add(fieldAttr34);
            this.ucERPSalseMaster.FieldAttrs.Add(fieldAttr35);
            this.ucERPSalseMaster.LogInfo = null;
            this.ucERPSalseMaster.Name = "ucERPSalseMaster";
            this.ucERPSalseMaster.RowAffectsCheck = true;
            this.ucERPSalseMaster.SelectCmd = this.ERPSalesMaster;
            this.ucERPSalseMaster.SelectCmdForUpdate = null;
            this.ucERPSalseMaster.ServerModify = true;
            this.ucERPSalseMaster.ServerModifyGetMax = false;
            this.ucERPSalseMaster.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPSalseMaster.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPSalseMaster.UseTranscationScope = false;
            this.ucERPSalseMaster.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucERPSalseMaster.BeforeInsert += new Srvtools.UpdateComponentBeforeInsertEventHandler(this.ucERPSalseMaster_BeforeInsert);
            this.ucERPSalseMaster.AfterInsert += new Srvtools.UpdateComponentAfterInsertEventHandler(this.ucERPSalseMaster_AfterInsert);
            // 
            // infoERPDMType
            // 
            this.infoERPDMType.CacheConnection = false;
            this.infoERPDMType.CommandText = "select DMTypeNO,DMTypeID,Cast(DMTypeID as nvarchar(5))+\' : \'+DMTypeName as DMType" +
    "Name from ERPDMType\r\nwhere IsActive=1";
            this.infoERPDMType.CommandTimeout = 30;
            this.infoERPDMType.CommandType = System.Data.CommandType.Text;
            this.infoERPDMType.DynamicTableName = false;
            this.infoERPDMType.EEPAlias = null;
            this.infoERPDMType.EncodingAfter = null;
            this.infoERPDMType.EncodingBefore = "Windows-1252";
            this.infoERPDMType.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "DMTypeNO";
            this.infoERPDMType.KeyFields.Add(keyItem6);
            this.infoERPDMType.MultiSetWhere = false;
            this.infoERPDMType.Name = "infoERPDMType";
            this.infoERPDMType.NotificationAutoEnlist = false;
            this.infoERPDMType.SecExcept = null;
            this.infoERPDMType.SecFieldName = null;
            this.infoERPDMType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPDMType.SelectPaging = false;
            this.infoERPDMType.SelectTop = 0;
            this.infoERPDMType.SiteControl = false;
            this.infoERPDMType.SiteFieldName = null;
            this.infoERPDMType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoERPGrantType
            // 
            this.infoERPGrantType.CacheConnection = false;
            this.infoERPGrantType.CommandText = "select ERPGrantType.* from ERPGrantType";
            this.infoERPGrantType.CommandTimeout = 30;
            this.infoERPGrantType.CommandType = System.Data.CommandType.Text;
            this.infoERPGrantType.DynamicTableName = false;
            this.infoERPGrantType.EEPAlias = null;
            this.infoERPGrantType.EncodingAfter = null;
            this.infoERPGrantType.EncodingBefore = "Windows-1252";
            this.infoERPGrantType.InfoConnection = this.InfoConnection1;
            keyItem7.KeyName = "GranTypeNO";
            this.infoERPGrantType.KeyFields.Add(keyItem7);
            this.infoERPGrantType.MultiSetWhere = false;
            this.infoERPGrantType.Name = "infoERPGrantType";
            this.infoERPGrantType.NotificationAutoEnlist = false;
            this.infoERPGrantType.SecExcept = null;
            this.infoERPGrantType.SecFieldName = null;
            this.infoERPGrantType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPGrantType.SelectPaging = false;
            this.infoERPGrantType.SelectTop = 0;
            this.infoERPGrantType.SiteControl = false;
            this.infoERPGrantType.SiteFieldName = null;
            this.infoERPGrantType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoERPNewsType
            // 
            this.infoERPNewsType.CacheConnection = false;
            this.infoERPNewsType.CommandText = "select NewsTypeNO,NewsTypeID,NewsTypeID+\' : \'+NewsTypeName as NewsTypeName \r\nfrom" +
    " ERPNewsType\r\norder by NewsTypeID";
            this.infoERPNewsType.CommandTimeout = 30;
            this.infoERPNewsType.CommandType = System.Data.CommandType.Text;
            this.infoERPNewsType.DynamicTableName = false;
            this.infoERPNewsType.EEPAlias = null;
            this.infoERPNewsType.EncodingAfter = null;
            this.infoERPNewsType.EncodingBefore = "Windows-1252";
            this.infoERPNewsType.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "NewsTypeNO";
            this.infoERPNewsType.KeyFields.Add(keyItem8);
            this.infoERPNewsType.MultiSetWhere = false;
            this.infoERPNewsType.Name = "infoERPNewsType";
            this.infoERPNewsType.NotificationAutoEnlist = false;
            this.infoERPNewsType.SecExcept = null;
            this.infoERPNewsType.SecFieldName = null;
            this.infoERPNewsType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPNewsType.SelectPaging = false;
            this.infoERPNewsType.SelectTop = 0;
            this.infoERPNewsType.SiteControl = false;
            this.infoERPNewsType.SiteFieldName = null;
            this.infoERPNewsType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoERPNewsArea
            // 
            this.infoERPNewsArea.CacheConnection = false;
            this.infoERPNewsArea.CommandText = "select NewsAreaNO,NewsAreaID,NewsAreaID+\' : \'+NewsAreaName as NewsAreaName\r\nfrom " +
    "ERPNewsArea\r\norder by NewsAreaID";
            this.infoERPNewsArea.CommandTimeout = 30;
            this.infoERPNewsArea.CommandType = System.Data.CommandType.Text;
            this.infoERPNewsArea.DynamicTableName = false;
            this.infoERPNewsArea.EEPAlias = null;
            this.infoERPNewsArea.EncodingAfter = null;
            this.infoERPNewsArea.EncodingBefore = "Windows-1252";
            this.infoERPNewsArea.InfoConnection = this.InfoConnection1;
            keyItem9.KeyName = "NewsAreaNO";
            this.infoERPNewsArea.KeyFields.Add(keyItem9);
            this.infoERPNewsArea.MultiSetWhere = false;
            this.infoERPNewsArea.Name = "infoERPNewsArea";
            this.infoERPNewsArea.NotificationAutoEnlist = false;
            this.infoERPNewsArea.SecExcept = null;
            this.infoERPNewsArea.SecFieldName = null;
            this.infoERPNewsArea.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPNewsArea.SelectPaging = false;
            this.infoERPNewsArea.SelectTop = 0;
            this.infoERPNewsArea.SiteControl = false;
            this.infoERPNewsArea.SiteFieldName = null;
            this.infoERPNewsArea.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoERPNewsPublish
            // 
            this.infoERPNewsPublish.CacheConnection = false;
            this.infoERPNewsPublish.CommandText = "select NewsPublishNO,NewsPublishID,NewsPublishID+\' : \'+NewsPublishName as NewsPub" +
    "lishName\r\n from ERPNewsPublish\r\norder by NewsPublishID";
            this.infoERPNewsPublish.CommandTimeout = 30;
            this.infoERPNewsPublish.CommandType = System.Data.CommandType.Text;
            this.infoERPNewsPublish.DynamicTableName = false;
            this.infoERPNewsPublish.EEPAlias = null;
            this.infoERPNewsPublish.EncodingAfter = null;
            this.infoERPNewsPublish.EncodingBefore = "Windows-1252";
            this.infoERPNewsPublish.InfoConnection = this.InfoConnection1;
            keyItem10.KeyName = "NewsPublishNO";
            this.infoERPNewsPublish.KeyFields.Add(keyItem10);
            this.infoERPNewsPublish.MultiSetWhere = false;
            this.infoERPNewsPublish.Name = "infoERPNewsPublish";
            this.infoERPNewsPublish.NotificationAutoEnlist = false;
            this.infoERPNewsPublish.SecExcept = null;
            this.infoERPNewsPublish.SecFieldName = null;
            this.infoERPNewsPublish.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPNewsPublish.SelectPaging = false;
            this.infoERPNewsPublish.SelectTop = 0;
            this.infoERPNewsPublish.SiteControl = false;
            this.infoERPNewsPublish.SiteFieldName = null;
            this.infoERPNewsPublish.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ERPSalesDetails2
            // 
            this.ERPSalesDetails2.CacheConnection = false;
            this.ERPSalesDetails2.CommandText = "SELECT dbo.[ERPSalesDetails].* FROM dbo.[ERPSalesDetails]\r\nwhere IsActive=1\r\norde" +
    "r by SalesDate";
            this.ERPSalesDetails2.CommandTimeout = 30;
            this.ERPSalesDetails2.CommandType = System.Data.CommandType.Text;
            this.ERPSalesDetails2.DynamicTableName = false;
            this.ERPSalesDetails2.EEPAlias = null;
            this.ERPSalesDetails2.EncodingAfter = null;
            this.ERPSalesDetails2.EncodingBefore = "Windows-1252";
            this.ERPSalesDetails2.InfoConnection = this.InfoConnection1;
            keyItem11.KeyName = "ItemSeq";
            keyItem12.KeyName = "SalesMasterNO";
            this.ERPSalesDetails2.KeyFields.Add(keyItem11);
            this.ERPSalesDetails2.KeyFields.Add(keyItem12);
            this.ERPSalesDetails2.MultiSetWhere = false;
            this.ERPSalesDetails2.Name = "ERPSalesDetails2";
            this.ERPSalesDetails2.NotificationAutoEnlist = false;
            this.ERPSalesDetails2.SecExcept = null;
            this.ERPSalesDetails2.SecFieldName = null;
            this.ERPSalesDetails2.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPSalesDetails2.SelectPaging = false;
            this.ERPSalesDetails2.SelectTop = 0;
            this.ERPSalesDetails2.SiteControl = false;
            this.ERPSalesDetails2.SiteFieldName = null;
            this.ERPSalesDetails2.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPSalseDetails2
            // 
            this.ucERPSalseDetails2.AutoTrans = true;
            this.ucERPSalseDetails2.ExceptJoin = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "SalseMasterNO";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "ItemSeq";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "CustNO";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "UnitPrice";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "Commission";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "SalesDate";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "SalesQty";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "DMTypeID";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "SalesAmt";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "SalesTypeID";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "SalesEmployeeID";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "InvoiceYM";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "GrantTypeID";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "OfficeLines";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "Sections";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "OfficeAmt";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "OfficePrice";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "NewsPublishID";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "NewsAreaID";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "NewsTypeID";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "IsSetInvoice";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "SalesOutLine";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "IsImport";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "CreateBy";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "CreateDate";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr36);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr37);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr38);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr39);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr40);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr41);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr42);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr43);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr44);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr45);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr46);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr47);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr48);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr49);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr50);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr51);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr52);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr53);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr54);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr55);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr56);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr57);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr58);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr59);
            this.ucERPSalseDetails2.FieldAttrs.Add(fieldAttr60);
            this.ucERPSalseDetails2.LogInfo = null;
            this.ucERPSalseDetails2.Name = "ucERPSalseDetails2";
            this.ucERPSalseDetails2.RowAffectsCheck = true;
            this.ucERPSalseDetails2.SelectCmd = this.ERPSalesDetails2;
            this.ucERPSalseDetails2.SelectCmdForUpdate = null;
            this.ucERPSalseDetails2.ServerModify = true;
            this.ucERPSalseDetails2.ServerModifyGetMax = false;
            this.ucERPSalseDetails2.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPSalseDetails2.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPSalseDetails2.UseTranscationScope = false;
            this.ucERPSalseDetails2.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoCustomersAll
            // 
            this.infoCustomersAll.CacheConnection = false;
            this.infoCustomersAll.CommandText = resources.GetString("infoCustomersAll.CommandText");
            this.infoCustomersAll.CommandTimeout = 30;
            this.infoCustomersAll.CommandType = System.Data.CommandType.Text;
            this.infoCustomersAll.DynamicTableName = false;
            this.infoCustomersAll.EEPAlias = "JBADMIN";
            this.infoCustomersAll.EncodingAfter = null;
            this.infoCustomersAll.EncodingBefore = "Windows-1252";
            this.infoCustomersAll.InfoConnection = this.InfoConnection1;
            this.infoCustomersAll.MultiSetWhere = false;
            this.infoCustomersAll.Name = "infoCustomersAll";
            this.infoCustomersAll.NotificationAutoEnlist = false;
            this.infoCustomersAll.SecExcept = null;
            this.infoCustomersAll.SecFieldName = null;
            this.infoCustomersAll.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoCustomersAll.SelectPaging = false;
            this.infoCustomersAll.SelectTop = 0;
            this.infoCustomersAll.SiteControl = false;
            this.infoCustomersAll.SiteFieldName = null;
            this.infoCustomersAll.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoERPViewArea
            // 
            this.infoERPViewArea.CacheConnection = false;
            this.infoERPViewArea.CommandText = "select ViewAreaNO,ViewAreaID,ViewAreaName,ViewAreaName as Name from ERPViewArea";
            this.infoERPViewArea.CommandTimeout = 30;
            this.infoERPViewArea.CommandType = System.Data.CommandType.Text;
            this.infoERPViewArea.DynamicTableName = false;
            this.infoERPViewArea.EEPAlias = null;
            this.infoERPViewArea.EncodingAfter = null;
            this.infoERPViewArea.EncodingBefore = "Windows-1252";
            this.infoERPViewArea.InfoConnection = this.InfoConnection1;
            keyItem13.KeyName = "ViewAreaNO";
            this.infoERPViewArea.KeyFields.Add(keyItem13);
            this.infoERPViewArea.MultiSetWhere = false;
            this.infoERPViewArea.Name = "infoERPViewArea";
            this.infoERPViewArea.NotificationAutoEnlist = false;
            this.infoERPViewArea.SecExcept = null;
            this.infoERPViewArea.SecFieldName = null;
            this.infoERPViewArea.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPViewArea.SelectPaging = false;
            this.infoERPViewArea.SelectTop = 0;
            this.infoERPViewArea.SiteControl = false;
            this.infoERPViewArea.SiteFieldName = null;
            this.infoERPViewArea.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoSalesInfo
            // 
            this.infoSalesInfo.CacheConnection = false;
            this.infoSalesInfo.CommandText = resources.GetString("infoSalesInfo.CommandText");
            this.infoSalesInfo.CommandTimeout = 30;
            this.infoSalesInfo.CommandType = System.Data.CommandType.Text;
            this.infoSalesInfo.DynamicTableName = false;
            this.infoSalesInfo.EEPAlias = null;
            this.infoSalesInfo.EncodingAfter = null;
            this.infoSalesInfo.EncodingBefore = "Windows-1252";
            this.infoSalesInfo.InfoConnection = this.InfoConnection1;
            this.infoSalesInfo.MultiSetWhere = true;
            this.infoSalesInfo.Name = "infoSalesInfo";
            this.infoSalesInfo.NotificationAutoEnlist = false;
            this.infoSalesInfo.SecExcept = null;
            this.infoSalesInfo.SecFieldName = null;
            this.infoSalesInfo.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoSalesInfo.SelectPaging = false;
            this.infoSalesInfo.SelectTop = 0;
            this.infoSalesInfo.SiteControl = false;
            this.infoSalesInfo.SiteFieldName = null;
            this.infoSalesInfo.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoSalesMan)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomers)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPSalesType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPDMType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPGrantType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPNewsType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPNewsArea)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPNewsPublish)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesDetails2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomersAll)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPViewArea)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoSalesInfo)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand ERPSalesMaster;
        private Srvtools.InfoCommand ERPSalesDetails;
        private Srvtools.UpdateComponent ucERPSalseDetails;
        private Srvtools.InfoCommand infoSalesMan;
        private Srvtools.InfoCommand infoCustomers;
        private Srvtools.InfoCommand infoERPSalesType;
        private Srvtools.AutoNumber autoNumber1;
        private Srvtools.UpdateComponent ucERPSalseMaster;
        private Srvtools.InfoCommand infoERPDMType;
        private Srvtools.InfoCommand infoERPGrantType;
        private Srvtools.InfoCommand infoERPNewsType;
        private Srvtools.InfoCommand infoERPNewsArea;
        private Srvtools.InfoCommand infoERPNewsPublish;
        private Srvtools.InfoCommand ERPSalesDetails2;
        private Srvtools.UpdateComponent ucERPSalseDetails2;
        private Srvtools.InfoCommand infoCustomersAll;
        private Srvtools.InfoCommand infoERPViewArea;
        private Srvtools.InfoCommand infoSalesInfo;
    }
}
