//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace sERPSalesApply.CetusAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InvoiceAPIPortBinding", Namespace="http://webservice.cetustek.com/")]
    public partial class InvoiceAPIService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryAllowanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryInvoiceByOrderidOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateInvoiceV3OperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelAllowanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryWinningInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryInvoiceNumberByOrderidOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelInvoiceNoCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAllowanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryLoveCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InvoiceAPIService() {
            this.Url = global::sERPSalesApply.Properties.Settings.Default.sERPSalesInvoices_CetusAPI_InvoiceAPIService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryAllowanceCompletedEventHandler QueryAllowanceCompleted;
        
        /// <remarks/>
        public event QueryInvoiceCompletedEventHandler QueryInvoiceCompleted;
        
        /// <remarks/>
        public event CancelInvoiceCompletedEventHandler CancelInvoiceCompleted;
        
        /// <remarks/>
        public event QueryInvoiceByOrderidCompletedEventHandler QueryInvoiceByOrderidCompleted;
        
        /// <remarks/>
        public event CreateInvoiceV3CompletedEventHandler CreateInvoiceV3Completed;
        
        /// <remarks/>
        public event CancelAllowanceCompletedEventHandler CancelAllowanceCompleted;
        
        /// <remarks/>
        public event QueryWinningInvoiceCompletedEventHandler QueryWinningInvoiceCompleted;
        
        /// <remarks/>
        public event QueryInvoiceNumberByOrderidCompletedEventHandler QueryInvoiceNumberByOrderidCompleted;
        
        /// <remarks/>
        public event CancelInvoiceNoCheckCompletedEventHandler CancelInvoiceNoCheckCompleted;
        
        /// <remarks/>
        public event CreateAllowanceCompletedEventHandler CreateAllowanceCompleted;
        
        /// <remarks/>
        public event QueryLoveCodeCompletedEventHandler QueryLoveCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryAllowance([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string allowancenumber, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("QueryAllowance", new object[] {
                        allowancenumber,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryAllowanceAsync(string allowancenumber, string rentid, string source) {
            this.QueryAllowanceAsync(allowancenumber, rentid, source, null);
        }
        
        /// <remarks/>
        public void QueryAllowanceAsync(string allowancenumber, string rentid, string source, object userState) {
            if ((this.QueryAllowanceOperationCompleted == null)) {
                this.QueryAllowanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryAllowanceOperationCompleted);
            }
            this.InvokeAsync("QueryAllowance", new object[] {
                        allowancenumber,
                        rentid,
                        source}, this.QueryAllowanceOperationCompleted, userState);
        }
        
        private void OnQueryAllowanceOperationCompleted(object arg) {
            if ((this.QueryAllowanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryAllowanceCompleted(this, new QueryAllowanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryInvoice([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string invoicenumber, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string invoiceyear, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("QueryInvoice", new object[] {
                        invoicenumber,
                        invoiceyear,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryInvoiceAsync(string invoicenumber, string invoiceyear, string rentid, string source) {
            this.QueryInvoiceAsync(invoicenumber, invoiceyear, rentid, source, null);
        }
        
        /// <remarks/>
        public void QueryInvoiceAsync(string invoicenumber, string invoiceyear, string rentid, string source, object userState) {
            if ((this.QueryInvoiceOperationCompleted == null)) {
                this.QueryInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryInvoiceOperationCompleted);
            }
            this.InvokeAsync("QueryInvoice", new object[] {
                        invoicenumber,
                        invoiceyear,
                        rentid,
                        source}, this.QueryInvoiceOperationCompleted, userState);
        }
        
        private void OnQueryInvoiceOperationCompleted(object arg) {
            if ((this.QueryInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryInvoiceCompleted(this, new QueryInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CancelInvoice([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string invoicexml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("CancelInvoice", new object[] {
                        invoicexml,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelInvoiceAsync(string invoicexml, string rentid, string source) {
            this.CancelInvoiceAsync(invoicexml, rentid, source, null);
        }
        
        /// <remarks/>
        public void CancelInvoiceAsync(string invoicexml, string rentid, string source, object userState) {
            if ((this.CancelInvoiceOperationCompleted == null)) {
                this.CancelInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelInvoiceOperationCompleted);
            }
            this.InvokeAsync("CancelInvoice", new object[] {
                        invoicexml,
                        rentid,
                        source}, this.CancelInvoiceOperationCompleted, userState);
        }
        
        private void OnCancelInvoiceOperationCompleted(object arg) {
            if ((this.CancelInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelInvoiceCompleted(this, new CancelInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryInvoiceByOrderid([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string orderid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("QueryInvoiceByOrderid", new object[] {
                        orderid,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryInvoiceByOrderidAsync(string orderid, string rentid, string source) {
            this.QueryInvoiceByOrderidAsync(orderid, rentid, source, null);
        }
        
        /// <remarks/>
        public void QueryInvoiceByOrderidAsync(string orderid, string rentid, string source, object userState) {
            if ((this.QueryInvoiceByOrderidOperationCompleted == null)) {
                this.QueryInvoiceByOrderidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryInvoiceByOrderidOperationCompleted);
            }
            this.InvokeAsync("QueryInvoiceByOrderid", new object[] {
                        orderid,
                        rentid,
                        source}, this.QueryInvoiceByOrderidOperationCompleted, userState);
        }
        
        private void OnQueryInvoiceByOrderidOperationCompleted(object arg) {
            if ((this.QueryInvoiceByOrderidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryInvoiceByOrderidCompleted(this, new QueryInvoiceByOrderidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreateInvoiceV3([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string invoicexml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hastax, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("CreateInvoiceV3", new object[] {
                        invoicexml,
                        hastax,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateInvoiceV3Async(string invoicexml, string hastax, string rentid, string source) {
            this.CreateInvoiceV3Async(invoicexml, hastax, rentid, source, null);
        }
        
        /// <remarks/>
        public void CreateInvoiceV3Async(string invoicexml, string hastax, string rentid, string source, object userState) {
            if ((this.CreateInvoiceV3OperationCompleted == null)) {
                this.CreateInvoiceV3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateInvoiceV3OperationCompleted);
            }
            this.InvokeAsync("CreateInvoiceV3", new object[] {
                        invoicexml,
                        hastax,
                        rentid,
                        source}, this.CreateInvoiceV3OperationCompleted, userState);
        }
        
        private void OnCreateInvoiceV3OperationCompleted(object arg) {
            if ((this.CreateInvoiceV3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateInvoiceV3Completed(this, new CreateInvoiceV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CancelAllowance([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string allowancexml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("CancelAllowance", new object[] {
                        allowancexml,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelAllowanceAsync(string allowancexml, string rentid, string source) {
            this.CancelAllowanceAsync(allowancexml, rentid, source, null);
        }
        
        /// <remarks/>
        public void CancelAllowanceAsync(string allowancexml, string rentid, string source, object userState) {
            if ((this.CancelAllowanceOperationCompleted == null)) {
                this.CancelAllowanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelAllowanceOperationCompleted);
            }
            this.InvokeAsync("CancelAllowance", new object[] {
                        allowancexml,
                        rentid,
                        source}, this.CancelAllowanceOperationCompleted, userState);
        }
        
        private void OnCancelAllowanceOperationCompleted(object arg) {
            if ((this.CancelAllowanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelAllowanceCompleted(this, new CancelAllowanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryWinningInvoice([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string winningyear, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string winningmonth, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("QueryWinningInvoice", new object[] {
                        winningyear,
                        winningmonth,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryWinningInvoiceAsync(string winningyear, string winningmonth, string rentid, string source) {
            this.QueryWinningInvoiceAsync(winningyear, winningmonth, rentid, source, null);
        }
        
        /// <remarks/>
        public void QueryWinningInvoiceAsync(string winningyear, string winningmonth, string rentid, string source, object userState) {
            if ((this.QueryWinningInvoiceOperationCompleted == null)) {
                this.QueryWinningInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryWinningInvoiceOperationCompleted);
            }
            this.InvokeAsync("QueryWinningInvoice", new object[] {
                        winningyear,
                        winningmonth,
                        rentid,
                        source}, this.QueryWinningInvoiceOperationCompleted, userState);
        }
        
        private void OnQueryWinningInvoiceOperationCompleted(object arg) {
            if ((this.QueryWinningInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryWinningInvoiceCompleted(this, new QueryWinningInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryInvoiceNumberByOrderid([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string orderid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("QueryInvoiceNumberByOrderid", new object[] {
                        orderid,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryInvoiceNumberByOrderidAsync(string orderid, string rentid, string source) {
            this.QueryInvoiceNumberByOrderidAsync(orderid, rentid, source, null);
        }
        
        /// <remarks/>
        public void QueryInvoiceNumberByOrderidAsync(string orderid, string rentid, string source, object userState) {
            if ((this.QueryInvoiceNumberByOrderidOperationCompleted == null)) {
                this.QueryInvoiceNumberByOrderidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryInvoiceNumberByOrderidOperationCompleted);
            }
            this.InvokeAsync("QueryInvoiceNumberByOrderid", new object[] {
                        orderid,
                        rentid,
                        source}, this.QueryInvoiceNumberByOrderidOperationCompleted, userState);
        }
        
        private void OnQueryInvoiceNumberByOrderidOperationCompleted(object arg) {
            if ((this.QueryInvoiceNumberByOrderidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryInvoiceNumberByOrderidCompleted(this, new QueryInvoiceNumberByOrderidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CancelInvoiceNoCheck([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string invoicexml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("CancelInvoiceNoCheck", new object[] {
                        invoicexml,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelInvoiceNoCheckAsync(string invoicexml, string rentid, string source) {
            this.CancelInvoiceNoCheckAsync(invoicexml, rentid, source, null);
        }
        
        /// <remarks/>
        public void CancelInvoiceNoCheckAsync(string invoicexml, string rentid, string source, object userState) {
            if ((this.CancelInvoiceNoCheckOperationCompleted == null)) {
                this.CancelInvoiceNoCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelInvoiceNoCheckOperationCompleted);
            }
            this.InvokeAsync("CancelInvoiceNoCheck", new object[] {
                        invoicexml,
                        rentid,
                        source}, this.CancelInvoiceNoCheckOperationCompleted, userState);
        }
        
        private void OnCancelInvoiceNoCheckOperationCompleted(object arg) {
            if ((this.CancelInvoiceNoCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelInvoiceNoCheckCompleted(this, new CancelInvoiceNoCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreateAllowance([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string allowancexml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string checkallowance, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("CreateAllowance", new object[] {
                        allowancexml,
                        checkallowance,
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAllowanceAsync(string allowancexml, string checkallowance, string rentid, string source) {
            this.CreateAllowanceAsync(allowancexml, checkallowance, rentid, source, null);
        }
        
        /// <remarks/>
        public void CreateAllowanceAsync(string allowancexml, string checkallowance, string rentid, string source, object userState) {
            if ((this.CreateAllowanceOperationCompleted == null)) {
                this.CreateAllowanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAllowanceOperationCompleted);
            }
            this.InvokeAsync("CreateAllowance", new object[] {
                        allowancexml,
                        checkallowance,
                        rentid,
                        source}, this.CreateAllowanceOperationCompleted, userState);
        }
        
        private void OnCreateAllowanceOperationCompleted(object arg) {
            if ((this.CreateAllowanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAllowanceCompleted(this, new CreateAllowanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.cetustek.com/", ResponseNamespace="http://webservice.cetustek.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryLoveCode([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rentid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string source) {
            object[] results = this.Invoke("QueryLoveCode", new object[] {
                        rentid,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryLoveCodeAsync(string rentid, string source) {
            this.QueryLoveCodeAsync(rentid, source, null);
        }
        
        /// <remarks/>
        public void QueryLoveCodeAsync(string rentid, string source, object userState) {
            if ((this.QueryLoveCodeOperationCompleted == null)) {
                this.QueryLoveCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryLoveCodeOperationCompleted);
            }
            this.InvokeAsync("QueryLoveCode", new object[] {
                        rentid,
                        source}, this.QueryLoveCodeOperationCompleted, userState);
        }
        
        private void OnQueryLoveCodeOperationCompleted(object arg) {
            if ((this.QueryLoveCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryLoveCodeCompleted(this, new QueryLoveCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryAllowanceCompletedEventHandler(object sender, QueryAllowanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryAllowanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryAllowanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryInvoiceCompletedEventHandler(object sender, QueryInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CancelInvoiceCompletedEventHandler(object sender, CancelInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryInvoiceByOrderidCompletedEventHandler(object sender, QueryInvoiceByOrderidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryInvoiceByOrderidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryInvoiceByOrderidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateInvoiceV3CompletedEventHandler(object sender, CreateInvoiceV3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateInvoiceV3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateInvoiceV3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CancelAllowanceCompletedEventHandler(object sender, CancelAllowanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelAllowanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelAllowanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryWinningInvoiceCompletedEventHandler(object sender, QueryWinningInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryWinningInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryWinningInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryInvoiceNumberByOrderidCompletedEventHandler(object sender, QueryInvoiceNumberByOrderidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryInvoiceNumberByOrderidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryInvoiceNumberByOrderidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CancelInvoiceNoCheckCompletedEventHandler(object sender, CancelInvoiceNoCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelInvoiceNoCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelInvoiceNoCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateAllowanceCompletedEventHandler(object sender, CreateAllowanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAllowanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAllowanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryLoveCodeCompletedEventHandler(object sender, QueryLoveCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryLoveCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryLoveCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591