namespace sERP_Customer_Normal_Customer
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            Srvtools.Service service9 = new Srvtools.Service();
            Srvtools.Service service10 = new Srvtools.Service();
            Srvtools.Service service11 = new Srvtools.Service();
            Srvtools.Service service12 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem14 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem15 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem16 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.Customer = new Srvtools.InfoCommand(this.components);
            this.ucCustomer = new Srvtools.UpdateComponent(this.components);
            this.CustomerSaleType = new Srvtools.InfoCommand(this.components);
            this.ucCustomerSaleType = new Srvtools.UpdateComponent(this.components);
            this.CountryCity = new Srvtools.InfoCommand(this.components);
            this.ucCountryCity = new Srvtools.UpdateComponent(this.components);
            this.DonateMark = new Srvtools.InfoCommand(this.components);
            this.PayWay = new Srvtools.InfoCommand(this.components);
            this.SalesPerson = new Srvtools.InfoCommand(this.components);
            this.SalesSalesType = new Srvtools.InfoCommand(this.components);
            this.ucSalesSalesType = new Srvtools.UpdateComponent(this.components);
            this.SalesType = new Srvtools.InfoCommand(this.components);
            this.TaxType = new Srvtools.InfoCommand(this.components);
            this.Country = new Srvtools.InfoCommand(this.components);
            this.City = new Srvtools.InfoCommand(this.components);
            this.TelNO_Query = new Srvtools.InfoCommand(this.components);
            this.CustomerType = new Srvtools.InfoCommand(this.components);
            this.Customer_Query = new Srvtools.InfoCommand(this.components);
            this.InvoiceType = new Srvtools.InfoCommand(this.components);
            this.SalesTypeDateList = new Srvtools.InfoCommand(this.components);
            this.DevelopLevel = new Srvtools.InfoCommand(this.components);
            this.ContactLogs = new Srvtools.InfoCommand(this.components);
            this.ucContactLogs = new Srvtools.UpdateComponent(this.components);
            this.Dialogue = new Srvtools.InfoCommand(this.components);
            this.CountryArea = new Srvtools.InfoCommand(this.components);
            this.CustomerSaleKind = new Srvtools.InfoCommand(this.components);
            this.ucCustomerSaleKind = new Srvtools.UpdateComponent(this.components);
            this.SalesKind = new Srvtools.InfoCommand(this.components);
            this.SalesKindUser = new Srvtools.InfoCommand(this.components);
            this.Industry = new Srvtools.InfoCommand(this.components);
            this.SalesKindSalesType = new Srvtools.InfoCommand(this.components);
            this.UserSalesKind = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Customer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerSaleType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CountryCity)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DonateMark)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayWay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesPerson)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesSalesType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TaxType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Country)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.City)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TelNO_Query)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Customer_Query)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.InvoiceType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesTypeDateList)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DevelopLevel)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ContactLogs)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Dialogue)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CountryArea)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerSaleKind)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesKind)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesKindUser)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Industry)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesKindSalesType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UserSalesKind)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "GetCustomerID";
            service1.NonLogin = false;
            service1.ServiceName = "GetCustomerID";
            service2.DelegateName = "GetSalesTypeID";
            service2.NonLogin = false;
            service2.ServiceName = "GetSalesTypeID";
            service3.DelegateName = "CheckDuplicate_TaxNO";
            service3.NonLogin = false;
            service3.ServiceName = "CheckDuplicate_TaxNO";
            service4.DelegateName = "CheckDuplicate_CustomerNameAndTelNO";
            service4.NonLogin = false;
            service4.ServiceName = "CheckDuplicate_CustomerNameAndTelNO";
            service5.DelegateName = "SelectSalesMasterWhereCustomerID";
            service5.NonLogin = false;
            service5.ServiceName = "SelectSalesMasterWhereCustomerID";
            service6.DelegateName = "GetGridDataSalesTypeDate";
            service6.NonLogin = false;
            service6.ServiceName = "GetGridDataSalesTypeDate";
            service7.DelegateName = "procAddCustomerSaleTypeBySales";
            service7.NonLogin = false;
            service7.ServiceName = "procAddCustomerSaleTypeBySales";
            service8.DelegateName = "GetSalesKindID";
            service8.NonLogin = false;
            service8.ServiceName = "GetSalesKindID";
            service9.DelegateName = "GetCustSalesTypeID";
            service9.NonLogin = false;
            service9.ServiceName = "GetCustSalesTypeID";
            service10.DelegateName = "procAddCustomerSaleTypeBySalesType";
            service10.NonLogin = false;
            service10.ServiceName = "procAddCustomerSaleTypeBySalesType";
            service11.DelegateName = "procUpdateDevelopLevel";
            service11.NonLogin = false;
            service11.ServiceName = "procUpdateDevelopLevel";
            service12.DelegateName = "GetUserCustomerTypeID";
            service12.NonLogin = false;
            service12.ServiceName = "GetUserCustomerTypeID";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            this.serviceManager1.ServiceCollection.Add(service9);
            this.serviceManager1.ServiceCollection.Add(service10);
            this.serviceManager1.ServiceCollection.Add(service11);
            this.serviceManager1.ServiceCollection.Add(service12);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBERP";
            // 
            // Customer
            // 
            this.Customer.CacheConnection = false;
            this.Customer.CommandText = resources.GetString("Customer.CommandText");
            this.Customer.CommandTimeout = 30;
            this.Customer.CommandType = System.Data.CommandType.Text;
            this.Customer.DynamicTableName = false;
            this.Customer.EEPAlias = "JBERP";
            this.Customer.EncodingAfter = null;
            this.Customer.EncodingBefore = "Windows-1252";
            this.Customer.EncodingConvert = null;
            this.Customer.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CustomerID";
            this.Customer.KeyFields.Add(keyItem1);
            this.Customer.MultiSetWhere = false;
            this.Customer.Name = "Customer";
            this.Customer.NotificationAutoEnlist = false;
            this.Customer.SecExcept = null;
            this.Customer.SecFieldName = null;
            this.Customer.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Customer.SelectPaging = false;
            this.Customer.SelectTop = 0;
            this.Customer.SiteControl = false;
            this.Customer.SiteFieldName = null;
            this.Customer.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucCustomer
            // 
            this.ucCustomer.AutoTrans = true;
            this.ucCustomer.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "CustomerID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "CustomerName";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "ShortName";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "TelNO";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "FaxNO";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "Addr_Country";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "Addr_City";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "Addr_Desc";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "ZIPCode";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "TaxNO";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "DonateMark";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "NPOBAN";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "CustomerTypeID";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "ARCNO";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "CreateBy";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = "_username";
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "CreateDate";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = "";
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "LastUpdateBy";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr17.DefaultValue = "_username";
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "LastUpdateDate";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr18.DefaultValue = "";
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            this.ucCustomer.FieldAttrs.Add(fieldAttr1);
            this.ucCustomer.FieldAttrs.Add(fieldAttr2);
            this.ucCustomer.FieldAttrs.Add(fieldAttr3);
            this.ucCustomer.FieldAttrs.Add(fieldAttr4);
            this.ucCustomer.FieldAttrs.Add(fieldAttr5);
            this.ucCustomer.FieldAttrs.Add(fieldAttr6);
            this.ucCustomer.FieldAttrs.Add(fieldAttr7);
            this.ucCustomer.FieldAttrs.Add(fieldAttr8);
            this.ucCustomer.FieldAttrs.Add(fieldAttr9);
            this.ucCustomer.FieldAttrs.Add(fieldAttr10);
            this.ucCustomer.FieldAttrs.Add(fieldAttr11);
            this.ucCustomer.FieldAttrs.Add(fieldAttr12);
            this.ucCustomer.FieldAttrs.Add(fieldAttr13);
            this.ucCustomer.FieldAttrs.Add(fieldAttr14);
            this.ucCustomer.FieldAttrs.Add(fieldAttr15);
            this.ucCustomer.FieldAttrs.Add(fieldAttr16);
            this.ucCustomer.FieldAttrs.Add(fieldAttr17);
            this.ucCustomer.FieldAttrs.Add(fieldAttr18);
            this.ucCustomer.LogInfo = null;
            this.ucCustomer.Name = "ucCustomer";
            this.ucCustomer.RowAffectsCheck = true;
            this.ucCustomer.SelectCmd = this.Customer;
            this.ucCustomer.SelectCmdForUpdate = null;
            this.ucCustomer.SendSQLCmd = true;
            this.ucCustomer.ServerModify = true;
            this.ucCustomer.ServerModifyGetMax = false;
            this.ucCustomer.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucCustomer.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucCustomer.UseTranscationScope = false;
            this.ucCustomer.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucCustomer.BeforeInsert += new Srvtools.UpdateComponentBeforeInsertEventHandler(this.ucCustomer_BeforeInsert);
            this.ucCustomer.AfterDelete += new Srvtools.UpdateComponentAfterDeleteEventHandler(this.ucCustomer_AfterDelete);
            this.ucCustomer.BeforeModify += new Srvtools.UpdateComponentBeforeModifyEventHandler(this.ucCustomer_BeforeModify);
            // 
            // CustomerSaleType
            // 
            this.CustomerSaleType.CacheConnection = false;
            this.CustomerSaleType.CommandText = resources.GetString("CustomerSaleType.CommandText");
            this.CustomerSaleType.CommandTimeout = 30;
            this.CustomerSaleType.CommandType = System.Data.CommandType.Text;
            this.CustomerSaleType.DynamicTableName = false;
            this.CustomerSaleType.EEPAlias = "JBERP";
            this.CustomerSaleType.EncodingAfter = null;
            this.CustomerSaleType.EncodingBefore = "Windows-1252";
            this.CustomerSaleType.EncodingConvert = null;
            this.CustomerSaleType.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "CustomerID";
            keyItem3.KeyName = "SalesTypeID";
            this.CustomerSaleType.KeyFields.Add(keyItem2);
            this.CustomerSaleType.KeyFields.Add(keyItem3);
            this.CustomerSaleType.MultiSetWhere = false;
            this.CustomerSaleType.Name = "CustomerSaleType";
            this.CustomerSaleType.NotificationAutoEnlist = false;
            this.CustomerSaleType.SecExcept = null;
            this.CustomerSaleType.SecFieldName = null;
            this.CustomerSaleType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustomerSaleType.SelectPaging = false;
            this.CustomerSaleType.SelectTop = 0;
            this.CustomerSaleType.SiteControl = false;
            this.CustomerSaleType.SiteFieldName = null;
            this.CustomerSaleType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucCustomerSaleType
            // 
            this.ucCustomerSaleType.AutoTrans = true;
            this.ucCustomerSaleType.ExceptJoin = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "CustomerID";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "SalesTypeID";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "SalesTypeName";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "SalesID";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "TaxType";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "PayWay";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "BalanceDate";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "DebtorDays";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "AccountClerk";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "EmailAddress";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "CreateBy";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = "_username";
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "CreateDate";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = "_sysdate";
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "LastUpdateBy";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr31.DefaultValue = "_username";
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "LastUpdateDate";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr32.DefaultValue = "_sysdate";
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "QInvoiceType";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr19);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr20);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr21);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr22);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr23);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr24);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr25);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr26);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr27);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr28);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr29);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr30);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr31);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr32);
            this.ucCustomerSaleType.FieldAttrs.Add(fieldAttr33);
            this.ucCustomerSaleType.LogInfo = null;
            this.ucCustomerSaleType.Name = "ucCustomerSaleType";
            this.ucCustomerSaleType.RowAffectsCheck = true;
            this.ucCustomerSaleType.SelectCmd = this.CustomerSaleType;
            this.ucCustomerSaleType.SelectCmdForUpdate = null;
            this.ucCustomerSaleType.SendSQLCmd = true;
            this.ucCustomerSaleType.ServerModify = true;
            this.ucCustomerSaleType.ServerModifyGetMax = false;
            this.ucCustomerSaleType.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucCustomerSaleType.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucCustomerSaleType.UseTranscationScope = false;
            this.ucCustomerSaleType.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // CountryCity
            // 
            this.CountryCity.CacheConnection = false;
            this.CountryCity.CommandText = "select CountryCity.* from CountryCity";
            this.CountryCity.CommandTimeout = 30;
            this.CountryCity.CommandType = System.Data.CommandType.Text;
            this.CountryCity.DynamicTableName = false;
            this.CountryCity.EEPAlias = "JBERP";
            this.CountryCity.EncodingAfter = null;
            this.CountryCity.EncodingBefore = "Windows-1252";
            this.CountryCity.EncodingConvert = null;
            this.CountryCity.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "AutoKey";
            this.CountryCity.KeyFields.Add(keyItem4);
            this.CountryCity.MultiSetWhere = false;
            this.CountryCity.Name = "CountryCity";
            this.CountryCity.NotificationAutoEnlist = false;
            this.CountryCity.SecExcept = null;
            this.CountryCity.SecFieldName = null;
            this.CountryCity.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CountryCity.SelectPaging = false;
            this.CountryCity.SelectTop = 0;
            this.CountryCity.SiteControl = false;
            this.CountryCity.SiteFieldName = null;
            this.CountryCity.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucCountryCity
            // 
            this.ucCountryCity.AutoTrans = true;
            this.ucCountryCity.ExceptJoin = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "AutoKey";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "Country";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "City";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "ZIPCode";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "SortID";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "CreateBy";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = "_username";
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "CreateDate";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = "_sysdate";
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "LastUpdateBy";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = "_username";
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "LastUpdateDate";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = "_sysdate";
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            this.ucCountryCity.FieldAttrs.Add(fieldAttr34);
            this.ucCountryCity.FieldAttrs.Add(fieldAttr35);
            this.ucCountryCity.FieldAttrs.Add(fieldAttr36);
            this.ucCountryCity.FieldAttrs.Add(fieldAttr37);
            this.ucCountryCity.FieldAttrs.Add(fieldAttr38);
            this.ucCountryCity.FieldAttrs.Add(fieldAttr39);
            this.ucCountryCity.FieldAttrs.Add(fieldAttr40);
            this.ucCountryCity.FieldAttrs.Add(fieldAttr41);
            this.ucCountryCity.FieldAttrs.Add(fieldAttr42);
            this.ucCountryCity.LogInfo = null;
            this.ucCountryCity.Name = "ucCountryCity";
            this.ucCountryCity.RowAffectsCheck = true;
            this.ucCountryCity.SelectCmd = null;
            this.ucCountryCity.SelectCmdForUpdate = null;
            this.ucCountryCity.SendSQLCmd = true;
            this.ucCountryCity.ServerModify = true;
            this.ucCountryCity.ServerModifyGetMax = false;
            this.ucCountryCity.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucCountryCity.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucCountryCity.UseTranscationScope = false;
            this.ucCountryCity.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // DonateMark
            // 
            this.DonateMark.CacheConnection = false;
            this.DonateMark.CommandText = "SELECT DonateMarkID,DonateMark FROM DonateMark";
            this.DonateMark.CommandTimeout = 30;
            this.DonateMark.CommandType = System.Data.CommandType.Text;
            this.DonateMark.DynamicTableName = false;
            this.DonateMark.EEPAlias = "JBERP";
            this.DonateMark.EncodingAfter = null;
            this.DonateMark.EncodingBefore = "Windows-1252";
            this.DonateMark.EncodingConvert = null;
            this.DonateMark.InfoConnection = this.InfoConnection1;
            this.DonateMark.MultiSetWhere = false;
            this.DonateMark.Name = "DonateMark";
            this.DonateMark.NotificationAutoEnlist = false;
            this.DonateMark.SecExcept = null;
            this.DonateMark.SecFieldName = null;
            this.DonateMark.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.DonateMark.SelectPaging = false;
            this.DonateMark.SelectTop = 0;
            this.DonateMark.SiteControl = false;
            this.DonateMark.SiteFieldName = null;
            this.DonateMark.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // PayWay
            // 
            this.PayWay.CacheConnection = false;
            this.PayWay.CommandText = "SELECT PayWayID,PayWayName FROM PayWay Order By PayWayID";
            this.PayWay.CommandTimeout = 30;
            this.PayWay.CommandType = System.Data.CommandType.Text;
            this.PayWay.DynamicTableName = false;
            this.PayWay.EEPAlias = "JBERP";
            this.PayWay.EncodingAfter = null;
            this.PayWay.EncodingBefore = "Windows-1252";
            this.PayWay.EncodingConvert = null;
            this.PayWay.InfoConnection = this.InfoConnection1;
            this.PayWay.MultiSetWhere = false;
            this.PayWay.Name = "PayWay";
            this.PayWay.NotificationAutoEnlist = false;
            this.PayWay.SecExcept = null;
            this.PayWay.SecFieldName = null;
            this.PayWay.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PayWay.SelectPaging = false;
            this.PayWay.SelectTop = 0;
            this.PayWay.SiteControl = false;
            this.PayWay.SiteFieldName = null;
            this.PayWay.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesPerson
            // 
            this.SalesPerson.CacheConnection = false;
            this.SalesPerson.CommandText = resources.GetString("SalesPerson.CommandText");
            this.SalesPerson.CommandTimeout = 30;
            this.SalesPerson.CommandType = System.Data.CommandType.Text;
            this.SalesPerson.DynamicTableName = false;
            this.SalesPerson.EEPAlias = "JBERP";
            this.SalesPerson.EncodingAfter = null;
            this.SalesPerson.EncodingBefore = "Windows-1252";
            this.SalesPerson.EncodingConvert = null;
            this.SalesPerson.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "AutoKey";
            this.SalesPerson.KeyFields.Add(keyItem5);
            this.SalesPerson.MultiSetWhere = false;
            this.SalesPerson.Name = "SalesPerson";
            this.SalesPerson.NotificationAutoEnlist = false;
            this.SalesPerson.SecExcept = null;
            this.SalesPerson.SecFieldName = null;
            this.SalesPerson.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesPerson.SelectPaging = false;
            this.SalesPerson.SelectTop = 0;
            this.SalesPerson.SiteControl = false;
            this.SalesPerson.SiteFieldName = null;
            this.SalesPerson.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesSalesType
            // 
            this.SalesSalesType.CacheConnection = false;
            this.SalesSalesType.CommandText = resources.GetString("SalesSalesType.CommandText");
            this.SalesSalesType.CommandTimeout = 30;
            this.SalesSalesType.CommandType = System.Data.CommandType.Text;
            this.SalesSalesType.DynamicTableName = false;
            this.SalesSalesType.EEPAlias = "JBERP";
            this.SalesSalesType.EncodingAfter = null;
            this.SalesSalesType.EncodingBefore = "Windows-1252";
            this.SalesSalesType.EncodingConvert = null;
            this.SalesSalesType.InfoConnection = this.InfoConnection1;
            this.SalesSalesType.MultiSetWhere = false;
            this.SalesSalesType.Name = "SalesSalesType";
            this.SalesSalesType.NotificationAutoEnlist = false;
            this.SalesSalesType.SecExcept = null;
            this.SalesSalesType.SecFieldName = null;
            this.SalesSalesType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesSalesType.SelectPaging = false;
            this.SalesSalesType.SelectTop = 0;
            this.SalesSalesType.SiteControl = false;
            this.SalesSalesType.SiteFieldName = null;
            this.SalesSalesType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucSalesSalesType
            // 
            this.ucSalesSalesType.AutoTrans = true;
            this.ucSalesSalesType.ExceptJoin = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "AutoKey";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = "";
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "SalesID";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "SalesTypeID";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "CreateBy";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "CreateDate";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            this.ucSalesSalesType.FieldAttrs.Add(fieldAttr43);
            this.ucSalesSalesType.FieldAttrs.Add(fieldAttr44);
            this.ucSalesSalesType.FieldAttrs.Add(fieldAttr45);
            this.ucSalesSalesType.FieldAttrs.Add(fieldAttr46);
            this.ucSalesSalesType.FieldAttrs.Add(fieldAttr47);
            this.ucSalesSalesType.LogInfo = null;
            this.ucSalesSalesType.Name = "ucSalesSalesType";
            this.ucSalesSalesType.RowAffectsCheck = true;
            this.ucSalesSalesType.SelectCmd = null;
            this.ucSalesSalesType.SelectCmdForUpdate = null;
            this.ucSalesSalesType.SendSQLCmd = true;
            this.ucSalesSalesType.ServerModify = true;
            this.ucSalesSalesType.ServerModifyGetMax = false;
            this.ucSalesSalesType.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucSalesSalesType.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucSalesSalesType.UseTranscationScope = false;
            this.ucSalesSalesType.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // SalesType
            // 
            this.SalesType.CacheConnection = false;
            this.SalesType.CommandText = "SELECT\r\n      [SalesTypeID],\r\n      [SalesTypeName],\r\n      [SalesTypeID]+\'-\'+[Sa" +
    "lesTypeName] as [SalesTypeName1],\r\n      [InsGroupID],\r\n      [Unit]\r\nFROM [Sale" +
    "sType]  ORDER BY SalesTypeID";
            this.SalesType.CommandTimeout = 30;
            this.SalesType.CommandType = System.Data.CommandType.Text;
            this.SalesType.DynamicTableName = false;
            this.SalesType.EEPAlias = "JBERP";
            this.SalesType.EncodingAfter = null;
            this.SalesType.EncodingBefore = "Windows-1252";
            this.SalesType.EncodingConvert = null;
            this.SalesType.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "AutoKey";
            this.SalesType.KeyFields.Add(keyItem6);
            this.SalesType.MultiSetWhere = false;
            this.SalesType.Name = "SalesType";
            this.SalesType.NotificationAutoEnlist = false;
            this.SalesType.SecExcept = null;
            this.SalesType.SecFieldName = null;
            this.SalesType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesType.SelectPaging = false;
            this.SalesType.SelectTop = 0;
            this.SalesType.SiteControl = false;
            this.SalesType.SiteFieldName = null;
            this.SalesType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // TaxType
            // 
            this.TaxType.CacheConnection = false;
            this.TaxType.CommandText = "SELECT TaxTypeID,TaxTypeName FROM  TaxType";
            this.TaxType.CommandTimeout = 30;
            this.TaxType.CommandType = System.Data.CommandType.Text;
            this.TaxType.DynamicTableName = false;
            this.TaxType.EEPAlias = "JBERP";
            this.TaxType.EncodingAfter = null;
            this.TaxType.EncodingBefore = "Windows-1252";
            this.TaxType.EncodingConvert = null;
            this.TaxType.InfoConnection = this.InfoConnection1;
            this.TaxType.MultiSetWhere = false;
            this.TaxType.Name = "TaxType";
            this.TaxType.NotificationAutoEnlist = false;
            this.TaxType.SecExcept = null;
            this.TaxType.SecFieldName = null;
            this.TaxType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.TaxType.SelectPaging = false;
            this.TaxType.SelectTop = 0;
            this.TaxType.SiteControl = false;
            this.TaxType.SiteFieldName = null;
            this.TaxType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Country
            // 
            this.Country.CacheConnection = false;
            this.Country.CommandText = "SELECT DISTINCT Country FROM CountryCity";
            this.Country.CommandTimeout = 30;
            this.Country.CommandType = System.Data.CommandType.Text;
            this.Country.DynamicTableName = false;
            this.Country.EEPAlias = "JBERP";
            this.Country.EncodingAfter = null;
            this.Country.EncodingBefore = "Windows-1252";
            this.Country.EncodingConvert = null;
            this.Country.InfoConnection = this.InfoConnection1;
            keyItem7.KeyName = "AutoKey";
            this.Country.KeyFields.Add(keyItem7);
            this.Country.MultiSetWhere = false;
            this.Country.Name = "Country";
            this.Country.NotificationAutoEnlist = false;
            this.Country.SecExcept = null;
            this.Country.SecFieldName = null;
            this.Country.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Country.SelectPaging = false;
            this.Country.SelectTop = 0;
            this.Country.SiteControl = false;
            this.Country.SiteFieldName = null;
            this.Country.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // City
            // 
            this.City.CacheConnection = false;
            this.City.CommandText = "SELECT Country,City,ZIPCode FROM CountryCity";
            this.City.CommandTimeout = 30;
            this.City.CommandType = System.Data.CommandType.Text;
            this.City.DynamicTableName = false;
            this.City.EEPAlias = "JBERP";
            this.City.EncodingAfter = null;
            this.City.EncodingBefore = "Windows-1252";
            this.City.EncodingConvert = null;
            this.City.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "AutoKey";
            this.City.KeyFields.Add(keyItem8);
            this.City.MultiSetWhere = false;
            this.City.Name = "City";
            this.City.NotificationAutoEnlist = false;
            this.City.SecExcept = null;
            this.City.SecFieldName = null;
            this.City.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.City.SelectPaging = false;
            this.City.SelectTop = 0;
            this.City.SiteControl = false;
            this.City.SiteFieldName = null;
            this.City.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // TelNO_Query
            // 
            this.TelNO_Query.CacheConnection = false;
            this.TelNO_Query.CommandText = "select distinct  top 50 TelNO from Customer";
            this.TelNO_Query.CommandTimeout = 30;
            this.TelNO_Query.CommandType = System.Data.CommandType.Text;
            this.TelNO_Query.DynamicTableName = false;
            this.TelNO_Query.EEPAlias = "JBERP";
            this.TelNO_Query.EncodingAfter = null;
            this.TelNO_Query.EncodingBefore = "Windows-1252";
            this.TelNO_Query.EncodingConvert = null;
            this.TelNO_Query.InfoConnection = this.InfoConnection1;
            this.TelNO_Query.MultiSetWhere = false;
            this.TelNO_Query.Name = "TelNO_Query";
            this.TelNO_Query.NotificationAutoEnlist = false;
            this.TelNO_Query.SecExcept = null;
            this.TelNO_Query.SecFieldName = null;
            this.TelNO_Query.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.TelNO_Query.SelectPaging = false;
            this.TelNO_Query.SelectTop = 0;
            this.TelNO_Query.SiteControl = false;
            this.TelNO_Query.SiteFieldName = null;
            this.TelNO_Query.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CustomerType
            // 
            this.CustomerType.CacheConnection = false;
            this.CustomerType.CommandText = "SELECT CustomerTypeID,CustomerTypeName FROM CustomerType";
            this.CustomerType.CommandTimeout = 30;
            this.CustomerType.CommandType = System.Data.CommandType.Text;
            this.CustomerType.DynamicTableName = false;
            this.CustomerType.EEPAlias = "JBERP";
            this.CustomerType.EncodingAfter = null;
            this.CustomerType.EncodingBefore = "Windows-1252";
            this.CustomerType.EncodingConvert = null;
            this.CustomerType.InfoConnection = this.InfoConnection1;
            this.CustomerType.MultiSetWhere = false;
            this.CustomerType.Name = "CustomerType";
            this.CustomerType.NotificationAutoEnlist = false;
            this.CustomerType.SecExcept = null;
            this.CustomerType.SecFieldName = null;
            this.CustomerType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustomerType.SelectPaging = false;
            this.CustomerType.SelectTop = 0;
            this.CustomerType.SiteControl = false;
            this.CustomerType.SiteFieldName = null;
            this.CustomerType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Customer_Query
            // 
            this.Customer_Query.CacheConnection = false;
            this.Customer_Query.CommandText = "SELECT top 50 CustomerID,CustomerName  FROM Customer";
            this.Customer_Query.CommandTimeout = 30;
            this.Customer_Query.CommandType = System.Data.CommandType.Text;
            this.Customer_Query.DynamicTableName = false;
            this.Customer_Query.EEPAlias = "JBERP";
            this.Customer_Query.EncodingAfter = null;
            this.Customer_Query.EncodingBefore = "Windows-1252";
            this.Customer_Query.EncodingConvert = null;
            this.Customer_Query.InfoConnection = this.InfoConnection1;
            keyItem9.KeyName = "CustomerID";
            this.Customer_Query.KeyFields.Add(keyItem9);
            this.Customer_Query.MultiSetWhere = false;
            this.Customer_Query.Name = "Customer_Query";
            this.Customer_Query.NotificationAutoEnlist = false;
            this.Customer_Query.SecExcept = null;
            this.Customer_Query.SecFieldName = null;
            this.Customer_Query.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Customer_Query.SelectPaging = false;
            this.Customer_Query.SelectTop = 0;
            this.Customer_Query.SiteControl = false;
            this.Customer_Query.SiteFieldName = null;
            this.Customer_Query.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // InvoiceType
            // 
            this.InvoiceType.CacheConnection = false;
            this.InvoiceType.CommandText = "select InvoiceType.InvoiceTypeID,InvoiceType.InvoiceTypeName from InvoiceType\r\nwh" +
    "ere InvoiceTypeID in(\'97\',\'98\',\'99\')";
            this.InvoiceType.CommandTimeout = 30;
            this.InvoiceType.CommandType = System.Data.CommandType.Text;
            this.InvoiceType.DynamicTableName = false;
            this.InvoiceType.EEPAlias = "JBERP";
            this.InvoiceType.EncodingAfter = null;
            this.InvoiceType.EncodingBefore = "Windows-1252";
            this.InvoiceType.EncodingConvert = null;
            this.InvoiceType.InfoConnection = this.InfoConnection1;
            this.InvoiceType.MultiSetWhere = false;
            this.InvoiceType.Name = "InvoiceType";
            this.InvoiceType.NotificationAutoEnlist = false;
            this.InvoiceType.SecExcept = null;
            this.InvoiceType.SecFieldName = null;
            this.InvoiceType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.InvoiceType.SelectPaging = false;
            this.InvoiceType.SelectTop = 0;
            this.InvoiceType.SiteControl = false;
            this.InvoiceType.SiteFieldName = null;
            this.InvoiceType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesTypeDateList
            // 
            this.SalesTypeDateList.CacheConnection = false;
            this.SalesTypeDateList.CommandText = "SELECT SalesTypeID,SalesDate,0 AS SalesCount\r\n FROM InvoiceDetails WHERE 1=2";
            this.SalesTypeDateList.CommandTimeout = 30;
            this.SalesTypeDateList.CommandType = System.Data.CommandType.Text;
            this.SalesTypeDateList.DynamicTableName = false;
            this.SalesTypeDateList.EEPAlias = "JBERP";
            this.SalesTypeDateList.EncodingAfter = null;
            this.SalesTypeDateList.EncodingBefore = "Windows-1252";
            this.SalesTypeDateList.EncodingConvert = null;
            this.SalesTypeDateList.InfoConnection = this.InfoConnection1;
            this.SalesTypeDateList.MultiSetWhere = false;
            this.SalesTypeDateList.Name = "SalesTypeDateList";
            this.SalesTypeDateList.NotificationAutoEnlist = false;
            this.SalesTypeDateList.SecExcept = null;
            this.SalesTypeDateList.SecFieldName = null;
            this.SalesTypeDateList.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesTypeDateList.SelectPaging = false;
            this.SalesTypeDateList.SelectTop = 0;
            this.SalesTypeDateList.SiteControl = false;
            this.SalesTypeDateList.SiteFieldName = null;
            this.SalesTypeDateList.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // DevelopLevel
            // 
            this.DevelopLevel.CacheConnection = false;
            this.DevelopLevel.CommandText = "SELECT *  FROM DEVELOPLEVEL\r\nORDER BY  DevelopLevelID";
            this.DevelopLevel.CommandTimeout = 30;
            this.DevelopLevel.CommandType = System.Data.CommandType.Text;
            this.DevelopLevel.DynamicTableName = false;
            this.DevelopLevel.EEPAlias = "JBERP";
            this.DevelopLevel.EncodingAfter = null;
            this.DevelopLevel.EncodingBefore = "Windows-1252";
            this.DevelopLevel.EncodingConvert = null;
            this.DevelopLevel.InfoConnection = this.InfoConnection1;
            keyItem10.KeyName = "AutoKey";
            this.DevelopLevel.KeyFields.Add(keyItem10);
            this.DevelopLevel.MultiSetWhere = false;
            this.DevelopLevel.Name = "DevelopLevel";
            this.DevelopLevel.NotificationAutoEnlist = false;
            this.DevelopLevel.SecExcept = null;
            this.DevelopLevel.SecFieldName = null;
            this.DevelopLevel.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.DevelopLevel.SelectPaging = false;
            this.DevelopLevel.SelectTop = 0;
            this.DevelopLevel.SiteControl = false;
            this.DevelopLevel.SiteFieldName = null;
            this.DevelopLevel.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ContactLogs
            // 
            this.ContactLogs.CacheConnection = false;
            this.ContactLogs.CommandText = "SELECT *,dbo.funReturnContactLogsViewer(ShareTo) as ShareToName\r\n FROM ContactLog" +
    "s\r\nORDER BY AutoKey DESC";
            this.ContactLogs.CommandTimeout = 30;
            this.ContactLogs.CommandType = System.Data.CommandType.Text;
            this.ContactLogs.DynamicTableName = false;
            this.ContactLogs.EEPAlias = "JBERP";
            this.ContactLogs.EncodingAfter = null;
            this.ContactLogs.EncodingBefore = "Windows-1252";
            this.ContactLogs.EncodingConvert = null;
            this.ContactLogs.InfoConnection = this.InfoConnection1;
            keyItem11.KeyName = "AutoKey";
            this.ContactLogs.KeyFields.Add(keyItem11);
            this.ContactLogs.MultiSetWhere = false;
            this.ContactLogs.Name = "ContactLogs";
            this.ContactLogs.NotificationAutoEnlist = false;
            this.ContactLogs.SecExcept = null;
            this.ContactLogs.SecFieldName = null;
            this.ContactLogs.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ContactLogs.SelectPaging = false;
            this.ContactLogs.SelectTop = 0;
            this.ContactLogs.SiteControl = false;
            this.ContactLogs.SiteFieldName = null;
            this.ContactLogs.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucContactLogs
            // 
            this.ucContactLogs.AutoTrans = true;
            this.ucContactLogs.ExceptJoin = false;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "AutoKey";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "CustomerID";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "SalesTypeID";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "ContactDate";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "ContactDescr";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "Dialogue";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "CreateBy";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = "_usercode";
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "CreateByName";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = "_username";
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "CreateDate";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            this.ucContactLogs.FieldAttrs.Add(fieldAttr48);
            this.ucContactLogs.FieldAttrs.Add(fieldAttr49);
            this.ucContactLogs.FieldAttrs.Add(fieldAttr50);
            this.ucContactLogs.FieldAttrs.Add(fieldAttr51);
            this.ucContactLogs.FieldAttrs.Add(fieldAttr52);
            this.ucContactLogs.FieldAttrs.Add(fieldAttr53);
            this.ucContactLogs.FieldAttrs.Add(fieldAttr54);
            this.ucContactLogs.FieldAttrs.Add(fieldAttr55);
            this.ucContactLogs.FieldAttrs.Add(fieldAttr56);
            this.ucContactLogs.LogInfo = null;
            this.ucContactLogs.Name = "ucContactLogs";
            this.ucContactLogs.RowAffectsCheck = true;
            this.ucContactLogs.SelectCmd = this.ContactLogs;
            this.ucContactLogs.SelectCmdForUpdate = null;
            this.ucContactLogs.SendSQLCmd = true;
            this.ucContactLogs.ServerModify = true;
            this.ucContactLogs.ServerModifyGetMax = false;
            this.ucContactLogs.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucContactLogs.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucContactLogs.UseTranscationScope = false;
            this.ucContactLogs.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucContactLogs.BeforeInsert += new Srvtools.UpdateComponentBeforeInsertEventHandler(this.ucContactLogs_BeforeInsert);
            // 
            // Dialogue
            // 
            this.Dialogue.CacheConnection = false;
            this.Dialogue.CommandText = "SELECT CustomerID,SalesKindID,Dialogue FROM ContactLogs\r\nWHERE (Dialogue != \'\' an" +
    "d   Dialogue is not null)  AND CustomerID != \'\'\r\nGROUP BY CustomerID,SalesKindID" +
    ",Dialogue ";
            this.Dialogue.CommandTimeout = 30;
            this.Dialogue.CommandType = System.Data.CommandType.Text;
            this.Dialogue.DynamicTableName = false;
            this.Dialogue.EEPAlias = "JBERP";
            this.Dialogue.EncodingAfter = null;
            this.Dialogue.EncodingBefore = "Windows-1252";
            this.Dialogue.EncodingConvert = null;
            this.Dialogue.InfoConnection = this.InfoConnection1;
            this.Dialogue.MultiSetWhere = false;
            this.Dialogue.Name = "Dialogue";
            this.Dialogue.NotificationAutoEnlist = false;
            this.Dialogue.SecExcept = null;
            this.Dialogue.SecFieldName = null;
            this.Dialogue.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Dialogue.SelectPaging = false;
            this.Dialogue.SelectTop = 0;
            this.Dialogue.SiteControl = false;
            this.Dialogue.SiteFieldName = null;
            this.Dialogue.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CountryArea
            // 
            this.CountryArea.CacheConnection = false;
            this.CountryArea.CommandText = "SELECT ContryAreaID, ContryAreaName,ContryAreaID+\'-\'+ContryAreaName AS IDName\r\nFR" +
    "OM  HUNTER.dbo.HUT_ContryArea";
            this.CountryArea.CommandTimeout = 30;
            this.CountryArea.CommandType = System.Data.CommandType.Text;
            this.CountryArea.DynamicTableName = false;
            this.CountryArea.EEPAlias = null;
            this.CountryArea.EncodingAfter = null;
            this.CountryArea.EncodingBefore = "Windows-1252";
            this.CountryArea.EncodingConvert = null;
            this.CountryArea.InfoConnection = this.InfoConnection1;
            keyItem12.KeyName = "ContryAreaID";
            this.CountryArea.KeyFields.Add(keyItem12);
            this.CountryArea.MultiSetWhere = false;
            this.CountryArea.Name = "CountryArea";
            this.CountryArea.NotificationAutoEnlist = false;
            this.CountryArea.SecExcept = null;
            this.CountryArea.SecFieldName = null;
            this.CountryArea.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CountryArea.SelectPaging = false;
            this.CountryArea.SelectTop = 0;
            this.CountryArea.SiteControl = false;
            this.CountryArea.SiteFieldName = null;
            this.CountryArea.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CustomerSaleKind
            // 
            this.CustomerSaleKind.CacheConnection = false;
            this.CustomerSaleKind.CommandText = resources.GetString("CustomerSaleKind.CommandText");
            this.CustomerSaleKind.CommandTimeout = 30;
            this.CustomerSaleKind.CommandType = System.Data.CommandType.Text;
            this.CustomerSaleKind.DynamicTableName = false;
            this.CustomerSaleKind.EEPAlias = "JBERP";
            this.CustomerSaleKind.EncodingAfter = null;
            this.CustomerSaleKind.EncodingBefore = "Windows-1252";
            this.CustomerSaleKind.EncodingConvert = null;
            this.CustomerSaleKind.InfoConnection = this.InfoConnection1;
            keyItem13.KeyName = "CustomerID";
            keyItem14.KeyName = "SalesKindID";
            this.CustomerSaleKind.KeyFields.Add(keyItem13);
            this.CustomerSaleKind.KeyFields.Add(keyItem14);
            this.CustomerSaleKind.MultiSetWhere = false;
            this.CustomerSaleKind.Name = "CustomerSaleKind";
            this.CustomerSaleKind.NotificationAutoEnlist = false;
            this.CustomerSaleKind.SecExcept = null;
            this.CustomerSaleKind.SecFieldName = null;
            this.CustomerSaleKind.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CustomerSaleKind.SelectPaging = false;
            this.CustomerSaleKind.SelectTop = 0;
            this.CustomerSaleKind.SiteControl = false;
            this.CustomerSaleKind.SiteFieldName = null;
            this.CustomerSaleKind.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucCustomerSaleKind
            // 
            this.ucCustomerSaleKind.AutoTrans = true;
            this.ucCustomerSaleKind.ExceptJoin = false;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "CustomerID";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "SalesKindID";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "DevelopLevelID";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "CreateBy";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "CreateDate";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            this.ucCustomerSaleKind.FieldAttrs.Add(fieldAttr57);
            this.ucCustomerSaleKind.FieldAttrs.Add(fieldAttr58);
            this.ucCustomerSaleKind.FieldAttrs.Add(fieldAttr59);
            this.ucCustomerSaleKind.FieldAttrs.Add(fieldAttr60);
            this.ucCustomerSaleKind.FieldAttrs.Add(fieldAttr61);
            this.ucCustomerSaleKind.LogInfo = null;
            this.ucCustomerSaleKind.Name = "ucCustomerSaleKind";
            this.ucCustomerSaleKind.RowAffectsCheck = true;
            this.ucCustomerSaleKind.SelectCmd = this.CustomerSaleKind;
            this.ucCustomerSaleKind.SelectCmdForUpdate = null;
            this.ucCustomerSaleKind.SendSQLCmd = true;
            this.ucCustomerSaleKind.ServerModify = true;
            this.ucCustomerSaleKind.ServerModifyGetMax = false;
            this.ucCustomerSaleKind.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucCustomerSaleKind.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucCustomerSaleKind.UseTranscationScope = false;
            this.ucCustomerSaleKind.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // SalesKind
            // 
            this.SalesKind.CacheConnection = false;
            this.SalesKind.CommandText = "SELECT  *\r\n FROM SalesKind ORDER BY SalesKindID";
            this.SalesKind.CommandTimeout = 30;
            this.SalesKind.CommandType = System.Data.CommandType.Text;
            this.SalesKind.DynamicTableName = false;
            this.SalesKind.EEPAlias = "JBERP";
            this.SalesKind.EncodingAfter = null;
            this.SalesKind.EncodingBefore = "Windows-1252";
            this.SalesKind.EncodingConvert = null;
            this.SalesKind.InfoConnection = this.InfoConnection1;
            keyItem15.KeyName = "AutoKey";
            this.SalesKind.KeyFields.Add(keyItem15);
            this.SalesKind.MultiSetWhere = false;
            this.SalesKind.Name = "SalesKind";
            this.SalesKind.NotificationAutoEnlist = false;
            this.SalesKind.SecExcept = null;
            this.SalesKind.SecFieldName = null;
            this.SalesKind.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesKind.SelectPaging = false;
            this.SalesKind.SelectTop = 0;
            this.SalesKind.SiteControl = false;
            this.SalesKind.SiteFieldName = null;
            this.SalesKind.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesKindUser
            // 
            this.SalesKindUser.CacheConnection = false;
            this.SalesKindUser.CommandText = resources.GetString("SalesKindUser.CommandText");
            this.SalesKindUser.CommandTimeout = 30;
            this.SalesKindUser.CommandType = System.Data.CommandType.Text;
            this.SalesKindUser.DynamicTableName = false;
            this.SalesKindUser.EEPAlias = "JBERP";
            this.SalesKindUser.EncodingAfter = null;
            this.SalesKindUser.EncodingBefore = "Windows-1252";
            this.SalesKindUser.EncodingConvert = null;
            this.SalesKindUser.InfoConnection = this.InfoConnection1;
            this.SalesKindUser.MultiSetWhere = false;
            this.SalesKindUser.Name = "SalesKindUser";
            this.SalesKindUser.NotificationAutoEnlist = false;
            this.SalesKindUser.SecExcept = null;
            this.SalesKindUser.SecFieldName = null;
            this.SalesKindUser.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesKindUser.SelectPaging = false;
            this.SalesKindUser.SelectTop = 0;
            this.SalesKindUser.SiteControl = false;
            this.SalesKindUser.SiteFieldName = null;
            this.SalesKindUser.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Industry
            // 
            this.Industry.CacheConnection = false;
            this.Industry.CommandText = "SELECT * FROM Hunter.dbo.vHUT_UserCareerCategory";
            this.Industry.CommandTimeout = 30;
            this.Industry.CommandType = System.Data.CommandType.Text;
            this.Industry.DynamicTableName = false;
            this.Industry.EEPAlias = null;
            this.Industry.EncodingAfter = null;
            this.Industry.EncodingBefore = "Windows-1252";
            this.Industry.EncodingConvert = null;
            this.Industry.InfoConnection = this.InfoConnection1;
            this.Industry.MultiSetWhere = false;
            this.Industry.Name = "Industry";
            this.Industry.NotificationAutoEnlist = false;
            this.Industry.SecExcept = null;
            this.Industry.SecFieldName = null;
            this.Industry.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Industry.SelectPaging = false;
            this.Industry.SelectTop = 0;
            this.Industry.SiteControl = false;
            this.Industry.SiteFieldName = null;
            this.Industry.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesKindSalesType
            // 
            this.SalesKindSalesType.CacheConnection = false;
            this.SalesKindSalesType.CommandText = resources.GetString("SalesKindSalesType.CommandText");
            this.SalesKindSalesType.CommandTimeout = 30;
            this.SalesKindSalesType.CommandType = System.Data.CommandType.Text;
            this.SalesKindSalesType.DynamicTableName = false;
            this.SalesKindSalesType.EEPAlias = "JBERP";
            this.SalesKindSalesType.EncodingAfter = null;
            this.SalesKindSalesType.EncodingBefore = "Windows-1252";
            this.SalesKindSalesType.EncodingConvert = null;
            this.SalesKindSalesType.InfoConnection = this.InfoConnection1;
            keyItem16.KeyName = "AutoKey";
            this.SalesKindSalesType.KeyFields.Add(keyItem16);
            this.SalesKindSalesType.MultiSetWhere = false;
            this.SalesKindSalesType.Name = "SalesKindSalesType";
            this.SalesKindSalesType.NotificationAutoEnlist = false;
            this.SalesKindSalesType.SecExcept = null;
            this.SalesKindSalesType.SecFieldName = null;
            this.SalesKindSalesType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesKindSalesType.SelectPaging = false;
            this.SalesKindSalesType.SelectTop = 0;
            this.SalesKindSalesType.SiteControl = false;
            this.SalesKindSalesType.SiteFieldName = null;
            this.SalesKindSalesType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // UserSalesKind
            // 
            this.UserSalesKind.CacheConnection = false;
            this.UserSalesKind.CommandText = resources.GetString("UserSalesKind.CommandText");
            this.UserSalesKind.CommandTimeout = 30;
            this.UserSalesKind.CommandType = System.Data.CommandType.Text;
            this.UserSalesKind.DynamicTableName = false;
            this.UserSalesKind.EEPAlias = "JBERP";
            this.UserSalesKind.EncodingAfter = null;
            this.UserSalesKind.EncodingBefore = "Windows-1252";
            this.UserSalesKind.EncodingConvert = null;
            this.UserSalesKind.InfoConnection = this.InfoConnection1;
            this.UserSalesKind.MultiSetWhere = false;
            this.UserSalesKind.Name = "UserSalesKind";
            this.UserSalesKind.NotificationAutoEnlist = false;
            this.UserSalesKind.SecExcept = null;
            this.UserSalesKind.SecFieldName = null;
            this.UserSalesKind.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.UserSalesKind.SelectPaging = false;
            this.UserSalesKind.SelectTop = 0;
            this.UserSalesKind.SiteControl = false;
            this.UserSalesKind.SiteFieldName = null;
            this.UserSalesKind.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Customer)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerSaleType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CountryCity)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DonateMark)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayWay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesPerson)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesSalesType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TaxType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Country)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.City)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TelNO_Query)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Customer_Query)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.InvoiceType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesTypeDateList)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DevelopLevel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ContactLogs)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Dialogue)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CountryArea)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CustomerSaleKind)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesKind)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesKindUser)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Industry)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesKindSalesType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UserSalesKind)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand Customer;
        private Srvtools.UpdateComponent ucCustomer;
        private Srvtools.InfoCommand CustomerSaleType;
        private Srvtools.UpdateComponent ucCustomerSaleType;
        private Srvtools.InfoCommand CountryCity;
        private Srvtools.UpdateComponent ucCountryCity;
        private Srvtools.InfoCommand DonateMark;
        private Srvtools.InfoCommand PayWay;
        private Srvtools.InfoCommand SalesPerson;
        private Srvtools.InfoCommand SalesSalesType;
        private Srvtools.UpdateComponent ucSalesSalesType;
        private Srvtools.InfoCommand SalesType;
        private Srvtools.InfoCommand TaxType;
        private Srvtools.InfoCommand Country;
        private Srvtools.InfoCommand City;
        private Srvtools.InfoCommand TelNO_Query;
        private Srvtools.InfoCommand CustomerType;
        private Srvtools.InfoCommand Customer_Query;
        private Srvtools.InfoCommand InvoiceType;
        private Srvtools.InfoCommand SalesTypeDateList;
        private Srvtools.InfoCommand DevelopLevel;
        private Srvtools.InfoCommand ContactLogs;
        private Srvtools.UpdateComponent ucContactLogs;
        private Srvtools.InfoCommand Dialogue;
        private Srvtools.InfoCommand CountryArea;
        private Srvtools.InfoCommand CustomerSaleKind;
        private Srvtools.UpdateComponent ucCustomerSaleKind;
        private Srvtools.InfoCommand SalesKind;
        private Srvtools.InfoCommand SalesKindUser;
        private Srvtools.InfoCommand Industry;
        private Srvtools.InfoCommand SalesKindSalesType;
        private Srvtools.InfoCommand UserSalesKind;
    }
}
