namespace sERPSalesEmail
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.ERPSalesDetails = new Srvtools.InfoCommand(this.components);
            this.ucERPSalesDetails = new Srvtools.UpdateComponent(this.components);
            this.View_ERPSalesDetails = new Srvtools.InfoCommand(this.components);
            this.SalesYM_ERPSalesDetails = new Srvtools.InfoCommand(this.components);
            this.View_ERPCustomers = new Srvtools.InfoCommand(this.components);
            this.ERPSalesMan = new Srvtools.InfoCommand(this.components);
            this.User = new Srvtools.InfoCommand(this.components);
            this.IsAcceptePaper = new Srvtools.InfoCommand(this.components);
            this.InvoiceYM = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_ERPSalesDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesYM_ERPSalesDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_ERPCustomers)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesMan)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.User)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.IsAcceptePaper)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.InvoiceYM)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "UpdateERPSalesEmail";
            service1.NonLogin = false;
            service1.ServiceName = "UpdateERPSalesEmail";
            this.serviceManager1.ServiceCollection.Add(service1);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // ERPSalesDetails
            // 
            this.ERPSalesDetails.CacheConnection = false;
            this.ERPSalesDetails.CommandText = resources.GetString("ERPSalesDetails.CommandText");
            this.ERPSalesDetails.CommandTimeout = 30;
            this.ERPSalesDetails.CommandType = System.Data.CommandType.Text;
            this.ERPSalesDetails.DynamicTableName = false;
            this.ERPSalesDetails.EEPAlias = null;
            this.ERPSalesDetails.EncodingAfter = null;
            this.ERPSalesDetails.EncodingBefore = "Windows-1252";
            this.ERPSalesDetails.EncodingConvert = null;
            this.ERPSalesDetails.InfoConnection = this.InfoConnection1;
            this.ERPSalesDetails.MultiSetWhere = false;
            this.ERPSalesDetails.Name = "ERPSalesDetails";
            this.ERPSalesDetails.NotificationAutoEnlist = false;
            this.ERPSalesDetails.SecExcept = null;
            this.ERPSalesDetails.SecFieldName = null;
            this.ERPSalesDetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPSalesDetails.SelectPaging = false;
            this.ERPSalesDetails.SelectTop = 0;
            this.ERPSalesDetails.SiteControl = false;
            this.ERPSalesDetails.SiteFieldName = null;
            this.ERPSalesDetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPSalesDetails
            // 
            this.ucERPSalesDetails.AutoTrans = true;
            this.ucERPSalesDetails.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "SalesMasterNO";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "ItemSeq";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "CustNO";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "SalesID";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "SalesEmployeeID";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "SalesTypeID";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "DMTypeID";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "SalesDate";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "InvoiceYM";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "GrantTypeID";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "CustPrice";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "SalesQty";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "SalesQtyView";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "CustAmt";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "Commission";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "PublishCount";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "PresentCount";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "PresentWNewsCount";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "SalesDescr";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "SalesDescrDate";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "SalesDescrAlert";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "CustLines";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "OfficePrice";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "OfficeLines";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "OfficeAmt";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "NewsTypeID";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "NewsAreaID";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "NewsPublishID";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "Sections";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "IsActive";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "IsSetInvoice";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "SalesOutLine";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "IsImport";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "CreateBy";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "CreateDate";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "AcceptDate";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "IsTransSys";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "InvoiceYMPoint";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "depositSeq";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "ViewAreaID";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "ContractDescr";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "IsInvoice";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "LastUpdateBy";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "LastUpdateDate";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "depositOV";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "SysDate";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "Remark1";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "AFrameXY";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "BFrameXY";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "CFrameXY";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr1);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr2);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr3);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr4);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr5);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr6);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr7);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr8);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr9);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr10);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr11);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr12);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr13);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr14);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr15);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr16);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr17);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr18);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr19);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr20);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr21);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr22);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr23);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr24);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr25);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr26);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr27);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr28);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr29);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr30);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr31);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr32);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr33);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr34);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr35);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr36);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr37);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr38);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr39);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr40);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr41);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr42);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr43);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr44);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr45);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr46);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr47);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr48);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr49);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr50);
            this.ucERPSalesDetails.LogInfo = null;
            this.ucERPSalesDetails.Name = "ucERPSalesDetails";
            this.ucERPSalesDetails.RowAffectsCheck = true;
            this.ucERPSalesDetails.SelectCmd = this.ERPSalesDetails;
            this.ucERPSalesDetails.SelectCmdForUpdate = null;
            this.ucERPSalesDetails.SendSQLCmd = true;
            this.ucERPSalesDetails.ServerModify = true;
            this.ucERPSalesDetails.ServerModifyGetMax = false;
            this.ucERPSalesDetails.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPSalesDetails.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPSalesDetails.UseTranscationScope = false;
            this.ucERPSalesDetails.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_ERPSalesDetails
            // 
            this.View_ERPSalesDetails.CacheConnection = false;
            this.View_ERPSalesDetails.CommandText = "SELECT * FROM dbo.[ERPSalesDetails]";
            this.View_ERPSalesDetails.CommandTimeout = 30;
            this.View_ERPSalesDetails.CommandType = System.Data.CommandType.Text;
            this.View_ERPSalesDetails.DynamicTableName = false;
            this.View_ERPSalesDetails.EEPAlias = null;
            this.View_ERPSalesDetails.EncodingAfter = null;
            this.View_ERPSalesDetails.EncodingBefore = "Windows-1252";
            this.View_ERPSalesDetails.EncodingConvert = null;
            this.View_ERPSalesDetails.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "SalesMasterNO";
            keyItem2.KeyName = "ItemSeq";
            this.View_ERPSalesDetails.KeyFields.Add(keyItem1);
            this.View_ERPSalesDetails.KeyFields.Add(keyItem2);
            this.View_ERPSalesDetails.MultiSetWhere = false;
            this.View_ERPSalesDetails.Name = "View_ERPSalesDetails";
            this.View_ERPSalesDetails.NotificationAutoEnlist = false;
            this.View_ERPSalesDetails.SecExcept = null;
            this.View_ERPSalesDetails.SecFieldName = null;
            this.View_ERPSalesDetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_ERPSalesDetails.SelectPaging = false;
            this.View_ERPSalesDetails.SelectTop = 0;
            this.View_ERPSalesDetails.SiteControl = false;
            this.View_ERPSalesDetails.SiteFieldName = null;
            this.View_ERPSalesDetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesYM_ERPSalesDetails
            // 
            this.SalesYM_ERPSalesDetails.CacheConnection = false;
            this.SalesYM_ERPSalesDetails.CommandText = resources.GetString("SalesYM_ERPSalesDetails.CommandText");
            this.SalesYM_ERPSalesDetails.CommandTimeout = 30;
            this.SalesYM_ERPSalesDetails.CommandType = System.Data.CommandType.Text;
            this.SalesYM_ERPSalesDetails.DynamicTableName = false;
            this.SalesYM_ERPSalesDetails.EEPAlias = null;
            this.SalesYM_ERPSalesDetails.EncodingAfter = null;
            this.SalesYM_ERPSalesDetails.EncodingBefore = "Windows-1252";
            this.SalesYM_ERPSalesDetails.EncodingConvert = null;
            this.SalesYM_ERPSalesDetails.InfoConnection = this.InfoConnection1;
            this.SalesYM_ERPSalesDetails.MultiSetWhere = false;
            this.SalesYM_ERPSalesDetails.Name = "SalesYM_ERPSalesDetails";
            this.SalesYM_ERPSalesDetails.NotificationAutoEnlist = false;
            this.SalesYM_ERPSalesDetails.SecExcept = null;
            this.SalesYM_ERPSalesDetails.SecFieldName = null;
            this.SalesYM_ERPSalesDetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesYM_ERPSalesDetails.SelectPaging = false;
            this.SalesYM_ERPSalesDetails.SelectTop = 0;
            this.SalesYM_ERPSalesDetails.SiteControl = false;
            this.SalesYM_ERPSalesDetails.SiteFieldName = null;
            this.SalesYM_ERPSalesDetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // View_ERPCustomers
            // 
            this.View_ERPCustomers.CacheConnection = false;
            this.View_ERPCustomers.CommandText = "select \'==不拘==\' as CustNO,\'  ==不拘==\' as CustShortName\r\nunion all\r\nselect  CustNO," +
    "(CustNO+\' : \'+CustShortName) as CustShortName\r\nfrom  DBO.ERPCustomers\r\norder by " +
    "CustShortName";
            this.View_ERPCustomers.CommandTimeout = 30;
            this.View_ERPCustomers.CommandType = System.Data.CommandType.Text;
            this.View_ERPCustomers.DynamicTableName = false;
            this.View_ERPCustomers.EEPAlias = null;
            this.View_ERPCustomers.EncodingAfter = null;
            this.View_ERPCustomers.EncodingBefore = "Windows-1252";
            this.View_ERPCustomers.EncodingConvert = null;
            this.View_ERPCustomers.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "CustNO";
            this.View_ERPCustomers.KeyFields.Add(keyItem3);
            this.View_ERPCustomers.MultiSetWhere = false;
            this.View_ERPCustomers.Name = "View_ERPCustomers";
            this.View_ERPCustomers.NotificationAutoEnlist = false;
            this.View_ERPCustomers.SecExcept = null;
            this.View_ERPCustomers.SecFieldName = null;
            this.View_ERPCustomers.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_ERPCustomers.SelectPaging = false;
            this.View_ERPCustomers.SelectTop = 0;
            this.View_ERPCustomers.SiteControl = false;
            this.View_ERPCustomers.SiteFieldName = null;
            this.View_ERPCustomers.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ERPSalesMan
            // 
            this.ERPSalesMan.CacheConnection = false;
            this.ERPSalesMan.CommandText = "select  \'==不拘==\' as SalesEmployeeID,\'==不拘==\' as SalesID,\'==不拘==\'  as SalesName\r\nu" +
    "nion all\r\nselect  SalesEmployeeID,SalesID,SalesName+\'-\'+SalesID as SalesName\r\nfr" +
    "om ERPSalesMan\r\nwhere IsMedia=1";
            this.ERPSalesMan.CommandTimeout = 30;
            this.ERPSalesMan.CommandType = System.Data.CommandType.Text;
            this.ERPSalesMan.DynamicTableName = false;
            this.ERPSalesMan.EEPAlias = null;
            this.ERPSalesMan.EncodingAfter = null;
            this.ERPSalesMan.EncodingBefore = "Windows-1252";
            this.ERPSalesMan.EncodingConvert = null;
            this.ERPSalesMan.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "SalesID";
            this.ERPSalesMan.KeyFields.Add(keyItem4);
            this.ERPSalesMan.MultiSetWhere = false;
            this.ERPSalesMan.Name = "ERPSalesMan";
            this.ERPSalesMan.NotificationAutoEnlist = false;
            this.ERPSalesMan.SecExcept = null;
            this.ERPSalesMan.SecFieldName = null;
            this.ERPSalesMan.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPSalesMan.SelectPaging = false;
            this.ERPSalesMan.SelectTop = 0;
            this.ERPSalesMan.SiteControl = false;
            this.ERPSalesMan.SiteFieldName = null;
            this.ERPSalesMan.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // User
            // 
            this.User.CacheConnection = false;
            this.User.CommandText = "SELECT USERID,EXT FROM EIPHRSYS.DBO.USERS";
            this.User.CommandTimeout = 30;
            this.User.CommandType = System.Data.CommandType.Text;
            this.User.DynamicTableName = false;
            this.User.EEPAlias = null;
            this.User.EncodingAfter = null;
            this.User.EncodingBefore = "Windows-1252";
            this.User.EncodingConvert = null;
            this.User.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "USERID";
            this.User.KeyFields.Add(keyItem5);
            this.User.MultiSetWhere = false;
            this.User.Name = "User";
            this.User.NotificationAutoEnlist = false;
            this.User.SecExcept = null;
            this.User.SecFieldName = null;
            this.User.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.User.SelectPaging = false;
            this.User.SelectTop = 0;
            this.User.SiteControl = false;
            this.User.SiteFieldName = null;
            this.User.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // IsAcceptePaper
            // 
            this.IsAcceptePaper.CacheConnection = false;
            this.IsAcceptePaper.CommandText = resources.GetString("IsAcceptePaper.CommandText");
            this.IsAcceptePaper.CommandTimeout = 30;
            this.IsAcceptePaper.CommandType = System.Data.CommandType.Text;
            this.IsAcceptePaper.DynamicTableName = false;
            this.IsAcceptePaper.EEPAlias = null;
            this.IsAcceptePaper.EncodingAfter = null;
            this.IsAcceptePaper.EncodingBefore = "Windows-1252";
            this.IsAcceptePaper.EncodingConvert = null;
            this.IsAcceptePaper.InfoConnection = this.InfoConnection1;
            this.IsAcceptePaper.MultiSetWhere = false;
            this.IsAcceptePaper.Name = "IsAcceptePaper";
            this.IsAcceptePaper.NotificationAutoEnlist = false;
            this.IsAcceptePaper.SecExcept = null;
            this.IsAcceptePaper.SecFieldName = null;
            this.IsAcceptePaper.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.IsAcceptePaper.SelectPaging = false;
            this.IsAcceptePaper.SelectTop = 0;
            this.IsAcceptePaper.SiteControl = false;
            this.IsAcceptePaper.SiteFieldName = null;
            this.IsAcceptePaper.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // InvoiceYM
            // 
            this.InvoiceYM.CacheConnection = false;
            this.InvoiceYM.CommandText = "select  \'不拘\' as InvoiceYM\r\nunion all\r\nSELECT distinct InvoiceYM\r\nFROM dbo.[ERPSal" +
    "esDetails]\r\norder by InvoiceYM desc";
            this.InvoiceYM.CommandTimeout = 30;
            this.InvoiceYM.CommandType = System.Data.CommandType.Text;
            this.InvoiceYM.DynamicTableName = false;
            this.InvoiceYM.EEPAlias = null;
            this.InvoiceYM.EncodingAfter = null;
            this.InvoiceYM.EncodingBefore = "Windows-1252";
            this.InvoiceYM.EncodingConvert = null;
            this.InvoiceYM.InfoConnection = this.InfoConnection1;
            this.InvoiceYM.MultiSetWhere = false;
            this.InvoiceYM.Name = "InvoiceYM";
            this.InvoiceYM.NotificationAutoEnlist = false;
            this.InvoiceYM.SecExcept = null;
            this.InvoiceYM.SecFieldName = null;
            this.InvoiceYM.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.InvoiceYM.SelectPaging = false;
            this.InvoiceYM.SelectTop = 0;
            this.InvoiceYM.SiteControl = false;
            this.InvoiceYM.SiteFieldName = null;
            this.InvoiceYM.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_ERPSalesDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesYM_ERPSalesDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_ERPCustomers)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesMan)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.User)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.IsAcceptePaper)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.InvoiceYM)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand ERPSalesDetails;
        private Srvtools.UpdateComponent ucERPSalesDetails;
        private Srvtools.InfoCommand View_ERPSalesDetails;
        private Srvtools.InfoCommand SalesYM_ERPSalesDetails;
        private Srvtools.InfoCommand View_ERPCustomers;
        private Srvtools.InfoCommand ERPSalesMan;
        private Srvtools.InfoCommand User;
        private Srvtools.InfoCommand IsAcceptePaper;
        private Srvtools.InfoCommand InvoiceYM;
    }
}
