namespace sPO_Normal_PRPOIQC
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            Srvtools.Service service9 = new Srvtools.Service();
            Srvtools.Service service10 = new Srvtools.Service();
            Srvtools.Service service11 = new Srvtools.Service();
            Srvtools.Service service12 = new Srvtools.Service();
            Srvtools.Service service13 = new Srvtools.Service();
            Srvtools.Service service14 = new Srvtools.Service();
            Srvtools.Service service15 = new Srvtools.Service();
            Srvtools.Service service16 = new Srvtools.Service();
            Srvtools.Service service17 = new Srvtools.Service();
            Srvtools.Service service18 = new Srvtools.Service();
            Srvtools.Service service19 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.ColumnItem columnItem1 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem2 = new Srvtools.ColumnItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.ColumnItem columnItem3 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem4 = new Srvtools.ColumnItem();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr69 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr70 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr71 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr72 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr73 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr74 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr75 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr76 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr77 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr78 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr79 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr80 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr81 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr82 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr83 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr84 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr85 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr86 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr87 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr88 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr89 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr90 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr91 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr92 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr93 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.POMaster = new Srvtools.InfoCommand(this.components);
            this.ucPOMaster = new Srvtools.UpdateComponent(this.components);
            this.PODetails = new Srvtools.InfoCommand(this.components);
            this.ucPODetails = new Srvtools.UpdateComponent(this.components);
            this.idPOMaster_PODetails = new Srvtools.InfoDataSource(this.components);
            this.View_POMaster = new Srvtools.InfoCommand(this.components);
            this.autoNumber1 = new Srvtools.AutoNumber(this.components);
            this.glCostCenter = new Srvtools.InfoCommand(this.components);
            this.ItemType = new Srvtools.InfoCommand(this.components);
            this.POType = new Srvtools.InfoCommand(this.components);
            this.RequistKind = new Srvtools.InfoCommand(this.components);
            this.Item = new Srvtools.InfoCommand(this.components);
            this.Vendors = new Srvtools.InfoCommand(this.components);
            this.Users = new Srvtools.InfoCommand(this.components);
            this.infoConnection2 = new Srvtools.InfoConnection(this.components);
            this.SYS_ORG = new Srvtools.InfoCommand(this.components);
            this.PODelivery = new Srvtools.InfoCommand(this.components);
            this.idPOMaster_PODelivery = new Srvtools.InfoDataSource(this.components);
            this.ucPODelivery = new Srvtools.UpdateComponent(this.components);
            this.InsGroup = new Srvtools.InfoCommand(this.components);
            this.infoConnection3 = new Srvtools.InfoConnection(this.components);
            this.PayWay = new Srvtools.InfoCommand(this.components);
            this.ResponsibleGROUPID = new Srvtools.InfoCommand(this.components);
            this.GROUPS = new Srvtools.InfoCommand(this.components);
            this.PODetailsHistory = new Srvtools.InfoCommand(this.components);
            this.ItemTypeAcno = new Srvtools.InfoCommand(this.components);
            this.ProofType = new Srvtools.InfoCommand(this.components);
            this.POPayType = new Srvtools.InfoCommand(this.components);
            this.AssetLocation = new Srvtools.InfoCommand(this.components);
            this.VoucherYear = new Srvtools.InfoCommand(this.components);
            this.Vendors1 = new Srvtools.InfoCommand(this.components);
            this.ShortTerm = new Srvtools.InfoCommand(this.components);
            this.UsersAll = new Srvtools.InfoCommand(this.components);
            this.ItemTypeItems = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.POMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_POMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.glCostCenter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.POType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RequistKind)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Item)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Vendors)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Users)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYS_ORG)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODelivery)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsGroup)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayWay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ResponsibleGROUPID)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.GROUPS)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODetailsHistory)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemTypeAcno)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ProofType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.POPayType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.AssetLocation)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.VoucherYear)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Vendors1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ShortTerm)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UsersAll)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemTypeItems)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "FlowStartUp";
            service1.NonLogin = false;
            service1.ServiceName = "FlowStartUp";
            service2.DelegateName = "GetUserOrgNOs";
            service2.NonLogin = false;
            service2.ServiceName = "GetUserOrgNOs";
            service3.DelegateName = "FlowStartUpByHand";
            service3.NonLogin = false;
            service3.ServiceName = "FlowStartUpByHand";
            service4.DelegateName = "GetOrgNO_CostCenterID";
            service4.NonLogin = false;
            service4.ServiceName = "GetOrgNO_CostCenterID";
            service5.DelegateName = "sysVariable_Default";
            service5.NonLogin = false;
            service5.ServiceName = "sysVariable_Default";
            service6.DelegateName = "IsPurchaserNotCompleted";
            service6.NonLogin = false;
            service6.ServiceName = "IsPurchaserNotCompleted";
            service7.DelegateName = "InsertAssetApplyFromPO_Normal_PRPOIQC";
            service7.NonLogin = false;
            service7.ServiceName = "InsertAssetApplyFromPO_Normal_PRPOIQC";
            service8.DelegateName = "PutPODeliveryToAPDetails";
            service8.NonLogin = false;
            service8.ServiceName = "PutPODeliveryToAPDetails";
            service9.DelegateName = "IsAllReceived";
            service9.NonLogin = false;
            service9.ServiceName = "IsAllReceived";
            service10.DelegateName = "NullProcedure";
            service10.NonLogin = false;
            service10.ServiceName = "NullProcedure";
            service11.DelegateName = "GetPlanPayDate";
            service11.NonLogin = false;
            service11.ServiceName = "GetPlanPayDate";
            service12.DelegateName = "PRTotalAmount";
            service12.NonLogin = false;
            service12.ServiceName = "PRTotalAmount";
            service13.DelegateName = "PRTotalAmount1";
            service13.NonLogin = false;
            service13.ServiceName = "PRTotalAmount1";
            service14.DelegateName = "PRTotalAmount2";
            service14.NonLogin = false;
            service14.ServiceName = "PRTotalAmount2";
            service15.DelegateName = "PostIsCatalogue";
            service15.NonLogin = false;
            service15.ServiceName = "PostIsCatalogue";
            service16.DelegateName = "DeliveryIsEnough";
            service16.NonLogin = false;
            service16.ServiceName = "DeliveryIsEnough";
            service17.DelegateName = "POTotalAmount";
            service17.NonLogin = false;
            service17.ServiceName = "POTotalAmount";
            service18.DelegateName = "POTotalAmount1";
            service18.NonLogin = false;
            service18.ServiceName = "POTotalAmount1";
            service19.DelegateName = "POTotalAmount2";
            service19.NonLogin = false;
            service19.ServiceName = "POTotalAmount2";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            this.serviceManager1.ServiceCollection.Add(service9);
            this.serviceManager1.ServiceCollection.Add(service10);
            this.serviceManager1.ServiceCollection.Add(service11);
            this.serviceManager1.ServiceCollection.Add(service12);
            this.serviceManager1.ServiceCollection.Add(service13);
            this.serviceManager1.ServiceCollection.Add(service14);
            this.serviceManager1.ServiceCollection.Add(service15);
            this.serviceManager1.ServiceCollection.Add(service16);
            this.serviceManager1.ServiceCollection.Add(service17);
            this.serviceManager1.ServiceCollection.Add(service18);
            this.serviceManager1.ServiceCollection.Add(service19);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // POMaster
            // 
            this.POMaster.CacheConnection = false;
            this.POMaster.CommandText = resources.GetString("POMaster.CommandText");
            this.POMaster.CommandTimeout = 30;
            this.POMaster.CommandType = System.Data.CommandType.Text;
            this.POMaster.DynamicTableName = false;
            this.POMaster.EEPAlias = null;
            this.POMaster.EncodingAfter = null;
            this.POMaster.EncodingBefore = "Windows-1252";
            this.POMaster.EncodingConvert = null;
            this.POMaster.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "PONO";
            this.POMaster.KeyFields.Add(keyItem1);
            this.POMaster.MultiSetWhere = true;
            this.POMaster.Name = "POMaster";
            this.POMaster.NotificationAutoEnlist = false;
            this.POMaster.SecExcept = null;
            this.POMaster.SecFieldName = null;
            this.POMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.POMaster.SelectPaging = false;
            this.POMaster.SelectTop = 0;
            this.POMaster.SiteControl = false;
            this.POMaster.SiteFieldName = null;
            this.POMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucPOMaster
            // 
            this.ucPOMaster.AutoTrans = true;
            this.ucPOMaster.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "PONO";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "ApplyDate";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "ApplyUserID";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "Description";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "CostCenterID";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ApplyOrg_NO";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "Org_NOParent";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "ItemTypeID";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "POTypeID";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "RequisitKindID";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "Flowflag";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CreateBy";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = "_username";
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "CreateDate";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = "_sysdate";
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "LastUpdateBy";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr14.DefaultValue = "_username";
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "LastUpdateDate";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr15.DefaultValue = "_sysdate";
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "ResponsibleGROUPID";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "FlagDeliveryEnough";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "AcSubno";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "Acno";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "SubAcno";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "RecVendor";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "PurVendor1";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "PurVendor2";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "PurVendor3";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "PurDocVen1";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "PurDocVen2";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "PurDocVen3";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "OtherFee";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "OtherFeeTax";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "OtherComment";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "POPayTypeID";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "PurComment";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "PurCommentFile";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "VoucherYear";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "Installments";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "AccountantRoleID";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "PrPic";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "PrDoc";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "IsAdd";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "IsCatalogue";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "RequestNotes";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "ShortTermNO";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "Org_NOParent1";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            this.ucPOMaster.FieldAttrs.Add(fieldAttr1);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr2);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr3);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr4);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr5);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr6);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr7);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr8);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr9);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr10);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr11);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr12);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr13);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr14);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr15);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr16);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr17);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr18);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr19);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr20);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr21);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr22);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr23);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr24);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr25);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr26);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr27);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr28);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr29);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr30);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr31);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr32);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr33);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr34);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr35);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr36);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr37);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr38);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr39);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr40);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr41);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr42);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr43);
            this.ucPOMaster.LogInfo = null;
            this.ucPOMaster.Name = "ucPOMaster";
            this.ucPOMaster.RowAffectsCheck = true;
            this.ucPOMaster.SelectCmd = this.POMaster;
            this.ucPOMaster.SelectCmdForUpdate = null;
            this.ucPOMaster.SendSQLCmd = true;
            this.ucPOMaster.ServerModify = true;
            this.ucPOMaster.ServerModifyGetMax = false;
            this.ucPOMaster.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucPOMaster.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucPOMaster.UseTranscationScope = false;
            this.ucPOMaster.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucPOMaster.AfterApplied += new System.EventHandler(this.ucPOMaster_AfterApplied);
            // 
            // PODetails
            // 
            this.PODetails.CacheConnection = false;
            this.PODetails.CommandText = resources.GetString("PODetails.CommandText");
            this.PODetails.CommandTimeout = 30;
            this.PODetails.CommandType = System.Data.CommandType.Text;
            this.PODetails.DynamicTableName = false;
            this.PODetails.EEPAlias = null;
            this.PODetails.EncodingAfter = null;
            this.PODetails.EncodingBefore = "Windows-1252";
            this.PODetails.EncodingConvert = null;
            this.PODetails.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "PONO";
            keyItem3.KeyName = "ItemNO";
            this.PODetails.KeyFields.Add(keyItem2);
            this.PODetails.KeyFields.Add(keyItem3);
            this.PODetails.MultiSetWhere = false;
            this.PODetails.Name = "PODetails";
            this.PODetails.NotificationAutoEnlist = false;
            this.PODetails.SecExcept = null;
            this.PODetails.SecFieldName = null;
            this.PODetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PODetails.SelectPaging = false;
            this.PODetails.SelectTop = 0;
            this.PODetails.SiteControl = false;
            this.PODetails.SiteFieldName = null;
            this.PODetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucPODetails
            // 
            this.ucPODetails.AutoTrans = true;
            this.ucPODetails.ExceptJoin = false;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "PONO";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "ItemNO";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "ItemID";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "IsAsset";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "ItemSpec";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "RegQty";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "RegPrice";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "Unit";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "RegDate";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "PurQty";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "PurPrice";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "PurTax";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "PurVendor";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "PurComment";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "PurPriceVen1";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "PurPriceVen2";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "PurPriceVen3";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "CreateBy";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = "_username";
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "CreateDate";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = "_sysdate";
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "LastUpdateBy";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr63.DefaultValue = "_username";
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "LastUpdateDate";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr64.DefaultValue = "_sysdate";
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "FirstDeliveryDate";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = null;
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "FirstDeliveryQty";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = null;
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            this.ucPODetails.FieldAttrs.Add(fieldAttr44);
            this.ucPODetails.FieldAttrs.Add(fieldAttr45);
            this.ucPODetails.FieldAttrs.Add(fieldAttr46);
            this.ucPODetails.FieldAttrs.Add(fieldAttr47);
            this.ucPODetails.FieldAttrs.Add(fieldAttr48);
            this.ucPODetails.FieldAttrs.Add(fieldAttr49);
            this.ucPODetails.FieldAttrs.Add(fieldAttr50);
            this.ucPODetails.FieldAttrs.Add(fieldAttr51);
            this.ucPODetails.FieldAttrs.Add(fieldAttr52);
            this.ucPODetails.FieldAttrs.Add(fieldAttr53);
            this.ucPODetails.FieldAttrs.Add(fieldAttr54);
            this.ucPODetails.FieldAttrs.Add(fieldAttr55);
            this.ucPODetails.FieldAttrs.Add(fieldAttr56);
            this.ucPODetails.FieldAttrs.Add(fieldAttr57);
            this.ucPODetails.FieldAttrs.Add(fieldAttr58);
            this.ucPODetails.FieldAttrs.Add(fieldAttr59);
            this.ucPODetails.FieldAttrs.Add(fieldAttr60);
            this.ucPODetails.FieldAttrs.Add(fieldAttr61);
            this.ucPODetails.FieldAttrs.Add(fieldAttr62);
            this.ucPODetails.FieldAttrs.Add(fieldAttr63);
            this.ucPODetails.FieldAttrs.Add(fieldAttr64);
            this.ucPODetails.FieldAttrs.Add(fieldAttr65);
            this.ucPODetails.FieldAttrs.Add(fieldAttr66);
            this.ucPODetails.LogInfo = null;
            this.ucPODetails.Name = "ucPODetails";
            this.ucPODetails.RowAffectsCheck = true;
            this.ucPODetails.SelectCmd = this.PODetails;
            this.ucPODetails.SelectCmdForUpdate = null;
            this.ucPODetails.SendSQLCmd = true;
            this.ucPODetails.ServerModify = true;
            this.ucPODetails.ServerModifyGetMax = false;
            this.ucPODetails.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucPODetails.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucPODetails.UseTranscationScope = false;
            this.ucPODetails.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucPODetails.AfterInsert += new Srvtools.UpdateComponentAfterInsertEventHandler(this.ucPODetails_AfterInsert);
            this.ucPODetails.AfterModify += new Srvtools.UpdateComponentAfterModifyEventHandler(this.ucPODetails_AfterModify);
            // 
            // idPOMaster_PODetails
            // 
            this.idPOMaster_PODetails.Detail = this.PODetails;
            columnItem1.FieldName = "PONO";
            this.idPOMaster_PODetails.DetailColumns.Add(columnItem1);
            this.idPOMaster_PODetails.DynamicTableName = false;
            this.idPOMaster_PODetails.Master = this.POMaster;
            columnItem2.FieldName = "PONO";
            this.idPOMaster_PODetails.MasterColumns.Add(columnItem2);
            // 
            // View_POMaster
            // 
            this.View_POMaster.CacheConnection = false;
            this.View_POMaster.CommandText = "SELECT * FROM dbo.[POMaster]";
            this.View_POMaster.CommandTimeout = 30;
            this.View_POMaster.CommandType = System.Data.CommandType.Text;
            this.View_POMaster.DynamicTableName = false;
            this.View_POMaster.EEPAlias = null;
            this.View_POMaster.EncodingAfter = null;
            this.View_POMaster.EncodingBefore = "Windows-1252";
            this.View_POMaster.EncodingConvert = null;
            this.View_POMaster.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "PONO";
            this.View_POMaster.KeyFields.Add(keyItem4);
            this.View_POMaster.MultiSetWhere = false;
            this.View_POMaster.Name = "View_POMaster";
            this.View_POMaster.NotificationAutoEnlist = false;
            this.View_POMaster.SecExcept = null;
            this.View_POMaster.SecFieldName = null;
            this.View_POMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_POMaster.SelectPaging = false;
            this.View_POMaster.SelectTop = 0;
            this.View_POMaster.SiteControl = false;
            this.View_POMaster.SiteFieldName = null;
            this.View_POMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // autoNumber1
            // 
            this.autoNumber1.Active = true;
            this.autoNumber1.AutoNoID = "PONO";
            this.autoNumber1.Description = null;
            this.autoNumber1.GetFixed = "ReturnGetFixed()";
            this.autoNumber1.isNumFill = false;
            this.autoNumber1.Name = "autoNumber1";
            this.autoNumber1.Number = null;
            this.autoNumber1.NumDig = 5;
            this.autoNumber1.OldVersion = false;
            this.autoNumber1.OverFlow = true;
            this.autoNumber1.StartValue = 1;
            this.autoNumber1.Step = 1;
            this.autoNumber1.TargetColumn = "PONO";
            this.autoNumber1.UpdateComp = this.ucPOMaster;
            // 
            // glCostCenter
            // 
            this.glCostCenter.CacheConnection = false;
            this.glCostCenter.CommandText = "SELECT [CostCenterID],[CostCenterName] FROM [JBADMIN].[dbo].[glCostCenter]\r\n";
            this.glCostCenter.CommandTimeout = 30;
            this.glCostCenter.CommandType = System.Data.CommandType.Text;
            this.glCostCenter.DynamicTableName = false;
            this.glCostCenter.EEPAlias = "";
            this.glCostCenter.EncodingAfter = null;
            this.glCostCenter.EncodingBefore = "Windows-1252";
            this.glCostCenter.EncodingConvert = null;
            this.glCostCenter.InfoConnection = this.InfoConnection1;
            this.glCostCenter.MultiSetWhere = false;
            this.glCostCenter.Name = "glCostCenter";
            this.glCostCenter.NotificationAutoEnlist = false;
            this.glCostCenter.SecExcept = null;
            this.glCostCenter.SecFieldName = null;
            this.glCostCenter.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.glCostCenter.SelectPaging = false;
            this.glCostCenter.SelectTop = 0;
            this.glCostCenter.SiteControl = false;
            this.glCostCenter.SiteFieldName = null;
            this.glCostCenter.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ItemType
            // 
            this.ItemType.CacheConnection = false;
            this.ItemType.CommandText = "SELECT it.ItemTypeID,it.ItemTypeName,it.ResponsibleGROUPID,g.GROUPNAME FROM dbo.[" +
    "ItemType] it\r\nleft join EIPHRSYS.dbo.[GROUPS] g on it.ResponsibleGROUPID=g.GROUP" +
    "ID";
            this.ItemType.CommandTimeout = 30;
            this.ItemType.CommandType = System.Data.CommandType.Text;
            this.ItemType.DynamicTableName = false;
            this.ItemType.EEPAlias = "JBADMIN";
            this.ItemType.EncodingAfter = null;
            this.ItemType.EncodingBefore = "Windows-1252";
            this.ItemType.EncodingConvert = null;
            this.ItemType.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "ItemTypeID";
            this.ItemType.KeyFields.Add(keyItem5);
            this.ItemType.MultiSetWhere = false;
            this.ItemType.Name = "ItemType";
            this.ItemType.NotificationAutoEnlist = false;
            this.ItemType.SecExcept = null;
            this.ItemType.SecFieldName = null;
            this.ItemType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ItemType.SelectPaging = false;
            this.ItemType.SelectTop = 0;
            this.ItemType.SiteControl = false;
            this.ItemType.SiteFieldName = null;
            this.ItemType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // POType
            // 
            this.POType.CacheConnection = false;
            this.POType.CommandText = "SELECT [POTypeID],[POTypeName]  FROM [POType]";
            this.POType.CommandTimeout = 30;
            this.POType.CommandType = System.Data.CommandType.Text;
            this.POType.DynamicTableName = false;
            this.POType.EEPAlias = "";
            this.POType.EncodingAfter = null;
            this.POType.EncodingBefore = "Windows-1252";
            this.POType.EncodingConvert = null;
            this.POType.InfoConnection = this.InfoConnection1;
            this.POType.MultiSetWhere = false;
            this.POType.Name = "POType";
            this.POType.NotificationAutoEnlist = false;
            this.POType.SecExcept = null;
            this.POType.SecFieldName = null;
            this.POType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.POType.SelectPaging = false;
            this.POType.SelectTop = 0;
            this.POType.SiteControl = false;
            this.POType.SiteFieldName = null;
            this.POType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RequistKind
            // 
            this.RequistKind.CacheConnection = false;
            this.RequistKind.CommandText = "SELECT  [RequisitKindID],[RequistKindName]  FROM [RequistKind]";
            this.RequistKind.CommandTimeout = 30;
            this.RequistKind.CommandType = System.Data.CommandType.Text;
            this.RequistKind.DynamicTableName = false;
            this.RequistKind.EEPAlias = null;
            this.RequistKind.EncodingAfter = null;
            this.RequistKind.EncodingBefore = "Windows-1252";
            this.RequistKind.EncodingConvert = null;
            this.RequistKind.InfoConnection = this.InfoConnection1;
            this.RequistKind.MultiSetWhere = false;
            this.RequistKind.Name = "RequistKind";
            this.RequistKind.NotificationAutoEnlist = false;
            this.RequistKind.SecExcept = null;
            this.RequistKind.SecFieldName = null;
            this.RequistKind.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RequistKind.SelectPaging = false;
            this.RequistKind.SelectTop = 0;
            this.RequistKind.SiteControl = false;
            this.RequistKind.SiteFieldName = null;
            this.RequistKind.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Item
            // 
            this.Item.CacheConnection = false;
            this.Item.CommandText = "SELECT ItemID,ItemName,ItemTypeID,TaxRate,Unit,LeadTime,IsAsset FROM dbo.[Item]";
            this.Item.CommandTimeout = 30;
            this.Item.CommandType = System.Data.CommandType.Text;
            this.Item.DynamicTableName = false;
            this.Item.EEPAlias = "JBADMIN";
            this.Item.EncodingAfter = null;
            this.Item.EncodingBefore = "Windows-1252";
            this.Item.EncodingConvert = null;
            this.Item.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "ItemID";
            this.Item.KeyFields.Add(keyItem6);
            this.Item.MultiSetWhere = false;
            this.Item.Name = "Item";
            this.Item.NotificationAutoEnlist = false;
            this.Item.SecExcept = null;
            this.Item.SecFieldName = null;
            this.Item.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Item.SelectPaging = false;
            this.Item.SelectTop = 0;
            this.Item.SiteControl = false;
            this.Item.SiteFieldName = null;
            this.Item.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Vendors
            // 
            this.Vendors.CacheConnection = false;
            this.Vendors.CommandText = "select View_Vendors_VendorItemType.* from View_Vendors_VendorItemType";
            this.Vendors.CommandTimeout = 30;
            this.Vendors.CommandType = System.Data.CommandType.Text;
            this.Vendors.DynamicTableName = false;
            this.Vendors.EEPAlias = null;
            this.Vendors.EncodingAfter = null;
            this.Vendors.EncodingBefore = "Windows-1252";
            this.Vendors.EncodingConvert = null;
            this.Vendors.InfoConnection = this.InfoConnection1;
            this.Vendors.MultiSetWhere = false;
            this.Vendors.Name = "Vendors";
            this.Vendors.NotificationAutoEnlist = false;
            this.Vendors.SecExcept = null;
            this.Vendors.SecFieldName = null;
            this.Vendors.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Vendors.SelectPaging = false;
            this.Vendors.SelectTop = 0;
            this.Vendors.SiteControl = false;
            this.Vendors.SiteFieldName = null;
            this.Vendors.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Users
            // 
            this.Users.CacheConnection = false;
            this.Users.CommandText = "SELECT USERID,USERNAME FROM  [EIPHRSYS].[dbo].[USERS]\r\nwhere users.[DESCRIPTION]=" +
    "\'JB\'";
            this.Users.CommandTimeout = 30;
            this.Users.CommandType = System.Data.CommandType.Text;
            this.Users.DynamicTableName = false;
            this.Users.EEPAlias = "EIPHRSYS";
            this.Users.EncodingAfter = null;
            this.Users.EncodingBefore = "Windows-1252";
            this.Users.EncodingConvert = null;
            this.Users.InfoConnection = this.infoConnection2;
            keyItem7.KeyName = "USERID";
            this.Users.KeyFields.Add(keyItem7);
            this.Users.MultiSetWhere = false;
            this.Users.Name = "Users";
            this.Users.NotificationAutoEnlist = false;
            this.Users.SecExcept = null;
            this.Users.SecFieldName = null;
            this.Users.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Users.SelectPaging = false;
            this.Users.SelectTop = 0;
            this.Users.SiteControl = false;
            this.Users.SiteFieldName = null;
            this.Users.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoConnection2
            // 
            this.infoConnection2.EEPAlias = "EIPHRSYS";
            // 
            // SYS_ORG
            // 
            this.SYS_ORG.CacheConnection = false;
            this.SYS_ORG.CommandText = "SELECT  [ORG_NO]\r\n      ,[ORG_DESC]\r\n      ,[COSTCENTERID]\r\n  FROM [SYS_ORG]";
            this.SYS_ORG.CommandTimeout = 30;
            this.SYS_ORG.CommandType = System.Data.CommandType.Text;
            this.SYS_ORG.DynamicTableName = false;
            this.SYS_ORG.EEPAlias = "EIPHRSYS";
            this.SYS_ORG.EncodingAfter = null;
            this.SYS_ORG.EncodingBefore = "Windows-1252";
            this.SYS_ORG.EncodingConvert = null;
            this.SYS_ORG.InfoConnection = this.infoConnection2;
            this.SYS_ORG.MultiSetWhere = false;
            this.SYS_ORG.Name = "SYS_ORG";
            this.SYS_ORG.NotificationAutoEnlist = false;
            this.SYS_ORG.SecExcept = null;
            this.SYS_ORG.SecFieldName = null;
            this.SYS_ORG.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SYS_ORG.SelectPaging = false;
            this.SYS_ORG.SelectTop = 0;
            this.SYS_ORG.SiteControl = false;
            this.SYS_ORG.SiteFieldName = null;
            this.SYS_ORG.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // PODelivery
            // 
            this.PODelivery.CacheConnection = false;
            this.PODelivery.CommandText = resources.GetString("PODelivery.CommandText");
            this.PODelivery.CommandTimeout = 30;
            this.PODelivery.CommandType = System.Data.CommandType.Text;
            this.PODelivery.DynamicTableName = false;
            this.PODelivery.EEPAlias = null;
            this.PODelivery.EncodingAfter = null;
            this.PODelivery.EncodingBefore = "Windows-1252";
            this.PODelivery.EncodingConvert = null;
            this.PODelivery.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "PONO";
            keyItem9.KeyName = "ItemNO";
            keyItem10.KeyName = "DeliveryNO";
            this.PODelivery.KeyFields.Add(keyItem8);
            this.PODelivery.KeyFields.Add(keyItem9);
            this.PODelivery.KeyFields.Add(keyItem10);
            this.PODelivery.MultiSetWhere = false;
            this.PODelivery.Name = "PODelivery";
            this.PODelivery.NotificationAutoEnlist = false;
            this.PODelivery.SecExcept = null;
            this.PODelivery.SecFieldName = null;
            this.PODelivery.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PODelivery.SelectPaging = false;
            this.PODelivery.SelectTop = 0;
            this.PODelivery.SiteControl = false;
            this.PODelivery.SiteFieldName = null;
            this.PODelivery.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // idPOMaster_PODelivery
            // 
            this.idPOMaster_PODelivery.Detail = this.PODelivery;
            columnItem3.FieldName = "PONO";
            this.idPOMaster_PODelivery.DetailColumns.Add(columnItem3);
            this.idPOMaster_PODelivery.DynamicTableName = false;
            this.idPOMaster_PODelivery.Master = this.POMaster;
            columnItem4.FieldName = "PONO";
            this.idPOMaster_PODelivery.MasterColumns.Add(columnItem4);
            // 
            // ucPODelivery
            // 
            this.ucPODelivery.AutoTrans = true;
            this.ucPODelivery.ExceptJoin = false;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "PONO";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr67.DefaultValue = null;
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "ItemNO";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr68.DefaultValue = null;
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            fieldAttr69.CheckNull = false;
            fieldAttr69.DataField = "DeliveryNO";
            fieldAttr69.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr69.DefaultValue = null;
            fieldAttr69.TrimLength = 0;
            fieldAttr69.UpdateEnable = true;
            fieldAttr69.WhereMode = true;
            fieldAttr70.CheckNull = false;
            fieldAttr70.DataField = "DeliveryDate";
            fieldAttr70.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr70.DefaultValue = null;
            fieldAttr70.TrimLength = 0;
            fieldAttr70.UpdateEnable = true;
            fieldAttr70.WhereMode = true;
            fieldAttr71.CheckNull = false;
            fieldAttr71.DataField = "DeliveryQty";
            fieldAttr71.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr71.DefaultValue = null;
            fieldAttr71.TrimLength = 0;
            fieldAttr71.UpdateEnable = true;
            fieldAttr71.WhereMode = true;
            fieldAttr72.CheckNull = false;
            fieldAttr72.DataField = "PurPrice";
            fieldAttr72.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr72.DefaultValue = null;
            fieldAttr72.TrimLength = 0;
            fieldAttr72.UpdateEnable = true;
            fieldAttr72.WhereMode = true;
            fieldAttr73.CheckNull = false;
            fieldAttr73.DataField = "OtherFee";
            fieldAttr73.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr73.DefaultValue = null;
            fieldAttr73.TrimLength = 0;
            fieldAttr73.UpdateEnable = true;
            fieldAttr73.WhereMode = true;
            fieldAttr74.CheckNull = false;
            fieldAttr74.DataField = "TotalPrice";
            fieldAttr74.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr74.DefaultValue = null;
            fieldAttr74.TrimLength = 0;
            fieldAttr74.UpdateEnable = true;
            fieldAttr74.WhereMode = true;
            fieldAttr75.CheckNull = false;
            fieldAttr75.DataField = "InvoiceNO";
            fieldAttr75.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr75.DefaultValue = null;
            fieldAttr75.TrimLength = 0;
            fieldAttr75.UpdateEnable = true;
            fieldAttr75.WhereMode = true;
            fieldAttr76.CheckNull = false;
            fieldAttr76.DataField = "PayWayID";
            fieldAttr76.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr76.DefaultValue = null;
            fieldAttr76.TrimLength = 0;
            fieldAttr76.UpdateEnable = true;
            fieldAttr76.WhereMode = true;
            fieldAttr77.CheckNull = false;
            fieldAttr77.DataField = "DebtorDays";
            fieldAttr77.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr77.DefaultValue = null;
            fieldAttr77.TrimLength = 0;
            fieldAttr77.UpdateEnable = true;
            fieldAttr77.WhereMode = true;
            fieldAttr78.CheckNull = false;
            fieldAttr78.DataField = "Surveyors";
            fieldAttr78.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr78.DefaultValue = null;
            fieldAttr78.TrimLength = 0;
            fieldAttr78.UpdateEnable = true;
            fieldAttr78.WhereMode = true;
            fieldAttr79.CheckNull = false;
            fieldAttr79.DataField = "CreateBy";
            fieldAttr79.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr79.DefaultValue = "_username";
            fieldAttr79.TrimLength = 0;
            fieldAttr79.UpdateEnable = true;
            fieldAttr79.WhereMode = true;
            fieldAttr80.CheckNull = false;
            fieldAttr80.DataField = "CreateDate";
            fieldAttr80.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr80.DefaultValue = "_sysdate";
            fieldAttr80.TrimLength = 0;
            fieldAttr80.UpdateEnable = true;
            fieldAttr80.WhereMode = true;
            fieldAttr81.CheckNull = false;
            fieldAttr81.DataField = "LastUpdateBy";
            fieldAttr81.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr81.DefaultValue = "_username";
            fieldAttr81.TrimLength = 0;
            fieldAttr81.UpdateEnable = true;
            fieldAttr81.WhereMode = true;
            fieldAttr82.CheckNull = false;
            fieldAttr82.DataField = "LastUpdateDate";
            fieldAttr82.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr82.DefaultValue = "_sysdate";
            fieldAttr82.TrimLength = 0;
            fieldAttr82.UpdateEnable = true;
            fieldAttr82.WhereMode = true;
            fieldAttr83.CheckNull = false;
            fieldAttr83.DataField = "AcceptanceDate";
            fieldAttr83.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr83.DefaultValue = null;
            fieldAttr83.TrimLength = 0;
            fieldAttr83.UpdateEnable = true;
            fieldAttr83.WhereMode = true;
            fieldAttr84.CheckNull = false;
            fieldAttr84.DataField = "AcceptanceQty";
            fieldAttr84.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr84.DefaultValue = null;
            fieldAttr84.TrimLength = 0;
            fieldAttr84.UpdateEnable = true;
            fieldAttr84.WhereMode = true;
            fieldAttr85.CheckNull = false;
            fieldAttr85.DataField = "AcceptanceTax";
            fieldAttr85.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr85.DefaultValue = null;
            fieldAttr85.TrimLength = 0;
            fieldAttr85.UpdateEnable = true;
            fieldAttr85.WhereMode = true;
            fieldAttr86.CheckNull = false;
            fieldAttr86.DataField = "ReturnQty";
            fieldAttr86.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr86.DefaultValue = null;
            fieldAttr86.TrimLength = 0;
            fieldAttr86.UpdateEnable = true;
            fieldAttr86.WhereMode = true;
            fieldAttr87.CheckNull = false;
            fieldAttr87.DataField = "IsCompleted";
            fieldAttr87.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr87.DefaultValue = null;
            fieldAttr87.TrimLength = 0;
            fieldAttr87.UpdateEnable = true;
            fieldAttr87.WhereMode = true;
            fieldAttr88.CheckNull = false;
            fieldAttr88.DataField = "AccountNO";
            fieldAttr88.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr88.DefaultValue = null;
            fieldAttr88.TrimLength = 0;
            fieldAttr88.UpdateEnable = true;
            fieldAttr88.WhereMode = true;
            fieldAttr89.CheckNull = false;
            fieldAttr89.DataField = "ProofTypeID";
            fieldAttr89.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr89.DefaultValue = null;
            fieldAttr89.TrimLength = 0;
            fieldAttr89.UpdateEnable = true;
            fieldAttr89.WhereMode = true;
            fieldAttr90.CheckNull = false;
            fieldAttr90.DataField = "AssetLocaID";
            fieldAttr90.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr90.DefaultValue = null;
            fieldAttr90.TrimLength = 0;
            fieldAttr90.UpdateEnable = true;
            fieldAttr90.WhereMode = true;
            fieldAttr91.CheckNull = false;
            fieldAttr91.DataField = "PayTo";
            fieldAttr91.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr91.DefaultValue = null;
            fieldAttr91.TrimLength = 0;
            fieldAttr91.UpdateEnable = true;
            fieldAttr91.WhereMode = true;
            fieldAttr92.CheckNull = false;
            fieldAttr92.DataField = "PlanPayDate";
            fieldAttr92.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr92.DefaultValue = null;
            fieldAttr92.TrimLength = 0;
            fieldAttr92.UpdateEnable = true;
            fieldAttr92.WhereMode = true;
            fieldAttr93.CheckNull = false;
            fieldAttr93.DataField = "AcceptancePic";
            fieldAttr93.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr93.DefaultValue = null;
            fieldAttr93.TrimLength = 0;
            fieldAttr93.UpdateEnable = true;
            fieldAttr93.WhereMode = true;
            this.ucPODelivery.FieldAttrs.Add(fieldAttr67);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr68);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr69);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr70);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr71);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr72);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr73);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr74);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr75);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr76);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr77);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr78);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr79);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr80);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr81);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr82);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr83);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr84);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr85);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr86);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr87);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr88);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr89);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr90);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr91);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr92);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr93);
            this.ucPODelivery.LogInfo = null;
            this.ucPODelivery.Name = "ucPODelivery";
            this.ucPODelivery.RowAffectsCheck = true;
            this.ucPODelivery.SelectCmd = this.PODelivery;
            this.ucPODelivery.SelectCmdForUpdate = null;
            this.ucPODelivery.SendSQLCmd = true;
            this.ucPODelivery.ServerModify = true;
            this.ucPODelivery.ServerModifyGetMax = false;
            this.ucPODelivery.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucPODelivery.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucPODelivery.UseTranscationScope = false;
            this.ucPODelivery.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // InsGroup
            // 
            this.InsGroup.CacheConnection = false;
            this.InsGroup.CommandText = "SELECT [InsGroupID] ,[InsGroupShortName],AccountantRoleID\r\n  FROM [JBADMIN].[dbo]" +
    ".[InsGroup] where IsActive=1";
            this.InsGroup.CommandTimeout = 30;
            this.InsGroup.CommandType = System.Data.CommandType.Text;
            this.InsGroup.DynamicTableName = false;
            this.InsGroup.EEPAlias = null;
            this.InsGroup.EncodingAfter = null;
            this.InsGroup.EncodingBefore = "Windows-1252";
            this.InsGroup.EncodingConvert = null;
            this.InsGroup.InfoConnection = this.InfoConnection1;
            this.InsGroup.MultiSetWhere = false;
            this.InsGroup.Name = "InsGroup";
            this.InsGroup.NotificationAutoEnlist = false;
            this.InsGroup.SecExcept = null;
            this.InsGroup.SecFieldName = null;
            this.InsGroup.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.InsGroup.SelectPaging = false;
            this.InsGroup.SelectTop = 0;
            this.InsGroup.SiteControl = false;
            this.InsGroup.SiteFieldName = null;
            this.InsGroup.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoConnection3
            // 
            this.infoConnection3.EEPAlias = "JBERP";
            // 
            // PayWay
            // 
            this.PayWay.CacheConnection = false;
            this.PayWay.CommandText = "SELECT  [PayWayID],[PayWayName]\r\n  FROM [PayWay]";
            this.PayWay.CommandTimeout = 30;
            this.PayWay.CommandType = System.Data.CommandType.Text;
            this.PayWay.DynamicTableName = false;
            this.PayWay.EEPAlias = "JBERP";
            this.PayWay.EncodingAfter = null;
            this.PayWay.EncodingBefore = "Windows-1252";
            this.PayWay.EncodingConvert = null;
            this.PayWay.InfoConnection = this.infoConnection3;
            this.PayWay.MultiSetWhere = false;
            this.PayWay.Name = "PayWay";
            this.PayWay.NotificationAutoEnlist = false;
            this.PayWay.SecExcept = null;
            this.PayWay.SecFieldName = null;
            this.PayWay.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PayWay.SelectPaging = false;
            this.PayWay.SelectTop = 0;
            this.PayWay.SiteControl = false;
            this.PayWay.SiteFieldName = null;
            this.PayWay.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ResponsibleGROUPID
            // 
            this.ResponsibleGROUPID.CacheConnection = false;
            this.ResponsibleGROUPID.CommandText = "SELECT distinct [ResponsibleGROUPID],g.GROUPNAME\r\n  FROM [ItemType] it\r\n  left jo" +
    "in [EIPHRSYS].[dbo].[GROUPS] g on g.[GROUPID]=it.[ResponsibleGROUPID]\r\n";
            this.ResponsibleGROUPID.CommandTimeout = 30;
            this.ResponsibleGROUPID.CommandType = System.Data.CommandType.Text;
            this.ResponsibleGROUPID.DynamicTableName = false;
            this.ResponsibleGROUPID.EEPAlias = "";
            this.ResponsibleGROUPID.EncodingAfter = null;
            this.ResponsibleGROUPID.EncodingBefore = "Windows-1252";
            this.ResponsibleGROUPID.EncodingConvert = null;
            this.ResponsibleGROUPID.InfoConnection = this.InfoConnection1;
            this.ResponsibleGROUPID.MultiSetWhere = false;
            this.ResponsibleGROUPID.Name = "ResponsibleGROUPID";
            this.ResponsibleGROUPID.NotificationAutoEnlist = false;
            this.ResponsibleGROUPID.SecExcept = null;
            this.ResponsibleGROUPID.SecFieldName = null;
            this.ResponsibleGROUPID.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ResponsibleGROUPID.SelectPaging = false;
            this.ResponsibleGROUPID.SelectTop = 0;
            this.ResponsibleGROUPID.SiteControl = false;
            this.ResponsibleGROUPID.SiteFieldName = null;
            this.ResponsibleGROUPID.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // GROUPS
            // 
            this.GROUPS.CacheConnection = false;
            this.GROUPS.CommandText = "SELECT [GROUPID]\r\n      ,[GROUPNAME]\r\n  FROM [EIPHRSYS].[dbo].[GROUPS]\r\n where IS" +
    "ROLE=\'Y\'";
            this.GROUPS.CommandTimeout = 30;
            this.GROUPS.CommandType = System.Data.CommandType.Text;
            this.GROUPS.DynamicTableName = false;
            this.GROUPS.EEPAlias = "EIPHRSYS";
            this.GROUPS.EncodingAfter = null;
            this.GROUPS.EncodingBefore = "Windows-1252";
            this.GROUPS.EncodingConvert = null;
            this.GROUPS.InfoConnection = this.InfoConnection1;
            keyItem11.KeyName = "GROUPID";
            this.GROUPS.KeyFields.Add(keyItem11);
            this.GROUPS.MultiSetWhere = false;
            this.GROUPS.Name = "GROUPS";
            this.GROUPS.NotificationAutoEnlist = false;
            this.GROUPS.SecExcept = null;
            this.GROUPS.SecFieldName = null;
            this.GROUPS.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.GROUPS.SelectPaging = false;
            this.GROUPS.SelectTop = 0;
            this.GROUPS.SiteControl = false;
            this.GROUPS.SiteFieldName = null;
            this.GROUPS.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // PODetailsHistory
            // 
            this.PODetailsHistory.CacheConnection = false;
            this.PODetailsHistory.CommandText = resources.GetString("PODetailsHistory.CommandText");
            this.PODetailsHistory.CommandTimeout = 30;
            this.PODetailsHistory.CommandType = System.Data.CommandType.Text;
            this.PODetailsHistory.DynamicTableName = false;
            this.PODetailsHistory.EEPAlias = "";
            this.PODetailsHistory.EncodingAfter = null;
            this.PODetailsHistory.EncodingBefore = "Windows-1252";
            this.PODetailsHistory.EncodingConvert = null;
            this.PODetailsHistory.InfoConnection = this.InfoConnection1;
            this.PODetailsHistory.MultiSetWhere = true;
            this.PODetailsHistory.Name = "PODetailsHistory";
            this.PODetailsHistory.NotificationAutoEnlist = false;
            this.PODetailsHistory.SecExcept = null;
            this.PODetailsHistory.SecFieldName = null;
            this.PODetailsHistory.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PODetailsHistory.SelectPaging = false;
            this.PODetailsHistory.SelectTop = 0;
            this.PODetailsHistory.SiteControl = false;
            this.PODetailsHistory.SiteFieldName = null;
            this.PODetailsHistory.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ItemTypeAcno
            // 
            this.ItemTypeAcno.CacheConnection = false;
            this.ItemTypeAcno.CommandText = resources.GetString("ItemTypeAcno.CommandText");
            this.ItemTypeAcno.CommandTimeout = 30;
            this.ItemTypeAcno.CommandType = System.Data.CommandType.Text;
            this.ItemTypeAcno.DynamicTableName = false;
            this.ItemTypeAcno.EEPAlias = null;
            this.ItemTypeAcno.EncodingAfter = null;
            this.ItemTypeAcno.EncodingBefore = "Windows-1252";
            this.ItemTypeAcno.EncodingConvert = null;
            this.ItemTypeAcno.InfoConnection = this.InfoConnection1;
            this.ItemTypeAcno.MultiSetWhere = false;
            this.ItemTypeAcno.Name = "ItemTypeAcno";
            this.ItemTypeAcno.NotificationAutoEnlist = false;
            this.ItemTypeAcno.SecExcept = null;
            this.ItemTypeAcno.SecFieldName = null;
            this.ItemTypeAcno.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ItemTypeAcno.SelectPaging = false;
            this.ItemTypeAcno.SelectTop = 0;
            this.ItemTypeAcno.SiteControl = false;
            this.ItemTypeAcno.SiteFieldName = null;
            this.ItemTypeAcno.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ProofType
            // 
            this.ProofType.CacheConnection = false;
            this.ProofType.CommandText = "SELECT  [ProofTypeID],[ProofTypeName] FROM [ProofType]";
            this.ProofType.CommandTimeout = 30;
            this.ProofType.CommandType = System.Data.CommandType.Text;
            this.ProofType.DynamicTableName = false;
            this.ProofType.EEPAlias = null;
            this.ProofType.EncodingAfter = null;
            this.ProofType.EncodingBefore = "Windows-1252";
            this.ProofType.EncodingConvert = null;
            this.ProofType.InfoConnection = this.InfoConnection1;
            this.ProofType.MultiSetWhere = false;
            this.ProofType.Name = "ProofType";
            this.ProofType.NotificationAutoEnlist = false;
            this.ProofType.SecExcept = null;
            this.ProofType.SecFieldName = null;
            this.ProofType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ProofType.SelectPaging = false;
            this.ProofType.SelectTop = 0;
            this.ProofType.SiteControl = false;
            this.ProofType.SiteFieldName = null;
            this.ProofType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // POPayType
            // 
            this.POPayType.CacheConnection = false;
            this.POPayType.CommandText = "select POPayTypeID,POPayTypeName  from POPayType";
            this.POPayType.CommandTimeout = 30;
            this.POPayType.CommandType = System.Data.CommandType.Text;
            this.POPayType.DynamicTableName = false;
            this.POPayType.EEPAlias = null;
            this.POPayType.EncodingAfter = null;
            this.POPayType.EncodingBefore = "Windows-1252";
            this.POPayType.EncodingConvert = null;
            this.POPayType.InfoConnection = this.InfoConnection1;
            this.POPayType.MultiSetWhere = false;
            this.POPayType.Name = "POPayType";
            this.POPayType.NotificationAutoEnlist = false;
            this.POPayType.SecExcept = null;
            this.POPayType.SecFieldName = null;
            this.POPayType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.POPayType.SelectPaging = false;
            this.POPayType.SelectTop = 0;
            this.POPayType.SiteControl = false;
            this.POPayType.SiteFieldName = null;
            this.POPayType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // AssetLocation
            // 
            this.AssetLocation.CacheConnection = false;
            this.AssetLocation.CommandText = "select AssetLocation.AssetLocaID,\r\n            AssetLocation.AssetLocaName\r\nfrom " +
    "AssetLocation where IsActive =1\r\norder by  AssetLocation.AssetLocaID";
            this.AssetLocation.CommandTimeout = 30;
            this.AssetLocation.CommandType = System.Data.CommandType.Text;
            this.AssetLocation.DynamicTableName = false;
            this.AssetLocation.EEPAlias = null;
            this.AssetLocation.EncodingAfter = null;
            this.AssetLocation.EncodingBefore = "Windows-1252";
            this.AssetLocation.EncodingConvert = null;
            this.AssetLocation.InfoConnection = this.InfoConnection1;
            keyItem12.KeyName = "AssetLocaID";
            this.AssetLocation.KeyFields.Add(keyItem12);
            this.AssetLocation.MultiSetWhere = false;
            this.AssetLocation.Name = "AssetLocation";
            this.AssetLocation.NotificationAutoEnlist = false;
            this.AssetLocation.SecExcept = null;
            this.AssetLocation.SecFieldName = null;
            this.AssetLocation.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.AssetLocation.SelectPaging = false;
            this.AssetLocation.SelectTop = 0;
            this.AssetLocation.SiteControl = false;
            this.AssetLocation.SiteFieldName = null;
            this.AssetLocation.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // VoucherYear
            // 
            this.VoucherYear.CacheConnection = false;
            this.VoucherYear.CommandText = "select distinct VoucherYear from glYearBudget\r\n";
            this.VoucherYear.CommandTimeout = 30;
            this.VoucherYear.CommandType = System.Data.CommandType.Text;
            this.VoucherYear.DynamicTableName = false;
            this.VoucherYear.EEPAlias = "";
            this.VoucherYear.EncodingAfter = null;
            this.VoucherYear.EncodingBefore = "Windows-1252";
            this.VoucherYear.EncodingConvert = null;
            this.VoucherYear.InfoConnection = this.InfoConnection1;
            this.VoucherYear.MultiSetWhere = false;
            this.VoucherYear.Name = "VoucherYear";
            this.VoucherYear.NotificationAutoEnlist = false;
            this.VoucherYear.SecExcept = null;
            this.VoucherYear.SecFieldName = null;
            this.VoucherYear.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.VoucherYear.SelectPaging = false;
            this.VoucherYear.SelectTop = 0;
            this.VoucherYear.SiteControl = false;
            this.VoucherYear.SiteFieldName = null;
            this.VoucherYear.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Vendors1
            // 
            this.Vendors1.CacheConnection = false;
            this.Vendors1.CommandText = "select v.*,p.PayTermName from Vendors v\r\nleft join dbo.PayTerm p on p.PayTermID=v" +
    ".PayTermID";
            this.Vendors1.CommandTimeout = 30;
            this.Vendors1.CommandType = System.Data.CommandType.Text;
            this.Vendors1.DynamicTableName = false;
            this.Vendors1.EEPAlias = null;
            this.Vendors1.EncodingAfter = null;
            this.Vendors1.EncodingBefore = "Windows-1252";
            this.Vendors1.EncodingConvert = null;
            this.Vendors1.InfoConnection = this.InfoConnection1;
            this.Vendors1.MultiSetWhere = false;
            this.Vendors1.Name = "Vendors1";
            this.Vendors1.NotificationAutoEnlist = false;
            this.Vendors1.SecExcept = null;
            this.Vendors1.SecFieldName = null;
            this.Vendors1.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Vendors1.SelectPaging = false;
            this.Vendors1.SelectTop = 0;
            this.Vendors1.SiteControl = false;
            this.Vendors1.SiteFieldName = null;
            this.Vendors1.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ShortTerm
            // 
            this.ShortTerm.CacheConnection = false;
            this.ShortTerm.CommandText = resources.GetString("ShortTerm.CommandText");
            this.ShortTerm.CommandTimeout = 30;
            this.ShortTerm.CommandType = System.Data.CommandType.Text;
            this.ShortTerm.DynamicTableName = false;
            this.ShortTerm.EEPAlias = null;
            this.ShortTerm.EncodingAfter = null;
            this.ShortTerm.EncodingBefore = "Windows-1252";
            this.ShortTerm.EncodingConvert = null;
            this.ShortTerm.InfoConnection = this.InfoConnection1;
            this.ShortTerm.MultiSetWhere = false;
            this.ShortTerm.Name = "ShortTerm";
            this.ShortTerm.NotificationAutoEnlist = false;
            this.ShortTerm.SecExcept = null;
            this.ShortTerm.SecFieldName = "";
            this.ShortTerm.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ShortTerm.SelectPaging = false;
            this.ShortTerm.SelectTop = 0;
            this.ShortTerm.SiteControl = false;
            this.ShortTerm.SiteFieldName = null;
            this.ShortTerm.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // UsersAll
            // 
            this.UsersAll.CacheConnection = false;
            this.UsersAll.CommandText = "SELECT USERID,USERNAME FROM  [EIPHRSYS].[dbo].[USERS]";
            this.UsersAll.CommandTimeout = 30;
            this.UsersAll.CommandType = System.Data.CommandType.Text;
            this.UsersAll.DynamicTableName = false;
            this.UsersAll.EEPAlias = "EIPHRSYS";
            this.UsersAll.EncodingAfter = null;
            this.UsersAll.EncodingBefore = "Windows-1252";
            this.UsersAll.EncodingConvert = null;
            this.UsersAll.InfoConnection = this.infoConnection2;
            keyItem13.KeyName = "USERID";
            this.UsersAll.KeyFields.Add(keyItem13);
            this.UsersAll.MultiSetWhere = false;
            this.UsersAll.Name = "UsersAll";
            this.UsersAll.NotificationAutoEnlist = false;
            this.UsersAll.SecExcept = null;
            this.UsersAll.SecFieldName = null;
            this.UsersAll.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.UsersAll.SelectPaging = false;
            this.UsersAll.SelectTop = 0;
            this.UsersAll.SiteControl = false;
            this.UsersAll.SiteFieldName = null;
            this.UsersAll.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ItemTypeItems
            // 
            this.ItemTypeItems.CacheConnection = false;
            this.ItemTypeItems.CommandText = "SELECT * FROM View_ItemTypeItems ORDER BY ITEMTYPEID";
            this.ItemTypeItems.CommandTimeout = 30;
            this.ItemTypeItems.CommandType = System.Data.CommandType.Text;
            this.ItemTypeItems.DynamicTableName = false;
            this.ItemTypeItems.EEPAlias = "JBADMIN";
            this.ItemTypeItems.EncodingAfter = null;
            this.ItemTypeItems.EncodingBefore = "Windows-1252";
            this.ItemTypeItems.EncodingConvert = null;
            this.ItemTypeItems.InfoConnection = this.InfoConnection1;
            this.ItemTypeItems.MultiSetWhere = false;
            this.ItemTypeItems.Name = "ItemTypeItems";
            this.ItemTypeItems.NotificationAutoEnlist = false;
            this.ItemTypeItems.SecExcept = null;
            this.ItemTypeItems.SecFieldName = null;
            this.ItemTypeItems.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ItemTypeItems.SelectPaging = false;
            this.ItemTypeItems.SelectTop = 0;
            this.ItemTypeItems.SiteControl = false;
            this.ItemTypeItems.SiteFieldName = null;
            this.ItemTypeItems.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.POMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_POMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.glCostCenter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.POType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RequistKind)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Item)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Vendors)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Users)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYS_ORG)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODelivery)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsGroup)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayWay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ResponsibleGROUPID)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.GROUPS)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODetailsHistory)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemTypeAcno)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ProofType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.POPayType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.AssetLocation)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.VoucherYear)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Vendors1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ShortTerm)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UsersAll)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemTypeItems)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand POMaster;
        private Srvtools.UpdateComponent ucPOMaster;
        private Srvtools.InfoCommand PODetails;
        private Srvtools.UpdateComponent ucPODetails;
        private Srvtools.InfoDataSource idPOMaster_PODetails;
        private Srvtools.InfoCommand View_POMaster;
        private Srvtools.AutoNumber autoNumber1;
        private Srvtools.InfoCommand glCostCenter;
        private Srvtools.InfoCommand ItemType;
        private Srvtools.InfoCommand POType;
        private Srvtools.InfoCommand RequistKind;
        private Srvtools.InfoCommand Item;
        private Srvtools.InfoCommand Vendors;
        private Srvtools.InfoCommand Users;
        private Srvtools.InfoConnection infoConnection2;
        private Srvtools.InfoCommand SYS_ORG;
        private Srvtools.InfoCommand PODelivery;
        private Srvtools.InfoDataSource idPOMaster_PODelivery;
        private Srvtools.UpdateComponent ucPODelivery;
        private Srvtools.InfoCommand InsGroup;
        private Srvtools.InfoConnection infoConnection3;
        private Srvtools.InfoCommand PayWay;
        private Srvtools.InfoCommand ResponsibleGROUPID;
        private Srvtools.InfoCommand GROUPS;
        private Srvtools.InfoCommand PODetailsHistory;
        private Srvtools.InfoCommand ItemTypeAcno;
        private Srvtools.InfoCommand ProofType;
        private Srvtools.InfoCommand POPayType;
        private Srvtools.InfoCommand AssetLocation;
        private Srvtools.InfoCommand VoucherYear;
        private Srvtools.InfoCommand Vendors1;
        private Srvtools.InfoCommand ShortTerm;
        private Srvtools.InfoCommand UsersAll;
        private Srvtools.InfoCommand ItemTypeItems;

    }
}
