namespace sPO_Normal_Requisition
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.ColumnItem columnItem1 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem2 = new Srvtools.ColumnItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.ColumnItem columnItem3 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem4 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem5 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem6 = new Srvtools.ColumnItem();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.POMaster = new Srvtools.InfoCommand(this.components);
            this.ucPOMaster = new Srvtools.UpdateComponent(this.components);
            this.PODetails = new Srvtools.InfoCommand(this.components);
            this.ucPODetails = new Srvtools.UpdateComponent(this.components);
            this.idPOMaster_PODetails = new Srvtools.InfoDataSource(this.components);
            this.View_POMaster = new Srvtools.InfoCommand(this.components);
            this.autoNumber1 = new Srvtools.AutoNumber(this.components);
            this.glCostCenter = new Srvtools.InfoCommand(this.components);
            this.ItemType = new Srvtools.InfoCommand(this.components);
            this.POType = new Srvtools.InfoCommand(this.components);
            this.RequistKind = new Srvtools.InfoCommand(this.components);
            this.Item = new Srvtools.InfoCommand(this.components);
            this.Vendors = new Srvtools.InfoCommand(this.components);
            this.Users = new Srvtools.InfoCommand(this.components);
            this.infoConnection2 = new Srvtools.InfoConnection(this.components);
            this.SYS_ORG = new Srvtools.InfoCommand(this.components);
            this.PODelivery = new Srvtools.InfoCommand(this.components);
            this.idPODetails_PODelivery = new Srvtools.InfoDataSource(this.components);
            this.ucPODelivery = new Srvtools.UpdateComponent(this.components);
            this.InsGroup = new Srvtools.InfoCommand(this.components);
            this.infoConnection3 = new Srvtools.InfoConnection(this.components);
            this.PayWay = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.POMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_POMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.glCostCenter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.POType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RequistKind)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Item)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Vendors)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Users)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYS_ORG)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODelivery)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsGroup)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayWay)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "FlowStartUp";
            service1.NonLogin = false;
            service1.ServiceName = "FlowStartUp";
            service2.DelegateName = "GetUserOrgNOs";
            service2.NonLogin = false;
            service2.ServiceName = "GetUserOrgNOs";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // POMaster
            // 
            this.POMaster.CacheConnection = false;
            this.POMaster.CommandText = "SELECT dbo.[POMaster].* FROM dbo.[POMaster] order by PONO desc";
            this.POMaster.CommandTimeout = 30;
            this.POMaster.CommandType = System.Data.CommandType.Text;
            this.POMaster.DynamicTableName = false;
            this.POMaster.EEPAlias = null;
            this.POMaster.EncodingAfter = null;
            this.POMaster.EncodingBefore = "Windows-1252";
            this.POMaster.EncodingConvert = null;
            this.POMaster.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "PONO";
            this.POMaster.KeyFields.Add(keyItem1);
            this.POMaster.MultiSetWhere = false;
            this.POMaster.Name = "POMaster";
            this.POMaster.NotificationAutoEnlist = false;
            this.POMaster.SecExcept = null;
            this.POMaster.SecFieldName = null;
            this.POMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.POMaster.SelectPaging = false;
            this.POMaster.SelectTop = 0;
            this.POMaster.SiteControl = false;
            this.POMaster.SiteFieldName = null;
            this.POMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucPOMaster
            // 
            this.ucPOMaster.AutoTrans = true;
            this.ucPOMaster.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "PONO";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "ApplyDate";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "ApplyUserID";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "Description";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "CostCenterID";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ApplyOrg_NO";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "Org_NOParent";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "ItemTypeID";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "POTypeID";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "RequisitKindID";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "Flowflag";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CreateBy";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = "_username";
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "CreateDate";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = "_sysdate";
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "LastUpdateBy";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = "_username";
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "LastUpdateDate";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = "_sysdate";
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "ResponsibleGROUPID";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            this.ucPOMaster.FieldAttrs.Add(fieldAttr1);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr2);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr3);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr4);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr5);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr6);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr7);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr8);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr9);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr10);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr11);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr12);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr13);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr14);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr15);
            this.ucPOMaster.FieldAttrs.Add(fieldAttr16);
            this.ucPOMaster.LogInfo = null;
            this.ucPOMaster.Name = "ucPOMaster";
            this.ucPOMaster.RowAffectsCheck = true;
            this.ucPOMaster.SelectCmd = this.POMaster;
            this.ucPOMaster.SelectCmdForUpdate = null;
            this.ucPOMaster.SendSQLCmd = true;
            this.ucPOMaster.ServerModify = true;
            this.ucPOMaster.ServerModifyGetMax = false;
            this.ucPOMaster.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucPOMaster.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucPOMaster.UseTranscationScope = false;
            this.ucPOMaster.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // PODetails
            // 
            this.PODetails.CacheConnection = false;
            this.PODetails.CommandText = "SELECT dbo.[PODetails].*,\'\' as ItemTypeIDTemp FROM dbo.[PODetails]";
            this.PODetails.CommandTimeout = 30;
            this.PODetails.CommandType = System.Data.CommandType.Text;
            this.PODetails.DynamicTableName = false;
            this.PODetails.EEPAlias = null;
            this.PODetails.EncodingAfter = null;
            this.PODetails.EncodingBefore = "Windows-1252";
            this.PODetails.EncodingConvert = null;
            this.PODetails.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "PONO";
            keyItem3.KeyName = "ItemNO";
            this.PODetails.KeyFields.Add(keyItem2);
            this.PODetails.KeyFields.Add(keyItem3);
            this.PODetails.MultiSetWhere = false;
            this.PODetails.Name = "PODetails";
            this.PODetails.NotificationAutoEnlist = false;
            this.PODetails.SecExcept = null;
            this.PODetails.SecFieldName = null;
            this.PODetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PODetails.SelectPaging = false;
            this.PODetails.SelectTop = 0;
            this.PODetails.SiteControl = false;
            this.PODetails.SiteFieldName = null;
            this.PODetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucPODetails
            // 
            this.ucPODetails.AutoTrans = true;
            this.ucPODetails.ExceptJoin = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "PONO";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "ItemNO";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "ItemID";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "ItemSpec";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "RegQty";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "RegPrice";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "Unit";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "RegDate";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "RecVendor";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "PurQty";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "PurPrice";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "OtherFee";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "DeliveryTimes";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "PurVendor";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "PurComment";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "PurPriceVen1";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "PurVendor1";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "PurPriceVen2";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "PurVendor2";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "PurPriceVen3";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "PurVendor3";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "PurDocVen1";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "PurDocVen2";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "PurDocVen3";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "CreateBy";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = "_username";
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "CreateDate";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = "_sysdate";
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "LastUpdateBy";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = "_username";
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "LastUpdateDate";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = "_sysdate";
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            this.ucPODetails.FieldAttrs.Add(fieldAttr17);
            this.ucPODetails.FieldAttrs.Add(fieldAttr18);
            this.ucPODetails.FieldAttrs.Add(fieldAttr19);
            this.ucPODetails.FieldAttrs.Add(fieldAttr20);
            this.ucPODetails.FieldAttrs.Add(fieldAttr21);
            this.ucPODetails.FieldAttrs.Add(fieldAttr22);
            this.ucPODetails.FieldAttrs.Add(fieldAttr23);
            this.ucPODetails.FieldAttrs.Add(fieldAttr24);
            this.ucPODetails.FieldAttrs.Add(fieldAttr25);
            this.ucPODetails.FieldAttrs.Add(fieldAttr26);
            this.ucPODetails.FieldAttrs.Add(fieldAttr27);
            this.ucPODetails.FieldAttrs.Add(fieldAttr28);
            this.ucPODetails.FieldAttrs.Add(fieldAttr29);
            this.ucPODetails.FieldAttrs.Add(fieldAttr30);
            this.ucPODetails.FieldAttrs.Add(fieldAttr31);
            this.ucPODetails.FieldAttrs.Add(fieldAttr32);
            this.ucPODetails.FieldAttrs.Add(fieldAttr33);
            this.ucPODetails.FieldAttrs.Add(fieldAttr34);
            this.ucPODetails.FieldAttrs.Add(fieldAttr35);
            this.ucPODetails.FieldAttrs.Add(fieldAttr36);
            this.ucPODetails.FieldAttrs.Add(fieldAttr37);
            this.ucPODetails.FieldAttrs.Add(fieldAttr38);
            this.ucPODetails.FieldAttrs.Add(fieldAttr39);
            this.ucPODetails.FieldAttrs.Add(fieldAttr40);
            this.ucPODetails.FieldAttrs.Add(fieldAttr41);
            this.ucPODetails.FieldAttrs.Add(fieldAttr42);
            this.ucPODetails.FieldAttrs.Add(fieldAttr43);
            this.ucPODetails.FieldAttrs.Add(fieldAttr44);
            this.ucPODetails.LogInfo = null;
            this.ucPODetails.Name = "ucPODetails";
            this.ucPODetails.RowAffectsCheck = true;
            this.ucPODetails.SelectCmd = this.PODetails;
            this.ucPODetails.SelectCmdForUpdate = null;
            this.ucPODetails.SendSQLCmd = true;
            this.ucPODetails.ServerModify = true;
            this.ucPODetails.ServerModifyGetMax = false;
            this.ucPODetails.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucPODetails.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucPODetails.UseTranscationScope = false;
            this.ucPODetails.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // idPOMaster_PODetails
            // 
            this.idPOMaster_PODetails.Detail = this.PODetails;
            columnItem1.FieldName = "PONO";
            this.idPOMaster_PODetails.DetailColumns.Add(columnItem1);
            this.idPOMaster_PODetails.DynamicTableName = false;
            this.idPOMaster_PODetails.Master = this.POMaster;
            columnItem2.FieldName = "PONO";
            this.idPOMaster_PODetails.MasterColumns.Add(columnItem2);
            // 
            // View_POMaster
            // 
            this.View_POMaster.CacheConnection = false;
            this.View_POMaster.CommandText = "SELECT * FROM dbo.[POMaster]";
            this.View_POMaster.CommandTimeout = 30;
            this.View_POMaster.CommandType = System.Data.CommandType.Text;
            this.View_POMaster.DynamicTableName = false;
            this.View_POMaster.EEPAlias = null;
            this.View_POMaster.EncodingAfter = null;
            this.View_POMaster.EncodingBefore = "Windows-1252";
            this.View_POMaster.EncodingConvert = null;
            this.View_POMaster.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "PONO";
            this.View_POMaster.KeyFields.Add(keyItem4);
            this.View_POMaster.MultiSetWhere = false;
            this.View_POMaster.Name = "View_POMaster";
            this.View_POMaster.NotificationAutoEnlist = false;
            this.View_POMaster.SecExcept = null;
            this.View_POMaster.SecFieldName = null;
            this.View_POMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_POMaster.SelectPaging = false;
            this.View_POMaster.SelectTop = 0;
            this.View_POMaster.SiteControl = false;
            this.View_POMaster.SiteFieldName = null;
            this.View_POMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // autoNumber1
            // 
            this.autoNumber1.Active = true;
            this.autoNumber1.AutoNoID = "PONO";
            this.autoNumber1.Description = null;
            this.autoNumber1.GetFixed = "ReturnGetFixed()";
            this.autoNumber1.isNumFill = false;
            this.autoNumber1.Name = "autoNumber1";
            this.autoNumber1.Number = null;
            this.autoNumber1.NumDig = 5;
            this.autoNumber1.OldVersion = false;
            this.autoNumber1.OverFlow = true;
            this.autoNumber1.StartValue = 1;
            this.autoNumber1.Step = 1;
            this.autoNumber1.TargetColumn = "PONO";
            this.autoNumber1.UpdateComp = this.ucPOMaster;
            // 
            // glCostCenter
            // 
            this.glCostCenter.CacheConnection = false;
            this.glCostCenter.CommandText = "select CostCenterID,CostCenterName  from glCostCenter";
            this.glCostCenter.CommandTimeout = 30;
            this.glCostCenter.CommandType = System.Data.CommandType.Text;
            this.glCostCenter.DynamicTableName = false;
            this.glCostCenter.EEPAlias = null;
            this.glCostCenter.EncodingAfter = null;
            this.glCostCenter.EncodingBefore = "Windows-1252";
            this.glCostCenter.EncodingConvert = null;
            this.glCostCenter.InfoConnection = this.InfoConnection1;
            this.glCostCenter.MultiSetWhere = false;
            this.glCostCenter.Name = "glCostCenter";
            this.glCostCenter.NotificationAutoEnlist = false;
            this.glCostCenter.SecExcept = null;
            this.glCostCenter.SecFieldName = null;
            this.glCostCenter.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.glCostCenter.SelectPaging = false;
            this.glCostCenter.SelectTop = 0;
            this.glCostCenter.SiteControl = false;
            this.glCostCenter.SiteFieldName = null;
            this.glCostCenter.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ItemType
            // 
            this.ItemType.CacheConnection = false;
            this.ItemType.CommandText = "SELECT it.ItemTypeID,it.ItemTypeName,it.ResponsibleGROUPID,g.GROUPNAME FROM dbo.[" +
    "ItemType] it\r\nleft join EIPHRSYS.dbo.[GROUPS] g on it.ResponsibleGROUPID=g.GROUP" +
    "ID";
            this.ItemType.CommandTimeout = 30;
            this.ItemType.CommandType = System.Data.CommandType.Text;
            this.ItemType.DynamicTableName = false;
            this.ItemType.EEPAlias = "JBADMIN";
            this.ItemType.EncodingAfter = null;
            this.ItemType.EncodingBefore = "Windows-1252";
            this.ItemType.EncodingConvert = null;
            this.ItemType.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "ItemTypeID";
            this.ItemType.KeyFields.Add(keyItem5);
            this.ItemType.MultiSetWhere = false;
            this.ItemType.Name = "ItemType";
            this.ItemType.NotificationAutoEnlist = false;
            this.ItemType.SecExcept = null;
            this.ItemType.SecFieldName = null;
            this.ItemType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ItemType.SelectPaging = false;
            this.ItemType.SelectTop = 0;
            this.ItemType.SiteControl = false;
            this.ItemType.SiteFieldName = null;
            this.ItemType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // POType
            // 
            this.POType.CacheConnection = false;
            this.POType.CommandText = "SELECT [POTypeID],[POTypeName]  FROM [POType]";
            this.POType.CommandTimeout = 30;
            this.POType.CommandType = System.Data.CommandType.Text;
            this.POType.DynamicTableName = false;
            this.POType.EEPAlias = null;
            this.POType.EncodingAfter = null;
            this.POType.EncodingBefore = "Windows-1252";
            this.POType.EncodingConvert = null;
            this.POType.InfoConnection = this.InfoConnection1;
            this.POType.MultiSetWhere = false;
            this.POType.Name = "POType";
            this.POType.NotificationAutoEnlist = false;
            this.POType.SecExcept = null;
            this.POType.SecFieldName = null;
            this.POType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.POType.SelectPaging = false;
            this.POType.SelectTop = 0;
            this.POType.SiteControl = false;
            this.POType.SiteFieldName = null;
            this.POType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RequistKind
            // 
            this.RequistKind.CacheConnection = false;
            this.RequistKind.CommandText = "SELECT  [RequisitKindID],[RequistKindName]  FROM [RequistKind]";
            this.RequistKind.CommandTimeout = 30;
            this.RequistKind.CommandType = System.Data.CommandType.Text;
            this.RequistKind.DynamicTableName = false;
            this.RequistKind.EEPAlias = null;
            this.RequistKind.EncodingAfter = null;
            this.RequistKind.EncodingBefore = "Windows-1252";
            this.RequistKind.EncodingConvert = null;
            this.RequistKind.InfoConnection = this.InfoConnection1;
            this.RequistKind.MultiSetWhere = false;
            this.RequistKind.Name = "RequistKind";
            this.RequistKind.NotificationAutoEnlist = false;
            this.RequistKind.SecExcept = null;
            this.RequistKind.SecFieldName = null;
            this.RequistKind.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RequistKind.SelectPaging = false;
            this.RequistKind.SelectTop = 0;
            this.RequistKind.SiteControl = false;
            this.RequistKind.SiteFieldName = null;
            this.RequistKind.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Item
            // 
            this.Item.CacheConnection = false;
            this.Item.CommandText = "SELECT ItemID,ItemName,ItemTypeID,IsTax FROM dbo.[Item]";
            this.Item.CommandTimeout = 30;
            this.Item.CommandType = System.Data.CommandType.Text;
            this.Item.DynamicTableName = false;
            this.Item.EEPAlias = "JBADMIN";
            this.Item.EncodingAfter = null;
            this.Item.EncodingBefore = "Windows-1252";
            this.Item.EncodingConvert = null;
            this.Item.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "ItemID";
            this.Item.KeyFields.Add(keyItem6);
            this.Item.MultiSetWhere = false;
            this.Item.Name = "Item";
            this.Item.NotificationAutoEnlist = false;
            this.Item.SecExcept = null;
            this.Item.SecFieldName = null;
            this.Item.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Item.SelectPaging = false;
            this.Item.SelectTop = 0;
            this.Item.SiteControl = false;
            this.Item.SiteFieldName = null;
            this.Item.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Vendors
            // 
            this.Vendors.CacheConnection = false;
            this.Vendors.CommandText = resources.GetString("Vendors.CommandText");
            this.Vendors.CommandTimeout = 30;
            this.Vendors.CommandType = System.Data.CommandType.Text;
            this.Vendors.DynamicTableName = false;
            this.Vendors.EEPAlias = null;
            this.Vendors.EncodingAfter = null;
            this.Vendors.EncodingBefore = "Windows-1252";
            this.Vendors.EncodingConvert = null;
            this.Vendors.InfoConnection = this.InfoConnection1;
            this.Vendors.MultiSetWhere = false;
            this.Vendors.Name = "Vendors";
            this.Vendors.NotificationAutoEnlist = false;
            this.Vendors.SecExcept = null;
            this.Vendors.SecFieldName = null;
            this.Vendors.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Vendors.SelectPaging = false;
            this.Vendors.SelectTop = 0;
            this.Vendors.SiteControl = false;
            this.Vendors.SiteFieldName = null;
            this.Vendors.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Users
            // 
            this.Users.CacheConnection = false;
            this.Users.CommandText = "SELECT  [USERID]\r\n      ,[USERNAME]\r\n  FROM [USERS]";
            this.Users.CommandTimeout = 30;
            this.Users.CommandType = System.Data.CommandType.Text;
            this.Users.DynamicTableName = false;
            this.Users.EEPAlias = "EIPHRSYS";
            this.Users.EncodingAfter = null;
            this.Users.EncodingBefore = "Windows-1252";
            this.Users.EncodingConvert = null;
            this.Users.InfoConnection = this.infoConnection2;
            keyItem7.KeyName = "USERID";
            this.Users.KeyFields.Add(keyItem7);
            this.Users.MultiSetWhere = false;
            this.Users.Name = "Users";
            this.Users.NotificationAutoEnlist = false;
            this.Users.SecExcept = null;
            this.Users.SecFieldName = null;
            this.Users.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Users.SelectPaging = false;
            this.Users.SelectTop = 0;
            this.Users.SiteControl = false;
            this.Users.SiteFieldName = null;
            this.Users.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoConnection2
            // 
            this.infoConnection2.EEPAlias = "EIPHRSYS";
            // 
            // SYS_ORG
            // 
            this.SYS_ORG.CacheConnection = false;
            this.SYS_ORG.CommandText = "SELECT  [ORG_NO]\r\n      ,[ORG_DESC]\r\n      ,[COSTCENTERID]\r\n  FROM [SYS_ORG]";
            this.SYS_ORG.CommandTimeout = 30;
            this.SYS_ORG.CommandType = System.Data.CommandType.Text;
            this.SYS_ORG.DynamicTableName = false;
            this.SYS_ORG.EEPAlias = "EIPHRSYS";
            this.SYS_ORG.EncodingAfter = null;
            this.SYS_ORG.EncodingBefore = "Windows-1252";
            this.SYS_ORG.EncodingConvert = null;
            this.SYS_ORG.InfoConnection = this.infoConnection2;
            this.SYS_ORG.MultiSetWhere = false;
            this.SYS_ORG.Name = "SYS_ORG";
            this.SYS_ORG.NotificationAutoEnlist = false;
            this.SYS_ORG.SecExcept = null;
            this.SYS_ORG.SecFieldName = null;
            this.SYS_ORG.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SYS_ORG.SelectPaging = false;
            this.SYS_ORG.SelectTop = 0;
            this.SYS_ORG.SiteControl = false;
            this.SYS_ORG.SiteFieldName = null;
            this.SYS_ORG.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // PODelivery
            // 
            this.PODelivery.CacheConnection = false;
            this.PODelivery.CommandText = "SELECT * FROM dbo.[PODelivery]";
            this.PODelivery.CommandTimeout = 30;
            this.PODelivery.CommandType = System.Data.CommandType.Text;
            this.PODelivery.DynamicTableName = false;
            this.PODelivery.EEPAlias = null;
            this.PODelivery.EncodingAfter = null;
            this.PODelivery.EncodingBefore = "Windows-1252";
            this.PODelivery.EncodingConvert = null;
            this.PODelivery.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "PONO";
            keyItem9.KeyName = "ItemNO";
            keyItem10.KeyName = "DeliveryNO";
            this.PODelivery.KeyFields.Add(keyItem8);
            this.PODelivery.KeyFields.Add(keyItem9);
            this.PODelivery.KeyFields.Add(keyItem10);
            this.PODelivery.MultiSetWhere = false;
            this.PODelivery.Name = "PODelivery";
            this.PODelivery.NotificationAutoEnlist = false;
            this.PODelivery.SecExcept = null;
            this.PODelivery.SecFieldName = null;
            this.PODelivery.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PODelivery.SelectPaging = false;
            this.PODelivery.SelectTop = 0;
            this.PODelivery.SiteControl = false;
            this.PODelivery.SiteFieldName = null;
            this.PODelivery.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // idPODetails_PODelivery
            // 
            this.idPODetails_PODelivery.Detail = this.PODelivery;
            columnItem3.FieldName = "PONO";
            columnItem4.FieldName = "ItemNO";
            this.idPODetails_PODelivery.DetailColumns.Add(columnItem3);
            this.idPODetails_PODelivery.DetailColumns.Add(columnItem4);
            this.idPODetails_PODelivery.DynamicTableName = false;
            this.idPODetails_PODelivery.Master = this.PODetails;
            columnItem5.FieldName = "PONO";
            columnItem6.FieldName = "ItemNO";
            this.idPODetails_PODelivery.MasterColumns.Add(columnItem5);
            this.idPODetails_PODelivery.MasterColumns.Add(columnItem6);
            // 
            // ucPODelivery
            // 
            this.ucPODelivery.AutoTrans = true;
            this.ucPODelivery.ExceptJoin = false;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "PONO";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "ItemNO";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "DeliveryNO";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "DeliveryDate";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "DeliveryQty";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "PurPrice";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "OtherFee";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "TotalPrice";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "InvoiceNO";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "PayWayID";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "DebtorDays";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "Surveyors";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "CreateBy";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = "_username";
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "CreateDate";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = "_sysdate";
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "LastUpdateBy";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = "_username";
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "LastUpdateDate";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = "_sysdate";
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            this.ucPODelivery.FieldAttrs.Add(fieldAttr45);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr46);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr47);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr48);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr49);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr50);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr51);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr52);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr53);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr54);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr55);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr56);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr57);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr58);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr59);
            this.ucPODelivery.FieldAttrs.Add(fieldAttr60);
            this.ucPODelivery.LogInfo = null;
            this.ucPODelivery.Name = "ucPODelivery";
            this.ucPODelivery.RowAffectsCheck = true;
            this.ucPODelivery.SelectCmd = this.PODelivery;
            this.ucPODelivery.SelectCmdForUpdate = null;
            this.ucPODelivery.SendSQLCmd = true;
            this.ucPODelivery.ServerModify = true;
            this.ucPODelivery.ServerModifyGetMax = false;
            this.ucPODelivery.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucPODelivery.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucPODelivery.UseTranscationScope = false;
            this.ucPODelivery.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // InsGroup
            // 
            this.InsGroup.CacheConnection = false;
            this.InsGroup.CommandText = "SELECT [InsGroupID] ,[InsGroupShortName]\r\n  FROM [JBADMIN].[dbo].[InsGroup] where" +
    " IsActive=1";
            this.InsGroup.CommandTimeout = 30;
            this.InsGroup.CommandType = System.Data.CommandType.Text;
            this.InsGroup.DynamicTableName = false;
            this.InsGroup.EEPAlias = null;
            this.InsGroup.EncodingAfter = null;
            this.InsGroup.EncodingBefore = "Windows-1252";
            this.InsGroup.EncodingConvert = null;
            this.InsGroup.InfoConnection = this.InfoConnection1;
            this.InsGroup.MultiSetWhere = false;
            this.InsGroup.Name = "InsGroup";
            this.InsGroup.NotificationAutoEnlist = false;
            this.InsGroup.SecExcept = null;
            this.InsGroup.SecFieldName = null;
            this.InsGroup.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.InsGroup.SelectPaging = false;
            this.InsGroup.SelectTop = 0;
            this.InsGroup.SiteControl = false;
            this.InsGroup.SiteFieldName = null;
            this.InsGroup.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoConnection3
            // 
            this.infoConnection3.EEPAlias = "JBERP";
            // 
            // PayWay
            // 
            this.PayWay.CacheConnection = false;
            this.PayWay.CommandText = "SELECT  [PayWayID],[PayWayName]\r\n  FROM [PayWay]";
            this.PayWay.CommandTimeout = 30;
            this.PayWay.CommandType = System.Data.CommandType.Text;
            this.PayWay.DynamicTableName = false;
            this.PayWay.EEPAlias = "JBERP";
            this.PayWay.EncodingAfter = null;
            this.PayWay.EncodingBefore = "Windows-1252";
            this.PayWay.EncodingConvert = null;
            this.PayWay.InfoConnection = this.infoConnection3;
            this.PayWay.MultiSetWhere = false;
            this.PayWay.Name = "PayWay";
            this.PayWay.NotificationAutoEnlist = false;
            this.PayWay.SecExcept = null;
            this.PayWay.SecFieldName = null;
            this.PayWay.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PayWay.SelectPaging = false;
            this.PayWay.SelectTop = 0;
            this.PayWay.SiteControl = false;
            this.PayWay.SiteFieldName = null;
            this.PayWay.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.POMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_POMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.glCostCenter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.POType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RequistKind)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Item)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Vendors)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Users)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SYS_ORG)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PODelivery)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.InsGroup)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PayWay)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand POMaster;
        private Srvtools.UpdateComponent ucPOMaster;
        private Srvtools.InfoCommand PODetails;
        private Srvtools.UpdateComponent ucPODetails;
        private Srvtools.InfoDataSource idPOMaster_PODetails;
        private Srvtools.InfoCommand View_POMaster;
        private Srvtools.AutoNumber autoNumber1;
        private Srvtools.InfoCommand glCostCenter;
        private Srvtools.InfoCommand ItemType;
        private Srvtools.InfoCommand POType;
        private Srvtools.InfoCommand RequistKind;
        private Srvtools.InfoCommand Item;
        private Srvtools.InfoCommand Vendors;
        private Srvtools.InfoCommand Users;
        private Srvtools.InfoConnection infoConnection2;
        private Srvtools.InfoCommand SYS_ORG;
        private Srvtools.InfoCommand PODelivery;
        private Srvtools.InfoDataSource idPODetails_PODelivery;
        private Srvtools.UpdateComponent ucPODelivery;
        private Srvtools.InfoCommand InsGroup;
        private Srvtools.InfoConnection infoConnection3;
        private Srvtools.InfoCommand PayWay;
    }
}
