namespace sSalesTarget
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.SalesMonthTarget = new Srvtools.InfoCommand(this.components);
            this.ucSalesMonthTarget = new Srvtools.UpdateComponent(this.components);
            this.SalesDayTarget = new Srvtools.InfoCommand(this.components);
            this.ucSalesDayTarget = new Srvtools.UpdateComponent(this.components);
            this.View_SalesMonthTarget = new Srvtools.InfoCommand(this.components);
            this.View_SalesDayTarget = new Srvtools.InfoCommand(this.components);
            this.SalesYearTarget = new Srvtools.InfoCommand(this.components);
            this.ucSalesYearTarget = new Srvtools.UpdateComponent(this.components);
            this.autoNumber1 = new Srvtools.AutoNumber(this.components);
            this.autoNumber2 = new Srvtools.AutoNumber(this.components);
            this.autoNumber3 = new Srvtools.AutoNumber(this.components);
            this.SalesDayTargetSales = new Srvtools.InfoCommand(this.components);
            this.USERS = new Srvtools.InfoCommand(this.components);
            this.month = new Srvtools.InfoCommand(this.components);
            this.SalesTypeName = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesMonthTarget)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDayTarget)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_SalesMonthTarget)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_SalesDayTarget)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesYearTarget)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDayTargetSales)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.USERS)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.month)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesTypeName)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // SalesMonthTarget
            // 
            this.SalesMonthTarget.CacheConnection = false;
            this.SalesMonthTarget.CommandText = resources.GetString("SalesMonthTarget.CommandText");
            this.SalesMonthTarget.CommandTimeout = 30;
            this.SalesMonthTarget.CommandType = System.Data.CommandType.Text;
            this.SalesMonthTarget.DynamicTableName = false;
            this.SalesMonthTarget.EEPAlias = null;
            this.SalesMonthTarget.EncodingAfter = null;
            this.SalesMonthTarget.EncodingBefore = "Windows-1252";
            this.SalesMonthTarget.EncodingConvert = null;
            this.SalesMonthTarget.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "Year";
            keyItem2.KeyName = "Sales";
            keyItem3.KeyName = "SalesTypeID";
            keyItem4.KeyName = "SubClass";
            this.SalesMonthTarget.KeyFields.Add(keyItem1);
            this.SalesMonthTarget.KeyFields.Add(keyItem2);
            this.SalesMonthTarget.KeyFields.Add(keyItem3);
            this.SalesMonthTarget.KeyFields.Add(keyItem4);
            this.SalesMonthTarget.MultiSetWhere = false;
            this.SalesMonthTarget.Name = "SalesMonthTarget";
            this.SalesMonthTarget.NotificationAutoEnlist = false;
            this.SalesMonthTarget.SecExcept = null;
            this.SalesMonthTarget.SecFieldName = null;
            this.SalesMonthTarget.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesMonthTarget.SelectPaging = false;
            this.SalesMonthTarget.SelectTop = 0;
            this.SalesMonthTarget.SiteControl = false;
            this.SalesMonthTarget.SiteFieldName = null;
            this.SalesMonthTarget.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucSalesMonthTarget
            // 
            this.ucSalesMonthTarget.AutoTrans = true;
            this.ucSalesMonthTarget.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "AutoKey";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "Year";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "Sales";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "一月";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "二月";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "三月";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "四月";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "五月";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "六月";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "七月";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "八月";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "九月";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "十月";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "十一月";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "十二月";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "SalesTypeID";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "SubClass";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr1);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr2);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr3);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr4);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr5);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr6);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr7);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr8);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr9);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr10);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr11);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr12);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr13);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr14);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr15);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr16);
            this.ucSalesMonthTarget.FieldAttrs.Add(fieldAttr17);
            this.ucSalesMonthTarget.LogInfo = null;
            this.ucSalesMonthTarget.Name = "ucSalesMonthTarget";
            this.ucSalesMonthTarget.RowAffectsCheck = false;
            this.ucSalesMonthTarget.SelectCmd = this.SalesMonthTarget;
            this.ucSalesMonthTarget.SelectCmdForUpdate = null;
            this.ucSalesMonthTarget.SendSQLCmd = true;
            this.ucSalesMonthTarget.ServerModify = true;
            this.ucSalesMonthTarget.ServerModifyGetMax = false;
            this.ucSalesMonthTarget.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucSalesMonthTarget.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucSalesMonthTarget.UseTranscationScope = false;
            this.ucSalesMonthTarget.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // SalesDayTarget
            // 
            this.SalesDayTarget.CacheConnection = false;
            this.SalesDayTarget.CommandText = resources.GetString("SalesDayTarget.CommandText");
            this.SalesDayTarget.CommandTimeout = 30;
            this.SalesDayTarget.CommandType = System.Data.CommandType.Text;
            this.SalesDayTarget.DynamicTableName = false;
            this.SalesDayTarget.EEPAlias = null;
            this.SalesDayTarget.EncodingAfter = null;
            this.SalesDayTarget.EncodingBefore = "Windows-1252";
            this.SalesDayTarget.EncodingConvert = null;
            this.SalesDayTarget.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "Year";
            keyItem6.KeyName = "Month";
            keyItem7.KeyName = "Sales";
            keyItem8.KeyName = "SalesTypeID";
            keyItem9.KeyName = "SubClass";
            this.SalesDayTarget.KeyFields.Add(keyItem5);
            this.SalesDayTarget.KeyFields.Add(keyItem6);
            this.SalesDayTarget.KeyFields.Add(keyItem7);
            this.SalesDayTarget.KeyFields.Add(keyItem8);
            this.SalesDayTarget.KeyFields.Add(keyItem9);
            this.SalesDayTarget.MultiSetWhere = false;
            this.SalesDayTarget.Name = "SalesDayTarget";
            this.SalesDayTarget.NotificationAutoEnlist = false;
            this.SalesDayTarget.SecExcept = null;
            this.SalesDayTarget.SecFieldName = null;
            this.SalesDayTarget.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesDayTarget.SelectPaging = false;
            this.SalesDayTarget.SelectTop = 0;
            this.SalesDayTarget.SiteControl = false;
            this.SalesDayTarget.SiteFieldName = null;
            this.SalesDayTarget.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucSalesDayTarget
            // 
            this.ucSalesDayTarget.AutoTrans = true;
            this.ucSalesDayTarget.ExceptJoin = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "AutoKey";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "Year";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "Month";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "Sales";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "一日";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "二日";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "三日";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "四日";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "五日";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "六日";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "七日";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "八日";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "九日";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "十日";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "十一日";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "十二日";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "十三日";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "十四日";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "十五日";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "十六日";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "十七日";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "十八日";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "十九日";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "二十日";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "二十一日";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "二十二日";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "二十三日";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "二十四日";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "二十五日";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "二十六日";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "二十七日";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "二十八日";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "二十九日";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "三十日";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "三十一日";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "SalesTypeID";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "SubClass";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr18);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr19);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr20);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr21);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr22);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr23);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr24);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr25);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr26);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr27);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr28);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr29);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr30);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr31);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr32);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr33);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr34);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr35);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr36);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr37);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr38);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr39);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr40);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr41);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr42);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr43);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr44);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr45);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr46);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr47);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr48);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr49);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr50);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr51);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr52);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr53);
            this.ucSalesDayTarget.FieldAttrs.Add(fieldAttr54);
            this.ucSalesDayTarget.LogInfo = null;
            this.ucSalesDayTarget.Name = "ucSalesDayTarget";
            this.ucSalesDayTarget.RowAffectsCheck = false;
            this.ucSalesDayTarget.SelectCmd = this.SalesDayTarget;
            this.ucSalesDayTarget.SelectCmdForUpdate = null;
            this.ucSalesDayTarget.SendSQLCmd = true;
            this.ucSalesDayTarget.ServerModify = true;
            this.ucSalesDayTarget.ServerModifyGetMax = false;
            this.ucSalesDayTarget.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucSalesDayTarget.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucSalesDayTarget.UseTranscationScope = false;
            this.ucSalesDayTarget.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_SalesMonthTarget
            // 
            this.View_SalesMonthTarget.CacheConnection = false;
            this.View_SalesMonthTarget.CommandText = "SELECT * FROM dbo.[SalesMonthTarget]";
            this.View_SalesMonthTarget.CommandTimeout = 30;
            this.View_SalesMonthTarget.CommandType = System.Data.CommandType.Text;
            this.View_SalesMonthTarget.DynamicTableName = false;
            this.View_SalesMonthTarget.EEPAlias = null;
            this.View_SalesMonthTarget.EncodingAfter = null;
            this.View_SalesMonthTarget.EncodingBefore = "Windows-1252";
            this.View_SalesMonthTarget.EncodingConvert = null;
            this.View_SalesMonthTarget.InfoConnection = this.InfoConnection1;
            keyItem10.KeyName = "AutoKey";
            this.View_SalesMonthTarget.KeyFields.Add(keyItem10);
            this.View_SalesMonthTarget.MultiSetWhere = false;
            this.View_SalesMonthTarget.Name = "View_SalesMonthTarget";
            this.View_SalesMonthTarget.NotificationAutoEnlist = false;
            this.View_SalesMonthTarget.SecExcept = null;
            this.View_SalesMonthTarget.SecFieldName = null;
            this.View_SalesMonthTarget.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_SalesMonthTarget.SelectPaging = false;
            this.View_SalesMonthTarget.SelectTop = 0;
            this.View_SalesMonthTarget.SiteControl = false;
            this.View_SalesMonthTarget.SiteFieldName = null;
            this.View_SalesMonthTarget.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // View_SalesDayTarget
            // 
            this.View_SalesDayTarget.CacheConnection = false;
            this.View_SalesDayTarget.CommandText = "SELECT * FROM dbo.[SalesDayTarget]";
            this.View_SalesDayTarget.CommandTimeout = 30;
            this.View_SalesDayTarget.CommandType = System.Data.CommandType.Text;
            this.View_SalesDayTarget.DynamicTableName = false;
            this.View_SalesDayTarget.EEPAlias = null;
            this.View_SalesDayTarget.EncodingAfter = null;
            this.View_SalesDayTarget.EncodingBefore = "Windows-1252";
            this.View_SalesDayTarget.EncodingConvert = null;
            this.View_SalesDayTarget.InfoConnection = this.InfoConnection1;
            keyItem11.KeyName = "AutoKey";
            this.View_SalesDayTarget.KeyFields.Add(keyItem11);
            this.View_SalesDayTarget.MultiSetWhere = false;
            this.View_SalesDayTarget.Name = "View_SalesDayTarget";
            this.View_SalesDayTarget.NotificationAutoEnlist = false;
            this.View_SalesDayTarget.SecExcept = null;
            this.View_SalesDayTarget.SecFieldName = null;
            this.View_SalesDayTarget.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_SalesDayTarget.SelectPaging = false;
            this.View_SalesDayTarget.SelectTop = 0;
            this.View_SalesDayTarget.SiteControl = false;
            this.View_SalesDayTarget.SiteFieldName = null;
            this.View_SalesDayTarget.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesYearTarget
            // 
            this.SalesYearTarget.CacheConnection = false;
            this.SalesYearTarget.CommandText = resources.GetString("SalesYearTarget.CommandText");
            this.SalesYearTarget.CommandTimeout = 30;
            this.SalesYearTarget.CommandType = System.Data.CommandType.Text;
            this.SalesYearTarget.DynamicTableName = false;
            this.SalesYearTarget.EEPAlias = null;
            this.SalesYearTarget.EncodingAfter = null;
            this.SalesYearTarget.EncodingBefore = "Windows-1252";
            this.SalesYearTarget.EncodingConvert = null;
            this.SalesYearTarget.InfoConnection = this.InfoConnection1;
            keyItem12.KeyName = "Year";
            this.SalesYearTarget.KeyFields.Add(keyItem12);
            this.SalesYearTarget.MultiSetWhere = false;
            this.SalesYearTarget.Name = "SalesYearTarget";
            this.SalesYearTarget.NotificationAutoEnlist = false;
            this.SalesYearTarget.SecExcept = null;
            this.SalesYearTarget.SecFieldName = null;
            this.SalesYearTarget.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesYearTarget.SelectPaging = false;
            this.SalesYearTarget.SelectTop = 0;
            this.SalesYearTarget.SiteControl = false;
            this.SalesYearTarget.SiteFieldName = null;
            this.SalesYearTarget.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucSalesYearTarget
            // 
            this.ucSalesYearTarget.AutoTrans = true;
            this.ucSalesYearTarget.ExceptJoin = false;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "AutoKey";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "Year";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "Target1";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "Target2";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            this.ucSalesYearTarget.FieldAttrs.Add(fieldAttr55);
            this.ucSalesYearTarget.FieldAttrs.Add(fieldAttr56);
            this.ucSalesYearTarget.FieldAttrs.Add(fieldAttr57);
            this.ucSalesYearTarget.FieldAttrs.Add(fieldAttr58);
            this.ucSalesYearTarget.LogInfo = null;
            this.ucSalesYearTarget.Name = "ucSalesYearTarget";
            this.ucSalesYearTarget.RowAffectsCheck = true;
            this.ucSalesYearTarget.SelectCmd = this.SalesYearTarget;
            this.ucSalesYearTarget.SelectCmdForUpdate = null;
            this.ucSalesYearTarget.SendSQLCmd = true;
            this.ucSalesYearTarget.ServerModify = true;
            this.ucSalesYearTarget.ServerModifyGetMax = false;
            this.ucSalesYearTarget.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucSalesYearTarget.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucSalesYearTarget.UseTranscationScope = false;
            this.ucSalesYearTarget.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // autoNumber1
            // 
            this.autoNumber1.Active = true;
            this.autoNumber1.AutoNoID = "AutoKey1";
            this.autoNumber1.Description = null;
            this.autoNumber1.GetFixed = "";
            this.autoNumber1.isNumFill = false;
            this.autoNumber1.Name = "autoNumber1";
            this.autoNumber1.Number = null;
            this.autoNumber1.NumDig = 10;
            this.autoNumber1.OldVersion = false;
            this.autoNumber1.OverFlow = true;
            this.autoNumber1.StartValue = 1;
            this.autoNumber1.Step = 1;
            this.autoNumber1.TargetColumn = "AutoKey";
            this.autoNumber1.UpdateComp = this.ucSalesYearTarget;
            // 
            // autoNumber2
            // 
            this.autoNumber2.Active = true;
            this.autoNumber2.AutoNoID = "AutoKey2";
            this.autoNumber2.Description = null;
            this.autoNumber2.GetFixed = "";
            this.autoNumber2.isNumFill = false;
            this.autoNumber2.Name = "autoNumber2";
            this.autoNumber2.Number = null;
            this.autoNumber2.NumDig = 10;
            this.autoNumber2.OldVersion = false;
            this.autoNumber2.OverFlow = true;
            this.autoNumber2.StartValue = 1;
            this.autoNumber2.Step = 1;
            this.autoNumber2.TargetColumn = "AutoKey";
            this.autoNumber2.UpdateComp = this.ucSalesMonthTarget;
            // 
            // autoNumber3
            // 
            this.autoNumber3.Active = true;
            this.autoNumber3.AutoNoID = "AutoKey3";
            this.autoNumber3.Description = null;
            this.autoNumber3.GetFixed = "";
            this.autoNumber3.isNumFill = false;
            this.autoNumber3.Name = "autoNumber3";
            this.autoNumber3.Number = null;
            this.autoNumber3.NumDig = 10;
            this.autoNumber3.OldVersion = false;
            this.autoNumber3.OverFlow = true;
            this.autoNumber3.StartValue = 1;
            this.autoNumber3.Step = 1;
            this.autoNumber3.TargetColumn = "AutoKey";
            this.autoNumber3.UpdateComp = this.ucSalesDayTarget;
            // 
            // SalesDayTargetSales
            // 
            this.SalesDayTargetSales.CacheConnection = false;
            this.SalesDayTargetSales.CommandText = "SELECT distinct s.Sales,u.USERNAME FROM dbo.[SalesDayTarget] s\r\ninner join EIPHRS" +
    "YS.dbo.USERS u on s.Sales=u.USERID";
            this.SalesDayTargetSales.CommandTimeout = 30;
            this.SalesDayTargetSales.CommandType = System.Data.CommandType.Text;
            this.SalesDayTargetSales.DynamicTableName = false;
            this.SalesDayTargetSales.EEPAlias = null;
            this.SalesDayTargetSales.EncodingAfter = null;
            this.SalesDayTargetSales.EncodingBefore = "Windows-1252";
            this.SalesDayTargetSales.EncodingConvert = null;
            this.SalesDayTargetSales.InfoConnection = this.InfoConnection1;
            this.SalesDayTargetSales.MultiSetWhere = false;
            this.SalesDayTargetSales.Name = "SalesDayTargetSales";
            this.SalesDayTargetSales.NotificationAutoEnlist = false;
            this.SalesDayTargetSales.SecExcept = null;
            this.SalesDayTargetSales.SecFieldName = null;
            this.SalesDayTargetSales.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesDayTargetSales.SelectPaging = false;
            this.SalesDayTargetSales.SelectTop = 0;
            this.SalesDayTargetSales.SiteControl = false;
            this.SalesDayTargetSales.SiteFieldName = null;
            this.SalesDayTargetSales.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // USERS
            // 
            this.USERS.CacheConnection = false;
            this.USERS.CommandText = "SELECT USERID,USERNAME FROM  EIPHRSYS.dbo.USERS";
            this.USERS.CommandTimeout = 30;
            this.USERS.CommandType = System.Data.CommandType.Text;
            this.USERS.DynamicTableName = false;
            this.USERS.EEPAlias = null;
            this.USERS.EncodingAfter = null;
            this.USERS.EncodingBefore = "Windows-1252";
            this.USERS.EncodingConvert = null;
            this.USERS.InfoConnection = this.InfoConnection1;
            keyItem13.KeyName = "USERID";
            this.USERS.KeyFields.Add(keyItem13);
            this.USERS.MultiSetWhere = false;
            this.USERS.Name = "USERS";
            this.USERS.NotificationAutoEnlist = false;
            this.USERS.SecExcept = null;
            this.USERS.SecFieldName = null;
            this.USERS.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.USERS.SelectPaging = false;
            this.USERS.SelectTop = 0;
            this.USERS.SiteControl = false;
            this.USERS.SiteFieldName = null;
            this.USERS.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // month
            // 
            this.month.CacheConnection = false;
            this.month.CommandText = resources.GetString("month.CommandText");
            this.month.CommandTimeout = 30;
            this.month.CommandType = System.Data.CommandType.Text;
            this.month.DynamicTableName = false;
            this.month.EEPAlias = null;
            this.month.EncodingAfter = null;
            this.month.EncodingBefore = "Windows-1252";
            this.month.EncodingConvert = null;
            this.month.InfoConnection = this.InfoConnection1;
            this.month.MultiSetWhere = false;
            this.month.Name = "month";
            this.month.NotificationAutoEnlist = false;
            this.month.SecExcept = null;
            this.month.SecFieldName = null;
            this.month.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.month.SelectPaging = false;
            this.month.SelectTop = 0;
            this.month.SiteControl = false;
            this.month.SiteFieldName = null;
            this.month.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SalesTypeName
            // 
            this.SalesTypeName.CacheConnection = false;
            this.SalesTypeName.CommandText = "SELECT [SalesTypeID]\r\n      ,[SalesTypeName]\r\n  FROM [JBADMIN].[dbo].[ERPSalesTyp" +
    "e] where SalesTypeID in(\'1\',\'31\')";
            this.SalesTypeName.CommandTimeout = 30;
            this.SalesTypeName.CommandType = System.Data.CommandType.Text;
            this.SalesTypeName.DynamicTableName = false;
            this.SalesTypeName.EEPAlias = null;
            this.SalesTypeName.EncodingAfter = null;
            this.SalesTypeName.EncodingBefore = "Windows-1252";
            this.SalesTypeName.EncodingConvert = null;
            this.SalesTypeName.InfoConnection = this.InfoConnection1;
            this.SalesTypeName.MultiSetWhere = false;
            this.SalesTypeName.Name = "SalesTypeName";
            this.SalesTypeName.NotificationAutoEnlist = false;
            this.SalesTypeName.SecExcept = null;
            this.SalesTypeName.SecFieldName = null;
            this.SalesTypeName.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SalesTypeName.SelectPaging = false;
            this.SalesTypeName.SelectTop = 0;
            this.SalesTypeName.SiteControl = false;
            this.SalesTypeName.SiteFieldName = null;
            this.SalesTypeName.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesMonthTarget)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDayTarget)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_SalesMonthTarget)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_SalesDayTarget)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesYearTarget)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesDayTargetSales)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.USERS)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.month)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SalesTypeName)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand SalesMonthTarget;
        private Srvtools.UpdateComponent ucSalesMonthTarget;
        private Srvtools.InfoCommand SalesDayTarget;
        private Srvtools.UpdateComponent ucSalesDayTarget;
        private Srvtools.InfoCommand View_SalesMonthTarget;
        private Srvtools.InfoCommand View_SalesDayTarget;
        private Srvtools.InfoCommand SalesYearTarget;
        private Srvtools.UpdateComponent ucSalesYearTarget;
        private Srvtools.AutoNumber autoNumber1;
        private Srvtools.AutoNumber autoNumber2;
        private Srvtools.AutoNumber autoNumber3;
        private Srvtools.InfoCommand SalesDayTargetSales;
        private Srvtools.InfoCommand USERS;
        private Srvtools.InfoCommand month;
        private Srvtools.InfoCommand SalesTypeName;
    }
}
