namespace sSalesApplyMasterTest2
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.ColumnItem columnItem1 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem2 = new Srvtools.ColumnItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.ERPSalesApplyMaster = new Srvtools.InfoCommand(this.components);
            this.ucERPSalesApplyMaster = new Srvtools.UpdateComponent(this.components);
            this.ERPSalesApplyDetails = new Srvtools.InfoCommand(this.components);
            this.ucERPSalesApplyDetails = new Srvtools.UpdateComponent(this.components);
            this.idERPSalesApplyMaster_ERPSalesApplyDetails = new Srvtools.InfoDataSource(this.components);
            this.View_ERPSalesApplyMaster = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesApplyMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesApplyDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_ERPSalesApplyMaster)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // ERPSalesApplyMaster
            // 
            this.ERPSalesApplyMaster.CacheConnection = false;
            this.ERPSalesApplyMaster.CommandText = "SELECT dbo.[ERPSalesApplyMaster].* FROM dbo.[ERPSalesApplyMaster]";
            this.ERPSalesApplyMaster.CommandTimeout = 30;
            this.ERPSalesApplyMaster.CommandType = System.Data.CommandType.Text;
            this.ERPSalesApplyMaster.DynamicTableName = false;
            this.ERPSalesApplyMaster.EEPAlias = null;
            this.ERPSalesApplyMaster.EncodingAfter = null;
            this.ERPSalesApplyMaster.EncodingBefore = "Windows-1252";
            this.ERPSalesApplyMaster.EncodingConvert = null;
            this.ERPSalesApplyMaster.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "SalesApplyNO";
            this.ERPSalesApplyMaster.KeyFields.Add(keyItem1);
            this.ERPSalesApplyMaster.MultiSetWhere = false;
            this.ERPSalesApplyMaster.Name = "ERPSalesApplyMaster";
            this.ERPSalesApplyMaster.NotificationAutoEnlist = false;
            this.ERPSalesApplyMaster.SecExcept = null;
            this.ERPSalesApplyMaster.SecFieldName = null;
            this.ERPSalesApplyMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPSalesApplyMaster.SelectPaging = false;
            this.ERPSalesApplyMaster.SelectTop = 0;
            this.ERPSalesApplyMaster.SiteControl = false;
            this.ERPSalesApplyMaster.SiteFieldName = null;
            this.ERPSalesApplyMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPSalesApplyMaster
            // 
            this.ucERPSalesApplyMaster.AutoTrans = true;
            this.ucERPSalesApplyMaster.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "SalesApplyNO";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "CustNO";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "Contact";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "ApplyDate";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "SalesYM";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ApplyEmpID";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "ApplyOrg_NO";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "AssetGroupTypeID";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "Org_NOParent";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "SalesID";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "TaxNO";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "SalesOutLine";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "SalesNotes";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "InsGroupID";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "SalesTypeID";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "SalesItemID";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "SalesItemType";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "SalesItemName";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "SalesExceptionID";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "SalesExceptionName";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "ExceptDealTypeID";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "ExceptDealTypeName";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "ExceptDealItemID";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "ExceptDealItemName";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "InvoiceAmt";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "ExceptAmt";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "DispatchAreaID";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "DispatchAreaManager";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "IsPostToNjbExcept";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "flowflag";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "ProofTypeID";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "CreateBy";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "CreateDate";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr1);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr2);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr3);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr4);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr5);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr6);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr7);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr8);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr9);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr10);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr11);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr12);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr13);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr14);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr15);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr16);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr17);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr18);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr19);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr20);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr21);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr22);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr23);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr24);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr25);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr26);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr27);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr28);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr29);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr30);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr31);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr32);
            this.ucERPSalesApplyMaster.FieldAttrs.Add(fieldAttr33);
            this.ucERPSalesApplyMaster.LogInfo = null;
            this.ucERPSalesApplyMaster.Name = "ucERPSalesApplyMaster";
            this.ucERPSalesApplyMaster.RowAffectsCheck = true;
            this.ucERPSalesApplyMaster.SelectCmd = this.ERPSalesApplyMaster;
            this.ucERPSalesApplyMaster.SelectCmdForUpdate = null;
            this.ucERPSalesApplyMaster.SendSQLCmd = true;
            this.ucERPSalesApplyMaster.ServerModify = true;
            this.ucERPSalesApplyMaster.ServerModifyGetMax = false;
            this.ucERPSalesApplyMaster.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPSalesApplyMaster.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPSalesApplyMaster.UseTranscationScope = false;
            this.ucERPSalesApplyMaster.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // ERPSalesApplyDetails
            // 
            this.ERPSalesApplyDetails.CacheConnection = false;
            this.ERPSalesApplyDetails.CommandText = "SELECT dbo.[ERPSalesApplyDetails].* FROM dbo.[ERPSalesApplyDetails]";
            this.ERPSalesApplyDetails.CommandTimeout = 30;
            this.ERPSalesApplyDetails.CommandType = System.Data.CommandType.Text;
            this.ERPSalesApplyDetails.DynamicTableName = false;
            this.ERPSalesApplyDetails.EEPAlias = null;
            this.ERPSalesApplyDetails.EncodingAfter = null;
            this.ERPSalesApplyDetails.EncodingBefore = "Windows-1252";
            this.ERPSalesApplyDetails.EncodingConvert = null;
            this.ERPSalesApplyDetails.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "SalesApplyNO";
            keyItem3.KeyName = "ItemSeq";
            this.ERPSalesApplyDetails.KeyFields.Add(keyItem2);
            this.ERPSalesApplyDetails.KeyFields.Add(keyItem3);
            this.ERPSalesApplyDetails.MultiSetWhere = false;
            this.ERPSalesApplyDetails.Name = "ERPSalesApplyDetails";
            this.ERPSalesApplyDetails.NotificationAutoEnlist = false;
            this.ERPSalesApplyDetails.SecExcept = null;
            this.ERPSalesApplyDetails.SecFieldName = null;
            this.ERPSalesApplyDetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPSalesApplyDetails.SelectPaging = false;
            this.ERPSalesApplyDetails.SelectTop = 0;
            this.ERPSalesApplyDetails.SiteControl = false;
            this.ERPSalesApplyDetails.SiteFieldName = null;
            this.ERPSalesApplyDetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPSalesApplyDetails
            // 
            this.ucERPSalesApplyDetails.AutoTrans = true;
            this.ucERPSalesApplyDetails.ExceptJoin = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "SalesApplyNO";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "ItemSeq";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "ItemOutLine";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "InvoiceYM";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "SalesQty";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "SalesPrice";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "SalesAmt";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "SalesTax";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "SalesTotal";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "EmpLaAmt";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "EmpCount";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "InvoiceAmt";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "InvoiceNO";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "SalesDate";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "CreateBy";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "CreateDate";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr34);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr35);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr36);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr37);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr38);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr39);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr40);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr41);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr42);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr43);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr44);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr45);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr46);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr47);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr48);
            this.ucERPSalesApplyDetails.FieldAttrs.Add(fieldAttr49);
            this.ucERPSalesApplyDetails.LogInfo = null;
            this.ucERPSalesApplyDetails.Name = "ucERPSalesApplyDetails";
            this.ucERPSalesApplyDetails.RowAffectsCheck = true;
            this.ucERPSalesApplyDetails.SelectCmd = this.ERPSalesApplyDetails;
            this.ucERPSalesApplyDetails.SelectCmdForUpdate = null;
            this.ucERPSalesApplyDetails.SendSQLCmd = true;
            this.ucERPSalesApplyDetails.ServerModify = true;
            this.ucERPSalesApplyDetails.ServerModifyGetMax = false;
            this.ucERPSalesApplyDetails.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPSalesApplyDetails.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPSalesApplyDetails.UseTranscationScope = false;
            this.ucERPSalesApplyDetails.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // idERPSalesApplyMaster_ERPSalesApplyDetails
            // 
            this.idERPSalesApplyMaster_ERPSalesApplyDetails.Detail = this.ERPSalesApplyDetails;
            columnItem1.FieldName = "SalesApplyNO";
            this.idERPSalesApplyMaster_ERPSalesApplyDetails.DetailColumns.Add(columnItem1);
            this.idERPSalesApplyMaster_ERPSalesApplyDetails.DynamicTableName = false;
            this.idERPSalesApplyMaster_ERPSalesApplyDetails.Master = this.ERPSalesApplyMaster;
            columnItem2.FieldName = "SalesApplyNO";
            this.idERPSalesApplyMaster_ERPSalesApplyDetails.MasterColumns.Add(columnItem2);
            // 
            // View_ERPSalesApplyMaster
            // 
            this.View_ERPSalesApplyMaster.CacheConnection = false;
            this.View_ERPSalesApplyMaster.CommandText = "SELECT * FROM dbo.[ERPSalesApplyMaster]";
            this.View_ERPSalesApplyMaster.CommandTimeout = 30;
            this.View_ERPSalesApplyMaster.CommandType = System.Data.CommandType.Text;
            this.View_ERPSalesApplyMaster.DynamicTableName = false;
            this.View_ERPSalesApplyMaster.EEPAlias = null;
            this.View_ERPSalesApplyMaster.EncodingAfter = null;
            this.View_ERPSalesApplyMaster.EncodingBefore = "Windows-1252";
            this.View_ERPSalesApplyMaster.EncodingConvert = null;
            this.View_ERPSalesApplyMaster.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "SalesApplyNO";
            this.View_ERPSalesApplyMaster.KeyFields.Add(keyItem4);
            this.View_ERPSalesApplyMaster.MultiSetWhere = false;
            this.View_ERPSalesApplyMaster.Name = "View_ERPSalesApplyMaster";
            this.View_ERPSalesApplyMaster.NotificationAutoEnlist = false;
            this.View_ERPSalesApplyMaster.SecExcept = null;
            this.View_ERPSalesApplyMaster.SecFieldName = null;
            this.View_ERPSalesApplyMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_ERPSalesApplyMaster.SelectPaging = false;
            this.View_ERPSalesApplyMaster.SelectTop = 0;
            this.View_ERPSalesApplyMaster.SiteControl = false;
            this.View_ERPSalesApplyMaster.SiteFieldName = null;
            this.View_ERPSalesApplyMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesApplyMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesApplyDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_ERPSalesApplyMaster)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand ERPSalesApplyMaster;
        private Srvtools.UpdateComponent ucERPSalesApplyMaster;
        private Srvtools.InfoCommand ERPSalesApplyDetails;
        private Srvtools.UpdateComponent ucERPSalesApplyDetails;
        private Srvtools.InfoDataSource idERPSalesApplyMaster_ERPSalesApplyDetails;
        private Srvtools.InfoCommand View_ERPSalesApplyMaster;
    }
}
