namespace sERPToDoCustomer
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem14 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr69 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr70 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr71 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr72 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr73 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr74 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr75 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr76 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr77 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr78 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr79 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr80 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr81 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr82 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr83 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr84 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr85 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr86 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr87 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr88 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr89 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr90 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr91 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr92 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr93 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr94 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr95 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr96 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr97 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr98 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr99 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr100 = new Srvtools.FieldAttr();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.ERPSalesMaster = new Srvtools.InfoCommand(this.components);
            this.ucERPSalesMaster = new Srvtools.UpdateComponent(this.components);
            this.ERPSalesDetails = new Srvtools.InfoCommand(this.components);
            this.ucERPSalesDetails = new Srvtools.UpdateComponent(this.components);
            this.infoQuery = new Srvtools.InfoCommand(this.components);
            this.infoCustomerToDoNotes = new Srvtools.InfoCommand(this.components);
            this.infoConnection2 = new Srvtools.InfoConnection(this.components);
            this.updateCustomerToDoNotes = new Srvtools.UpdateComponent(this.components);
            this.infoNextCallTime = new Srvtools.InfoCommand(this.components);
            this.infoPostSource = new Srvtools.InfoCommand(this.components);
            this.infoPostType = new Srvtools.InfoCommand(this.components);
            this.infoCustomerToDoNotesList = new Srvtools.InfoCommand(this.components);
            this.infoTempToDoNotes = new Srvtools.InfoCommand(this.components);
            this.updateTempToDoNotes = new Srvtools.UpdateComponent(this.components);
            this.infoCustomerInfo = new Srvtools.InfoCommand(this.components);
            this.updateCustomerInfo = new Srvtools.UpdateComponent(this.components);
            this.infoERPOffice = new Srvtools.InfoCommand(this.components);
            this.infoERPJobWeekend = new Srvtools.InfoCommand(this.components);
            this.infoForeignDorm = new Srvtools.InfoCommand(this.components);
            this.infoERPCustNationality = new Srvtools.InfoCommand(this.components);
            this.infoERPNationality = new Srvtools.InfoCommand(this.components);
            this.updateCustNationality = new Srvtools.UpdateComponent(this.components);
            this.infoImportantRecord = new Srvtools.InfoCommand(this.components);
            this.updateImportantRecord = new Srvtools.UpdateComponent(this.components);
            this.updateContactRecord = new Srvtools.UpdateComponent(this.components);
            this.infoContactRecord = new Srvtools.InfoCommand(this.components);
            this.ERPCustomers = new Srvtools.InfoCommand(this.components);
            this.ucERPCustomers = new Srvtools.UpdateComponent(this.components);
            this.infoInvoiceType = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoQuery)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomerToDoNotes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoNextCallTime)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoPostSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoPostType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomerToDoNotesList)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoTempToDoNotes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomerInfo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPOffice)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPJobWeekend)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoForeignDorm)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPCustNationality)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPNationality)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoImportantRecord)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoContactRecord)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPCustomers)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoInvoiceType)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "AddCustomerToDoNotes";
            service1.NonLogin = false;
            service1.ServiceName = "AddCustomerToDoNotes";
            service2.DelegateName = "AddCustomerToDoNotesSalse";
            service2.NonLogin = false;
            service2.ServiceName = "AddCustomerToDoNotesSalse";
            service3.DelegateName = "getQuerylist";
            service3.NonLogin = false;
            service3.ServiceName = "getQuerylist";
            service4.DelegateName = "UpdateERPSalesMasterDaysAlert";
            service4.NonLogin = false;
            service4.ServiceName = "UpdateERPSalesMasterDaysAlert";
            service5.DelegateName = "UpdateSetElectronicEmail";
            service5.NonLogin = false;
            service5.ServiceName = "UpdateSetElectronicEmail";
            service6.DelegateName = "procAddCustomerERPPayKind";
            service6.NonLogin = false;
            service6.ServiceName = "procAddCustomerERPPayKind";
            service7.DelegateName = "AddCustomerToDoNotes2";
            service7.NonLogin = false;
            service7.ServiceName = "AddCustomerToDoNotes2";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // ERPSalesMaster
            // 
            this.ERPSalesMaster.CacheConnection = false;
            this.ERPSalesMaster.CommandText = resources.GetString("ERPSalesMaster.CommandText");
            this.ERPSalesMaster.CommandTimeout = 30;
            this.ERPSalesMaster.CommandType = System.Data.CommandType.Text;
            this.ERPSalesMaster.DynamicTableName = false;
            this.ERPSalesMaster.EEPAlias = null;
            this.ERPSalesMaster.EncodingAfter = null;
            this.ERPSalesMaster.EncodingBefore = "Windows-1252";
            this.ERPSalesMaster.EncodingConvert = null;
            this.ERPSalesMaster.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "SalesMasterNO";
            this.ERPSalesMaster.KeyFields.Add(keyItem1);
            this.ERPSalesMaster.MultiSetWhere = false;
            this.ERPSalesMaster.Name = "ERPSalesMaster";
            this.ERPSalesMaster.NotificationAutoEnlist = false;
            this.ERPSalesMaster.SecExcept = null;
            this.ERPSalesMaster.SecFieldName = null;
            this.ERPSalesMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPSalesMaster.SelectPaging = false;
            this.ERPSalesMaster.SelectTop = 0;
            this.ERPSalesMaster.SiteControl = false;
            this.ERPSalesMaster.SiteFieldName = null;
            this.ERPSalesMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPSalesMaster
            // 
            this.ucERPSalesMaster.AutoTrans = true;
            this.ucERPSalesMaster.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "SalesMasterNO";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "CustNO";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "KeepDays";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "KeepDaysAlert";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            this.ucERPSalesMaster.FieldAttrs.Add(fieldAttr1);
            this.ucERPSalesMaster.FieldAttrs.Add(fieldAttr2);
            this.ucERPSalesMaster.FieldAttrs.Add(fieldAttr3);
            this.ucERPSalesMaster.FieldAttrs.Add(fieldAttr4);
            this.ucERPSalesMaster.LogInfo = null;
            this.ucERPSalesMaster.Name = "ucERPSalesMaster";
            this.ucERPSalesMaster.RowAffectsCheck = true;
            this.ucERPSalesMaster.SelectCmd = this.ERPSalesMaster;
            this.ucERPSalesMaster.SelectCmdForUpdate = null;
            this.ucERPSalesMaster.SendSQLCmd = true;
            this.ucERPSalesMaster.ServerModify = true;
            this.ucERPSalesMaster.ServerModifyGetMax = false;
            this.ucERPSalesMaster.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPSalesMaster.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPSalesMaster.UseTranscationScope = false;
            this.ucERPSalesMaster.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // ERPSalesDetails
            // 
            this.ERPSalesDetails.CacheConnection = false;
            this.ERPSalesDetails.CommandText = resources.GetString("ERPSalesDetails.CommandText");
            this.ERPSalesDetails.CommandTimeout = 30;
            this.ERPSalesDetails.CommandType = System.Data.CommandType.Text;
            this.ERPSalesDetails.DynamicTableName = false;
            this.ERPSalesDetails.EEPAlias = null;
            this.ERPSalesDetails.EncodingAfter = null;
            this.ERPSalesDetails.EncodingBefore = "Windows-1252";
            this.ERPSalesDetails.EncodingConvert = null;
            this.ERPSalesDetails.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "SalesMasterNO";
            keyItem3.KeyName = "ItemSeq";
            this.ERPSalesDetails.KeyFields.Add(keyItem2);
            this.ERPSalesDetails.KeyFields.Add(keyItem3);
            this.ERPSalesDetails.MultiSetWhere = false;
            this.ERPSalesDetails.Name = "ERPSalesDetails";
            this.ERPSalesDetails.NotificationAutoEnlist = false;
            this.ERPSalesDetails.SecExcept = null;
            this.ERPSalesDetails.SecFieldName = null;
            this.ERPSalesDetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPSalesDetails.SelectPaging = false;
            this.ERPSalesDetails.SelectTop = 0;
            this.ERPSalesDetails.SiteControl = false;
            this.ERPSalesDetails.SiteFieldName = null;
            this.ERPSalesDetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPSalesDetails
            // 
            this.ucERPSalesDetails.AutoTrans = true;
            this.ucERPSalesDetails.ExceptJoin = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "SalesMasterNO";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ItemSeq";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "CustNO";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "SalesDescr";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "SalesDescrDate";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "SalesDescrAlert";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr5);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr6);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr7);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr8);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr9);
            this.ucERPSalesDetails.FieldAttrs.Add(fieldAttr10);
            this.ucERPSalesDetails.LogInfo = null;
            this.ucERPSalesDetails.Name = "ucERPSalesDetails";
            this.ucERPSalesDetails.RowAffectsCheck = true;
            this.ucERPSalesDetails.SelectCmd = this.ERPSalesDetails;
            this.ucERPSalesDetails.SelectCmdForUpdate = null;
            this.ucERPSalesDetails.SendSQLCmd = true;
            this.ucERPSalesDetails.ServerModify = true;
            this.ucERPSalesDetails.ServerModifyGetMax = false;
            this.ucERPSalesDetails.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPSalesDetails.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPSalesDetails.UseTranscationScope = false;
            this.ucERPSalesDetails.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoQuery
            // 
            this.infoQuery.CacheConnection = false;
            this.infoQuery.CommandText = "select \'\' SalesID,\'\' as CustNO,\'\' as SDate,\'\' as EDate,0 as Sourse";
            this.infoQuery.CommandTimeout = 30;
            this.infoQuery.CommandType = System.Data.CommandType.Text;
            this.infoQuery.DynamicTableName = false;
            this.infoQuery.EEPAlias = null;
            this.infoQuery.EncodingAfter = null;
            this.infoQuery.EncodingBefore = "Windows-1252";
            this.infoQuery.EncodingConvert = null;
            this.infoQuery.InfoConnection = this.InfoConnection1;
            this.infoQuery.MultiSetWhere = false;
            this.infoQuery.Name = "infoQuery";
            this.infoQuery.NotificationAutoEnlist = false;
            this.infoQuery.SecExcept = null;
            this.infoQuery.SecFieldName = null;
            this.infoQuery.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoQuery.SelectPaging = false;
            this.infoQuery.SelectTop = 0;
            this.infoQuery.SiteControl = false;
            this.infoQuery.SiteFieldName = null;
            this.infoQuery.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoCustomerToDoNotes
            // 
            this.infoCustomerToDoNotes.CacheConnection = false;
            this.infoCustomerToDoNotes.CommandText = resources.GetString("infoCustomerToDoNotes.CommandText");
            this.infoCustomerToDoNotes.CommandTimeout = 30;
            this.infoCustomerToDoNotes.CommandType = System.Data.CommandType.Text;
            this.infoCustomerToDoNotes.DynamicTableName = false;
            this.infoCustomerToDoNotes.EEPAlias = "";
            this.infoCustomerToDoNotes.EncodingAfter = null;
            this.infoCustomerToDoNotes.EncodingBefore = "Windows-1252";
            this.infoCustomerToDoNotes.EncodingConvert = null;
            this.infoCustomerToDoNotes.InfoConnection = this.infoConnection2;
            keyItem4.KeyName = "CustNO";
            this.infoCustomerToDoNotes.KeyFields.Add(keyItem4);
            this.infoCustomerToDoNotes.MultiSetWhere = false;
            this.infoCustomerToDoNotes.Name = "infoCustomerToDoNotes";
            this.infoCustomerToDoNotes.NotificationAutoEnlist = false;
            this.infoCustomerToDoNotes.SecExcept = null;
            this.infoCustomerToDoNotes.SecFieldName = null;
            this.infoCustomerToDoNotes.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoCustomerToDoNotes.SelectPaging = false;
            this.infoCustomerToDoNotes.SelectTop = 0;
            this.infoCustomerToDoNotes.SiteControl = false;
            this.infoCustomerToDoNotes.SiteFieldName = null;
            this.infoCustomerToDoNotes.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoConnection2
            // 
            this.infoConnection2.EEPAlias = "JBADMIN";
            // 
            // updateCustomerToDoNotes
            // 
            this.updateCustomerToDoNotes.AutoTrans = true;
            this.updateCustomerToDoNotes.ExceptJoin = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "AutoKey";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CustNO";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "Notes";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "NextCallDate";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "NextCallTime";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "NotesCreateDate";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "UpdateBy";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "UpateDate";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            this.updateCustomerToDoNotes.FieldAttrs.Add(fieldAttr11);
            this.updateCustomerToDoNotes.FieldAttrs.Add(fieldAttr12);
            this.updateCustomerToDoNotes.FieldAttrs.Add(fieldAttr13);
            this.updateCustomerToDoNotes.FieldAttrs.Add(fieldAttr14);
            this.updateCustomerToDoNotes.FieldAttrs.Add(fieldAttr15);
            this.updateCustomerToDoNotes.FieldAttrs.Add(fieldAttr16);
            this.updateCustomerToDoNotes.FieldAttrs.Add(fieldAttr17);
            this.updateCustomerToDoNotes.FieldAttrs.Add(fieldAttr18);
            this.updateCustomerToDoNotes.LogInfo = null;
            this.updateCustomerToDoNotes.Name = "updateCustomerToDoNotes";
            this.updateCustomerToDoNotes.RowAffectsCheck = true;
            this.updateCustomerToDoNotes.SelectCmd = this.infoCustomerToDoNotes;
            this.updateCustomerToDoNotes.SelectCmdForUpdate = null;
            this.updateCustomerToDoNotes.SendSQLCmd = true;
            this.updateCustomerToDoNotes.ServerModify = true;
            this.updateCustomerToDoNotes.ServerModifyGetMax = false;
            this.updateCustomerToDoNotes.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateCustomerToDoNotes.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateCustomerToDoNotes.UseTranscationScope = false;
            this.updateCustomerToDoNotes.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoNextCallTime
            // 
            this.infoNextCallTime.CacheConnection = false;
            this.infoNextCallTime.CommandText = "select  distinct Isnull(NextCallTime,\'\') as NextCallTime\r\nfrom ERPCustomerToDoNot" +
    "es\r\norder by NextCallTime";
            this.infoNextCallTime.CommandTimeout = 30;
            this.infoNextCallTime.CommandType = System.Data.CommandType.Text;
            this.infoNextCallTime.DynamicTableName = false;
            this.infoNextCallTime.EEPAlias = "JBADMIN";
            this.infoNextCallTime.EncodingAfter = null;
            this.infoNextCallTime.EncodingBefore = "Windows-1252";
            this.infoNextCallTime.EncodingConvert = null;
            this.infoNextCallTime.InfoConnection = this.infoConnection2;
            this.infoNextCallTime.MultiSetWhere = false;
            this.infoNextCallTime.Name = "infoNextCallTime";
            this.infoNextCallTime.NotificationAutoEnlist = false;
            this.infoNextCallTime.SecExcept = null;
            this.infoNextCallTime.SecFieldName = null;
            this.infoNextCallTime.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoNextCallTime.SelectPaging = false;
            this.infoNextCallTime.SelectTop = 0;
            this.infoNextCallTime.SiteControl = false;
            this.infoNextCallTime.SiteFieldName = null;
            this.infoNextCallTime.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoPostSource
            // 
            this.infoPostSource.CacheConnection = false;
            this.infoPostSource.CommandText = "select  ID,SourceName\r\nfrom ERPPostSource";
            this.infoPostSource.CommandTimeout = 30;
            this.infoPostSource.CommandType = System.Data.CommandType.Text;
            this.infoPostSource.DynamicTableName = false;
            this.infoPostSource.EEPAlias = "JBADMIN";
            this.infoPostSource.EncodingAfter = null;
            this.infoPostSource.EncodingBefore = "Windows-1252";
            this.infoPostSource.EncodingConvert = null;
            this.infoPostSource.InfoConnection = this.infoConnection2;
            this.infoPostSource.MultiSetWhere = false;
            this.infoPostSource.Name = "infoPostSource";
            this.infoPostSource.NotificationAutoEnlist = false;
            this.infoPostSource.SecExcept = null;
            this.infoPostSource.SecFieldName = null;
            this.infoPostSource.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoPostSource.SelectPaging = false;
            this.infoPostSource.SelectTop = 0;
            this.infoPostSource.SiteControl = false;
            this.infoPostSource.SiteFieldName = null;
            this.infoPostSource.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoPostType
            // 
            this.infoPostType.CacheConnection = false;
            this.infoPostType.CommandText = "select  ListID,ListContent\r\nfrom ERPReferenceTable\r\nwhere ListCategory=\'PostType\'" +
    "";
            this.infoPostType.CommandTimeout = 30;
            this.infoPostType.CommandType = System.Data.CommandType.Text;
            this.infoPostType.DynamicTableName = false;
            this.infoPostType.EEPAlias = "JBADMIN";
            this.infoPostType.EncodingAfter = null;
            this.infoPostType.EncodingBefore = "Windows-1252";
            this.infoPostType.EncodingConvert = null;
            this.infoPostType.InfoConnection = this.infoConnection2;
            this.infoPostType.MultiSetWhere = false;
            this.infoPostType.Name = "infoPostType";
            this.infoPostType.NotificationAutoEnlist = false;
            this.infoPostType.SecExcept = null;
            this.infoPostType.SecFieldName = null;
            this.infoPostType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoPostType.SelectPaging = false;
            this.infoPostType.SelectTop = 0;
            this.infoPostType.SiteControl = false;
            this.infoPostType.SiteFieldName = null;
            this.infoPostType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoCustomerToDoNotesList
            // 
            this.infoCustomerToDoNotesList.CacheConnection = false;
            this.infoCustomerToDoNotesList.CommandText = resources.GetString("infoCustomerToDoNotesList.CommandText");
            this.infoCustomerToDoNotesList.CommandTimeout = 30;
            this.infoCustomerToDoNotesList.CommandType = System.Data.CommandType.Text;
            this.infoCustomerToDoNotesList.DynamicTableName = false;
            this.infoCustomerToDoNotesList.EEPAlias = "JBADMIN";
            this.infoCustomerToDoNotesList.EncodingAfter = null;
            this.infoCustomerToDoNotesList.EncodingBefore = "Windows-1252";
            this.infoCustomerToDoNotesList.EncodingConvert = null;
            this.infoCustomerToDoNotesList.InfoConnection = this.infoConnection2;
            keyItem5.KeyName = "AutoKey";
            this.infoCustomerToDoNotesList.KeyFields.Add(keyItem5);
            this.infoCustomerToDoNotesList.MultiSetWhere = false;
            this.infoCustomerToDoNotesList.Name = "infoCustomerToDoNotesList";
            this.infoCustomerToDoNotesList.NotificationAutoEnlist = false;
            this.infoCustomerToDoNotesList.SecExcept = null;
            this.infoCustomerToDoNotesList.SecFieldName = null;
            this.infoCustomerToDoNotesList.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoCustomerToDoNotesList.SelectPaging = false;
            this.infoCustomerToDoNotesList.SelectTop = 0;
            this.infoCustomerToDoNotesList.SiteControl = false;
            this.infoCustomerToDoNotesList.SiteFieldName = null;
            this.infoCustomerToDoNotesList.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoTempToDoNotes
            // 
            this.infoTempToDoNotes.CacheConnection = false;
            this.infoTempToDoNotes.CommandText = resources.GetString("infoTempToDoNotes.CommandText");
            this.infoTempToDoNotes.CommandTimeout = 30;
            this.infoTempToDoNotes.CommandType = System.Data.CommandType.Text;
            this.infoTempToDoNotes.DynamicTableName = false;
            this.infoTempToDoNotes.EEPAlias = "JBADMIN";
            this.infoTempToDoNotes.EncodingAfter = null;
            this.infoTempToDoNotes.EncodingBefore = "Windows-1252";
            this.infoTempToDoNotes.EncodingConvert = null;
            this.infoTempToDoNotes.InfoConnection = this.infoConnection2;
            keyItem6.KeyName = "CustNO";
            this.infoTempToDoNotes.KeyFields.Add(keyItem6);
            this.infoTempToDoNotes.MultiSetWhere = false;
            this.infoTempToDoNotes.Name = "infoTempToDoNotes";
            this.infoTempToDoNotes.NotificationAutoEnlist = false;
            this.infoTempToDoNotes.SecExcept = null;
            this.infoTempToDoNotes.SecFieldName = null;
            this.infoTempToDoNotes.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoTempToDoNotes.SelectPaging = false;
            this.infoTempToDoNotes.SelectTop = 0;
            this.infoTempToDoNotes.SiteControl = false;
            this.infoTempToDoNotes.SiteFieldName = null;
            this.infoTempToDoNotes.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // updateTempToDoNotes
            // 
            this.updateTempToDoNotes.AutoTrans = true;
            this.updateTempToDoNotes.ExceptJoin = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "AutoKey";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "CustNO";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "Notes";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "NextCallDate";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "NextCallTime";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "NotesCreateDate";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "UpdateBy";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "UpateDate";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "CustShortName";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "CustName";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr19);
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr20);
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr21);
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr22);
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr23);
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr24);
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr25);
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr26);
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr27);
            this.updateTempToDoNotes.FieldAttrs.Add(fieldAttr28);
            this.updateTempToDoNotes.LogInfo = null;
            this.updateTempToDoNotes.Name = "updateTempToDoNotes";
            this.updateTempToDoNotes.RowAffectsCheck = true;
            this.updateTempToDoNotes.SelectCmd = this.infoTempToDoNotes;
            this.updateTempToDoNotes.SelectCmdForUpdate = null;
            this.updateTempToDoNotes.SendSQLCmd = true;
            this.updateTempToDoNotes.ServerModify = true;
            this.updateTempToDoNotes.ServerModifyGetMax = false;
            this.updateTempToDoNotes.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateTempToDoNotes.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateTempToDoNotes.UseTranscationScope = false;
            this.updateTempToDoNotes.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoCustomerInfo
            // 
            this.infoCustomerInfo.CacheConnection = false;
            this.infoCustomerInfo.CommandText = "SELECT   *\r\n FROM dbo.ERPCustomers as C \t";
            this.infoCustomerInfo.CommandTimeout = 30;
            this.infoCustomerInfo.CommandType = System.Data.CommandType.Text;
            this.infoCustomerInfo.DynamicTableName = false;
            this.infoCustomerInfo.EEPAlias = "JBADMIN";
            this.infoCustomerInfo.EncodingAfter = null;
            this.infoCustomerInfo.EncodingBefore = "Windows-1252";
            this.infoCustomerInfo.EncodingConvert = null;
            this.infoCustomerInfo.InfoConnection = this.infoConnection2;
            keyItem7.KeyName = "CustNO";
            this.infoCustomerInfo.KeyFields.Add(keyItem7);
            this.infoCustomerInfo.MultiSetWhere = false;
            this.infoCustomerInfo.Name = "infoCustomerInfo";
            this.infoCustomerInfo.NotificationAutoEnlist = false;
            this.infoCustomerInfo.SecExcept = null;
            this.infoCustomerInfo.SecFieldName = null;
            this.infoCustomerInfo.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoCustomerInfo.SelectPaging = false;
            this.infoCustomerInfo.SelectTop = 0;
            this.infoCustomerInfo.SiteControl = false;
            this.infoCustomerInfo.SiteFieldName = null;
            this.infoCustomerInfo.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // updateCustomerInfo
            // 
            this.updateCustomerInfo.AutoTrans = true;
            this.updateCustomerInfo.ExceptJoin = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "AutoKey";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "CustNO";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "Notes";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "NextCallDate";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "NextCallTime";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "NotesCreateDate";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "UpdateBy";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "UpateDate";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "CustShortName";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "CustName";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr29);
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr30);
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr31);
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr32);
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr33);
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr34);
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr35);
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr36);
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr37);
            this.updateCustomerInfo.FieldAttrs.Add(fieldAttr38);
            this.updateCustomerInfo.LogInfo = null;
            this.updateCustomerInfo.Name = "updateCustomerInfo";
            this.updateCustomerInfo.RowAffectsCheck = true;
            this.updateCustomerInfo.SelectCmd = this.infoCustomerInfo;
            this.updateCustomerInfo.SelectCmdForUpdate = null;
            this.updateCustomerInfo.SendSQLCmd = true;
            this.updateCustomerInfo.ServerModify = true;
            this.updateCustomerInfo.ServerModifyGetMax = false;
            this.updateCustomerInfo.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateCustomerInfo.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateCustomerInfo.UseTranscationScope = false;
            this.updateCustomerInfo.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoERPOffice
            // 
            this.infoERPOffice.CacheConnection = false;
            this.infoERPOffice.CommandText = "select  *\r\nfrom ERPOffice";
            this.infoERPOffice.CommandTimeout = 30;
            this.infoERPOffice.CommandType = System.Data.CommandType.Text;
            this.infoERPOffice.DynamicTableName = false;
            this.infoERPOffice.EEPAlias = "";
            this.infoERPOffice.EncodingAfter = null;
            this.infoERPOffice.EncodingBefore = "Windows-1252";
            this.infoERPOffice.EncodingConvert = null;
            this.infoERPOffice.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "iAutoKey";
            this.infoERPOffice.KeyFields.Add(keyItem8);
            this.infoERPOffice.MultiSetWhere = false;
            this.infoERPOffice.Name = "infoERPOffice";
            this.infoERPOffice.NotificationAutoEnlist = false;
            this.infoERPOffice.SecExcept = null;
            this.infoERPOffice.SecFieldName = null;
            this.infoERPOffice.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPOffice.SelectPaging = false;
            this.infoERPOffice.SelectTop = 0;
            this.infoERPOffice.SiteControl = false;
            this.infoERPOffice.SiteFieldName = null;
            this.infoERPOffice.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoERPJobWeekend
            // 
            this.infoERPJobWeekend.CacheConnection = false;
            this.infoERPJobWeekend.CommandText = "select  *\r\nfrom ERPJobWeekend";
            this.infoERPJobWeekend.CommandTimeout = 30;
            this.infoERPJobWeekend.CommandType = System.Data.CommandType.Text;
            this.infoERPJobWeekend.DynamicTableName = false;
            this.infoERPJobWeekend.EEPAlias = "";
            this.infoERPJobWeekend.EncodingAfter = null;
            this.infoERPJobWeekend.EncodingBefore = "Windows-1252";
            this.infoERPJobWeekend.EncodingConvert = null;
            this.infoERPJobWeekend.InfoConnection = this.InfoConnection1;
            keyItem9.KeyName = "iAutoKey";
            this.infoERPJobWeekend.KeyFields.Add(keyItem9);
            this.infoERPJobWeekend.MultiSetWhere = false;
            this.infoERPJobWeekend.Name = "infoERPJobWeekend";
            this.infoERPJobWeekend.NotificationAutoEnlist = false;
            this.infoERPJobWeekend.SecExcept = null;
            this.infoERPJobWeekend.SecFieldName = null;
            this.infoERPJobWeekend.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPJobWeekend.SelectPaging = false;
            this.infoERPJobWeekend.SelectTop = 0;
            this.infoERPJobWeekend.SiteControl = false;
            this.infoERPJobWeekend.SiteFieldName = null;
            this.infoERPJobWeekend.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoForeignDorm
            // 
            this.infoForeignDorm.CacheConnection = false;
            this.infoForeignDorm.CommandText = "select  distinct ForeignDorm\r\nfrom ERPCustomers\r\nwhere Isnull(ForeignDorm,\'\')!=\'\'" +
    "\r\norder by ForeignDorm";
            this.infoForeignDorm.CommandTimeout = 30;
            this.infoForeignDorm.CommandType = System.Data.CommandType.Text;
            this.infoForeignDorm.DynamicTableName = false;
            this.infoForeignDorm.EEPAlias = "JBADMIN";
            this.infoForeignDorm.EncodingAfter = null;
            this.infoForeignDorm.EncodingBefore = "Windows-1252";
            this.infoForeignDorm.EncodingConvert = null;
            this.infoForeignDorm.InfoConnection = this.infoConnection2;
            this.infoForeignDorm.MultiSetWhere = false;
            this.infoForeignDorm.Name = "infoForeignDorm";
            this.infoForeignDorm.NotificationAutoEnlist = false;
            this.infoForeignDorm.SecExcept = null;
            this.infoForeignDorm.SecFieldName = null;
            this.infoForeignDorm.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoForeignDorm.SelectPaging = false;
            this.infoForeignDorm.SelectTop = 0;
            this.infoForeignDorm.SiteControl = false;
            this.infoForeignDorm.SiteFieldName = null;
            this.infoForeignDorm.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoERPCustNationality
            // 
            this.infoERPCustNationality.CacheConnection = false;
            this.infoERPCustNationality.CommandText = "select * from ERPCustNationality";
            this.infoERPCustNationality.CommandTimeout = 30;
            this.infoERPCustNationality.CommandType = System.Data.CommandType.Text;
            this.infoERPCustNationality.DynamicTableName = false;
            this.infoERPCustNationality.EEPAlias = null;
            this.infoERPCustNationality.EncodingAfter = null;
            this.infoERPCustNationality.EncodingBefore = "Windows-1252";
            this.infoERPCustNationality.EncodingConvert = null;
            this.infoERPCustNationality.InfoConnection = this.InfoConnection1;
            keyItem10.KeyName = "AutoKey";
            this.infoERPCustNationality.KeyFields.Add(keyItem10);
            this.infoERPCustNationality.MultiSetWhere = false;
            this.infoERPCustNationality.Name = "infoERPCustNationality";
            this.infoERPCustNationality.NotificationAutoEnlist = false;
            this.infoERPCustNationality.SecExcept = null;
            this.infoERPCustNationality.SecFieldName = null;
            this.infoERPCustNationality.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPCustNationality.SelectPaging = false;
            this.infoERPCustNationality.SelectTop = 0;
            this.infoERPCustNationality.SiteControl = false;
            this.infoERPCustNationality.SiteFieldName = null;
            this.infoERPCustNationality.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoERPNationality
            // 
            this.infoERPNationality.CacheConnection = false;
            this.infoERPNationality.CommandText = "select * from ERPNationality";
            this.infoERPNationality.CommandTimeout = 30;
            this.infoERPNationality.CommandType = System.Data.CommandType.Text;
            this.infoERPNationality.DynamicTableName = false;
            this.infoERPNationality.EEPAlias = null;
            this.infoERPNationality.EncodingAfter = null;
            this.infoERPNationality.EncodingBefore = "Windows-1252";
            this.infoERPNationality.EncodingConvert = null;
            this.infoERPNationality.InfoConnection = this.InfoConnection1;
            keyItem11.KeyName = "NationalityNo";
            this.infoERPNationality.KeyFields.Add(keyItem11);
            this.infoERPNationality.MultiSetWhere = false;
            this.infoERPNationality.Name = "infoERPNationality";
            this.infoERPNationality.NotificationAutoEnlist = false;
            this.infoERPNationality.SecExcept = null;
            this.infoERPNationality.SecFieldName = null;
            this.infoERPNationality.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoERPNationality.SelectPaging = false;
            this.infoERPNationality.SelectTop = 0;
            this.infoERPNationality.SiteControl = false;
            this.infoERPNationality.SiteFieldName = null;
            this.infoERPNationality.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // updateCustNationality
            // 
            this.updateCustNationality.AutoTrans = true;
            this.updateCustNationality.ExceptJoin = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "CustNO";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "NationalityNo";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "Female";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "Male";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "UpdateBy";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "UpateDate";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "AutoKey";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            this.updateCustNationality.FieldAttrs.Add(fieldAttr39);
            this.updateCustNationality.FieldAttrs.Add(fieldAttr40);
            this.updateCustNationality.FieldAttrs.Add(fieldAttr41);
            this.updateCustNationality.FieldAttrs.Add(fieldAttr42);
            this.updateCustNationality.FieldAttrs.Add(fieldAttr43);
            this.updateCustNationality.FieldAttrs.Add(fieldAttr44);
            this.updateCustNationality.FieldAttrs.Add(fieldAttr45);
            this.updateCustNationality.LogInfo = null;
            this.updateCustNationality.Name = "updateCustNationality";
            this.updateCustNationality.RowAffectsCheck = true;
            this.updateCustNationality.SelectCmd = this.infoERPCustNationality;
            this.updateCustNationality.SelectCmdForUpdate = null;
            this.updateCustNationality.SendSQLCmd = true;
            this.updateCustNationality.ServerModify = true;
            this.updateCustNationality.ServerModifyGetMax = false;
            this.updateCustNationality.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateCustNationality.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateCustNationality.UseTranscationScope = false;
            this.updateCustNationality.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoImportantRecord
            // 
            this.infoImportantRecord.CacheConnection = false;
            this.infoImportantRecord.CommandText = "select * from ERPCustImportantRecord\r\norder by CreateDate desc";
            this.infoImportantRecord.CommandTimeout = 30;
            this.infoImportantRecord.CommandType = System.Data.CommandType.Text;
            this.infoImportantRecord.DynamicTableName = false;
            this.infoImportantRecord.EEPAlias = null;
            this.infoImportantRecord.EncodingAfter = null;
            this.infoImportantRecord.EncodingBefore = "Windows-1252";
            this.infoImportantRecord.EncodingConvert = null;
            this.infoImportantRecord.InfoConnection = this.InfoConnection1;
            keyItem12.KeyName = "AutoKey";
            this.infoImportantRecord.KeyFields.Add(keyItem12);
            this.infoImportantRecord.MultiSetWhere = false;
            this.infoImportantRecord.Name = "infoImportantRecord";
            this.infoImportantRecord.NotificationAutoEnlist = false;
            this.infoImportantRecord.SecExcept = null;
            this.infoImportantRecord.SecFieldName = null;
            this.infoImportantRecord.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoImportantRecord.SelectPaging = false;
            this.infoImportantRecord.SelectTop = 0;
            this.infoImportantRecord.SiteControl = false;
            this.infoImportantRecord.SiteFieldName = null;
            this.infoImportantRecord.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // updateImportantRecord
            // 
            this.updateImportantRecord.AutoTrans = true;
            this.updateImportantRecord.ExceptJoin = false;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "CustNO";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "Description";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "UpdateBy";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "UpateDate";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "AutoKey";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            this.updateImportantRecord.FieldAttrs.Add(fieldAttr46);
            this.updateImportantRecord.FieldAttrs.Add(fieldAttr47);
            this.updateImportantRecord.FieldAttrs.Add(fieldAttr48);
            this.updateImportantRecord.FieldAttrs.Add(fieldAttr49);
            this.updateImportantRecord.FieldAttrs.Add(fieldAttr50);
            this.updateImportantRecord.LogInfo = null;
            this.updateImportantRecord.Name = "updateImportantRecord";
            this.updateImportantRecord.RowAffectsCheck = true;
            this.updateImportantRecord.SelectCmd = this.infoImportantRecord;
            this.updateImportantRecord.SelectCmdForUpdate = null;
            this.updateImportantRecord.SendSQLCmd = true;
            this.updateImportantRecord.ServerModify = true;
            this.updateImportantRecord.ServerModifyGetMax = false;
            this.updateImportantRecord.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateImportantRecord.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateImportantRecord.UseTranscationScope = false;
            this.updateImportantRecord.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // updateContactRecord
            // 
            this.updateContactRecord.AutoTrans = true;
            this.updateContactRecord.ExceptJoin = false;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "CustNO";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "Description";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "UpdateBy";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "UpateDate";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "AutoKey";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            this.updateContactRecord.FieldAttrs.Add(fieldAttr51);
            this.updateContactRecord.FieldAttrs.Add(fieldAttr52);
            this.updateContactRecord.FieldAttrs.Add(fieldAttr53);
            this.updateContactRecord.FieldAttrs.Add(fieldAttr54);
            this.updateContactRecord.FieldAttrs.Add(fieldAttr55);
            this.updateContactRecord.LogInfo = null;
            this.updateContactRecord.Name = "updateContactRecord";
            this.updateContactRecord.RowAffectsCheck = true;
            this.updateContactRecord.SelectCmd = this.infoContactRecord;
            this.updateContactRecord.SelectCmdForUpdate = null;
            this.updateContactRecord.SendSQLCmd = true;
            this.updateContactRecord.ServerModify = true;
            this.updateContactRecord.ServerModifyGetMax = false;
            this.updateContactRecord.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateContactRecord.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateContactRecord.UseTranscationScope = false;
            this.updateContactRecord.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoContactRecord
            // 
            this.infoContactRecord.CacheConnection = false;
            this.infoContactRecord.CommandText = "select * from ERPCustContactRecord\r\norder by CreateDate desc";
            this.infoContactRecord.CommandTimeout = 30;
            this.infoContactRecord.CommandType = System.Data.CommandType.Text;
            this.infoContactRecord.DynamicTableName = false;
            this.infoContactRecord.EEPAlias = null;
            this.infoContactRecord.EncodingAfter = null;
            this.infoContactRecord.EncodingBefore = "Windows-1252";
            this.infoContactRecord.EncodingConvert = null;
            this.infoContactRecord.InfoConnection = this.InfoConnection1;
            keyItem13.KeyName = "AutoKey";
            this.infoContactRecord.KeyFields.Add(keyItem13);
            this.infoContactRecord.MultiSetWhere = false;
            this.infoContactRecord.Name = "infoContactRecord";
            this.infoContactRecord.NotificationAutoEnlist = false;
            this.infoContactRecord.SecExcept = null;
            this.infoContactRecord.SecFieldName = null;
            this.infoContactRecord.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoContactRecord.SelectPaging = false;
            this.infoContactRecord.SelectTop = 0;
            this.infoContactRecord.SiteControl = false;
            this.infoContactRecord.SiteFieldName = null;
            this.infoContactRecord.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ERPCustomers
            // 
            this.ERPCustomers.CacheConnection = false;
            this.ERPCustomers.CommandText = resources.GetString("ERPCustomers.CommandText");
            this.ERPCustomers.CommandTimeout = 30;
            this.ERPCustomers.CommandType = System.Data.CommandType.Text;
            this.ERPCustomers.DynamicTableName = false;
            this.ERPCustomers.EEPAlias = "JBADMIN";
            this.ERPCustomers.EncodingAfter = null;
            this.ERPCustomers.EncodingBefore = "Windows-1252";
            this.ERPCustomers.EncodingConvert = null;
            this.ERPCustomers.InfoConnection = this.InfoConnection1;
            keyItem14.KeyName = "CustNO";
            this.ERPCustomers.KeyFields.Add(keyItem14);
            this.ERPCustomers.MultiSetWhere = false;
            this.ERPCustomers.Name = "ERPCustomers";
            this.ERPCustomers.NotificationAutoEnlist = false;
            this.ERPCustomers.SecExcept = null;
            this.ERPCustomers.SecFieldName = null;
            this.ERPCustomers.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ERPCustomers.SelectPaging = false;
            this.ERPCustomers.SelectTop = 0;
            this.ERPCustomers.SiteControl = false;
            this.ERPCustomers.SiteFieldName = null;
            this.ERPCustomers.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucERPCustomers
            // 
            this.ucERPCustomers.AutoTrans = true;
            this.ucERPCustomers.ExceptJoin = false;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "CustNO";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "CustName";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "CustShortName";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "SalesID";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "BossName";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "TaxNO";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "IndustryTypeID";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = null;
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "CustTelNO";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr63.DefaultValue = null;
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "CustCityNO";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr64.DefaultValue = null;
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "CustRegion";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = null;
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "CustPost";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = null;
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "CustAddr";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr67.DefaultValue = null;
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "CustFaxNO";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr68.DefaultValue = null;
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            fieldAttr69.CheckNull = false;
            fieldAttr69.DataField = "CustDeptID";
            fieldAttr69.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr69.DefaultValue = null;
            fieldAttr69.TrimLength = 0;
            fieldAttr69.UpdateEnable = true;
            fieldAttr69.WhereMode = true;
            fieldAttr70.CheckNull = false;
            fieldAttr70.DataField = "CustDeptName";
            fieldAttr70.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr70.DefaultValue = null;
            fieldAttr70.TrimLength = 0;
            fieldAttr70.UpdateEnable = true;
            fieldAttr70.WhereMode = true;
            fieldAttr71.CheckNull = false;
            fieldAttr71.DataField = "CustAreaID";
            fieldAttr71.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr71.DefaultValue = null;
            fieldAttr71.TrimLength = 0;
            fieldAttr71.UpdateEnable = true;
            fieldAttr71.WhereMode = true;
            fieldAttr72.CheckNull = false;
            fieldAttr72.DataField = "PMID";
            fieldAttr72.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr72.DefaultValue = null;
            fieldAttr72.TrimLength = 0;
            fieldAttr72.UpdateEnable = true;
            fieldAttr72.WhereMode = true;
            fieldAttr73.CheckNull = false;
            fieldAttr73.DataField = "ContactA";
            fieldAttr73.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr73.DefaultValue = null;
            fieldAttr73.TrimLength = 0;
            fieldAttr73.UpdateEnable = true;
            fieldAttr73.WhereMode = true;
            fieldAttr74.CheckNull = false;
            fieldAttr74.DataField = "ContactATel";
            fieldAttr74.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr74.DefaultValue = null;
            fieldAttr74.TrimLength = 0;
            fieldAttr74.UpdateEnable = true;
            fieldAttr74.WhereMode = true;
            fieldAttr75.CheckNull = false;
            fieldAttr75.DataField = "ContactASubTel";
            fieldAttr75.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr75.DefaultValue = null;
            fieldAttr75.TrimLength = 0;
            fieldAttr75.UpdateEnable = true;
            fieldAttr75.WhereMode = true;
            fieldAttr76.CheckNull = false;
            fieldAttr76.DataField = "ContactAMail";
            fieldAttr76.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr76.DefaultValue = null;
            fieldAttr76.TrimLength = 0;
            fieldAttr76.UpdateEnable = true;
            fieldAttr76.WhereMode = true;
            fieldAttr77.CheckNull = false;
            fieldAttr77.DataField = "ContactAJobID";
            fieldAttr77.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr77.DefaultValue = null;
            fieldAttr77.TrimLength = 0;
            fieldAttr77.UpdateEnable = true;
            fieldAttr77.WhereMode = true;
            fieldAttr78.CheckNull = false;
            fieldAttr78.DataField = "ContactAIsMail";
            fieldAttr78.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr78.DefaultValue = null;
            fieldAttr78.TrimLength = 0;
            fieldAttr78.UpdateEnable = true;
            fieldAttr78.WhereMode = true;
            fieldAttr79.CheckNull = false;
            fieldAttr79.DataField = "ContactB";
            fieldAttr79.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr79.DefaultValue = null;
            fieldAttr79.TrimLength = 0;
            fieldAttr79.UpdateEnable = true;
            fieldAttr79.WhereMode = true;
            fieldAttr80.CheckNull = false;
            fieldAttr80.DataField = "ContactBTel";
            fieldAttr80.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr80.DefaultValue = null;
            fieldAttr80.TrimLength = 0;
            fieldAttr80.UpdateEnable = true;
            fieldAttr80.WhereMode = true;
            fieldAttr81.CheckNull = false;
            fieldAttr81.DataField = "ContactBSubTel";
            fieldAttr81.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr81.DefaultValue = null;
            fieldAttr81.TrimLength = 0;
            fieldAttr81.UpdateEnable = true;
            fieldAttr81.WhereMode = true;
            fieldAttr82.CheckNull = false;
            fieldAttr82.DataField = "ContactBMail";
            fieldAttr82.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr82.DefaultValue = null;
            fieldAttr82.TrimLength = 0;
            fieldAttr82.UpdateEnable = true;
            fieldAttr82.WhereMode = true;
            fieldAttr83.CheckNull = false;
            fieldAttr83.DataField = "ContactBJobID";
            fieldAttr83.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr83.DefaultValue = null;
            fieldAttr83.TrimLength = 0;
            fieldAttr83.UpdateEnable = true;
            fieldAttr83.WhereMode = true;
            fieldAttr84.CheckNull = false;
            fieldAttr84.DataField = "ContactBIsMail";
            fieldAttr84.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr84.DefaultValue = null;
            fieldAttr84.TrimLength = 0;
            fieldAttr84.UpdateEnable = true;
            fieldAttr84.WhereMode = true;
            fieldAttr85.CheckNull = false;
            fieldAttr85.DataField = "BalanceDay";
            fieldAttr85.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr85.DefaultValue = null;
            fieldAttr85.TrimLength = 0;
            fieldAttr85.UpdateEnable = true;
            fieldAttr85.WhereMode = true;
            fieldAttr86.CheckNull = false;
            fieldAttr86.DataField = "CustNotes";
            fieldAttr86.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr86.DefaultValue = null;
            fieldAttr86.TrimLength = 0;
            fieldAttr86.UpdateEnable = true;
            fieldAttr86.WhereMode = true;
            fieldAttr87.CheckNull = false;
            fieldAttr87.DataField = "RecallDate";
            fieldAttr87.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr87.DefaultValue = null;
            fieldAttr87.TrimLength = 0;
            fieldAttr87.UpdateEnable = true;
            fieldAttr87.WhereMode = true;
            fieldAttr88.CheckNull = false;
            fieldAttr88.DataField = "IsPutInvoice";
            fieldAttr88.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr88.DefaultValue = null;
            fieldAttr88.TrimLength = 0;
            fieldAttr88.UpdateEnable = true;
            fieldAttr88.WhereMode = true;
            fieldAttr89.CheckNull = false;
            fieldAttr89.DataField = "IsPutPaperInvoice";
            fieldAttr89.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr89.DefaultValue = null;
            fieldAttr89.TrimLength = 0;
            fieldAttr89.UpdateEnable = true;
            fieldAttr89.WhereMode = true;
            fieldAttr90.CheckNull = false;
            fieldAttr90.DataField = "CreateBy";
            fieldAttr90.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr90.DefaultValue = "_username";
            fieldAttr90.TrimLength = 0;
            fieldAttr90.UpdateEnable = true;
            fieldAttr90.WhereMode = true;
            fieldAttr91.CheckNull = false;
            fieldAttr91.DataField = "CreateDate";
            fieldAttr91.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr91.DefaultValue = null;
            fieldAttr91.TrimLength = 0;
            fieldAttr91.UpdateEnable = true;
            fieldAttr91.WhereMode = true;
            fieldAttr92.CheckNull = false;
            fieldAttr92.DataField = "LastUpdateBy";
            fieldAttr92.DefaultMode = Srvtools.DefaultModeType.InsertAndUpdate;
            fieldAttr92.DefaultValue = "_username";
            fieldAttr92.TrimLength = 0;
            fieldAttr92.UpdateEnable = true;
            fieldAttr92.WhereMode = true;
            fieldAttr93.CheckNull = false;
            fieldAttr93.DataField = "LastUpdateDate";
            fieldAttr93.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr93.DefaultValue = null;
            fieldAttr93.TrimLength = 0;
            fieldAttr93.UpdateEnable = true;
            fieldAttr93.WhereMode = true;
            fieldAttr94.CheckNull = false;
            fieldAttr94.DataField = "LatelyDayD";
            fieldAttr94.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr94.DefaultValue = null;
            fieldAttr94.TrimLength = 0;
            fieldAttr94.UpdateEnable = true;
            fieldAttr94.WhereMode = true;
            fieldAttr95.CheckNull = false;
            fieldAttr95.DataField = "LatelyDayP";
            fieldAttr95.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr95.DefaultValue = null;
            fieldAttr95.TrimLength = 0;
            fieldAttr95.UpdateEnable = true;
            fieldAttr95.WhereMode = true;
            fieldAttr96.CheckNull = false;
            fieldAttr96.DataField = "LatelyDayW";
            fieldAttr96.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr96.DefaultValue = null;
            fieldAttr96.TrimLength = 0;
            fieldAttr96.UpdateEnable = true;
            fieldAttr96.WhereMode = true;
            fieldAttr97.CheckNull = false;
            fieldAttr97.DataField = "LatelyDayN";
            fieldAttr97.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr97.DefaultValue = null;
            fieldAttr97.TrimLength = 0;
            fieldAttr97.UpdateEnable = true;
            fieldAttr97.WhereMode = true;
            fieldAttr98.CheckNull = false;
            fieldAttr98.DataField = "DealNotesP";
            fieldAttr98.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr98.DefaultValue = null;
            fieldAttr98.TrimLength = 0;
            fieldAttr98.UpdateEnable = true;
            fieldAttr98.WhereMode = true;
            fieldAttr99.CheckNull = false;
            fieldAttr99.DataField = "DealNotesW";
            fieldAttr99.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr99.DefaultValue = null;
            fieldAttr99.TrimLength = 0;
            fieldAttr99.UpdateEnable = true;
            fieldAttr99.WhereMode = true;
            fieldAttr100.CheckNull = false;
            fieldAttr100.DataField = "DealNotesN";
            fieldAttr100.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr100.DefaultValue = null;
            fieldAttr100.TrimLength = 0;
            fieldAttr100.UpdateEnable = true;
            fieldAttr100.WhereMode = true;
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr56);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr57);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr58);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr59);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr60);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr61);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr62);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr63);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr64);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr65);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr66);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr67);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr68);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr69);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr70);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr71);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr72);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr73);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr74);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr75);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr76);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr77);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr78);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr79);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr80);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr81);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr82);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr83);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr84);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr85);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr86);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr87);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr88);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr89);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr90);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr91);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr92);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr93);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr94);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr95);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr96);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr97);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr98);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr99);
            this.ucERPCustomers.FieldAttrs.Add(fieldAttr100);
            this.ucERPCustomers.LogInfo = null;
            this.ucERPCustomers.Name = "ucERPCustomers";
            this.ucERPCustomers.RowAffectsCheck = false;
            this.ucERPCustomers.SelectCmd = this.ERPCustomers;
            this.ucERPCustomers.SelectCmdForUpdate = null;
            this.ucERPCustomers.SendSQLCmd = true;
            this.ucERPCustomers.ServerModify = true;
            this.ucERPCustomers.ServerModifyGetMax = false;
            this.ucERPCustomers.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucERPCustomers.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucERPCustomers.UseTranscationScope = false;
            this.ucERPCustomers.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucERPCustomers.AfterInsert += new Srvtools.UpdateComponentAfterInsertEventHandler(this.ucERPCustomers_AfterInsert);
            this.ucERPCustomers.AfterModify += new Srvtools.UpdateComponentAfterModifyEventHandler(this.ucERPCustomers_AfterModify);
            // 
            // infoInvoiceType
            // 
            this.infoInvoiceType.CacheConnection = false;
            this.infoInvoiceType.CommandText = "select InvoiceTypeID,InvoiceTypeName from InvoiceType where InvoiceTypeID in(\'97\'" +
    ",\'98\',\'99\')";
            this.infoInvoiceType.CommandTimeout = 30;
            this.infoInvoiceType.CommandType = System.Data.CommandType.Text;
            this.infoInvoiceType.DynamicTableName = false;
            this.infoInvoiceType.EEPAlias = "JBERP";
            this.infoInvoiceType.EncodingAfter = null;
            this.infoInvoiceType.EncodingBefore = "Windows-1252";
            this.infoInvoiceType.EncodingConvert = null;
            this.infoInvoiceType.InfoConnection = this.InfoConnection1;
            this.infoInvoiceType.MultiSetWhere = false;
            this.infoInvoiceType.Name = "infoInvoiceType";
            this.infoInvoiceType.NotificationAutoEnlist = false;
            this.infoInvoiceType.SecExcept = null;
            this.infoInvoiceType.SecFieldName = null;
            this.infoInvoiceType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoInvoiceType.SelectPaging = false;
            this.infoInvoiceType.SelectTop = 0;
            this.infoInvoiceType.SiteControl = false;
            this.infoInvoiceType.SiteFieldName = null;
            this.infoInvoiceType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPSalesDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoQuery)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomerToDoNotes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoNextCallTime)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoPostSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoPostType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomerToDoNotesList)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoTempToDoNotes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCustomerInfo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPOffice)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPJobWeekend)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoForeignDorm)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPCustNationality)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoERPNationality)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoImportantRecord)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoContactRecord)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ERPCustomers)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoInvoiceType)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand ERPSalesMaster;
        private Srvtools.UpdateComponent ucERPSalesMaster;
        private Srvtools.InfoCommand ERPSalesDetails;
        private Srvtools.UpdateComponent ucERPSalesDetails;
        private Srvtools.InfoCommand infoQuery;
        private Srvtools.InfoCommand infoCustomerToDoNotes;
        private Srvtools.InfoConnection infoConnection2;
        private Srvtools.UpdateComponent updateCustomerToDoNotes;
        private Srvtools.InfoCommand infoNextCallTime;
        private Srvtools.InfoCommand infoPostSource;
        private Srvtools.InfoCommand infoPostType;
        private Srvtools.InfoCommand infoCustomerToDoNotesList;
        private Srvtools.InfoCommand infoTempToDoNotes;
        private Srvtools.UpdateComponent updateTempToDoNotes;
        private Srvtools.InfoCommand infoCustomerInfo;
        private Srvtools.UpdateComponent updateCustomerInfo;
        private Srvtools.InfoCommand infoERPOffice;
        private Srvtools.InfoCommand infoERPJobWeekend;
        private Srvtools.InfoCommand infoForeignDorm;
        private Srvtools.InfoCommand infoERPCustNationality;
        private Srvtools.InfoCommand infoERPNationality;
        private Srvtools.UpdateComponent updateCustNationality;
        private Srvtools.InfoCommand infoImportantRecord;
        private Srvtools.UpdateComponent updateImportantRecord;
        private Srvtools.UpdateComponent updateContactRecord;
        private Srvtools.InfoCommand infoContactRecord;
        private Srvtools.InfoCommand ERPCustomers;
        private Srvtools.UpdateComponent ucERPCustomers;
        private Srvtools.InfoCommand infoInvoiceType;

    }
}
