namespace sPowerData
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            Srvtools.Service service9 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.PowerMaster = new Srvtools.InfoCommand(this.components);
            this.ucPowerMaster = new Srvtools.UpdateComponent(this.components);
            this.infoDormID = new Srvtools.InfoCommand(this.components);
            this.infoPowerTitle = new Srvtools.InfoCommand(this.components);
            this.infoEmployeeFees = new Srvtools.InfoCommand(this.components);
            this.infoConnection2 = new Srvtools.InfoConnection(this.components);
            this.PowerQuery = new Srvtools.InfoCommand(this.components);
            this.infoCompID = new Srvtools.InfoCommand(this.components);
            this.infoEmp = new Srvtools.InfoCommand(this.components);
            this.infoEmployeeFeesPower = new Srvtools.InfoCommand(this.components);
            this.infoDorm = new Srvtools.InfoCommand(this.components);
            this.ucDorm = new Srvtools.UpdateComponent(this.components);
            this.infoConnection3 = new Srvtools.InfoConnection(this.components);
            this.infoDormJS = new Srvtools.InfoCommand(this.components);
            this.ucDormJS = new Srvtools.UpdateComponent(this.components);
            this.infoAcnoCost = new Srvtools.InfoCommand(this.components);
            this.infoglDorm = new Srvtools.InfoCommand(this.components);
            this.ucglDorm = new Srvtools.UpdateComponent(this.components);
            this.infoBankFees = new Srvtools.InfoCommand(this.components);
            this.infoConnection4 = new Srvtools.InfoConnection(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PowerMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoDormID)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoPowerTitle)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoEmployeeFees)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PowerQuery)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCompID)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoEmp)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoEmployeeFeesPower)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoDorm)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoDormJS)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoAcnoCost)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoglDorm)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoBankFees)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection4)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "getDormIDData";
            service1.NonLogin = false;
            service1.ServiceName = "getDormIDData";
            service2.DelegateName = "getRoomIDData";
            service2.NonLogin = false;
            service2.ServiceName = "getRoomIDData";
            service3.DelegateName = "EmployeeFeesData";
            service3.NonLogin = false;
            service3.ServiceName = "EmployeeFeesData";
            service4.DelegateName = "CheckYearMonth";
            service4.NonLogin = false;
            service4.ServiceName = "CheckYearMonth";
            service5.DelegateName = "GetEmployer";
            service5.NonLogin = false;
            service5.ServiceName = "GetEmployer";
            service6.DelegateName = "DeleteEmpFees";
            service6.NonLogin = false;
            service6.ServiceName = "DeleteEmpFees";
            service7.DelegateName = "GetDorm";
            service7.NonLogin = false;
            service7.ServiceName = "GetDorm";
            service8.DelegateName = "ReportFWCRMDormFee";
            service8.NonLogin = false;
            service8.ServiceName = "ReportFWCRMDormFee";
            service9.DelegateName = "UpdateFeeIsExcel";
            service9.NonLogin = false;
            service9.ServiceName = "UpdateFeeIsExcel";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            this.serviceManager1.ServiceCollection.Add(service9);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // PowerMaster
            // 
            this.PowerMaster.CacheConnection = false;
            this.PowerMaster.CommandText = resources.GetString("PowerMaster.CommandText");
            this.PowerMaster.CommandTimeout = 30;
            this.PowerMaster.CommandType = System.Data.CommandType.Text;
            this.PowerMaster.DynamicTableName = false;
            this.PowerMaster.EEPAlias = null;
            this.PowerMaster.EncodingAfter = null;
            this.PowerMaster.EncodingBefore = "Windows-1252";
            this.PowerMaster.EncodingConvert = null;
            this.PowerMaster.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "PowerID";
            this.PowerMaster.KeyFields.Add(keyItem1);
            this.PowerMaster.MultiSetWhere = false;
            this.PowerMaster.Name = "PowerMaster";
            this.PowerMaster.NotificationAutoEnlist = false;
            this.PowerMaster.SecExcept = null;
            this.PowerMaster.SecFieldName = null;
            this.PowerMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PowerMaster.SelectPaging = false;
            this.PowerMaster.SelectTop = 0;
            this.PowerMaster.SiteControl = false;
            this.PowerMaster.SiteFieldName = null;
            this.PowerMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucPowerMaster
            // 
            this.ucPowerMaster.AutoTrans = true;
            this.ucPowerMaster.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "PowerID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "CompanyID";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "PowerDate";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "DormID";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "PowerQty";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "LastPowerMeter";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "NowPowerMeter";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "PowerAmount";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "DiffAmount";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "CreateBy";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "CreateDate";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "LastUpdateBy";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "LastUpdateDate";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr1);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr2);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr3);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr4);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr5);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr6);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr7);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr8);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr9);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr10);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr11);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr12);
            this.ucPowerMaster.FieldAttrs.Add(fieldAttr13);
            this.ucPowerMaster.LogInfo = null;
            this.ucPowerMaster.Name = "ucPowerMaster";
            this.ucPowerMaster.RowAffectsCheck = true;
            this.ucPowerMaster.SelectCmd = this.PowerMaster;
            this.ucPowerMaster.SelectCmdForUpdate = null;
            this.ucPowerMaster.SendSQLCmd = true;
            this.ucPowerMaster.ServerModify = true;
            this.ucPowerMaster.ServerModifyGetMax = false;
            this.ucPowerMaster.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucPowerMaster.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucPowerMaster.UseTranscationScope = false;
            this.ucPowerMaster.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucPowerMaster.AfterApplied += new System.EventHandler(this.ucPowerMaster_AfterApplied);
            // 
            // infoDormID
            // 
            this.infoDormID.CacheConnection = false;
            this.infoDormID.CommandText = "select distinct v.RoomID,v.RoomName+\' (單價:\'+Cast(v.PowerQty as nvarchar(10))+\')\' " +
    "as RoomNameText\r\nfrom View_EmployeePowerLive v\r\norder by RoomNameText, v.RoomID";
            this.infoDormID.CommandTimeout = 30;
            this.infoDormID.CommandType = System.Data.CommandType.Text;
            this.infoDormID.DynamicTableName = false;
            this.infoDormID.EEPAlias = "";
            this.infoDormID.EncodingAfter = null;
            this.infoDormID.EncodingBefore = "Windows-1252";
            this.infoDormID.EncodingConvert = null;
            this.infoDormID.InfoConnection = this.InfoConnection1;
            this.infoDormID.MultiSetWhere = false;
            this.infoDormID.Name = "infoDormID";
            this.infoDormID.NotificationAutoEnlist = false;
            this.infoDormID.SecExcept = null;
            this.infoDormID.SecFieldName = null;
            this.infoDormID.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoDormID.SelectPaging = false;
            this.infoDormID.SelectTop = 0;
            this.infoDormID.SiteControl = false;
            this.infoDormID.SiteFieldName = null;
            this.infoDormID.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoPowerTitle
            // 
            this.infoPowerTitle.CacheConnection = false;
            this.infoPowerTitle.CommandText = "select 0 as PowerID,\'1900/01/01\' as PowerDate,\'\' as DormID,0 as PowerQty,0 as IsB" +
    "ill,\'\' as YearMonth,0 as CompanyID";
            this.infoPowerTitle.CommandTimeout = 30;
            this.infoPowerTitle.CommandType = System.Data.CommandType.Text;
            this.infoPowerTitle.DynamicTableName = false;
            this.infoPowerTitle.EEPAlias = null;
            this.infoPowerTitle.EncodingAfter = null;
            this.infoPowerTitle.EncodingBefore = "Windows-1252";
            this.infoPowerTitle.EncodingConvert = null;
            this.infoPowerTitle.InfoConnection = this.InfoConnection1;
            this.infoPowerTitle.MultiSetWhere = false;
            this.infoPowerTitle.Name = "infoPowerTitle";
            this.infoPowerTitle.NotificationAutoEnlist = false;
            this.infoPowerTitle.SecExcept = null;
            this.infoPowerTitle.SecFieldName = null;
            this.infoPowerTitle.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoPowerTitle.SelectPaging = false;
            this.infoPowerTitle.SelectTop = 0;
            this.infoPowerTitle.SiteControl = false;
            this.infoPowerTitle.SiteFieldName = null;
            this.infoPowerTitle.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoEmployeeFees
            // 
            this.infoEmployeeFees.CacheConnection = false;
            this.infoEmployeeFees.CommandText = "select * from View_EmployeeFees";
            this.infoEmployeeFees.CommandTimeout = 30;
            this.infoEmployeeFees.CommandType = System.Data.CommandType.Text;
            this.infoEmployeeFees.DynamicTableName = false;
            this.infoEmployeeFees.EEPAlias = "";
            this.infoEmployeeFees.EncodingAfter = null;
            this.infoEmployeeFees.EncodingBefore = "Windows-1252";
            this.infoEmployeeFees.EncodingConvert = null;
            this.infoEmployeeFees.InfoConnection = this.InfoConnection1;
            this.infoEmployeeFees.MultiSetWhere = false;
            this.infoEmployeeFees.Name = "infoEmployeeFees";
            this.infoEmployeeFees.NotificationAutoEnlist = false;
            this.infoEmployeeFees.SecExcept = null;
            this.infoEmployeeFees.SecFieldName = null;
            this.infoEmployeeFees.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoEmployeeFees.SelectPaging = false;
            this.infoEmployeeFees.SelectTop = 0;
            this.infoEmployeeFees.SiteControl = false;
            this.infoEmployeeFees.SiteFieldName = null;
            this.infoEmployeeFees.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoConnection2
            // 
            this.infoConnection2.EEPAlias = "FWCRMJS";
            // 
            // PowerQuery
            // 
            this.PowerQuery.CacheConnection = false;
            this.PowerQuery.CommandText = resources.GetString("PowerQuery.CommandText");
            this.PowerQuery.CommandTimeout = 30;
            this.PowerQuery.CommandType = System.Data.CommandType.Text;
            this.PowerQuery.DynamicTableName = false;
            this.PowerQuery.EEPAlias = null;
            this.PowerQuery.EncodingAfter = null;
            this.PowerQuery.EncodingBefore = "Windows-1252";
            this.PowerQuery.EncodingConvert = null;
            this.PowerQuery.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "PowerID";
            this.PowerQuery.KeyFields.Add(keyItem2);
            this.PowerQuery.MultiSetWhere = false;
            this.PowerQuery.Name = "PowerQuery";
            this.PowerQuery.NotificationAutoEnlist = false;
            this.PowerQuery.SecExcept = null;
            this.PowerQuery.SecFieldName = null;
            this.PowerQuery.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.PowerQuery.SelectPaging = false;
            this.PowerQuery.SelectTop = 0;
            this.PowerQuery.SiteControl = false;
            this.PowerQuery.SiteFieldName = null;
            this.PowerQuery.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoCompID
            // 
            this.infoCompID.CacheConnection = false;
            this.infoCompID.CommandText = "select CompanyID,CompName from FWCRMCompany\r\n";
            this.infoCompID.CommandTimeout = 30;
            this.infoCompID.CommandType = System.Data.CommandType.Text;
            this.infoCompID.DynamicTableName = false;
            this.infoCompID.EEPAlias = "";
            this.infoCompID.EncodingAfter = null;
            this.infoCompID.EncodingBefore = "Windows-1252";
            this.infoCompID.EncodingConvert = null;
            this.infoCompID.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "CompanyID";
            this.infoCompID.KeyFields.Add(keyItem3);
            this.infoCompID.MultiSetWhere = false;
            this.infoCompID.Name = "infoCompID";
            this.infoCompID.NotificationAutoEnlist = false;
            this.infoCompID.SecExcept = null;
            this.infoCompID.SecFieldName = null;
            this.infoCompID.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoCompID.SelectPaging = false;
            this.infoCompID.SelectTop = 0;
            this.infoCompID.SiteControl = false;
            this.infoCompID.SiteFieldName = null;
            this.infoCompID.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoEmp
            // 
            this.infoEmp.CacheConnection = false;
            this.infoEmp.CommandText = "select * from View_EmployeeFees";
            this.infoEmp.CommandTimeout = 30;
            this.infoEmp.CommandType = System.Data.CommandType.Text;
            this.infoEmp.DynamicTableName = false;
            this.infoEmp.EEPAlias = null;
            this.infoEmp.EncodingAfter = null;
            this.infoEmp.EncodingBefore = "Windows-1252";
            this.infoEmp.EncodingConvert = null;
            this.infoEmp.InfoConnection = this.InfoConnection1;
            this.infoEmp.MultiSetWhere = false;
            this.infoEmp.Name = "infoEmp";
            this.infoEmp.NotificationAutoEnlist = false;
            this.infoEmp.SecExcept = null;
            this.infoEmp.SecFieldName = null;
            this.infoEmp.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoEmp.SelectPaging = false;
            this.infoEmp.SelectTop = 0;
            this.infoEmp.SiteControl = false;
            this.infoEmp.SiteFieldName = null;
            this.infoEmp.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoEmployeeFeesPower
            // 
            this.infoEmployeeFeesPower.CacheConnection = false;
            this.infoEmployeeFeesPower.CommandText = "select * from View_EmployeeFeesPower";
            this.infoEmployeeFeesPower.CommandTimeout = 30;
            this.infoEmployeeFeesPower.CommandType = System.Data.CommandType.Text;
            this.infoEmployeeFeesPower.DynamicTableName = false;
            this.infoEmployeeFeesPower.EEPAlias = "";
            this.infoEmployeeFeesPower.EncodingAfter = null;
            this.infoEmployeeFeesPower.EncodingBefore = "Windows-1252";
            this.infoEmployeeFeesPower.EncodingConvert = null;
            this.infoEmployeeFeesPower.InfoConnection = this.InfoConnection1;
            this.infoEmployeeFeesPower.MultiSetWhere = false;
            this.infoEmployeeFeesPower.Name = "infoEmployeeFeesPower";
            this.infoEmployeeFeesPower.NotificationAutoEnlist = false;
            this.infoEmployeeFeesPower.SecExcept = null;
            this.infoEmployeeFeesPower.SecFieldName = null;
            this.infoEmployeeFeesPower.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoEmployeeFeesPower.SelectPaging = false;
            this.infoEmployeeFeesPower.SelectTop = 0;
            this.infoEmployeeFeesPower.SiteControl = false;
            this.infoEmployeeFeesPower.SiteFieldName = null;
            this.infoEmployeeFeesPower.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoDorm
            // 
            this.infoDorm.CacheConnection = false;
            this.infoDorm.CommandText = "select *\r\nfrom ReferenceTable where ListCategory=\'Dorm\' \r\n";
            this.infoDorm.CommandTimeout = 30;
            this.infoDorm.CommandType = System.Data.CommandType.Text;
            this.infoDorm.DynamicTableName = false;
            this.infoDorm.EEPAlias = "FWCRM";
            this.infoDorm.EncodingAfter = null;
            this.infoDorm.EncodingBefore = "Windows-1252";
            this.infoDorm.EncodingConvert = null;
            this.infoDorm.InfoConnection = this.infoConnection2;
            keyItem4.KeyName = "AutoKey";
            this.infoDorm.KeyFields.Add(keyItem4);
            this.infoDorm.MultiSetWhere = false;
            this.infoDorm.Name = "infoDorm";
            this.infoDorm.NotificationAutoEnlist = false;
            this.infoDorm.SecExcept = null;
            this.infoDorm.SecFieldName = null;
            this.infoDorm.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoDorm.SelectPaging = false;
            this.infoDorm.SelectTop = 0;
            this.infoDorm.SiteControl = false;
            this.infoDorm.SiteFieldName = null;
            this.infoDorm.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucDorm
            // 
            this.ucDorm.AutoTrans = true;
            this.ucDorm.ExceptJoin = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "PowerID";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "CompanyID";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "PowerDate";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "DormID";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "PowerQty";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "LastPowerMeter";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "NowPowerMeter";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "PowerAmount";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "DiffAmount";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "CreateBy";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "CreateDate";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "LastUpdateBy";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "LastUpdateDate";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            this.ucDorm.FieldAttrs.Add(fieldAttr14);
            this.ucDorm.FieldAttrs.Add(fieldAttr15);
            this.ucDorm.FieldAttrs.Add(fieldAttr16);
            this.ucDorm.FieldAttrs.Add(fieldAttr17);
            this.ucDorm.FieldAttrs.Add(fieldAttr18);
            this.ucDorm.FieldAttrs.Add(fieldAttr19);
            this.ucDorm.FieldAttrs.Add(fieldAttr20);
            this.ucDorm.FieldAttrs.Add(fieldAttr21);
            this.ucDorm.FieldAttrs.Add(fieldAttr22);
            this.ucDorm.FieldAttrs.Add(fieldAttr23);
            this.ucDorm.FieldAttrs.Add(fieldAttr24);
            this.ucDorm.FieldAttrs.Add(fieldAttr25);
            this.ucDorm.FieldAttrs.Add(fieldAttr26);
            this.ucDorm.LogInfo = null;
            this.ucDorm.Name = "ucDorm";
            this.ucDorm.RowAffectsCheck = true;
            this.ucDorm.SelectCmd = this.infoDorm;
            this.ucDorm.SelectCmdForUpdate = null;
            this.ucDorm.SendSQLCmd = true;
            this.ucDorm.ServerModify = true;
            this.ucDorm.ServerModifyGetMax = false;
            this.ucDorm.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucDorm.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucDorm.UseTranscationScope = false;
            this.ucDorm.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoConnection3
            // 
            this.infoConnection3.EEPAlias = "FWCRMJS";
            // 
            // infoDormJS
            // 
            this.infoDormJS.CacheConnection = false;
            this.infoDormJS.CommandText = "select *\r\nfrom ReferenceTable where ListCategory=\'Dorm\' \r\n";
            this.infoDormJS.CommandTimeout = 30;
            this.infoDormJS.CommandType = System.Data.CommandType.Text;
            this.infoDormJS.DynamicTableName = false;
            this.infoDormJS.EEPAlias = "FWCRMJS";
            this.infoDormJS.EncodingAfter = null;
            this.infoDormJS.EncodingBefore = "Windows-1252";
            this.infoDormJS.EncodingConvert = null;
            this.infoDormJS.InfoConnection = this.infoConnection2;
            keyItem5.KeyName = "AutoKey";
            this.infoDormJS.KeyFields.Add(keyItem5);
            this.infoDormJS.MultiSetWhere = false;
            this.infoDormJS.Name = "infoDormJS";
            this.infoDormJS.NotificationAutoEnlist = false;
            this.infoDormJS.SecExcept = null;
            this.infoDormJS.SecFieldName = null;
            this.infoDormJS.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoDormJS.SelectPaging = false;
            this.infoDormJS.SelectTop = 0;
            this.infoDormJS.SiteControl = false;
            this.infoDormJS.SiteFieldName = null;
            this.infoDormJS.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucDormJS
            // 
            this.ucDormJS.AutoTrans = true;
            this.ucDormJS.ExceptJoin = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "PowerID";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "CompanyID";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "PowerDate";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "DormID";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "PowerQty";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "LastPowerMeter";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "NowPowerMeter";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "PowerAmount";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "DiffAmount";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "CreateBy";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "CreateDate";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "LastUpdateBy";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "LastUpdateDate";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            this.ucDormJS.FieldAttrs.Add(fieldAttr27);
            this.ucDormJS.FieldAttrs.Add(fieldAttr28);
            this.ucDormJS.FieldAttrs.Add(fieldAttr29);
            this.ucDormJS.FieldAttrs.Add(fieldAttr30);
            this.ucDormJS.FieldAttrs.Add(fieldAttr31);
            this.ucDormJS.FieldAttrs.Add(fieldAttr32);
            this.ucDormJS.FieldAttrs.Add(fieldAttr33);
            this.ucDormJS.FieldAttrs.Add(fieldAttr34);
            this.ucDormJS.FieldAttrs.Add(fieldAttr35);
            this.ucDormJS.FieldAttrs.Add(fieldAttr36);
            this.ucDormJS.FieldAttrs.Add(fieldAttr37);
            this.ucDormJS.FieldAttrs.Add(fieldAttr38);
            this.ucDormJS.FieldAttrs.Add(fieldAttr39);
            this.ucDormJS.LogInfo = null;
            this.ucDormJS.Name = "ucDormJS";
            this.ucDormJS.RowAffectsCheck = true;
            this.ucDormJS.SelectCmd = this.infoDormJS;
            this.ucDormJS.SelectCmdForUpdate = null;
            this.ucDormJS.SendSQLCmd = true;
            this.ucDormJS.ServerModify = true;
            this.ucDormJS.ServerModifyGetMax = false;
            this.ucDormJS.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucDormJS.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucDormJS.UseTranscationScope = false;
            this.ucDormJS.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoAcnoCost
            // 
            this.infoAcnoCost.CacheConnection = false;
            this.infoAcnoCost.CommandText = "select Cast(acno as nvarchar)+Cast(subacno as nvarchar) as AcnoCost from glAccoun" +
    "tItem where CompanyID=1 and ClassID=\'51\'\r\n";
            this.infoAcnoCost.CommandTimeout = 30;
            this.infoAcnoCost.CommandType = System.Data.CommandType.Text;
            this.infoAcnoCost.DynamicTableName = false;
            this.infoAcnoCost.EEPAlias = "";
            this.infoAcnoCost.EncodingAfter = null;
            this.infoAcnoCost.EncodingBefore = "Windows-1252";
            this.infoAcnoCost.EncodingConvert = null;
            this.infoAcnoCost.InfoConnection = this.InfoConnection1;
            this.infoAcnoCost.MultiSetWhere = false;
            this.infoAcnoCost.Name = "infoAcnoCost";
            this.infoAcnoCost.NotificationAutoEnlist = false;
            this.infoAcnoCost.SecExcept = null;
            this.infoAcnoCost.SecFieldName = null;
            this.infoAcnoCost.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoAcnoCost.SelectPaging = false;
            this.infoAcnoCost.SelectTop = 0;
            this.infoAcnoCost.SiteControl = false;
            this.infoAcnoCost.SiteFieldName = null;
            this.infoAcnoCost.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoglDorm
            // 
            this.infoglDorm.CacheConnection = false;
            this.infoglDorm.CommandText = "select *,case when CompanyID=2 then \'傑信管理\' else \'傑報人力\' end as CompanyName\r\nfrom g" +
    "lDorm \r\norder by CompanyID\r\n";
            this.infoglDorm.CommandTimeout = 30;
            this.infoglDorm.CommandType = System.Data.CommandType.Text;
            this.infoglDorm.DynamicTableName = false;
            this.infoglDorm.EEPAlias = "";
            this.infoglDorm.EncodingAfter = null;
            this.infoglDorm.EncodingBefore = "Windows-1252";
            this.infoglDorm.EncodingConvert = null;
            this.infoglDorm.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "AutoKey";
            this.infoglDorm.KeyFields.Add(keyItem6);
            this.infoglDorm.MultiSetWhere = false;
            this.infoglDorm.Name = "infoglDorm";
            this.infoglDorm.NotificationAutoEnlist = false;
            this.infoglDorm.SecExcept = null;
            this.infoglDorm.SecFieldName = null;
            this.infoglDorm.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoglDorm.SelectPaging = false;
            this.infoglDorm.SelectTop = 0;
            this.infoglDorm.SiteControl = false;
            this.infoglDorm.SiteFieldName = null;
            this.infoglDorm.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucglDorm
            // 
            this.ucglDorm.AutoTrans = true;
            this.ucglDorm.ExceptJoin = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "PowerID";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "CompanyID";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "PowerDate";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "DormID";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "PowerQty";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "LastPowerMeter";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "NowPowerMeter";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "PowerAmount";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "DiffAmount";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "CreateBy";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "CreateDate";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "LastUpdateBy";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "LastUpdateDate";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            this.ucglDorm.FieldAttrs.Add(fieldAttr40);
            this.ucglDorm.FieldAttrs.Add(fieldAttr41);
            this.ucglDorm.FieldAttrs.Add(fieldAttr42);
            this.ucglDorm.FieldAttrs.Add(fieldAttr43);
            this.ucglDorm.FieldAttrs.Add(fieldAttr44);
            this.ucglDorm.FieldAttrs.Add(fieldAttr45);
            this.ucglDorm.FieldAttrs.Add(fieldAttr46);
            this.ucglDorm.FieldAttrs.Add(fieldAttr47);
            this.ucglDorm.FieldAttrs.Add(fieldAttr48);
            this.ucglDorm.FieldAttrs.Add(fieldAttr49);
            this.ucglDorm.FieldAttrs.Add(fieldAttr50);
            this.ucglDorm.FieldAttrs.Add(fieldAttr51);
            this.ucglDorm.FieldAttrs.Add(fieldAttr52);
            this.ucglDorm.LogInfo = null;
            this.ucglDorm.Name = "ucglDorm";
            this.ucglDorm.RowAffectsCheck = true;
            this.ucglDorm.SelectCmd = this.infoglDorm;
            this.ucglDorm.SelectCmdForUpdate = null;
            this.ucglDorm.SendSQLCmd = true;
            this.ucglDorm.ServerModify = true;
            this.ucglDorm.ServerModifyGetMax = false;
            this.ucglDorm.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucglDorm.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucglDorm.UseTranscationScope = false;
            this.ucglDorm.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // infoBankFees
            // 
            this.infoBankFees.CacheConnection = false;
            this.infoBankFees.CommandText = resources.GetString("infoBankFees.CommandText");
            this.infoBankFees.CommandTimeout = 30;
            this.infoBankFees.CommandType = System.Data.CommandType.Text;
            this.infoBankFees.DynamicTableName = false;
            this.infoBankFees.EEPAlias = "FWCRMJSCare";
            this.infoBankFees.EncodingAfter = null;
            this.infoBankFees.EncodingBefore = "Windows-1252";
            this.infoBankFees.EncodingConvert = null;
            this.infoBankFees.InfoConnection = this.infoConnection4;
            this.infoBankFees.MultiSetWhere = false;
            this.infoBankFees.Name = "infoBankFees";
            this.infoBankFees.NotificationAutoEnlist = false;
            this.infoBankFees.SecExcept = null;
            this.infoBankFees.SecFieldName = null;
            this.infoBankFees.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.infoBankFees.SelectPaging = false;
            this.infoBankFees.SelectTop = 0;
            this.infoBankFees.SiteControl = false;
            this.infoBankFees.SiteFieldName = null;
            this.infoBankFees.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // infoConnection4
            // 
            this.infoConnection4.EEPAlias = "FWCRMJSCare";
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PowerMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoDormID)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoPowerTitle)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoEmployeeFees)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PowerQuery)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoCompID)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoEmp)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoEmployeeFeesPower)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoDorm)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoDormJS)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoAcnoCost)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoglDorm)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoBankFees)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infoConnection4)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand PowerMaster;
        private Srvtools.UpdateComponent ucPowerMaster;
        private Srvtools.InfoCommand infoDormID;
        private Srvtools.InfoCommand infoPowerTitle;
        private Srvtools.InfoCommand infoEmployeeFees;
        private Srvtools.InfoCommand PowerQuery;
        private Srvtools.InfoConnection infoConnection2;
        private Srvtools.InfoCommand infoCompID;
        private Srvtools.InfoCommand infoEmp;
        private Srvtools.InfoCommand infoEmployeeFeesPower;
        private Srvtools.InfoCommand infoDorm;
        private Srvtools.UpdateComponent ucDorm;
        private Srvtools.InfoConnection infoConnection3;
        private Srvtools.InfoCommand infoDormJS;
        private Srvtools.UpdateComponent ucDormJS;
        private Srvtools.InfoCommand infoAcnoCost;
        private Srvtools.InfoCommand infoglDorm;
        private Srvtools.UpdateComponent ucglDorm;
        private Srvtools.InfoCommand infoBankFees;
        private Srvtools.InfoConnection infoConnection4;
    }
}
