namespace sUser
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.HUT_User = new Srvtools.InfoCommand(this.components);
            this.ucHUT_User = new Srvtools.UpdateComponent(this.components);
            this.View_HUT_User = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.HUT_User)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_HUT_User)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "Hunter";
            // 
            // HUT_User
            // 
            this.HUT_User.CacheConnection = false;
            this.HUT_User.CommandText = "SELECT [HUT_User].* FROM [HUT_User]";
            this.HUT_User.CommandTimeout = 30;
            this.HUT_User.CommandType = System.Data.CommandType.Text;
            this.HUT_User.DynamicTableName = false;
            this.HUT_User.EEPAlias = null;
            this.HUT_User.EncodingAfter = null;
            this.HUT_User.EncodingBefore = "Windows-1252";
            this.HUT_User.InfoConnection = this.InfoConnection1;
            this.HUT_User.MultiSetWhere = false;
            this.HUT_User.Name = "HUT_User";
            this.HUT_User.NotificationAutoEnlist = false;
            this.HUT_User.SecExcept = null;
            this.HUT_User.SecFieldName = null;
            this.HUT_User.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.HUT_User.SelectPaging = false;
            this.HUT_User.SelectTop = 0;
            this.HUT_User.SiteControl = false;
            this.HUT_User.SiteFieldName = null;
            this.HUT_User.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucHUT_User
            // 
            this.ucHUT_User.AutoTrans = true;
            this.ucHUT_User.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "UserID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "NameC";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "NameE";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "Birthday";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "eMail1";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "eMail2";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "Gender";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "Height";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "Weight";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "BloodType";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "MarriageStatus";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "Country1";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "ArmyStatus";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "MobileNo1";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "MobileArea1";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "MobileNo2";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "MobileArea2";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "PhoneNo";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "DrivingLicense";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "Traffic";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "IMType";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "IMAccount";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "Address1";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "Address2";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "ExpPay";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "ExpDutyDt";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "ExpDutyArea";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "EduID1";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "SchoolName1";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "SchoolArea1";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "EduSubject1";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "Department1";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "GraduateYear1";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "GradStatus1";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "EduID2";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "SchoolName2";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "SchoolArea2";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "EduSubject2";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "Department2";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "GraduateYear2";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "GradStatus2";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "EduID3";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "SchoolName3";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "SchoolArea3";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "EduSubject3";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "Department3";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "GraduateYear3";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "GradStatus3";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "DocFile1";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "DocFile2";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "DocFile3";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "PhotoFile";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "ExcelFile";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "CreateBy";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "CreateDate";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "LastUpdateBy";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "LastUpdateDate";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            this.ucHUT_User.FieldAttrs.Add(fieldAttr1);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr2);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr3);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr4);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr5);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr6);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr7);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr8);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr9);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr10);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr11);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr12);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr13);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr14);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr15);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr16);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr17);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr18);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr19);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr20);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr21);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr22);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr23);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr24);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr25);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr26);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr27);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr28);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr29);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr30);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr31);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr32);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr33);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr34);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr35);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr36);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr37);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr38);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr39);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr40);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr41);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr42);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr43);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr44);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr45);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr46);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr47);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr48);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr49);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr50);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr51);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr52);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr53);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr54);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr55);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr56);
            this.ucHUT_User.FieldAttrs.Add(fieldAttr57);
            this.ucHUT_User.LogInfo = null;
            this.ucHUT_User.Name = null;
            this.ucHUT_User.RowAffectsCheck = true;
            this.ucHUT_User.SelectCmd = this.HUT_User;
            this.ucHUT_User.ServerModify = true;
            this.ucHUT_User.ServerModifyGetMax = false;
            this.ucHUT_User.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucHUT_User.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucHUT_User.UseTranscationScope = false;
            this.ucHUT_User.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_HUT_User
            // 
            this.View_HUT_User.CacheConnection = false;
            this.View_HUT_User.CommandText = "SELECT * FROM [HUT_User]";
            this.View_HUT_User.CommandTimeout = 30;
            this.View_HUT_User.CommandType = System.Data.CommandType.Text;
            this.View_HUT_User.DynamicTableName = false;
            this.View_HUT_User.EEPAlias = null;
            this.View_HUT_User.EncodingAfter = null;
            this.View_HUT_User.EncodingBefore = "Windows-1252";
            this.View_HUT_User.InfoConnection = this.InfoConnection1;
            this.View_HUT_User.MultiSetWhere = false;
            this.View_HUT_User.Name = "View_HUT_User";
            this.View_HUT_User.NotificationAutoEnlist = false;
            this.View_HUT_User.SecExcept = null;
            this.View_HUT_User.SecFieldName = null;
            this.View_HUT_User.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_HUT_User.SelectPaging = false;
            this.View_HUT_User.SelectTop = 0;
            this.View_HUT_User.SiteControl = false;
            this.View_HUT_User.SiteFieldName = null;
            this.View_HUT_User.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.HUT_User)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_HUT_User)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand HUT_User;
        private Srvtools.UpdateComponent ucHUT_User;
        private Srvtools.InfoCommand View_HUT_User;
    }
}
