namespace sCourseOpen
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            Srvtools.Service service9 = new Srvtools.Service();
            Srvtools.Service service10 = new Srvtools.Service();
            Srvtools.Service service11 = new Srvtools.Service();
            Srvtools.Service service12 = new Srvtools.Service();
            Srvtools.Service service13 = new Srvtools.Service();
            Srvtools.Service service14 = new Srvtools.Service();
            Srvtools.Service service15 = new Srvtools.Service();
            Srvtools.Service service16 = new Srvtools.Service();
            Srvtools.Service service17 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr69 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr70 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr71 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr72 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr73 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr74 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr75 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr76 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr77 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr78 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr79 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr80 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr81 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.CoursePlanDetails = new Srvtools.InfoCommand(this.components);
            this.ucCoursePlanDetails = new Srvtools.UpdateComponent(this.components);
            this.View_CoursePlanDetails = new Srvtools.InfoCommand(this.components);
            this.YearNO = new Srvtools.InfoCommand(this.components);
            this.CoursePlan = new Srvtools.InfoCommand(this.components);
            this.CourseOpenRecord = new Srvtools.InfoCommand(this.components);
            this.updateComponent1 = new Srvtools.UpdateComponent(this.components);
            this.CourseBookBill = new Srvtools.InfoCommand(this.components);
            this.updateComponent2 = new Srvtools.UpdateComponent(this.components);
            this.LastPlanYear = new Srvtools.InfoCommand(this.components);
            this.CourseType = new Srvtools.InfoCommand(this.components);
            this.CourseMethod = new Srvtools.InfoCommand(this.components);
            this.TestMethod = new Srvtools.InfoCommand(this.components);
            this.TRCompany = new Srvtools.InfoCommand(this.components);
            this.TRLocation = new Srvtools.InfoCommand(this.components);
            this.Teacher = new Srvtools.InfoCommand(this.components);
            this.CourseData = new Srvtools.InfoCommand(this.components);
            this.SpreadType = new Srvtools.InfoCommand(this.components);
            this.CourseOpenType = new Srvtools.InfoCommand(this.components);
            this.StudentTree = new Srvtools.InfoCommand(this.components);
            this.ExamPaper = new Srvtools.InfoCommand(this.components);
            this.OpenStatus = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CoursePlanDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_CoursePlanDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.YearNO)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CoursePlan)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseOpenRecord)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseBookBill)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastPlanYear)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseMethod)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TestMethod)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TRCompany)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TRLocation)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Teacher)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseData)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SpreadType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseOpenType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.StudentTree)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ExamPaper)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.OpenStatus)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "GetYearAndPlan";
            service1.NonLogin = false;
            service1.ServiceName = "GetYearAndPlan";
            service2.DelegateName = "procCoursePlanOpen";
            service2.NonLogin = false;
            service2.ServiceName = "procCoursePlanOpen";
            service3.DelegateName = "procCoursePlanOpenAdd";
            service3.NonLogin = false;
            service3.ServiceName = "procCoursePlanOpenAdd";
            service4.DelegateName = "procCoursePlanOpenBookBill";
            service4.NonLogin = false;
            service4.ServiceName = "procCoursePlanOpenBookBill";
            service5.DelegateName = "procCoursePlanOpenEnd";
            service5.NonLogin = false;
            service5.ServiceName = "procCoursePlanOpenEnd";
            service6.DelegateName = "ReportCourseOpenRecord";
            service6.NonLogin = false;
            service6.ServiceName = "ReportCourseOpenRecord";
            service7.DelegateName = "ReportCourseOpenBookBill";
            service7.NonLogin = false;
            service7.ServiceName = "ReportCourseOpenBookBill";
            service8.DelegateName = "procCoursePlanOpenEnd";
            service8.NonLogin = false;
            service8.ServiceName = "procCoursePlanOpenEnd";
            service9.DelegateName = "GetPlanOpenCourseStudents";
            service9.NonLogin = false;
            service9.ServiceName = "GetPlanOpenCourseStudents";
            service10.DelegateName = "procAddCourseOpenBookBill";
            service10.NonLogin = false;
            service10.ServiceName = "procAddCourseOpenBookBill";
            service11.DelegateName = "GetOpenCourseExamID";
            service11.NonLogin = false;
            service11.ServiceName = "GetOpenCourseExamID";
            service12.DelegateName = "GetOpenCourseDataID";
            service12.NonLogin = false;
            service12.ServiceName = "GetOpenCourseDataID";
            service13.DelegateName = "SetOpenCourseExam";
            service13.NonLogin = false;
            service13.ServiceName = "SetOpenCourseExam";
            service14.DelegateName = "DeleteCourseBookBill";
            service14.NonLogin = false;
            service14.ServiceName = "DeleteCourseBookBill";
            service15.DelegateName = "PlanCourseOpenStop";
            service15.NonLogin = false;
            service15.ServiceName = "PlanCourseOpenStop";
            service16.DelegateName = "procCourseOpenClose";
            service16.NonLogin = false;
            service16.ServiceName = "procCourseOpenClose";
            service17.DelegateName = "CheckIsOpenCourse";
            service17.NonLogin = false;
            service17.ServiceName = "CheckIsOpenCourse";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            this.serviceManager1.ServiceCollection.Add(service9);
            this.serviceManager1.ServiceCollection.Add(service10);
            this.serviceManager1.ServiceCollection.Add(service11);
            this.serviceManager1.ServiceCollection.Add(service12);
            this.serviceManager1.ServiceCollection.Add(service13);
            this.serviceManager1.ServiceCollection.Add(service14);
            this.serviceManager1.ServiceCollection.Add(service15);
            this.serviceManager1.ServiceCollection.Add(service16);
            this.serviceManager1.ServiceCollection.Add(service17);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "eTraining";
            // 
            // CoursePlanDetails
            // 
            this.CoursePlanDetails.CacheConnection = false;
            this.CoursePlanDetails.CommandText = resources.GetString("CoursePlanDetails.CommandText");
            this.CoursePlanDetails.CommandTimeout = 30;
            this.CoursePlanDetails.CommandType = System.Data.CommandType.Text;
            this.CoursePlanDetails.DynamicTableName = false;
            this.CoursePlanDetails.EEPAlias = null;
            this.CoursePlanDetails.EncodingAfter = null;
            this.CoursePlanDetails.EncodingBefore = "Windows-1252";
            this.CoursePlanDetails.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "AutoKey";
            this.CoursePlanDetails.KeyFields.Add(keyItem1);
            this.CoursePlanDetails.MultiSetWhere = false;
            this.CoursePlanDetails.Name = "CoursePlanDetails";
            this.CoursePlanDetails.NotificationAutoEnlist = false;
            this.CoursePlanDetails.SecExcept = null;
            this.CoursePlanDetails.SecFieldName = null;
            this.CoursePlanDetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CoursePlanDetails.SelectPaging = false;
            this.CoursePlanDetails.SelectTop = 0;
            this.CoursePlanDetails.SiteControl = false;
            this.CoursePlanDetails.SiteFieldName = null;
            this.CoursePlanDetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucCoursePlanDetails
            // 
            this.ucCoursePlanDetails.AutoTrans = true;
            this.ucCoursePlanDetails.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "AutoKey";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "ParentKey";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "PlanID";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "CourseID";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "CourseNO";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ClassName";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "IsClass";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "IsUserDefine";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "StudentID";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "JobID";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "DeptID";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "PlanDeptIDs";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "StartDate1";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "StartDate2";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "SpreadType";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "IsActive";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "OpenSeason";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "CreateBy";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "CreateDate";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "LastUpdateBy";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "LastUpdateDate";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr1);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr2);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr3);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr4);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr5);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr6);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr7);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr8);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr9);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr10);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr11);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr12);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr13);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr14);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr15);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr16);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr17);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr18);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr19);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr20);
            this.ucCoursePlanDetails.FieldAttrs.Add(fieldAttr21);
            this.ucCoursePlanDetails.LogInfo = null;
            this.ucCoursePlanDetails.Name = "ucCoursePlanDetails";
            this.ucCoursePlanDetails.RowAffectsCheck = true;
            this.ucCoursePlanDetails.SelectCmd = this.CoursePlanDetails;
            this.ucCoursePlanDetails.SelectCmdForUpdate = null;
            this.ucCoursePlanDetails.ServerModify = true;
            this.ucCoursePlanDetails.ServerModifyGetMax = false;
            this.ucCoursePlanDetails.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucCoursePlanDetails.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucCoursePlanDetails.UseTranscationScope = false;
            this.ucCoursePlanDetails.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_CoursePlanDetails
            // 
            this.View_CoursePlanDetails.CacheConnection = false;
            this.View_CoursePlanDetails.CommandText = "SELECT * FROM dbo.[CoursePlanDetails]";
            this.View_CoursePlanDetails.CommandTimeout = 30;
            this.View_CoursePlanDetails.CommandType = System.Data.CommandType.Text;
            this.View_CoursePlanDetails.DynamicTableName = false;
            this.View_CoursePlanDetails.EEPAlias = null;
            this.View_CoursePlanDetails.EncodingAfter = null;
            this.View_CoursePlanDetails.EncodingBefore = "Windows-1252";
            this.View_CoursePlanDetails.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "AutoKey";
            this.View_CoursePlanDetails.KeyFields.Add(keyItem2);
            this.View_CoursePlanDetails.MultiSetWhere = false;
            this.View_CoursePlanDetails.Name = "View_CoursePlanDetails";
            this.View_CoursePlanDetails.NotificationAutoEnlist = false;
            this.View_CoursePlanDetails.SecExcept = null;
            this.View_CoursePlanDetails.SecFieldName = null;
            this.View_CoursePlanDetails.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_CoursePlanDetails.SelectPaging = false;
            this.View_CoursePlanDetails.SelectTop = 0;
            this.View_CoursePlanDetails.SiteControl = false;
            this.View_CoursePlanDetails.SiteFieldName = null;
            this.View_CoursePlanDetails.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // YearNO
            // 
            this.YearNO.CacheConnection = false;
            this.YearNO.CommandText = "SELECT Distinct  YEAR  FROM CoursePlanRecord\r\nUNION\r\nSELECT YEAR(GETDATE())  AS Y" +
    "EAR\r\nORDER BY YEAR DESC";
            this.YearNO.CommandTimeout = 30;
            this.YearNO.CommandType = System.Data.CommandType.Text;
            this.YearNO.DynamicTableName = false;
            this.YearNO.EEPAlias = null;
            this.YearNO.EncodingAfter = null;
            this.YearNO.EncodingBefore = "Windows-1252";
            this.YearNO.InfoConnection = this.InfoConnection1;
            this.YearNO.MultiSetWhere = false;
            this.YearNO.Name = "YearNO";
            this.YearNO.NotificationAutoEnlist = false;
            this.YearNO.SecExcept = null;
            this.YearNO.SecFieldName = null;
            this.YearNO.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.YearNO.SelectPaging = false;
            this.YearNO.SelectTop = 0;
            this.YearNO.SiteControl = false;
            this.YearNO.SiteFieldName = null;
            this.YearNO.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CoursePlan
            // 
            this.CoursePlan.CacheConnection = false;
            this.CoursePlan.CommandText = resources.GetString("CoursePlan.CommandText");
            this.CoursePlan.CommandTimeout = 30;
            this.CoursePlan.CommandType = System.Data.CommandType.Text;
            this.CoursePlan.DynamicTableName = false;
            this.CoursePlan.EEPAlias = null;
            this.CoursePlan.EncodingAfter = null;
            this.CoursePlan.EncodingBefore = "Windows-1252";
            this.CoursePlan.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "PlanID";
            this.CoursePlan.KeyFields.Add(keyItem3);
            this.CoursePlan.MultiSetWhere = false;
            this.CoursePlan.Name = "CoursePlan";
            this.CoursePlan.NotificationAutoEnlist = false;
            this.CoursePlan.SecExcept = null;
            this.CoursePlan.SecFieldName = null;
            this.CoursePlan.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CoursePlan.SelectPaging = false;
            this.CoursePlan.SelectTop = 0;
            this.CoursePlan.SiteControl = false;
            this.CoursePlan.SiteFieldName = null;
            this.CoursePlan.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CourseOpenRecord
            // 
            this.CourseOpenRecord.CacheConnection = false;
            this.CourseOpenRecord.CommandText = resources.GetString("CourseOpenRecord.CommandText");
            this.CourseOpenRecord.CommandTimeout = 30;
            this.CourseOpenRecord.CommandType = System.Data.CommandType.Text;
            this.CourseOpenRecord.DynamicTableName = false;
            this.CourseOpenRecord.EEPAlias = null;
            this.CourseOpenRecord.EncodingAfter = null;
            this.CourseOpenRecord.EncodingBefore = "Windows-1252";
            this.CourseOpenRecord.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "CourseOpenID";
            this.CourseOpenRecord.KeyFields.Add(keyItem4);
            this.CourseOpenRecord.MultiSetWhere = false;
            this.CourseOpenRecord.Name = "CourseOpenRecord";
            this.CourseOpenRecord.NotificationAutoEnlist = false;
            this.CourseOpenRecord.SecExcept = null;
            this.CourseOpenRecord.SecFieldName = null;
            this.CourseOpenRecord.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CourseOpenRecord.SelectPaging = false;
            this.CourseOpenRecord.SelectTop = 0;
            this.CourseOpenRecord.SiteControl = false;
            this.CourseOpenRecord.SiteFieldName = null;
            this.CourseOpenRecord.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // updateComponent1
            // 
            this.updateComponent1.AutoTrans = true;
            this.updateComponent1.ExceptJoin = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "CourseOpenID";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "CoursePlanID";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "Year";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "CourseOpenType";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "CourseMaxCount";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "CourseID";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "CourseName";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "CourseType";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "CourseNO";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "CourseDataID";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "CourseStartDate";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "CourseEndDate";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "CourseStartDate";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "CourseEndDate";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "CourseStartHour";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "CourseEndHour";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "CourseMethod";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "CourseLocationID";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "CourseOpenStatus";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "CourseCloseDate";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "CourseTestMethod";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "ExamStartDate";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "ExamEndDate";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "CourseHours";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "ExamID";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "MainHost";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "SubHost";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "TeacherID1";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "TrainingFee";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "TeacherID2";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "IsOverseaCourse";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "IsAllowBooking";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "IsMustBeEval";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "IsOpenToLook";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "IsCert";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "Description";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "CreateBy";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "CreateDate";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "LastUpdateBy";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "LastUpdateDate";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "CanExamTime";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = null;
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "CourseOpenProperty";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr63.DefaultValue = null;
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "ParentCourseOpenID";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr64.DefaultValue = null;
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            this.updateComponent1.FieldAttrs.Add(fieldAttr22);
            this.updateComponent1.FieldAttrs.Add(fieldAttr23);
            this.updateComponent1.FieldAttrs.Add(fieldAttr24);
            this.updateComponent1.FieldAttrs.Add(fieldAttr25);
            this.updateComponent1.FieldAttrs.Add(fieldAttr26);
            this.updateComponent1.FieldAttrs.Add(fieldAttr27);
            this.updateComponent1.FieldAttrs.Add(fieldAttr28);
            this.updateComponent1.FieldAttrs.Add(fieldAttr29);
            this.updateComponent1.FieldAttrs.Add(fieldAttr30);
            this.updateComponent1.FieldAttrs.Add(fieldAttr31);
            this.updateComponent1.FieldAttrs.Add(fieldAttr32);
            this.updateComponent1.FieldAttrs.Add(fieldAttr33);
            this.updateComponent1.FieldAttrs.Add(fieldAttr34);
            this.updateComponent1.FieldAttrs.Add(fieldAttr35);
            this.updateComponent1.FieldAttrs.Add(fieldAttr36);
            this.updateComponent1.FieldAttrs.Add(fieldAttr37);
            this.updateComponent1.FieldAttrs.Add(fieldAttr38);
            this.updateComponent1.FieldAttrs.Add(fieldAttr39);
            this.updateComponent1.FieldAttrs.Add(fieldAttr40);
            this.updateComponent1.FieldAttrs.Add(fieldAttr41);
            this.updateComponent1.FieldAttrs.Add(fieldAttr42);
            this.updateComponent1.FieldAttrs.Add(fieldAttr43);
            this.updateComponent1.FieldAttrs.Add(fieldAttr44);
            this.updateComponent1.FieldAttrs.Add(fieldAttr45);
            this.updateComponent1.FieldAttrs.Add(fieldAttr46);
            this.updateComponent1.FieldAttrs.Add(fieldAttr47);
            this.updateComponent1.FieldAttrs.Add(fieldAttr48);
            this.updateComponent1.FieldAttrs.Add(fieldAttr49);
            this.updateComponent1.FieldAttrs.Add(fieldAttr50);
            this.updateComponent1.FieldAttrs.Add(fieldAttr51);
            this.updateComponent1.FieldAttrs.Add(fieldAttr52);
            this.updateComponent1.FieldAttrs.Add(fieldAttr53);
            this.updateComponent1.FieldAttrs.Add(fieldAttr54);
            this.updateComponent1.FieldAttrs.Add(fieldAttr55);
            this.updateComponent1.FieldAttrs.Add(fieldAttr56);
            this.updateComponent1.FieldAttrs.Add(fieldAttr57);
            this.updateComponent1.FieldAttrs.Add(fieldAttr58);
            this.updateComponent1.FieldAttrs.Add(fieldAttr59);
            this.updateComponent1.FieldAttrs.Add(fieldAttr60);
            this.updateComponent1.FieldAttrs.Add(fieldAttr61);
            this.updateComponent1.FieldAttrs.Add(fieldAttr62);
            this.updateComponent1.FieldAttrs.Add(fieldAttr63);
            this.updateComponent1.FieldAttrs.Add(fieldAttr64);
            this.updateComponent1.LogInfo = null;
            this.updateComponent1.Name = "updateComponent1";
            this.updateComponent1.RowAffectsCheck = true;
            this.updateComponent1.SelectCmd = this.CourseOpenRecord;
            this.updateComponent1.SelectCmdForUpdate = null;
            this.updateComponent1.ServerModify = true;
            this.updateComponent1.ServerModifyGetMax = false;
            this.updateComponent1.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateComponent1.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateComponent1.UseTranscationScope = false;
            this.updateComponent1.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // CourseBookBill
            // 
            this.CourseBookBill.CacheConnection = false;
            this.CourseBookBill.CommandText = resources.GetString("CourseBookBill.CommandText");
            this.CourseBookBill.CommandTimeout = 30;
            this.CourseBookBill.CommandType = System.Data.CommandType.Text;
            this.CourseBookBill.DynamicTableName = false;
            this.CourseBookBill.EEPAlias = null;
            this.CourseBookBill.EncodingAfter = null;
            this.CourseBookBill.EncodingBefore = "Windows-1252";
            this.CourseBookBill.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "AutoKey";
            this.CourseBookBill.KeyFields.Add(keyItem5);
            this.CourseBookBill.MultiSetWhere = false;
            this.CourseBookBill.Name = "CourseBookBill";
            this.CourseBookBill.NotificationAutoEnlist = false;
            this.CourseBookBill.SecExcept = null;
            this.CourseBookBill.SecFieldName = null;
            this.CourseBookBill.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CourseBookBill.SelectPaging = false;
            this.CourseBookBill.SelectTop = 0;
            this.CourseBookBill.SiteControl = false;
            this.CourseBookBill.SiteFieldName = null;
            this.CourseBookBill.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // updateComponent2
            // 
            this.updateComponent2.AutoTrans = true;
            this.updateComponent2.ExceptJoin = false;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "AutoKey";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = null;
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "CourseOpenID";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = null;
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "StudentID";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr67.DefaultValue = null;
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "DeptID";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr68.DefaultValue = null;
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            fieldAttr69.CheckNull = false;
            fieldAttr69.DataField = "CoursePlanStartDate1";
            fieldAttr69.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr69.DefaultValue = null;
            fieldAttr69.TrimLength = 0;
            fieldAttr69.UpdateEnable = true;
            fieldAttr69.WhereMode = true;
            fieldAttr70.CheckNull = false;
            fieldAttr70.DataField = "CoursePlanStartDate2";
            fieldAttr70.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr70.DefaultValue = null;
            fieldAttr70.TrimLength = 0;
            fieldAttr70.UpdateEnable = true;
            fieldAttr70.WhereMode = true;
            fieldAttr71.CheckNull = false;
            fieldAttr71.DataField = "ExamPoint";
            fieldAttr71.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr71.DefaultValue = null;
            fieldAttr71.TrimLength = 0;
            fieldAttr71.UpdateEnable = true;
            fieldAttr71.WhereMode = true;
            fieldAttr72.CheckNull = false;
            fieldAttr72.DataField = "TrainingFee";
            fieldAttr72.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr72.DefaultValue = null;
            fieldAttr72.TrimLength = 0;
            fieldAttr72.UpdateEnable = true;
            fieldAttr72.WhereMode = true;
            fieldAttr73.CheckNull = false;
            fieldAttr73.DataField = "RecordFrom";
            fieldAttr73.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr73.DefaultValue = null;
            fieldAttr73.TrimLength = 0;
            fieldAttr73.UpdateEnable = true;
            fieldAttr73.WhereMode = true;
            fieldAttr74.CheckNull = false;
            fieldAttr74.DataField = "IsActive";
            fieldAttr74.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr74.DefaultValue = null;
            fieldAttr74.TrimLength = 0;
            fieldAttr74.UpdateEnable = true;
            fieldAttr74.WhereMode = true;
            fieldAttr75.CheckNull = false;
            fieldAttr75.DataField = "IsAttend";
            fieldAttr75.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr75.DefaultValue = null;
            fieldAttr75.TrimLength = 0;
            fieldAttr75.UpdateEnable = true;
            fieldAttr75.WhereMode = true;
            fieldAttr76.CheckNull = false;
            fieldAttr76.DataField = "IsPass";
            fieldAttr76.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr76.DefaultValue = null;
            fieldAttr76.TrimLength = 0;
            fieldAttr76.UpdateEnable = true;
            fieldAttr76.WhereMode = true;
            fieldAttr77.CheckNull = false;
            fieldAttr77.DataField = "CreateBy";
            fieldAttr77.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr77.DefaultValue = null;
            fieldAttr77.TrimLength = 0;
            fieldAttr77.UpdateEnable = true;
            fieldAttr77.WhereMode = true;
            fieldAttr78.CheckNull = false;
            fieldAttr78.DataField = "CreateDate";
            fieldAttr78.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr78.DefaultValue = null;
            fieldAttr78.TrimLength = 0;
            fieldAttr78.UpdateEnable = true;
            fieldAttr78.WhereMode = true;
            fieldAttr79.CheckNull = false;
            fieldAttr79.DataField = "LastUpdateBy";
            fieldAttr79.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr79.DefaultValue = null;
            fieldAttr79.TrimLength = 0;
            fieldAttr79.UpdateEnable = true;
            fieldAttr79.WhereMode = true;
            fieldAttr80.CheckNull = false;
            fieldAttr80.DataField = "LastUpdateDate";
            fieldAttr80.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr80.DefaultValue = null;
            fieldAttr80.TrimLength = 0;
            fieldAttr80.UpdateEnable = true;
            fieldAttr80.WhereMode = true;
            fieldAttr81.CheckNull = false;
            fieldAttr81.DataField = "IsLeave";
            fieldAttr81.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr81.DefaultValue = null;
            fieldAttr81.TrimLength = 0;
            fieldAttr81.UpdateEnable = true;
            fieldAttr81.WhereMode = true;
            this.updateComponent2.FieldAttrs.Add(fieldAttr65);
            this.updateComponent2.FieldAttrs.Add(fieldAttr66);
            this.updateComponent2.FieldAttrs.Add(fieldAttr67);
            this.updateComponent2.FieldAttrs.Add(fieldAttr68);
            this.updateComponent2.FieldAttrs.Add(fieldAttr69);
            this.updateComponent2.FieldAttrs.Add(fieldAttr70);
            this.updateComponent2.FieldAttrs.Add(fieldAttr71);
            this.updateComponent2.FieldAttrs.Add(fieldAttr72);
            this.updateComponent2.FieldAttrs.Add(fieldAttr73);
            this.updateComponent2.FieldAttrs.Add(fieldAttr74);
            this.updateComponent2.FieldAttrs.Add(fieldAttr75);
            this.updateComponent2.FieldAttrs.Add(fieldAttr76);
            this.updateComponent2.FieldAttrs.Add(fieldAttr77);
            this.updateComponent2.FieldAttrs.Add(fieldAttr78);
            this.updateComponent2.FieldAttrs.Add(fieldAttr79);
            this.updateComponent2.FieldAttrs.Add(fieldAttr80);
            this.updateComponent2.FieldAttrs.Add(fieldAttr81);
            this.updateComponent2.LogInfo = null;
            this.updateComponent2.Name = "updateComponent2";
            this.updateComponent2.RowAffectsCheck = true;
            this.updateComponent2.SelectCmd = this.CourseBookBill;
            this.updateComponent2.SelectCmdForUpdate = null;
            this.updateComponent2.ServerModify = true;
            this.updateComponent2.ServerModifyGetMax = false;
            this.updateComponent2.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.updateComponent2.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.updateComponent2.UseTranscationScope = false;
            this.updateComponent2.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // LastPlanYear
            // 
            this.LastPlanYear.CacheConnection = false;
            this.LastPlanYear.CommandText = "SELECT  TOP 1    Year,SpreadType FROM  CoursePlanRecord ORDER BY YEAR DESC";
            this.LastPlanYear.CommandTimeout = 30;
            this.LastPlanYear.CommandType = System.Data.CommandType.Text;
            this.LastPlanYear.DynamicTableName = false;
            this.LastPlanYear.EEPAlias = null;
            this.LastPlanYear.EncodingAfter = null;
            this.LastPlanYear.EncodingBefore = "Windows-1252";
            this.LastPlanYear.InfoConnection = this.InfoConnection1;
            this.LastPlanYear.MultiSetWhere = false;
            this.LastPlanYear.Name = "LastPlanYear";
            this.LastPlanYear.NotificationAutoEnlist = false;
            this.LastPlanYear.SecExcept = null;
            this.LastPlanYear.SecFieldName = null;
            this.LastPlanYear.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.LastPlanYear.SelectPaging = false;
            this.LastPlanYear.SelectTop = 0;
            this.LastPlanYear.SiteControl = false;
            this.LastPlanYear.SiteFieldName = null;
            this.LastPlanYear.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CourseType
            // 
            this.CourseType.CacheConnection = false;
            this.CourseType.CommandText = "SELECT ID,NAME FROM LISTCOURSETYPE ORDER BY ID";
            this.CourseType.CommandTimeout = 30;
            this.CourseType.CommandType = System.Data.CommandType.Text;
            this.CourseType.DynamicTableName = false;
            this.CourseType.EEPAlias = null;
            this.CourseType.EncodingAfter = null;
            this.CourseType.EncodingBefore = "Windows-1252";
            this.CourseType.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "ID";
            this.CourseType.KeyFields.Add(keyItem6);
            this.CourseType.MultiSetWhere = false;
            this.CourseType.Name = "CourseType";
            this.CourseType.NotificationAutoEnlist = false;
            this.CourseType.SecExcept = null;
            this.CourseType.SecFieldName = null;
            this.CourseType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CourseType.SelectPaging = false;
            this.CourseType.SelectTop = 0;
            this.CourseType.SiteControl = false;
            this.CourseType.SiteFieldName = null;
            this.CourseType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CourseMethod
            // 
            this.CourseMethod.CacheConnection = false;
            this.CourseMethod.CommandText = "SELECT ID,NAME\r\nFROM LISTCOURSEMETHOD\r\nORDER BY ID";
            this.CourseMethod.CommandTimeout = 30;
            this.CourseMethod.CommandType = System.Data.CommandType.Text;
            this.CourseMethod.DynamicTableName = false;
            this.CourseMethod.EEPAlias = null;
            this.CourseMethod.EncodingAfter = null;
            this.CourseMethod.EncodingBefore = "Windows-1252";
            this.CourseMethod.InfoConnection = this.InfoConnection1;
            keyItem7.KeyName = "ID";
            this.CourseMethod.KeyFields.Add(keyItem7);
            this.CourseMethod.MultiSetWhere = false;
            this.CourseMethod.Name = "CourseMethod";
            this.CourseMethod.NotificationAutoEnlist = false;
            this.CourseMethod.SecExcept = null;
            this.CourseMethod.SecFieldName = null;
            this.CourseMethod.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CourseMethod.SelectPaging = false;
            this.CourseMethod.SelectTop = 0;
            this.CourseMethod.SiteControl = false;
            this.CourseMethod.SiteFieldName = null;
            this.CourseMethod.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // TestMethod
            // 
            this.TestMethod.CacheConnection = false;
            this.TestMethod.CommandText = "SELECT ID,NAME FROM ListTestMethod";
            this.TestMethod.CommandTimeout = 30;
            this.TestMethod.CommandType = System.Data.CommandType.Text;
            this.TestMethod.DynamicTableName = false;
            this.TestMethod.EEPAlias = null;
            this.TestMethod.EncodingAfter = null;
            this.TestMethod.EncodingBefore = "Windows-1252";
            this.TestMethod.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "ID";
            this.TestMethod.KeyFields.Add(keyItem8);
            this.TestMethod.MultiSetWhere = false;
            this.TestMethod.Name = "TestMethod";
            this.TestMethod.NotificationAutoEnlist = false;
            this.TestMethod.SecExcept = null;
            this.TestMethod.SecFieldName = null;
            this.TestMethod.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.TestMethod.SelectPaging = false;
            this.TestMethod.SelectTop = 0;
            this.TestMethod.SiteControl = false;
            this.TestMethod.SiteFieldName = null;
            this.TestMethod.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // TRCompany
            // 
            this.TRCompany.CacheConnection = false;
            this.TRCompany.CommandText = "SELECT ID,NAME  FROM TRAININGCOMPANY\r\nORDER BY NAME";
            this.TRCompany.CommandTimeout = 30;
            this.TRCompany.CommandType = System.Data.CommandType.Text;
            this.TRCompany.DynamicTableName = false;
            this.TRCompany.EEPAlias = null;
            this.TRCompany.EncodingAfter = null;
            this.TRCompany.EncodingBefore = "Windows-1252";
            this.TRCompany.InfoConnection = this.InfoConnection1;
            keyItem9.KeyName = "ID";
            this.TRCompany.KeyFields.Add(keyItem9);
            this.TRCompany.MultiSetWhere = false;
            this.TRCompany.Name = "TRCompany";
            this.TRCompany.NotificationAutoEnlist = false;
            this.TRCompany.SecExcept = null;
            this.TRCompany.SecFieldName = null;
            this.TRCompany.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.TRCompany.SelectPaging = false;
            this.TRCompany.SelectTop = 0;
            this.TRCompany.SiteControl = false;
            this.TRCompany.SiteFieldName = null;
            this.TRCompany.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // TRLocation
            // 
            this.TRLocation.CacheConnection = false;
            this.TRLocation.CommandText = "SELECT ID,NAME FROM COURSELOCATION";
            this.TRLocation.CommandTimeout = 30;
            this.TRLocation.CommandType = System.Data.CommandType.Text;
            this.TRLocation.DynamicTableName = false;
            this.TRLocation.EEPAlias = null;
            this.TRLocation.EncodingAfter = null;
            this.TRLocation.EncodingBefore = "Windows-1252";
            this.TRLocation.InfoConnection = this.InfoConnection1;
            keyItem10.KeyName = "ID";
            this.TRLocation.KeyFields.Add(keyItem10);
            this.TRLocation.MultiSetWhere = false;
            this.TRLocation.Name = "TRLocation";
            this.TRLocation.NotificationAutoEnlist = false;
            this.TRLocation.SecExcept = null;
            this.TRLocation.SecFieldName = null;
            this.TRLocation.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.TRLocation.SelectPaging = false;
            this.TRLocation.SelectTop = 0;
            this.TRLocation.SiteControl = false;
            this.TRLocation.SiteFieldName = null;
            this.TRLocation.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Teacher
            // 
            this.Teacher.CacheConnection = false;
            this.Teacher.CommandText = "SELECT A.STUDENTID,A.COURSEID,B.TEACHERNAME\r\nFROM STUDENTSCOURSES A,TEACHER B\r\nWH" +
    "ERE A.STUDENTID=B.TEACHERID";
            this.Teacher.CommandTimeout = 30;
            this.Teacher.CommandType = System.Data.CommandType.Text;
            this.Teacher.DynamicTableName = false;
            this.Teacher.EEPAlias = null;
            this.Teacher.EncodingAfter = null;
            this.Teacher.EncodingBefore = "Windows-1252";
            this.Teacher.InfoConnection = this.InfoConnection1;
            this.Teacher.MultiSetWhere = false;
            this.Teacher.Name = "Teacher";
            this.Teacher.NotificationAutoEnlist = false;
            this.Teacher.SecExcept = null;
            this.Teacher.SecFieldName = null;
            this.Teacher.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Teacher.SelectPaging = false;
            this.Teacher.SelectTop = 0;
            this.Teacher.SiteControl = false;
            this.Teacher.SiteFieldName = null;
            this.Teacher.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CourseData
            // 
            this.CourseData.CacheConnection = false;
            this.CourseData.CommandText = "SELECT CourseDataID,CourseDataName\r\nFROM COURSEDATA\r\nWHERE 1=2";
            this.CourseData.CommandTimeout = 30;
            this.CourseData.CommandType = System.Data.CommandType.Text;
            this.CourseData.DynamicTableName = false;
            this.CourseData.EEPAlias = null;
            this.CourseData.EncodingAfter = null;
            this.CourseData.EncodingBefore = "Windows-1252";
            this.CourseData.InfoConnection = this.InfoConnection1;
            keyItem11.KeyName = "CourseDataID";
            this.CourseData.KeyFields.Add(keyItem11);
            this.CourseData.MultiSetWhere = false;
            this.CourseData.Name = "CourseData";
            this.CourseData.NotificationAutoEnlist = false;
            this.CourseData.SecExcept = null;
            this.CourseData.SecFieldName = null;
            this.CourseData.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CourseData.SelectPaging = false;
            this.CourseData.SelectTop = 0;
            this.CourseData.SiteControl = false;
            this.CourseData.SiteFieldName = null;
            this.CourseData.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // SpreadType
            // 
            this.SpreadType.CacheConnection = false;
            this.SpreadType.CommandText = "SELECT ID ,NAME FROM LISTTABLE \r\nWHERE CLASS=\'SpreadType\'\r\nORDER BY ID";
            this.SpreadType.CommandTimeout = 30;
            this.SpreadType.CommandType = System.Data.CommandType.Text;
            this.SpreadType.DynamicTableName = false;
            this.SpreadType.EEPAlias = null;
            this.SpreadType.EncodingAfter = null;
            this.SpreadType.EncodingBefore = "Windows-1252";
            this.SpreadType.InfoConnection = this.InfoConnection1;
            this.SpreadType.MultiSetWhere = false;
            this.SpreadType.Name = "SpreadType";
            this.SpreadType.NotificationAutoEnlist = false;
            this.SpreadType.SecExcept = null;
            this.SpreadType.SecFieldName = null;
            this.SpreadType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.SpreadType.SelectPaging = false;
            this.SpreadType.SelectTop = 0;
            this.SpreadType.SiteControl = false;
            this.SpreadType.SiteFieldName = null;
            this.SpreadType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CourseOpenType
            // 
            this.CourseOpenType.CacheConnection = false;
            this.CourseOpenType.CommandText = "SELECT   ID,NAME\r\n FROM ListTable\r\nWHERE CLASS=\'CourseOpenType\'\r\nORDER BY ID\r\n";
            this.CourseOpenType.CommandTimeout = 30;
            this.CourseOpenType.CommandType = System.Data.CommandType.Text;
            this.CourseOpenType.DynamicTableName = false;
            this.CourseOpenType.EEPAlias = null;
            this.CourseOpenType.EncodingAfter = null;
            this.CourseOpenType.EncodingBefore = "Windows-1252";
            this.CourseOpenType.InfoConnection = this.InfoConnection1;
            this.CourseOpenType.MultiSetWhere = false;
            this.CourseOpenType.Name = "CourseOpenType";
            this.CourseOpenType.NotificationAutoEnlist = false;
            this.CourseOpenType.SecExcept = null;
            this.CourseOpenType.SecFieldName = null;
            this.CourseOpenType.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CourseOpenType.SelectPaging = false;
            this.CourseOpenType.SelectTop = 0;
            this.CourseOpenType.SiteControl = false;
            this.CourseOpenType.SiteFieldName = null;
            this.CourseOpenType.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // StudentTree
            // 
            this.StudentTree.CacheConnection = false;
            this.StudentTree.CommandText = resources.GetString("StudentTree.CommandText");
            this.StudentTree.CommandTimeout = 30;
            this.StudentTree.CommandType = System.Data.CommandType.Text;
            this.StudentTree.DynamicTableName = false;
            this.StudentTree.EEPAlias = null;
            this.StudentTree.EncodingAfter = null;
            this.StudentTree.EncodingBefore = "Windows-1252";
            this.StudentTree.InfoConnection = this.InfoConnection1;
            keyItem12.KeyName = "CourseID";
            this.StudentTree.KeyFields.Add(keyItem12);
            this.StudentTree.MultiSetWhere = false;
            this.StudentTree.Name = "StudentTree";
            this.StudentTree.NotificationAutoEnlist = false;
            this.StudentTree.SecExcept = null;
            this.StudentTree.SecFieldName = null;
            this.StudentTree.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.StudentTree.SelectPaging = false;
            this.StudentTree.SelectTop = 0;
            this.StudentTree.SiteControl = false;
            this.StudentTree.SiteFieldName = null;
            this.StudentTree.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ExamPaper
            // 
            this.ExamPaper.CacheConnection = false;
            this.ExamPaper.CommandText = "SELECT ExamPaperID,Name\r\nFROM ExamPaper\r\nWHERE ExamPaperID=0";
            this.ExamPaper.CommandTimeout = 30;
            this.ExamPaper.CommandType = System.Data.CommandType.Text;
            this.ExamPaper.DynamicTableName = false;
            this.ExamPaper.EEPAlias = null;
            this.ExamPaper.EncodingAfter = null;
            this.ExamPaper.EncodingBefore = "Windows-1252";
            this.ExamPaper.InfoConnection = this.InfoConnection1;
            this.ExamPaper.MultiSetWhere = false;
            this.ExamPaper.Name = "ExamPaper";
            this.ExamPaper.NotificationAutoEnlist = false;
            this.ExamPaper.SecExcept = null;
            this.ExamPaper.SecFieldName = null;
            this.ExamPaper.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ExamPaper.SelectPaging = false;
            this.ExamPaper.SelectTop = 0;
            this.ExamPaper.SiteControl = false;
            this.ExamPaper.SiteFieldName = null;
            this.ExamPaper.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // OpenStatus
            // 
            this.OpenStatus.CacheConnection = false;
            this.OpenStatus.CommandText = "SELECT ID,NAME\r\nFROM LISTTABLE \r\nWHERE CLASS=\'CourseOpenStatus\'\r\nORDER BY ID";
            this.OpenStatus.CommandTimeout = 30;
            this.OpenStatus.CommandType = System.Data.CommandType.Text;
            this.OpenStatus.DynamicTableName = false;
            this.OpenStatus.EEPAlias = null;
            this.OpenStatus.EncodingAfter = null;
            this.OpenStatus.EncodingBefore = "Windows-1252";
            this.OpenStatus.InfoConnection = this.InfoConnection1;
            this.OpenStatus.MultiSetWhere = false;
            this.OpenStatus.Name = "OpenStatus";
            this.OpenStatus.NotificationAutoEnlist = false;
            this.OpenStatus.SecExcept = null;
            this.OpenStatus.SecFieldName = null;
            this.OpenStatus.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.OpenStatus.SelectPaging = false;
            this.OpenStatus.SelectTop = 0;
            this.OpenStatus.SiteControl = false;
            this.OpenStatus.SiteFieldName = null;
            this.OpenStatus.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CoursePlanDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_CoursePlanDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.YearNO)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CoursePlan)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseOpenRecord)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseBookBill)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastPlanYear)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseMethod)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TestMethod)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TRCompany)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TRLocation)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Teacher)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseData)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SpreadType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CourseOpenType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.StudentTree)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ExamPaper)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.OpenStatus)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand CoursePlanDetails;
        private Srvtools.UpdateComponent ucCoursePlanDetails;
        private Srvtools.InfoCommand View_CoursePlanDetails;
        private Srvtools.InfoCommand YearNO;
        private Srvtools.InfoCommand CoursePlan;
        private Srvtools.InfoCommand CourseOpenRecord;
        private Srvtools.UpdateComponent updateComponent1;
        private Srvtools.InfoCommand CourseBookBill;
        private Srvtools.UpdateComponent updateComponent2;
        private Srvtools.InfoCommand LastPlanYear;
        private Srvtools.InfoCommand CourseType;
        private Srvtools.InfoCommand CourseMethod;
        private Srvtools.InfoCommand TestMethod;
        private Srvtools.InfoCommand TRCompany;
        private Srvtools.InfoCommand TRLocation;
        private Srvtools.InfoCommand Teacher;
        private Srvtools.InfoCommand CourseData;
        private Srvtools.InfoCommand SpreadType;
        private Srvtools.InfoCommand CourseOpenType;
        private Srvtools.InfoCommand StudentTree;
        private Srvtools.InfoCommand ExamPaper;
        private Srvtools.InfoCommand OpenStatus;
    }
}
