//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEPNetServer.CetusAPI {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.cetustek.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.cetustek.com/", ConfigurationName="CetusAPI.InvoiceAPI")]
    public interface InvoiceAPI {
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/CancelAllowanceRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/CancelAllowanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/CancelAllowance/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.CancelAllowanceResponse CancelAllowance(EEPNetServer.CetusAPI.CancelAllowanceRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/CancelInvoiceRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/CancelInvoiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/CancelInvoice/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.CancelInvoiceResponse CancelInvoice(EEPNetServer.CetusAPI.CancelInvoiceRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/CancelInvoiceNoCheckRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/CancelInvoiceNoCheckResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/CancelInvoiceNoCheck/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.CancelInvoiceNoCheckResponse CancelInvoiceNoCheck(EEPNetServer.CetusAPI.CancelInvoiceNoCheckRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/QueryAllowanceRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/QueryAllowanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/QueryAllowance/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.QueryAllowanceResponse QueryAllowance(EEPNetServer.CetusAPI.QueryAllowanceRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/QueryInvoiceByOrderidRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/QueryInvoiceByOrderidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/QueryInvoiceByOrderid/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.QueryInvoiceByOrderidResponse QueryInvoiceByOrderid(EEPNetServer.CetusAPI.QueryInvoiceByOrderidRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/QueryInvoiceNumberByOrderidRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/QueryInvoiceNumberByOrderidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/QueryInvoiceNumberByOrderid/Fault/Excep" +
            "tion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.QueryInvoiceNumberByOrderidResponse QueryInvoiceNumberByOrderid(EEPNetServer.CetusAPI.QueryInvoiceNumberByOrderidRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/QueryInvoiceRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/QueryInvoiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/QueryInvoice/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.QueryInvoiceResponse QueryInvoice(EEPNetServer.CetusAPI.QueryInvoiceRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/QueryLoveCodeRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/QueryLoveCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.QueryLoveCodeResponse QueryLoveCode(EEPNetServer.CetusAPI.QueryLoveCodeRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/CreateAllowanceRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/CreateAllowanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/CreateAllowance/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.CreateAllowanceResponse CreateAllowance(EEPNetServer.CetusAPI.CreateAllowanceRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/CreateInvoiceV3Request", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/CreateInvoiceV3Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/CreateInvoiceV3/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.CreateInvoiceV3Response CreateInvoiceV3(EEPNetServer.CetusAPI.CreateInvoiceV3Request request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.cetustek.com/InvoiceAPI/QueryWinningInvoiceRequest", ReplyAction="http://webservice.cetustek.com/InvoiceAPI/QueryWinningInvoiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EEPNetServer.CetusAPI.Exception), Action="http://webservice.cetustek.com/InvoiceAPI/QueryWinningInvoice/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EEPNetServer.CetusAPI.QueryWinningInvoiceResponse QueryWinningInvoice(EEPNetServer.CetusAPI.QueryWinningInvoiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelAllowance", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CancelAllowanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string allowancexml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public CancelAllowanceRequest() {
        }
        
        public CancelAllowanceRequest(string allowancexml, string rentid, string source) {
            this.allowancexml = allowancexml;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelAllowanceResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CancelAllowanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CancelAllowanceResponse() {
        }
        
        public CancelAllowanceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelInvoice", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CancelInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string invoicexml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public CancelInvoiceRequest() {
        }
        
        public CancelInvoiceRequest(string invoicexml, string rentid, string source) {
            this.invoicexml = invoicexml;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelInvoiceResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CancelInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CancelInvoiceResponse() {
        }
        
        public CancelInvoiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelInvoiceNoCheck", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CancelInvoiceNoCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string invoicexml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public CancelInvoiceNoCheckRequest() {
        }
        
        public CancelInvoiceNoCheckRequest(string invoicexml, string rentid, string source) {
            this.invoicexml = invoicexml;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelInvoiceNoCheckResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CancelInvoiceNoCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CancelInvoiceNoCheckResponse() {
        }
        
        public CancelInvoiceNoCheckResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllowance", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryAllowanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string allowancenumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public QueryAllowanceRequest() {
        }
        
        public QueryAllowanceRequest(string allowancenumber, string rentid, string source) {
            this.allowancenumber = allowancenumber;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllowanceResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryAllowanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryAllowanceResponse() {
        }
        
        public QueryAllowanceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryInvoiceByOrderid", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryInvoiceByOrderidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public QueryInvoiceByOrderidRequest() {
        }
        
        public QueryInvoiceByOrderidRequest(string orderid, string rentid, string source) {
            this.orderid = orderid;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryInvoiceByOrderidResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryInvoiceByOrderidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryInvoiceByOrderidResponse() {
        }
        
        public QueryInvoiceByOrderidResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryInvoiceNumberByOrderid", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryInvoiceNumberByOrderidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public QueryInvoiceNumberByOrderidRequest() {
        }
        
        public QueryInvoiceNumberByOrderidRequest(string orderid, string rentid, string source) {
            this.orderid = orderid;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryInvoiceNumberByOrderidResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryInvoiceNumberByOrderidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryInvoiceNumberByOrderidResponse() {
        }
        
        public QueryInvoiceNumberByOrderidResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryInvoice", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string invoicenumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string invoiceyear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public QueryInvoiceRequest() {
        }
        
        public QueryInvoiceRequest(string invoicenumber, string invoiceyear, string rentid, string source) {
            this.invoicenumber = invoicenumber;
            this.invoiceyear = invoiceyear;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryInvoiceResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryInvoiceResponse() {
        }
        
        public QueryInvoiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLoveCode", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryLoveCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public QueryLoveCodeRequest() {
        }
        
        public QueryLoveCodeRequest(string rentid, string source) {
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLoveCodeResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryLoveCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryLoveCodeResponse() {
        }
        
        public QueryLoveCodeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAllowance", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CreateAllowanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string allowancexml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string checkallowance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public CreateAllowanceRequest() {
        }
        
        public CreateAllowanceRequest(string allowancexml, string checkallowance, string rentid, string source) {
            this.allowancexml = allowancexml;
            this.checkallowance = checkallowance;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAllowanceResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CreateAllowanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CreateAllowanceResponse() {
        }
        
        public CreateAllowanceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateInvoiceV3", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CreateInvoiceV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string invoicexml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hastax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public CreateInvoiceV3Request() {
        }
        
        public CreateInvoiceV3Request(string invoicexml, string hastax, string rentid, string source) {
            this.invoicexml = invoicexml;
            this.hastax = hastax;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateInvoiceV3Response", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class CreateInvoiceV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CreateInvoiceV3Response() {
        }
        
        public CreateInvoiceV3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryWinningInvoice", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryWinningInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string winningyear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string winningmonth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rentid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source;
        
        public QueryWinningInvoiceRequest() {
        }
        
        public QueryWinningInvoiceRequest(string winningyear, string winningmonth, string rentid, string source) {
            this.winningyear = winningyear;
            this.winningmonth = winningmonth;
            this.rentid = rentid;
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryWinningInvoiceResponse", WrapperNamespace="http://webservice.cetustek.com/", IsWrapped=true)]
    public partial class QueryWinningInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.cetustek.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryWinningInvoiceResponse() {
        }
        
        public QueryWinningInvoiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvoiceAPIChannel : EEPNetServer.CetusAPI.InvoiceAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvoiceAPIClient : System.ServiceModel.ClientBase<EEPNetServer.CetusAPI.InvoiceAPI>, EEPNetServer.CetusAPI.InvoiceAPI {
        
        public InvoiceAPIClient() {
        }
        
        public InvoiceAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvoiceAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.CancelAllowanceResponse EEPNetServer.CetusAPI.InvoiceAPI.CancelAllowance(EEPNetServer.CetusAPI.CancelAllowanceRequest request) {
            return base.Channel.CancelAllowance(request);
        }
        
        public string CancelAllowance(string allowancexml, string rentid, string source) {
            EEPNetServer.CetusAPI.CancelAllowanceRequest inValue = new EEPNetServer.CetusAPI.CancelAllowanceRequest();
            inValue.allowancexml = allowancexml;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.CancelAllowanceResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).CancelAllowance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.CancelInvoiceResponse EEPNetServer.CetusAPI.InvoiceAPI.CancelInvoice(EEPNetServer.CetusAPI.CancelInvoiceRequest request) {
            return base.Channel.CancelInvoice(request);
        }
        
        public string CancelInvoice(string invoicexml, string rentid, string source) {
            EEPNetServer.CetusAPI.CancelInvoiceRequest inValue = new EEPNetServer.CetusAPI.CancelInvoiceRequest();
            inValue.invoicexml = invoicexml;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.CancelInvoiceResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).CancelInvoice(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.CancelInvoiceNoCheckResponse EEPNetServer.CetusAPI.InvoiceAPI.CancelInvoiceNoCheck(EEPNetServer.CetusAPI.CancelInvoiceNoCheckRequest request) {
            return base.Channel.CancelInvoiceNoCheck(request);
        }
        
        public string CancelInvoiceNoCheck(string invoicexml, string rentid, string source) {
            EEPNetServer.CetusAPI.CancelInvoiceNoCheckRequest inValue = new EEPNetServer.CetusAPI.CancelInvoiceNoCheckRequest();
            inValue.invoicexml = invoicexml;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.CancelInvoiceNoCheckResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).CancelInvoiceNoCheck(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.QueryAllowanceResponse EEPNetServer.CetusAPI.InvoiceAPI.QueryAllowance(EEPNetServer.CetusAPI.QueryAllowanceRequest request) {
            return base.Channel.QueryAllowance(request);
        }
        
        public string QueryAllowance(string allowancenumber, string rentid, string source) {
            EEPNetServer.CetusAPI.QueryAllowanceRequest inValue = new EEPNetServer.CetusAPI.QueryAllowanceRequest();
            inValue.allowancenumber = allowancenumber;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.QueryAllowanceResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).QueryAllowance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.QueryInvoiceByOrderidResponse EEPNetServer.CetusAPI.InvoiceAPI.QueryInvoiceByOrderid(EEPNetServer.CetusAPI.QueryInvoiceByOrderidRequest request) {
            return base.Channel.QueryInvoiceByOrderid(request);
        }
        
        public string QueryInvoiceByOrderid(string orderid, string rentid, string source) {
            EEPNetServer.CetusAPI.QueryInvoiceByOrderidRequest inValue = new EEPNetServer.CetusAPI.QueryInvoiceByOrderidRequest();
            inValue.orderid = orderid;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.QueryInvoiceByOrderidResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).QueryInvoiceByOrderid(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.QueryInvoiceNumberByOrderidResponse EEPNetServer.CetusAPI.InvoiceAPI.QueryInvoiceNumberByOrderid(EEPNetServer.CetusAPI.QueryInvoiceNumberByOrderidRequest request) {
            return base.Channel.QueryInvoiceNumberByOrderid(request);
        }
        
        public string QueryInvoiceNumberByOrderid(string orderid, string rentid, string source) {
            EEPNetServer.CetusAPI.QueryInvoiceNumberByOrderidRequest inValue = new EEPNetServer.CetusAPI.QueryInvoiceNumberByOrderidRequest();
            inValue.orderid = orderid;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.QueryInvoiceNumberByOrderidResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).QueryInvoiceNumberByOrderid(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.QueryInvoiceResponse EEPNetServer.CetusAPI.InvoiceAPI.QueryInvoice(EEPNetServer.CetusAPI.QueryInvoiceRequest request) {
            return base.Channel.QueryInvoice(request);
        }
        
        public string QueryInvoice(string invoicenumber, string invoiceyear, string rentid, string source) {
            EEPNetServer.CetusAPI.QueryInvoiceRequest inValue = new EEPNetServer.CetusAPI.QueryInvoiceRequest();
            inValue.invoicenumber = invoicenumber;
            inValue.invoiceyear = invoiceyear;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.QueryInvoiceResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).QueryInvoice(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.QueryLoveCodeResponse EEPNetServer.CetusAPI.InvoiceAPI.QueryLoveCode(EEPNetServer.CetusAPI.QueryLoveCodeRequest request) {
            return base.Channel.QueryLoveCode(request);
        }
        
        public string QueryLoveCode(string rentid, string source) {
            EEPNetServer.CetusAPI.QueryLoveCodeRequest inValue = new EEPNetServer.CetusAPI.QueryLoveCodeRequest();
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.QueryLoveCodeResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).QueryLoveCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.CreateAllowanceResponse EEPNetServer.CetusAPI.InvoiceAPI.CreateAllowance(EEPNetServer.CetusAPI.CreateAllowanceRequest request) {
            return base.Channel.CreateAllowance(request);
        }
        
        public string CreateAllowance(string allowancexml, string checkallowance, string rentid, string source) {
            EEPNetServer.CetusAPI.CreateAllowanceRequest inValue = new EEPNetServer.CetusAPI.CreateAllowanceRequest();
            inValue.allowancexml = allowancexml;
            inValue.checkallowance = checkallowance;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.CreateAllowanceResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).CreateAllowance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.CreateInvoiceV3Response EEPNetServer.CetusAPI.InvoiceAPI.CreateInvoiceV3(EEPNetServer.CetusAPI.CreateInvoiceV3Request request) {
            return base.Channel.CreateInvoiceV3(request);
        }
        
        public string CreateInvoiceV3(string invoicexml, string hastax, string rentid, string source) {
            EEPNetServer.CetusAPI.CreateInvoiceV3Request inValue = new EEPNetServer.CetusAPI.CreateInvoiceV3Request();
            inValue.invoicexml = invoicexml;
            inValue.hastax = hastax;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.CreateInvoiceV3Response retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).CreateInvoiceV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EEPNetServer.CetusAPI.QueryWinningInvoiceResponse EEPNetServer.CetusAPI.InvoiceAPI.QueryWinningInvoice(EEPNetServer.CetusAPI.QueryWinningInvoiceRequest request) {
            return base.Channel.QueryWinningInvoice(request);
        }
        
        public string QueryWinningInvoice(string winningyear, string winningmonth, string rentid, string source) {
            EEPNetServer.CetusAPI.QueryWinningInvoiceRequest inValue = new EEPNetServer.CetusAPI.QueryWinningInvoiceRequest();
            inValue.winningyear = winningyear;
            inValue.winningmonth = winningmonth;
            inValue.rentid = rentid;
            inValue.source = source;
            EEPNetServer.CetusAPI.QueryWinningInvoiceResponse retVal = ((EEPNetServer.CetusAPI.InvoiceAPI)(this)).QueryWinningInvoice(inValue);
            return retVal.@return;
        }
    }
}
