namespace sOutDoor
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            Srvtools.Service service9 = new Srvtools.Service();
            Srvtools.Service service10 = new Srvtools.Service();
            Srvtools.Service service11 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.OutDoor = new Srvtools.InfoCommand(this.components);
            this.ucOutDoor = new Srvtools.UpdateComponent(this.components);
            this.View_OutDoor = new Srvtools.InfoCommand(this.components);
            this.OutDoorID = new Srvtools.AutoNumber(this.components);
            this.Device = new Srvtools.InfoCommand(this.components);
            this.HY = new Srvtools.InfoCommand(this.components);
            this.HYGate = new Srvtools.InfoCommand(this.components);
            this.Employee = new Srvtools.InfoCommand(this.components);
            this.oilrate = new Srvtools.InfoCommand(this.components);
            this.targets = new Srvtools.InfoCommand(this.components);
            this.CostCenter = new Srvtools.InfoCommand(this.components);
            this.Organization = new Srvtools.InfoCommand(this.components);
            this.OutDoorList = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.OutDoor)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_OutDoor)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Device)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.HY)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.HYGate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Employee)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.oilrate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.targets)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CostCenter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Organization)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.OutDoorList)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "GetFromToFee";
            service1.NonLogin = false;
            service1.ServiceName = "GetFromToFee";
            service2.DelegateName = "GetOilRateByOutDate";
            service2.NonLogin = false;
            service2.ServiceName = "GetOilRateByOutDate";
            service3.DelegateName = "PutFeeToPettyCash";
            service3.NonLogin = false;
            service3.ServiceName = "PutFeeToPettyCash";
            service4.DelegateName = "CheckDeviceOverlap";
            service4.NonLogin = false;
            service4.ServiceName = "CheckDeviceOverlap";
            service5.DelegateName = "CheckEmpOutOverlap";
            service5.NonLogin = false;
            service5.ServiceName = "CheckEmpOutOverlap";
            service6.DelegateName = "GetEmpFlowAgentList";
            service6.NonLogin = false;
            service6.ServiceName = "GetEmpFlowAgentList";
            service7.DelegateName = "GetUserOrgNOs";
            service7.NonLogin = false;
            service7.ServiceName = "GetUserOrgNOs";
            service8.DelegateName = "GetEmpOutDoorList";
            service8.NonLogin = false;
            service8.ServiceName = "GetEmpOutDoorList";
            service9.DelegateName = "CheckApplyEmpIsGroupID";
            service9.NonLogin = false;
            service9.ServiceName = "CheckApplyEmpIsGroupID";
            service10.DelegateName = "GetPeriodWorkDays";
            service10.NonLogin = false;
            service10.ServiceName = "GetPeriodWorkDays";
            service11.DelegateName = "GetUserOrgNO";
            service11.NonLogin = false;
            service11.ServiceName = "GetUserOrgNO";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            this.serviceManager1.ServiceCollection.Add(service9);
            this.serviceManager1.ServiceCollection.Add(service10);
            this.serviceManager1.ServiceCollection.Add(service11);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // OutDoor
            // 
            this.OutDoor.CacheConnection = false;
            this.OutDoor.CommandText = resources.GetString("OutDoor.CommandText");
            this.OutDoor.CommandTimeout = 30;
            this.OutDoor.CommandType = System.Data.CommandType.Text;
            this.OutDoor.DynamicTableName = false;
            this.OutDoor.EEPAlias = null;
            this.OutDoor.EncodingAfter = null;
            this.OutDoor.EncodingBefore = "Windows-1252";
            this.OutDoor.EncodingConvert = null;
            this.OutDoor.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "OutDoorID";
            this.OutDoor.KeyFields.Add(keyItem1);
            this.OutDoor.MultiSetWhere = false;
            this.OutDoor.Name = "OutDoor";
            this.OutDoor.NotificationAutoEnlist = false;
            this.OutDoor.SecExcept = null;
            this.OutDoor.SecFieldName = null;
            this.OutDoor.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.OutDoor.SelectPaging = false;
            this.OutDoor.SelectTop = 0;
            this.OutDoor.SiteControl = false;
            this.OutDoor.SiteFieldName = null;
            this.OutDoor.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucOutDoor
            // 
            this.ucOutDoor.AutoTrans = true;
            this.ucOutDoor.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "OutDoorID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "ApplyDate";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "ApplyEmpID";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "DeviceItemsID";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "OutDateSta";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "OutDateEnd";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "StaTime";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "EndTime";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "Goal";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "Targets";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "OutLine";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "OutCome";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "Mileage";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "StaMile";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "EndMile";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "OilRate";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "TrafficFee";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "ParkingFee";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "HighWayFee";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "TotalFee";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "HYID1";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "FromHYGate1";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "ToHYGate1";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "Kms1";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "HYID2";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "FromHYGate2";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "ToHYGate2";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "Kms2";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "HYID3";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "FromHYGate3";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "ToHYGate3";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "Kms3";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "HYID4";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "FromHYGate4";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "ToHYGate4";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "Kms4";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "HYID5";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "FromHYGate5";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "ToHYGate5";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "Kms5";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "HYID6";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "FromHYGate6";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "ToHYGate6";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "Kms6";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "Flowflag";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = true;
            fieldAttr46.DataField = "CreateBy";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = "_username";
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "CreateDate";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "CommitUser";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr48.DefaultValue = "_username";
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            this.ucOutDoor.FieldAttrs.Add(fieldAttr1);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr2);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr3);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr4);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr5);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr6);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr7);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr8);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr9);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr10);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr11);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr12);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr13);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr14);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr15);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr16);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr17);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr18);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr19);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr20);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr21);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr22);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr23);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr24);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr25);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr26);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr27);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr28);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr29);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr30);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr31);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr32);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr33);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr34);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr35);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr36);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr37);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr38);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr39);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr40);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr41);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr42);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr43);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr44);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr45);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr46);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr47);
            this.ucOutDoor.FieldAttrs.Add(fieldAttr48);
            this.ucOutDoor.LogInfo = null;
            this.ucOutDoor.Name = "ucOutDoor";
            this.ucOutDoor.RowAffectsCheck = true;
            this.ucOutDoor.SelectCmd = this.OutDoor;
            this.ucOutDoor.SelectCmdForUpdate = null;
            this.ucOutDoor.SendSQLCmd = true;
            this.ucOutDoor.ServerModify = true;
            this.ucOutDoor.ServerModifyGetMax = false;
            this.ucOutDoor.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucOutDoor.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucOutDoor.UseTranscationScope = false;
            this.ucOutDoor.WhereMode = Srvtools.WhereModeType.Keyfields;
            this.ucOutDoor.BeforeInsert += new Srvtools.UpdateComponentBeforeInsertEventHandler(this.ucOutDoor_BeforeInsert);
            this.ucOutDoor.BeforeModify += new Srvtools.UpdateComponentBeforeModifyEventHandler(this.ucOutDoor_BeforeModify);
            // 
            // View_OutDoor
            // 
            this.View_OutDoor.CacheConnection = false;
            this.View_OutDoor.CommandText = "SELECT * FROM dbo.[OutDoor]";
            this.View_OutDoor.CommandTimeout = 30;
            this.View_OutDoor.CommandType = System.Data.CommandType.Text;
            this.View_OutDoor.DynamicTableName = false;
            this.View_OutDoor.EEPAlias = null;
            this.View_OutDoor.EncodingAfter = null;
            this.View_OutDoor.EncodingBefore = "Windows-1252";
            this.View_OutDoor.EncodingConvert = null;
            this.View_OutDoor.InfoConnection = this.InfoConnection1;
            this.View_OutDoor.MultiSetWhere = false;
            this.View_OutDoor.Name = "View_OutDoor";
            this.View_OutDoor.NotificationAutoEnlist = false;
            this.View_OutDoor.SecExcept = null;
            this.View_OutDoor.SecFieldName = null;
            this.View_OutDoor.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_OutDoor.SelectPaging = false;
            this.View_OutDoor.SelectTop = 0;
            this.View_OutDoor.SiteControl = false;
            this.View_OutDoor.SiteFieldName = null;
            this.View_OutDoor.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // OutDoorID
            // 
            this.OutDoorID.Active = true;
            this.OutDoorID.AutoNoID = "OutDoorID";
            this.OutDoorID.Description = null;
            this.OutDoorID.GetFixed = "O";
            this.OutDoorID.isNumFill = false;
            this.OutDoorID.Name = "OutDoorID";
            this.OutDoorID.Number = null;
            this.OutDoorID.NumDig = 8;
            this.OutDoorID.OldVersion = false;
            this.OutDoorID.OverFlow = true;
            this.OutDoorID.StartValue = 1;
            this.OutDoorID.Step = 1;
            this.OutDoorID.TargetColumn = "OutDoorID";
            this.OutDoorID.UpdateComp = this.ucOutDoor;
            // 
            // Device
            // 
            this.Device.CacheConnection = false;
            this.Device.CommandText = resources.GetString("Device.CommandText");
            this.Device.CommandTimeout = 30;
            this.Device.CommandType = System.Data.CommandType.Text;
            this.Device.DynamicTableName = false;
            this.Device.EEPAlias = null;
            this.Device.EncodingAfter = null;
            this.Device.EncodingBefore = "Windows-1252";
            this.Device.EncodingConvert = null;
            this.Device.InfoConnection = this.InfoConnection1;
            this.Device.MultiSetWhere = false;
            this.Device.Name = "Device";
            this.Device.NotificationAutoEnlist = false;
            this.Device.SecExcept = null;
            this.Device.SecFieldName = null;
            this.Device.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Device.SelectPaging = false;
            this.Device.SelectTop = 0;
            this.Device.SiteControl = false;
            this.Device.SiteFieldName = null;
            this.Device.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // HY
            // 
            this.HY.CacheConnection = false;
            this.HY.CommandText = "select  DISTINCT   HYGate.HYID,HYGate.HYName \r\nfrom HYGate\r\n";
            this.HY.CommandTimeout = 30;
            this.HY.CommandType = System.Data.CommandType.Text;
            this.HY.DynamicTableName = false;
            this.HY.EEPAlias = null;
            this.HY.EncodingAfter = null;
            this.HY.EncodingBefore = "Windows-1252";
            this.HY.EncodingConvert = null;
            this.HY.InfoConnection = this.InfoConnection1;
            this.HY.MultiSetWhere = false;
            this.HY.Name = "HY";
            this.HY.NotificationAutoEnlist = false;
            this.HY.SecExcept = null;
            this.HY.SecFieldName = null;
            this.HY.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.HY.SelectPaging = false;
            this.HY.SelectTop = 0;
            this.HY.SiteControl = false;
            this.HY.SiteFieldName = null;
            this.HY.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // HYGate
            // 
            this.HYGate.CacheConnection = false;
            this.HYGate.CommandText = "select HYGate.HYGate,HYGate.HYID,HYGate.Seq \r\nfrom HYGate\r\nORDER BY HYGate.HYID,H" +
    "YGate.Seq ";
            this.HYGate.CommandTimeout = 30;
            this.HYGate.CommandType = System.Data.CommandType.Text;
            this.HYGate.DynamicTableName = false;
            this.HYGate.EEPAlias = null;
            this.HYGate.EncodingAfter = null;
            this.HYGate.EncodingBefore = "Windows-1252";
            this.HYGate.EncodingConvert = null;
            this.HYGate.InfoConnection = this.InfoConnection1;
            this.HYGate.MultiSetWhere = false;
            this.HYGate.Name = "HYGate";
            this.HYGate.NotificationAutoEnlist = false;
            this.HYGate.SecExcept = null;
            this.HYGate.SecFieldName = null;
            this.HYGate.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.HYGate.SelectPaging = false;
            this.HYGate.SelectTop = 0;
            this.HYGate.SiteControl = false;
            this.HYGate.SiteFieldName = null;
            this.HYGate.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Employee
            // 
            this.Employee.CacheConnection = false;
            this.Employee.CommandText = resources.GetString("Employee.CommandText");
            this.Employee.CommandTimeout = 30;
            this.Employee.CommandType = System.Data.CommandType.Text;
            this.Employee.DynamicTableName = false;
            this.Employee.EEPAlias = null;
            this.Employee.EncodingAfter = null;
            this.Employee.EncodingBefore = "Windows-1252";
            this.Employee.EncodingConvert = null;
            this.Employee.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "EMPLOYEEID";
            this.Employee.KeyFields.Add(keyItem2);
            this.Employee.MultiSetWhere = false;
            this.Employee.Name = "Employee";
            this.Employee.NotificationAutoEnlist = false;
            this.Employee.SecExcept = null;
            this.Employee.SecFieldName = null;
            this.Employee.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Employee.SelectPaging = false;
            this.Employee.SelectTop = 0;
            this.Employee.SiteControl = false;
            this.Employee.SiteFieldName = null;
            this.Employee.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // oilrate
            // 
            this.oilrate.CacheConnection = false;
            this.oilrate.CommandText = "SELECT TOP 1\r\ndbo.funReturnOilRate(1,getdate()) as NCar,\r\ndbo.funReturnOilRate(2," +
    "getdate()) as NMoto,\r\ndbo.funReturnOilRate(3,getdate()) as NEtag\r\nFROM dbo.[Pett" +
    "yCashYM]";
            this.oilrate.CommandTimeout = 30;
            this.oilrate.CommandType = System.Data.CommandType.Text;
            this.oilrate.DynamicTableName = false;
            this.oilrate.EEPAlias = null;
            this.oilrate.EncodingAfter = null;
            this.oilrate.EncodingBefore = "Windows-1252";
            this.oilrate.EncodingConvert = null;
            this.oilrate.InfoConnection = this.InfoConnection1;
            this.oilrate.MultiSetWhere = false;
            this.oilrate.Name = "oilrate";
            this.oilrate.NotificationAutoEnlist = false;
            this.oilrate.SecExcept = null;
            this.oilrate.SecFieldName = null;
            this.oilrate.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.oilrate.SelectPaging = false;
            this.oilrate.SelectTop = 0;
            this.oilrate.SiteControl = false;
            this.oilrate.SiteFieldName = null;
            this.oilrate.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // targets
            // 
            this.targets.CacheConnection = false;
            this.targets.CommandText = "SELECT DISTINCT Targets FROM OutDoor";
            this.targets.CommandTimeout = 30;
            this.targets.CommandType = System.Data.CommandType.Text;
            this.targets.DynamicTableName = false;
            this.targets.EEPAlias = null;
            this.targets.EncodingAfter = null;
            this.targets.EncodingBefore = "Windows-1252";
            this.targets.EncodingConvert = null;
            this.targets.InfoConnection = this.InfoConnection1;
            this.targets.MultiSetWhere = false;
            this.targets.Name = "targets";
            this.targets.NotificationAutoEnlist = false;
            this.targets.SecExcept = null;
            this.targets.SecFieldName = null;
            this.targets.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.targets.SelectPaging = false;
            this.targets.SelectTop = 0;
            this.targets.SiteControl = false;
            this.targets.SiteFieldName = null;
            this.targets.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // CostCenter
            // 
            this.CostCenter.CacheConnection = false;
            this.CostCenter.CommandText = "--select CostCenter.CostCenterID,CostCenter.CostCenterName from CostCenter\r\nSELEC" +
    "T  CostCenterID,CostCenterName   FROM  glCostCenter";
            this.CostCenter.CommandTimeout = 30;
            this.CostCenter.CommandType = System.Data.CommandType.Text;
            this.CostCenter.DynamicTableName = false;
            this.CostCenter.EEPAlias = null;
            this.CostCenter.EncodingAfter = null;
            this.CostCenter.EncodingBefore = "Windows-1252";
            this.CostCenter.EncodingConvert = null;
            this.CostCenter.InfoConnection = this.InfoConnection1;
            this.CostCenter.MultiSetWhere = false;
            this.CostCenter.Name = "CostCenter";
            this.CostCenter.NotificationAutoEnlist = false;
            this.CostCenter.SecExcept = null;
            this.CostCenter.SecFieldName = null;
            this.CostCenter.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.CostCenter.SelectPaging = false;
            this.CostCenter.SelectTop = 0;
            this.CostCenter.SiteControl = false;
            this.CostCenter.SiteFieldName = null;
            this.CostCenter.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // Organization
            // 
            this.Organization.CacheConnection = false;
            this.Organization.CommandText = "SELECT ORG_NO,ORG_DESC,ORG_KIND,UPPER_ORG,CostCenterID FROM EIPHRSYS.dbo.sys_org " +
    "\r\nWHERE (Upper_Org=\'10000\' OR Upper_Org=\'13000\'  OR  ORG_NO=\'10000\' OR ORG_NO=\'9" +
    "9999\')\r\nORDER BY ORG_NO";
            this.Organization.CommandTimeout = 30;
            this.Organization.CommandType = System.Data.CommandType.Text;
            this.Organization.DynamicTableName = false;
            this.Organization.EEPAlias = null;
            this.Organization.EncodingAfter = null;
            this.Organization.EncodingBefore = "Windows-1252";
            this.Organization.EncodingConvert = null;
            this.Organization.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "ORG_NO";
            this.Organization.KeyFields.Add(keyItem3);
            this.Organization.MultiSetWhere = false;
            this.Organization.Name = "Organization";
            this.Organization.NotificationAutoEnlist = false;
            this.Organization.SecExcept = null;
            this.Organization.SecFieldName = null;
            this.Organization.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.Organization.SelectPaging = false;
            this.Organization.SelectTop = 0;
            this.Organization.SiteControl = false;
            this.Organization.SiteFieldName = null;
            this.Organization.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // OutDoorList
            // 
            this.OutDoorList.CacheConnection = false;
            this.OutDoorList.CommandText = resources.GetString("OutDoorList.CommandText");
            this.OutDoorList.CommandTimeout = 30;
            this.OutDoorList.CommandType = System.Data.CommandType.Text;
            this.OutDoorList.DynamicTableName = false;
            this.OutDoorList.EEPAlias = null;
            this.OutDoorList.EncodingAfter = null;
            this.OutDoorList.EncodingBefore = "Windows-1252";
            this.OutDoorList.EncodingConvert = null;
            this.OutDoorList.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "OUTDOORID";
            this.OutDoorList.KeyFields.Add(keyItem4);
            this.OutDoorList.MultiSetWhere = false;
            this.OutDoorList.Name = "OutDoorList";
            this.OutDoorList.NotificationAutoEnlist = false;
            this.OutDoorList.SecExcept = null;
            this.OutDoorList.SecFieldName = null;
            this.OutDoorList.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.OutDoorList.SelectPaging = false;
            this.OutDoorList.SelectTop = 0;
            this.OutDoorList.SiteControl = false;
            this.OutDoorList.SiteFieldName = null;
            this.OutDoorList.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.OutDoor)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_OutDoor)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Device)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.HY)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.HYGate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Employee)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.oilrate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.targets)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CostCenter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Organization)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.OutDoorList)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand OutDoor;
        private Srvtools.UpdateComponent ucOutDoor;
        private Srvtools.InfoCommand View_OutDoor;
        private Srvtools.AutoNumber OutDoorID;
        private Srvtools.InfoCommand Device;
        private Srvtools.InfoCommand HY;
        private Srvtools.InfoCommand HYGate;
        private Srvtools.InfoCommand Employee;
        private Srvtools.InfoCommand oilrate;
        private Srvtools.InfoCommand targets;
        private Srvtools.InfoCommand CostCenter;
        private Srvtools.InfoCommand Organization;
        private Srvtools.InfoCommand OutDoorList;
    }
}
