namespace sBizTravelQuery
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.ColumnItem columnItem1 = new Srvtools.ColumnItem();
            Srvtools.ColumnItem columnItem2 = new Srvtools.ColumnItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.BizTravelMaster = new Srvtools.InfoCommand(this.components);
            this.ucBizTravelMaster = new Srvtools.UpdateComponent(this.components);
            this.BizTravelDetails_Accom = new Srvtools.InfoCommand(this.components);
            this.ucBizTravelDetails_Accom = new Srvtools.UpdateComponent(this.components);
            this.idBizTravelMaster_BizTravelDetails_Accom = new Srvtools.InfoDataSource(this.components);
            this.View_BizTravelMaster = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.BizTravelMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.BizTravelDetails_Accom)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_BizTravelMaster)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "JBADMIN";
            // 
            // BizTravelMaster
            // 
            this.BizTravelMaster.CacheConnection = false;
            this.BizTravelMaster.CommandText = "SELECT dbo.[BizTravelMaster].* FROM dbo.[BizTravelMaster]";
            this.BizTravelMaster.CommandTimeout = 30;
            this.BizTravelMaster.CommandType = System.Data.CommandType.Text;
            this.BizTravelMaster.DynamicTableName = false;
            this.BizTravelMaster.EEPAlias = null;
            this.BizTravelMaster.EncodingAfter = null;
            this.BizTravelMaster.EncodingBefore = "Windows-1252";
            this.BizTravelMaster.EncodingConvert = null;
            this.BizTravelMaster.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "TvlNo";
            this.BizTravelMaster.KeyFields.Add(keyItem1);
            this.BizTravelMaster.MultiSetWhere = false;
            this.BizTravelMaster.Name = "BizTravelMaster";
            this.BizTravelMaster.NotificationAutoEnlist = false;
            this.BizTravelMaster.SecExcept = null;
            this.BizTravelMaster.SecFieldName = null;
            this.BizTravelMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.BizTravelMaster.SelectPaging = false;
            this.BizTravelMaster.SelectTop = 0;
            this.BizTravelMaster.SiteControl = false;
            this.BizTravelMaster.SiteFieldName = null;
            this.BizTravelMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucBizTravelMaster
            // 
            this.ucBizTravelMaster.AutoTrans = true;
            this.ucBizTravelMaster.ExceptJoin = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "TvlNo";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "BizTvlGist";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "ApplyEmpName";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "ApplyEmpID";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "CostCenterName";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "CostCenterID";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "ApplyDate";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "TvlDateS";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "TvlDateE";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "TvlNationCity";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "PreTvlDescr";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "AccCustomers";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "PlanVisitCustomers";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "DrawEmpID";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "DrawEmpName";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "InsuraceAmt";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "Currency1";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "BorrowAmt1";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "Currency2";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "BorrowAmt2";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "BorrowPayType";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "DemandDate";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "ACurrency1";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "ABorrowAmt1";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "ACurrency2";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "ABorrowAmt2";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "RealTvlAmt1";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "RealTvlAmt2";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "Notes";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "FeeDetailsPath";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "TvlReportsPath";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "FlowFlag";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "CreateDate";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "AccountType";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "AccountID";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "TotalAFVF";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "CompanyID";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr1);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr2);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr3);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr4);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr5);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr6);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr7);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr8);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr9);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr10);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr11);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr12);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr13);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr14);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr15);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr16);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr17);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr18);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr19);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr20);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr21);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr22);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr23);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr24);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr25);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr26);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr27);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr28);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr29);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr30);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr31);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr32);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr33);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr34);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr35);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr36);
            this.ucBizTravelMaster.FieldAttrs.Add(fieldAttr37);
            this.ucBizTravelMaster.LogInfo = null;
            this.ucBizTravelMaster.Name = "ucBizTravelMaster";
            this.ucBizTravelMaster.RowAffectsCheck = true;
            this.ucBizTravelMaster.SelectCmd = this.BizTravelMaster;
            this.ucBizTravelMaster.SelectCmdForUpdate = null;
            this.ucBizTravelMaster.SendSQLCmd = true;
            this.ucBizTravelMaster.ServerModify = true;
            this.ucBizTravelMaster.ServerModifyGetMax = false;
            this.ucBizTravelMaster.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucBizTravelMaster.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucBizTravelMaster.UseTranscationScope = false;
            this.ucBizTravelMaster.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // BizTravelDetails_Accom
            // 
            this.BizTravelDetails_Accom.CacheConnection = false;
            this.BizTravelDetails_Accom.CommandText = "SELECT dbo.[BizTravelDetails_Accom].* FROM dbo.[BizTravelDetails_Accom]";
            this.BizTravelDetails_Accom.CommandTimeout = 30;
            this.BizTravelDetails_Accom.CommandType = System.Data.CommandType.Text;
            this.BizTravelDetails_Accom.DynamicTableName = false;
            this.BizTravelDetails_Accom.EEPAlias = null;
            this.BizTravelDetails_Accom.EncodingAfter = null;
            this.BizTravelDetails_Accom.EncodingBefore = "Windows-1252";
            this.BizTravelDetails_Accom.EncodingConvert = null;
            this.BizTravelDetails_Accom.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "AutoKey";
            keyItem3.KeyName = "TvlNo";
            this.BizTravelDetails_Accom.KeyFields.Add(keyItem2);
            this.BizTravelDetails_Accom.KeyFields.Add(keyItem3);
            this.BizTravelDetails_Accom.MultiSetWhere = false;
            this.BizTravelDetails_Accom.Name = "BizTravelDetails_Accom";
            this.BizTravelDetails_Accom.NotificationAutoEnlist = false;
            this.BizTravelDetails_Accom.SecExcept = null;
            this.BizTravelDetails_Accom.SecFieldName = null;
            this.BizTravelDetails_Accom.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.BizTravelDetails_Accom.SelectPaging = false;
            this.BizTravelDetails_Accom.SelectTop = 0;
            this.BizTravelDetails_Accom.SiteControl = false;
            this.BizTravelDetails_Accom.SiteFieldName = null;
            this.BizTravelDetails_Accom.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucBizTravelDetails_Accom
            // 
            this.ucBizTravelDetails_Accom.AutoTrans = true;
            this.ucBizTravelDetails_Accom.ExceptJoin = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "AutoKey";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "TvlNo";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "AccStaffID";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "AccStaffName";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "AccStaffPID";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "AccStaffInsGroupName";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "AccStaffBirthday";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "AirfareVisafee";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "AiviPayType";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            this.ucBizTravelDetails_Accom.FieldAttrs.Add(fieldAttr38);
            this.ucBizTravelDetails_Accom.FieldAttrs.Add(fieldAttr39);
            this.ucBizTravelDetails_Accom.FieldAttrs.Add(fieldAttr40);
            this.ucBizTravelDetails_Accom.FieldAttrs.Add(fieldAttr41);
            this.ucBizTravelDetails_Accom.FieldAttrs.Add(fieldAttr42);
            this.ucBizTravelDetails_Accom.FieldAttrs.Add(fieldAttr43);
            this.ucBizTravelDetails_Accom.FieldAttrs.Add(fieldAttr44);
            this.ucBizTravelDetails_Accom.FieldAttrs.Add(fieldAttr45);
            this.ucBizTravelDetails_Accom.FieldAttrs.Add(fieldAttr46);
            this.ucBizTravelDetails_Accom.LogInfo = null;
            this.ucBizTravelDetails_Accom.Name = "ucBizTravelDetails_Accom";
            this.ucBizTravelDetails_Accom.RowAffectsCheck = true;
            this.ucBizTravelDetails_Accom.SelectCmd = this.BizTravelDetails_Accom;
            this.ucBizTravelDetails_Accom.SelectCmdForUpdate = null;
            this.ucBizTravelDetails_Accom.SendSQLCmd = true;
            this.ucBizTravelDetails_Accom.ServerModify = true;
            this.ucBizTravelDetails_Accom.ServerModifyGetMax = false;
            this.ucBizTravelDetails_Accom.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucBizTravelDetails_Accom.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucBizTravelDetails_Accom.UseTranscationScope = false;
            this.ucBizTravelDetails_Accom.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // idBizTravelMaster_BizTravelDetails_Accom
            // 
            this.idBizTravelMaster_BizTravelDetails_Accom.Detail = this.BizTravelDetails_Accom;
            columnItem1.FieldName = "TvlNo";
            this.idBizTravelMaster_BizTravelDetails_Accom.DetailColumns.Add(columnItem1);
            this.idBizTravelMaster_BizTravelDetails_Accom.DynamicTableName = false;
            this.idBizTravelMaster_BizTravelDetails_Accom.Master = this.BizTravelMaster;
            columnItem2.FieldName = "TvlNo";
            this.idBizTravelMaster_BizTravelDetails_Accom.MasterColumns.Add(columnItem2);
            // 
            // View_BizTravelMaster
            // 
            this.View_BizTravelMaster.CacheConnection = false;
            this.View_BizTravelMaster.CommandText = "SELECT * FROM dbo.[BizTravelMaster]";
            this.View_BizTravelMaster.CommandTimeout = 30;
            this.View_BizTravelMaster.CommandType = System.Data.CommandType.Text;
            this.View_BizTravelMaster.DynamicTableName = false;
            this.View_BizTravelMaster.EEPAlias = null;
            this.View_BizTravelMaster.EncodingAfter = null;
            this.View_BizTravelMaster.EncodingBefore = "Windows-1252";
            this.View_BizTravelMaster.EncodingConvert = null;
            this.View_BizTravelMaster.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "TvlNo";
            this.View_BizTravelMaster.KeyFields.Add(keyItem4);
            this.View_BizTravelMaster.MultiSetWhere = false;
            this.View_BizTravelMaster.Name = "View_BizTravelMaster";
            this.View_BizTravelMaster.NotificationAutoEnlist = false;
            this.View_BizTravelMaster.SecExcept = null;
            this.View_BizTravelMaster.SecFieldName = null;
            this.View_BizTravelMaster.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_BizTravelMaster.SelectPaging = false;
            this.View_BizTravelMaster.SelectTop = 0;
            this.View_BizTravelMaster.SiteControl = false;
            this.View_BizTravelMaster.SiteFieldName = null;
            this.View_BizTravelMaster.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.BizTravelMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.BizTravelDetails_Accom)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_BizTravelMaster)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand BizTravelMaster;
        private Srvtools.UpdateComponent ucBizTravelMaster;
        private Srvtools.InfoCommand BizTravelDetails_Accom;
        private Srvtools.UpdateComponent ucBizTravelDetails_Accom;
        private Srvtools.InfoDataSource idBizTravelMaster_BizTravelDetails_Accom;
        private Srvtools.InfoCommand View_BizTravelMaster;
    }
}
